### ISSUE TITLE
对于CAT的疑问 

### ISSUE THREAD

**Issue by topCoderzhangshuo** [dianping/cat#1005]

**Comment by topCoderzhangshuo** [comment]
1.
加载问题：
对于Client的配置引用，有三个地方，按加载顺序如下：
step1:
......./data/appdatas/cat/client.xml （可配置 app.name;server ip等）
step2:
.....src\main\resources\META-INF\app.properties （可配置 app.name）
step3:
.....src\main\resources\META-INF\cat\client.xml （可配置 app.name;server ip等）
为什么要重复设置呢？？完全配一个xml文件就行了啊。。是不是有些多余呢？


2.
![image](https://cloud.githubusercontent.com/assets/13445665/16327589/4094a02e-3a03-11e6-8015-e42311e73f23.png)


Transaction里的Type URL  与 URL.Forward 有什么不同？？感觉有些混乱。。URL.Forward难道是forward请求?URL事所有的请求？？

**Comment by youyong205** [comment]
你可以看下selvert的forward
