### ISSUE TITLE
关于/data/appdatas/cat描述不准确

### ISSUE THREAD

**Issue by helloworldtang** [dianping/cat#1021]
Windows 则是对系统运行盘下的/data/appdatas/cat和/data/applogs/cat有读写权限
==================
上面的描述改成这样是不是会更容易理解：
Windows 则是对系统运行盘下的/data/appdatas/cat和/data/applogs/cat有读写权限，如果cat服务运行在e盘的tomcat中，则需要对e:/data/appdatas/cat和e:/data/applogs/cat有读写权限

**Comment by helloworldtang** [comment]
编译、运行cat的操作步骤，按下面是否更方便新手学习，降低学习门槛
git clone https://github.com/dianping/cat.git
cd cat
git checkout mvn-repo
cp -R * ~/.m2/repository //有些Jar Maven下载不下来，通过这个方法可以解决编译问题
git checkout master
mvn clean install -DskipTests
mvn cat:install  //按提示输入连接本地mysql的一些信息
cd cat-home
mvn jetty:run
http://localhost:2281/cat

**Comment by scudy** [comment]
配置和日志是否可以不在 /data/目录下

**Comment by helloworldtang** [comment]
可以，那要改配置文件吧。
为什么要改目录呢？

**Comment by youyong205** [comment]
这块我补充下md~
