### ISSUE TITLE
Cat 支持Hessian RPC 服务方式吗

### ISSUE THREAD

**Issue by wappoint** [dianping/cat#1024]
Cat 支持Hessian RPC 服务方式吗

**Comment by qmwu2000** [comment]
大众点评就是基于hessian RPC服务的。


发自我的 iPhone

**Comment by wappoint** [comment]
有相关的Demo案例么~    源码中好像并未提到hessian 的方式。

**Comment by youyong205** [comment]
cat埋点和是不是hessian没关系的，hessian只是个序列化方式
