### ISSUE TITLE
添加产品线时，产品线项目就是没有东西？

### ISSUE THREAD

**Issue by jxctx88** [dianping/cat#1027]
server.xml的job-machine设置为true了

**Comment by youyong205** [comment]
等一个小时 就好了，插入项目信息是有延迟的

**Comment by youyong205** [comment]
job-machine=true

**Comment by sungine** [comment]
我这边发现报表合并配置部分 不知道怎么的被清空了
补充了配置文件
<all-config>
   <report id="transaction">
      <type id="URL">
         <name id="*"/>
      </type>
   </report>
   <report id="event">
      <type id="URL">
         <name id="*"/>
      </type>
      <type id="SQL">
         <name id="*"/>
      </type>
   </report>
</all-config>

对于allc-config的配置规则一直找不到资料
 @youyong205
