### ISSUE TITLE
在windows系统中,用eclipse怎么运行

### ISSUE THREAD

**Issue by dasxi** [dianping/cat#1037]
我用eclipse把cat下到本地,但是有很多报错,最突出的就是在cat中有很多包和类是找不到的,比如在client工程中cat类下import com.dianping.cat.configuration.client.entity.ClientConfig; 可是就没找到这个包和在这个包下的类?
即使install成功了,也 会提示这些类找不到之类的. 
有人在windows下运行的吗? 分享一下经验呗?

**Comment by qmwu2000** [comment]
请在命令行界面构建：mvn eclipse:eclipse，然后以普通文件方式import到eclipse中，再设置一下M2_REPO就可以了。


发自我的 iPhone

**Comment by youyong205** [comment]
mvn
