### ISSUE TITLE
LogView中的中文有几率显示乱码

### ISSUE THREAD

**Issue by visionding** [dianping/cat#1040]
环境：操作系统CentOS 6.4，Tomcat 8.5.4已设置UTF-8编码，数据库MySQL 5.1.73，单机部署，master分支最新代码编译安装
LogView里面记录的异常信息中文有几率显示乱码，多刷新几次就会有一次出现

**Comment by zhangzhxb520** [comment]
是不是MySql的编码不是UTF-8

**Comment by visionding** [comment]
@zhangzhxb520 MySQL是UTF-8的，页面刷新的时候有时是乱码，有时是正常的，只有LogView页面会这样子

**Comment by youyong205** [comment]
检查环境问题，这个和cat肯定没关系
