### ISSUE TITLE
麻烦开放这个地址好下载最新的包啊，mvn-repo里面版本才到2.4.0

### ISSUE THREAD

**Issue by huangxinjun** [dianping/cat#1052]
http://unidal.org/nexus/content/repositories/releases/

**Comment by sky91** [comment]
同问，仓库unidal.org/nexus挂了，怎么玩？

**Comment by qmwu2000** [comment]
不好意思，这个仓库不是很稳定，我们会尽快换一台机器部署。



发自我的 iPhone

**Comment by qmwu2000** [comment]
升级了unidal.org机器，系统应该会稳定些。如有其它问题，欢迎继续反馈，谢谢！

**Comment by zzk1314** [comment]
@qmwu2000
