### ISSUE TITLE
依赖找不到

### ISSUE THREAD

**Issue by lizhen5117** [dianping/cat#1054]
如下几个pom 依赖找不到额， 这是什么情况
大家是如何在缺少依赖的情况下部署的
<dependency>
				<groupId>org.unidal.framework</groupId>
				<artifactId>dal-jdbc</artifactId>
				<version>2.5.0</version>
			</dependency>
			<dependency>
				<groupId>org.unidal.framework</groupId>
				<artifactId>foundation-service</artifactId>
				<version>2.5.0</version>
			</dependency>
			<dependency>
				<groupId>org.unidal.framework</groupId>
				<artifactId>web-framework</artifactId>
				<version>2.5.0</version>
			</dependency>
			<dependency>
				<groupId>org.unidal.framework</groupId>
				<artifactId>test-framework</artifactId>
				<version>2.5.0</version>
			</dependency>
			<dependency>
				<groupId>org.unidal.webres</groupId>
				<artifactId>WebResServer</artifactId>
				<version>1.2.1</version>
			</dependency>

**Comment by qmwu2000** [comment]
请使用cat pom中自带的repository。
