### ISSUE TITLE
 [ERROR] [TcpSocketSender] Netty write buffer is full! Attempts: 1

### ISSUE THREAD

**Issue by sunqinbo** [dianping/cat#1055]
> cat server 端异常信息：
`
[11-24` 17:35:46.645] [ERROR] [TcpSocketSender] Netty write buffer is full! Attempts: 1

* 请问这个是什么原因造成的，如何处理？谢谢；可回复邮件：sunqinbo@dongao.com

**Comment by youyong205** [comment]
这个不影响的，就是服务端没有ready的时候打印的，会有重试机制
