### ISSUE TITLE
messageIdFactory不支持ipv6，但是NetworkInterfaceManager却能够解析出ipv6地址，造成NumberFormatException

### ISSUE THREAD

**Issue by fhqfhvtx** [dianping/cat#1056]
MessageIDFactory解释ip地址是是按照ipv4格式解析的。但是NetworkInterfaceManager却能够解析出ipv6地址。造成当NetworkInterfaceManager解析为ipv6地址时下messageIDFacotory报错。

![qq 20161125170123](https://cloud.githubusercontent.com/assets/5821003/20619857/a4982c1a-b331-11e6-908f-f77a3da1fba2.png)

建议
方案一：MessageIDFactory支持ipv6，不用ipv4格式解析地址。图中选中部分改为不解析
![image](https://cloud.githubusercontent.com/assets/5821003/20620060/b7988868-b332-11e6-9c90-19a45b122aa6.png)

方案二：NetworkInterfaceManager去掉ipv6支持，下面是我改后的
![image](https://cloud.githubusercontent.com/assets/5821003/20620015/65eaa23a-b332-11e6-965e-a86b3c39ab00.png)

**Comment by qmwu2000** [comment]
试试新的fix！
