### ISSUE TITLE
缺少的jar包怎么解决

### ISSUE THREAD

**Issue by Imtonoo** [dianping/cat#1058]
<groupId>org.unidal.maven.plugins</groupId>
					<artifactId>codegen-maven-plugin</artifactId>
					<version>2.4.2</version>

**Comment by Imtonoo** [comment]
翻墙可以，但起码告诉我哪里可以得到jar包吧...

**Comment by Imtonoo** [comment]
告诉我我连哪一个镜像吧...ibiblio Mirror of http://repo1.maven.org/maven2这个可以不，

**Comment by gejun123456** [comment]
http://unidal.org/nexus/content/repositories/releases/   这里可以下载

**Comment by zhaoshiling1017** [comment]
http://unidal.org/nexus/content/repositories/releases/这个是点评提供私服地址，在Cat项目pom.xml中有配置。你可以把这个镜像配置在~/.m2/settings.xml中：
　<mirror>
    <id>UK</id>
    <name>UK Central</name>
    <url>http://uk.maven.org/maven2</url>
    <mirrorOf>central</mirrorOf>
    </mirror>
这个是英国的镜像，不用翻墙就能正常下载jar。

**Comment by MonoCC** [comment]
把mvn-repo 分支检出来，复制到本地maven库中，master不兼容jdk8 特别注意。（注：文档里面都有怎么弄，认真看下。）

**Comment by youyong205** [comment]
jdk8的问题fix了，在试试吧

**Comment by luolenny** [comment]
大众点评CAT 部署 
修改pom.xml (2个)如下.
                <plugin>
                    <groupId>org.unidal.maven.plugins</groupId>
                    <artifactId>codegen-maven-plugin</artifactId>
                    <version>2.5.7</version>
                </plugin>
                <plugin>
                    <groupId>org.unidal.maven.plugins</groupId>
                    <artifactId>plexus-maven-plugin</artifactId>
                    <version>2.5.7</version>
                </plugin>

修改 .m2\setting.xml,使用点评的私有库
     <mirror>
      <id>Allmirror</id>
      <name>Central</name>
      <url>  http://unidal.org/nexus/content/repositories/releases/ </url>
      <mirrorOf>*</mirrorOf>
    </mirror>

**Comment by zzk1314** [comment]
@zhaoshiling1017  感谢，使用英国镜像地址就可以下载了
