### ISSUE TITLE
关于代码部署运行的页面不太一致的问题

### ISSUE THREAD

**Issue by melodyfair1971** [dianping/cat#1060]
你好:
1.github上的代码拉下来部署之后,发现有些文档的截图和代码部署的页面不太一样,例如告警监控规则配置..
2.代码部署的页面和github里的readme里提供的样式http://unidal.org/cat/r/home?op=view&docName=deploy的页面也不太一样

**Comment by youyong205** [comment]
大部分都差不多的，部署的是两个不同的版本。一些功能内部用，弄出去显得麻烦
