### ISSUE TITLE
内存溢出问题

### ISSUE THREAD

**Issue by songwie** [dianping/cat#1062]
cat线上使用一个月 存在严重的内存溢出问题，可能记录的监控太多，但是这种模式不应该导致内存溢出，
初步排除原因 发现内存分析都是ThreadLocal 绑定了太多的的Cat Message 信息，是不是ThreadLocat清除有问题，服务器来不及处理客户端应该抛弃吧，不应该导致内存溢出。

**Comment by 54ebb** [comment]
堆栈信息呢

**Comment by songwie** [comment]
![image](https://cloud.githubusercontent.com/assets/9819575/20783963/39d9bc72-b7d2-11e6-9f68-3f4d674ca137.png)

**Comment by songwie** [comment]
含有几百M甚至有的几个G的点评cat的message信息

**Comment by 54ebb** [comment]
查查这几点，看看有线索没有：
1、是不是埋点本身有问题
2、是不是应用逻辑有优化的地方？比如一个请求的处理中查询了上百次SQL或者缓存

**Comment by 54ebb** [comment]
查查这几点，看看有线索没有：
1、是不是埋点本身有问题
2、是不是应用逻辑有优化的地方？比如一个请求的处理中查询了上百次SQL或者缓存

**Comment by songwie** [comment]
我们是为了排查线上问题记录了很多的日志与监控 是不是太多导致的 如果开启cat的流量带宽被打到30M，我们也怀疑是记录的太多，不过感觉就算太多也应该抛弃不应该导致积压内存吧，这个客户端发送队列是不是可以在优化下。

**Comment by youyong205** [comment]
看你业务怎么记录，cat的队列就5000个，点评内部消息正常一个1-2k，估计你们那边埋点了大量的数据，然而每个消息节点也是大量数据，比如sql的明细，堆栈，导致每个消息都很大

**Comment by songwie** [comment]
对的，把方法栈打出来了

**Comment by zhaojiandong** [comment]
线程池调用dubbo接口，因为线程的reuse通过threadlcoal来分别不同线程，会存在问题的吧，经常oom
