### ISSUE TITLE
为什么要拿掉dependency

### ISSUE THREAD

**Issue by chinaboard** [dianping/cat#1065]
有段时间没看代码了，发现这部分似乎被干掉了，有什么说法吗？

**Comment by qmwu2000** [comment]
有用户反映，matrix和dependency不太常用，就在新版中屏蔽了，以降低系统的开销。如果很多人都觉得这两张报表还是非常有用的，我可以考虑将它们加回来。

**Comment by chinaboard** [comment]
matrix和dependency的埋点成本还是比较大，报表友好度可以进一步提升，个人觉得dependency还是可以有的

**Comment by chinaboard** [comment]
再就是有人反映不常用就直接干掉有人觉得好就解除屏蔽是不是太鲁莽了，为什么不加开关一类的选项让用户能够自行管理更友好一些

**Comment by youyong205** [comment]
我们内部研发版本这个report也去掉了，主要遇到一些报表实质性问题，后续版本我们会重新设计一个。
如果可以你可以做个开关自行管理，拜托别把自己当做我们老板，谢谢。

**Comment by chinaboard** [comment]
我只是抛出一个疑惑，最起码作为一个使用者不希望说有一些东西莫名其妙的就没有而且没有个说法，如果说拿自己做的东西就是单纯开源出来而不考虑社区氛围的话那我真是无话可说。

**Comment by youyong205** [comment]
既然不希望，你可以选择不用的~好的工具很多的~我们也没那么时间支持的很好~谢谢
