### ISSUE TITLE
git上打包后的版本与给定的实例版本不一致

### ISSUE THREAD

**Issue by zhaolizhi** [dianping/cat#1083]
如题，在预研过程中，发现版本说明中只到了1.2.8 而git给的示例中到了1.3.8 而在实时中找不到Metric这个的显示项，请问这个该如何解决！

**Comment by ahuazhu** [comment]
1.3.6后的版本去掉了这个feature。

**Comment by youyong205** [comment]
metric 就是业务大盘~
