### ISSUE TITLE
项目分组配置修改不生效(修改更新不了)

### ISSUE THREAD

**Issue by zhanggaofeng** [dianping/cat#1095]
![image](https://cloud.githubusercontent.com/assets/6221354/22822904/59b4b75a-efbc-11e6-80ed-4ac80632dd7b.png)
这个编辑之后保存没有任何反应，是什么问题！(业务监控)

**Comment by youyong205** [comment]
这个自己debug下，这个很多人都用起来的。

**Comment by wheatt** [comment]
您好，我也碰到了同样的问题，请问您解决了吗？怎么解决的
