### ISSUE TITLE
windows10   有虚拟网络时Inets.IP4.getLocalHostAddress()这个方法跑十几秒才能获取到值

### ISSUE THREAD

**Issue by hzqiyongpan** [dianping/cat#1109]
![image](https://cloud.githubusercontent.com/assets/4659635/23192492/b027dc4a-f8de-11e6-802e-e493b1221270.png)
![image](https://cloud.githubusercontent.com/assets/4659635/23192502/c121fe7c-f8de-11e6-8f58-815d9dc9a095.png)

windows10   有虚拟网络时Inets.IP4.getLocalHostAddress()这个方法跑十几秒才能获取到值

**Comment by qmwu2000** [comment]
应该name resolving timeout太长，可以在/etc/hosts中配一下，或者在jvm中传入-Dhost.ip=x.x.x.x规避

发自我的 iPhone

**Comment by hzqiyongpan** [comment]
禁用VM就好了
