### ISSUE TITLE
Cat的portal菜单看不到metric这一项

### ISSUE THREAD

**Issue by chenhangbiao** [dianping/cat#1137]
http://unidal.org/cat/r/t?domain=cat&ip=&date=2017042217&reportType=day&op=view 官网的左侧菜单就没有Metric，自己部署的菜单也没有Metric。

1、Cat.logMetric记录的数据在哪儿看呢？
2、要开启这个菜单需要什么配置吗？

多谢！

**Comment by qmwu2000** [comment]
metrics在Dashboard下的业务大盘中查看
