### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by wgd12389** [dianping/cat#1141]
您好，最近在使用cat的过程中发现， 比如我在集成的时候，假如client.xml的配置里有错误，导致客户端无法正常解析xml的时候，没有相关的报错提示，只是catmanager里的东西是null，这样感觉很不利于排查错误，是否改成解析有问题或者为null的时候抛出异常比较合适

**Comment by chinaboard** [comment]
排查姿势不对，如果cat没有起来的话在后台是看不到应用程序domain对应IP的情况

**Comment by wgd12389** [comment]
@chinaboard 我觉得和排查方式没关系吧，假如拿配置文件的冒号写成中文的来讲，如果是这样的，解析的时候难道不应该是抛异常吗，为什么还要正常启动呢，而且无论是否能看到domain中对应ip的情况，我如何定位就是我xml的配置写错而不是其他地方写错了呢

**Comment by chinaboard** [comment]
思路不一样吧，如果按照尽量减少侵入的方式来考虑，那么cat启动失败或出现异常是不应该让应用程序感知到的，所以cat是没有任何异常可以抛出的
如果非要在加载过程中让用户感知的话，自己稍微修改一下catclient的代码也没多大的工作量

在 2017年5月31日 下午4:27，jsondream <notifications@github.com>写道：

**Comment by wgd12389** [comment]
@chinaboard 我理解您的意思，我想表达的是如果解析失败，对业务无感知这个无可否认，但是比如像client.xml这些配置里面出现问题的时候，是否应该在cat的log文件中提示出解析配置文件错误呢。。这样能缩小很多用户排查这个错误的范围，对用户的友好度会更高啊

**Comment by chinaboard** [comment]
如果cat后台没有log过来的话，无非就是配置的问题

**Comment by youyong205** [comment]
主要cat 不希望引入业务，无论怎么cat，都不能报错，仅仅监控功能没有，出发点不太一样
