### ISSUE TITLE
通过文件设置app.name是否能做个兼容处理

### ISSUE THREAD

**Issue by aftersss** [dianping/cat#1147]
`使用cat需要在应用项目的src/main/resources/META-INF下，新建app.properties文件，加上项目名配置，如：app.name=**；`

这个对于我们的spring-boot项目非常不友好，能否做个兼容处理，如果获取不到这个配置，则从系统环境变量里获取：System.getProperty("app.name")。

**Comment by qmwu2000** [comment]
不错的建议，谢谢！

发自我的 iPhone
