### ISSUE TITLE
启动正常访问时后台报错

### ISSUE THREAD

**Issue by sungine** [dianping/cat#1150]
报错信息: Illegal access: this web application instance has been stopped already.  Could not load META-INF/services/javax.xml.parsers.SAXParserFactory.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.

同时管理界面上数据全部为空
![image](https://user-images.githubusercontent.com/15043043/27954052-d2b7ecf6-6340-11e7-8cf8-f7672c518d0a.png)

**Comment by nituchao** [comment]
解决了吗？我也遇到了

**Comment by qmwu2000** [comment]
什么web container？以及版本


发自我的 iPhone

**Comment by liangrui1988** [comment]
+1很多功能一点就报500,添加的还有报400, 刚测试埋了个点，什么也没有，不知从何下手排查,在本地怎么跑哈，很多实体都是在打包时生成的，这样很不方便本地调试

**Comment by liangrui1988** [comment]
我知道什么原因了，是因为没有权限建data/applogs/cat这个文件权限，改原码换了个目录就好了，但是我的埋点还是看不到，发现通过手动停止tomcat后，根本没停下来，一看top,好家伙，内存都快被几个cat吃光了，手动kill掉才行啊，还有修改：Request URL:http://192.168.20.243:7061/cat/s/config?op=domainGroupConfigSubmit&domain=PayOrder&content={%22id%22:%22PayOrder%22,%22groups%22:{%22main%22:{%22id%22:%22main%22,%22ips%22:[%22192.168.20.243%22]},%22event%22:{%22id%22:%22event%22,%22ips%22:[%22192.168.20.243%22]}}}
Request Method:GET
Status Code:400 Bad Request
Remote Address:192.168.20.243:7061
Referrer Policy:no-referrer-when-downgrade
