### ISSUE TITLE
离线报表计算QPS的公式为什么要乘以5

### ISSUE THREAD

**Issue by chixuan777** [dianping/cat#1151]

**Comment by chixuan777** [comment]
TransactionReportVisitor.java其中计算QPS的时候用最大值乘以1再除以5分钟
applicationState.setMaxQps(max * 1.0 / (5 * 60));
是不是直接applicationState.setMaxQps(max * 1.0);就可以呢？

**Comment by youyong205** [comment]
为了兼容最初版本统计粒度5分钟的，现在应该是1分钟的吧

**Comment by chixuan777** [comment]
master代码还是5分钟的唉
https://github.com/dianping/cat/blob/46dd96c7d7015352edf0dc2f793cdb290a03ee37/cat-home/src/main/java/com/dianping/cat/report/page/statistics/task/utilization/TransactionReportVisitor.java
