### ISSUE TITLE
com.dianping.cat.build.ComponentsConfigurator 编译出错

### ISSUE THREAD

**Issue by smartcat315** [dianping/cat#1153]
import com.dianping.cat.core.config.ConfigDao;
import com.dianping.cat.core.dal.HostinfoDao;
import com.dianping.cat.core.dal.TaskDao;
引入内容不存在

**Comment by qmwu2000** [comment]
这些代码都是codegen plugin生成的，在导入IDE之前，需要需要mvn eclipse:eclipse或者mvn idea:idea等


发自我的 iPhone

**Comment by smartcat315** [comment]
谢谢
