### ISSUE TITLE
cat server.xml关于hdfs的配置

### ISSUE THREAD

**Issue by zhudefu** [dianping/cat#1159]
请问在server.xml中的以下配置中
<hdfs id="logview" max-size="128M" server-uri="hdfs://IP/user/cat" base-dir="logview"/>
可以给ser-uri同时配置hadoop集群的namenode、secondarynamenode的IP吗，以应对hadoop集群主备节点切换的场景，谢谢！

**Comment by youyong205** [comment]
这个目前没有支持，你们有需求可以视图改下源码。
