### ISSUE TITLE
客户端接入报错 java.lang.NoClassDefFoundError: org/unidal/helper/Joiners$IBuilder

### ISSUE THREAD

**Issue by wybSoka** [dianping/cat#1160]
客户端接入报错 java.lang.NoClassDefFoundError: org/unidal/helper/Joiners$IBuilder  jdk 1.8

**Comment by youyong205** [comment]
先执行mvn eclipse:eclipse  ,另外把项目改为maven 依赖，cat-client还依赖其他项目
