### ISSUE TITLE
请问，cat是先将数据写到本地，然后再向服务器发送的么？

### ISSUE THREAD

**Issue by xcdsycn** [dianping/cat#1161]
当网络断掉的时候，是如何处理的呢？

**Comment by youyong205** [comment]
内存有队列，队列满了，后续会丢弃处理。

**Comment by xcdsycn** [comment]
这样的话不是有些日志就丢了？另外，如果网络出现异常，那么客户端采集的日志，也会丢了吧？还有，在什么情况下，会让被采集的应用出现OOM呢？我们原来的应用采用了CAT就会出现由于日志采集的问题，导致OOM，应用也受到了影响，这方面CAT是如何做的呢？
