### ISSUE TITLE
cat运行过程中报  [ERROR] [TcpSocketSender] Netty write buffer is full! Attempts: 12000， 请解决方案

### ISSUE THREAD

**Issue by shllove** [dianping/cat#1162]
cat运行过程中报  [ERROR] [TcpSocketSender] Netty write buffer is full! Attempts: 12000， 请解决方案

**Comment by qmwu2000** [comment]
这个问题可能的原因有：a）cat server配错了；b）cat server端不可用；c）cat server吞吐能力不够，而导致cat client本地缓冲区满后溢出。


发自我的 iPhone

**Comment by shllove** [comment]
@qmwu2000
感谢回复，请问下， 有哪些手段可以确认提到的3个问题呢？ 我是新手，刚接触，还望帮忙指导下，谢谢

**Comment by shllove** [comment]
补充一些信息， cat server运行正常，heartbeat可以正常查看，目前发现transcation有丢数据，定位到日志是  Netty write buffer is full!，   那么第二个server不可用应该可以排除，  请问 server配置错误的话，应该如何配置，  吞吐能力不够的话，又该如何调整？谢谢

**Comment by qmwu2000** [comment]
cat server吞吐不够，可以考虑一台性能更好的机器，或者减少应用的日志量，或者调优下cat服务端性能（比如JVM参数调整）
