### ISSUE TITLE
c# 的 client 在哪里

### ISSUE THREAD

**Issue by brotherhorse** [dianping/cat#1165]

**Comment by qmwu2000** [comment]
试试这个 https://github.com/dianping/cat.net

**Comment by brotherhorse** [comment]
谢谢，这个和ctripcorp/cat.net基本是一样的吧，ctripcorp/cat.net更新新一些


________________________________
发件人: Frankie Wu <notifications@github.com>
发送时间: 2017年9月9日 10:31
收件人: dianping/cat
抄送: brotherhorse; Author
主题: Re: [dianping/cat] c# 的 client 在哪里 (#1165)


Closed #1165<https://github.com/dianping/cat/issues/1165>.

―
