### ISSUE TITLE
接入cat，启动应用后，后访问url网址报空指针

### ISSUE THREAD

**Issue by MrZhangisGood** [dianping/cat#1166]
![image](https://user-images.githubusercontent.com/16771383/30149155-2db91eb8-93d9-11e7-8d65-8094f7bc2eb0.png)

java.lang.NullPointerException
	com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:94)
	com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:426)
	com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:45)
	org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

**Comment by MrZhangisGood** [comment]
client.xml  文件配置在 /data/appdatas/cat/client.xml

<config mode="client">
            <servers>
                    <server ip="10.10.105.242" port="2280" http-port="8080"/>
            </servers>
</config>


一模一样的应用代码，cat服务器，测试环境的应用可以用，预生产的不能用

**Comment by qmwu2000** [comment]
这个问题不应该啊，看代码没问题，除非server==null。

code中加了一个check，你再pull一下试试

**Comment by MrZhangisGood** [comment]
解决了，cat依赖的jar包与其他依赖的netty jar冲突，引起的不能初始化

**Comment by liushangdev** [comment]
@MrZhangisGood  你好我也遇到了和你同样的问题 能说下你是怎么解决的吗？谢谢

**Comment by MrZhangisGood** [comment]
> @MrZhangisGood 你好我也遇到了和你同样的问题 能说下你是怎么解决的吗？谢谢

我是因为jar冲突导致的
