### ISSUE TITLE
cat服务长时间不重启，“磁盘泄露”

### ISSUE THREAD

**Issue by itdeng** [dianping/cat#1168]
dump日志存HDFS方式：
超过一天的dump日志存入HDFS，然后删除本地。
但是文件是删除了，引用未关闭，导致磁盘泄露。

表现为：
df -h 与 du -sh统计不一致；若日志量大，N天后，能建文件夹，local不能存日志，cat服务不可用
通过命令lsof | grep "(deleted)"可看到文件为cat服务占用

**Comment by itdeng** [comment]
![image](https://user-images.githubusercontent.com/22071905/30361474-c3ee8ee0-9889-11e7-9cf3-c978dd925545.png)

**Comment by itdeng** [comment]
![image](https://user-images.githubusercontent.com/22071905/30361692-fee596fa-988a-11e7-910f-928449d6f8ab.png)

**Comment by itdeng** [comment]
此问题，不是100%出现，有时重启几次后不会有

**Comment by youyong205** [comment]
超过一天的dump日志存入HDFS，然后删除本地。
这个地方需要程序自动去做，不要手工去做吧。

**Comment by itdeng** [comment]
没有手工删，是程序删的。
有个时间段出现频率比较高，重启后可能同样情况，但多重启几次可能就好了。

**Comment by itdeng** [comment]
服务器是台云主机，不排除有机器原因。

**Comment by chinaboard** [comment]
早期我们遇到过类似的情况，排查后是上传HDFS过慢导致的，你这边也可以排查一下

**Comment by itdeng** [comment]
好的，多谢两位大神指导！~
