### ISSUE TITLE
同一线程生成两个MessageTree

### ISSUE THREAD

**Issue by andersonme** [dianping/cat#1171]
项目有时出现同一线程提交了两个MessageTree的情况：两个MessageTree的内容拼起来正好是完整的。如下：

PT1     enterprise      host162 172.16.3.162    main    139     http-nio-8081-exec-18   enterprise-ac1003a2-418177-217  null    null    null
t2017-09-15 09:01:27.835        URL     /api/shop/getShopInfoByUserId  
E2017-09-15 09:01:27.835        URL     URL.Server      0       IPS=172.16.10.148&VirtualIP=10.2.4.56&Server=enterprise.qbao.com
E2017-09-15 09:01:27.835        URL     URL.Server.Agent        0       HttpComponents/1.1
E2017-09-15 09:01:27.835        URL     URL.Method      0       HTTP/GET /api/shop/getShopInfoByUserId?userId=114328489
E2017-09-15 09:01:27.849        URL     URL.Server.Response.Code        0       200    
T2017-09-15 09:01:27.849        URL     /api/shop/getShopInfoByUserId   0       14072us

09:01:27 850-----
PT1     enterprise      host162 172.16.3.162    main    139     http-nio-8081-exec-18   enterprise-ac1003a2-418177-449  null    null    null
t2017-09-15 09:01:27.835        com.enterprise.Filter   TraceFilter.doFilter(..)
t2017-09-15 09:01:27.835        com.enterprise.Filter   AccessLogFilter.doFilter(..)   
t2017-09-15 09:01:27.835        com.enterprise.Filter   RegistIpLimitFilter.doFilter(..)
t2017-09-15 09:01:27.835        org.springframework.Filter      OncePerRequestFilter.doFilter(..)
t2017-09-15 09:01:27.835        com.enterprise.Filter   InvalideAPISessionFilter.doFilter(..)
t2017-09-15 09:01:27.835        com.enterprise.Filter   ApiPassIpFilter.doFilter(..)   
t2017-09-15 09:01:27.835        com.dianping.Filter     CatFilter.doFilter(..)
t2017-09-15 09:01:27.836        URL.Forward     /api/shop/getShopInfoByUserId
E2017-09-15 09:01:27.836        URL.Forward     URL.Forward.Method      0       HTTP/GET /api/shop/getShopInfoByUserId?userId=114328489
t2017-09-15 09:01:27.836        Framework.Spring        Spring.Controller
t2017-09-15 09:01:27.836        com.enterprise.Service  MerchantCommonServiceImpl.getMerchantObjByUserId(..)
t2017-09-15 09:01:27.836        com.enterprise.Service  MerchantCompanyService.getCompanyBaseInfoByUserId(..)
。。。。

**Comment by qmwu2000** [comment]
像是两个异步线程各产生了一个message tree

发自我的 iPhone

**Comment by bbgb1984** [comment]
如何解决呢？

**Comment by bbgb1984** [comment]
如何解决呢？

**Comment by andersonme** [comment]
同一台机器， 线程号一样，消息开始时间一样，处理的请求也一样，怎么变成两个线程了呢？  我前一个埋点URL 是放在Tomcat的execution(public * org.apache.catalina.core.StandardHostValve.invoke(..))这个点上，后一个埋点(Filter为起始）是放在应用的 execution(public * javax.servlet.Filter+.doFilter(..)) 这个点上，难道这两个执行点之间线程会切换吗？   对Tomcat的原理还是不太清楚啊，有哪位大神能看看？

**Comment by qmwu2000** [comment]
应该与servlet 3.0异步功能相关，你可以debug一下先


发自我的 iPhone

**Comment by andersonme** [comment]
找到原因了，是tomcat自己的webappclassloader所导致DefaultMessageManager在两个classloader中加载
