### ISSUE TITLE
transaction告警配置event告警配置等几个页面，提交时，tomcat报400

### ISSUE THREAD

**Issue by liyuyu550** [dianping/cat#1179]
发现这几个URL里包含特殊字符大括号{}，在高版本的tomcat中不支持。需要在catalina.properties中加入配置项tomcat.util.http.parser.HttpParser.requestTargetAllow=|,{,}

**Comment by youyong205** [comment]
其实最好在埋点不需要有那么多乱七八糟的字符。。。
