### ISSUE TITLE
Could not find artifact org.unidal.framework:framework-bom:pom:4.0.0

### ISSUE THREAD

**Issue by devenfan** [dianping/cat#1183]
Non-resolvable import POM: Could not find artifact org.unidal.framework:framework-bom:pom:4.0.0

**Comment by qiangmao** [comment]
Recommend use tag v2.0.0 for `cat`.
---

Founded here: 
Dependencies: https://github.com/unidal/frameworks
Plugins: https://github.com/unidal/maven-plugins

Steps:
 - `git clone https://github.com/unidal/frameworks.git`
 - `cd frameworks && git checkout v3.1.0`
 - `mvn -s settings.xml clean install -DskipTests`
 - `git clone https://github.com/unidal/maven-plugins.git`
 - `git checkout v2.5.8`
 - `cd manven-plugins && mvn -s settings.xml clean install -DskipTests`
 - `git checkout master`
 - `mvn -s settings.xml clean install -DskipTests`

Note:
---
- Plugin must use tag v2.5.8 for cat v2.0.0
- Plugin need some 3.1.0 framework dependencies, so need install 3.1.0 first 

Environment Details:
---
Platform: `Windows`
Maven: `3.3.9`
JAVA:	`jdk1.8.0_121(64 Bit)`

**Comment by boying** [comment]
1. git clone https://github.com/unidal/frameworks.git
2. cd frameworks && git checkout v4.0.0
3. mvn -s settings.xml clean install -DskipTests

then build cat will work

**Comment by devenfan** [comment]
@qiangmao @boying Thanks, both works!
