### ISSUE TITLE
官方 jar 包 下载失败 

### ISSUE THREAD

**Issue by cjeruen** [dianping/cat#1185]
> body (expected: 410711; received: 67247 -> [Help 1]
> 直接 浏览器下载 也是 失败  

> http://unidal.org/nexus/content/repositories/releases/org/unidal/framework/foundation-service/4.0.0/foundation-service-4.0.0.jar

> 各个版本的 jar 都下载失败

[ERROR] Failed to execute goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.6:dal-model (generate model) on project eunit-testfwk: Execution generate model of goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.6:dal-model failed: Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.5.6 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.unidal.maven.plugins:codegen:jar:2.5.6, org.unidal.framework:foundation-service:jar:3.0.4: Could not transfer artifact org.unidal.maven.plugins:codegen:jar:2.5.6 from/to plugins (http://unidal.org/nexus/content/repositories/releases): GET request of: org/unidal/maven/plugins/codegen/2.5.6/codegen-2.5.6.jar from plugins failed: Premature end of Content-Length delimited message body (expected: 410711; received: 67247 -> [Help 1]

**Comment by bjsbl** [comment]
切换到mvn-repo分支看看有么有

**Comment by cjeruen** [comment]
自己重新build 相关jar 已经解决.
