### ISSUE TITLE
switch-SH-NH-CNC-C3750G/switch-AntiDDoS/NetGraphBuilder.updateInterface(NetGraphBuilder.java:208) 

### ISSUE THREAD

**Issue by zhong12** [dianping/cat#1189]
执行一段时间cat-home 包这个空指针异常
switch-SH-NH-CNC-C3750G/switch-AntiDDoS/NetGraphBuilder.updateInterface(NetGraphBuilder.java:208)

**Comment by youyong205** [comment]
这个执行在新版本去掉了吧，没用的逻辑，点评内部特殊的，主要用于交换机监控

**Comment by zhong12** [comment]
好的，谢谢了
