### ISSUE TITLE
请问手机APP、浏览器到服务器是怎么监控的

### ISSUE THREAD

**Issue by jacobsy** [dianping/cat#1193]
看http://www.cctime.com/html/2016-8-25/1210947.htm 这里介绍第一层监控是指手机APP、和浏览器监控吗？开源项目里没有找到相关资料，能指导一下吗，谢谢。
![cat](https://user-images.githubusercontent.com/2225457/32936278-98782a66-cbae-11e7-93e6-521cd3377b82.jpg)

**Comment by youyong205** [comment]
这地方东西还比较多，没有open-source
