### ISSUE TITLE
被监听端一定要在data/appdatas/cat下创建client.xml吗？

### ISSUE THREAD

**Issue by xuqiming** [dianping/cat#1197]
我这边尝试使用Cat.initialize("ip")初始化但是似乎不起作用

**Comment by xuqiming** [comment]
我通过调试的方追踪代码的时候发现了META-INF/cat/client.xml这个目录
我创建了这个文件

<?xml version="1.0" encoding="utf-8"?>

<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
	<servers>
		
		<server ip="47.93.76.5" port="2280" http-port="8080" />
		
		
	</servers>

	<domain id="gailun" enabled="true" max-message-size="1000"/>
</config>

但是这个文件被读取的前提是META-INF/app.properties不存在

试了这种方式可以运行，似乎这种方式在文档中有没有提到，这样做会有什么问题吗

**Comment by birdie7761** [comment]
可以看一下，这个文档[https://github.com/dianping/cat/blob/master/%E6%A1%86%E6%9E%B6%E5%9F%8B%E7%82%B9%E6%96%B9%E6%A1%88%E9%9B%86%E6%88%90/Dianping%20CAT%20%E9%85%8D%E7%BD%AE%E5%8A%A0%E8%BD%BD%E8%AF%B4%E6%98%8E.md](url)
