### ISSUE TITLE
cat-home管理界面看不到matrix,depdendency

### ISSUE THREAD

**Issue by xbynet** [dianping/cat#1203]
我使用最新的master分支搭了个测试环境，管理界面看不到matrix,depdendency。其他的Transaction,Eevent之类的显示正常。
是因为我哪里没有配置好，还是因为是开源版本，这些功能被阉割了呢?

目前正在进行APM相关的技术调用，希望可以解答下。thanks。

**Comment by duguyixiaono1** [comment]
我的初浅理解，com.dianping.cat.analysis.DefaultMessageAnalyzerManager中把这两个分析器给删除了，见：
`@Override
	public void initialize() throws InitializationException {
		Map<String, MessageAnalyzer> map = lookupMap(MessageAnalyzer.class);

		for (MessageAnalyzer analyzer : map.values()) {
			analyzer.destroy();
		}

		m_analyzerNames = new ArrayList<String>(map.keySet());
		
		Collections.sort(m_analyzerNames, new Comparator<String>() {
			@Override
			public int compare(String str1, String str2) {
				String state = "state";
				String top = "top";

				if (state.equals(str1)) {
					return 1;
				} else if (state.equals(str2)) {
					return -1;
				}
				if (top.equals(str1)) {
					return -1;
				} else if (top.equals(str2)) {
					return 1;
				}
				return str1.compareTo(str2);
			}
		});
		
		m_analyzerNames.remove("matrix");
		m_analyzerNames.remove("dependency");
	}`

**Comment by xbynet** [comment]
谢谢你的解答 @duguyixiaono1  可是疑问仍在，取消注释应该也不可以吧(相关依赖已经被移除)？如果要开放这些功能需要什么条件呢？

**Comment by duguyixiaono1** [comment]
自己写分析器？

**Comment by qmwu2000** [comment]
这两个报表暂时给屏蔽了。这两个报表目前还不是很成熟，有些地方想的还不是很清楚，但系统资源消耗得有点大。


发自我的 iPhone

**Comment by xbynet** [comment]
谢谢 @duguyixiaono1 @qmwu2000 疑问已解决。
