### ISSUE TITLE
Sql异常：Table 'cat.app_speed_data_4' doesn't exist 

### ISSUE THREAD

**Issue by zzk1314** [dianping/cat#1213]
版本：2.0.0
时间：每天晚上的定时任务报错，xxx_2、3、4 doesn't exist
位置： DeleteTask | Speed
描述：源码的建表sql里有app_speed_data_1，但是没有2、3、4.
看源码这个任务是从m_config.getSpeeds()里拿到table后缀的id

**Comment by youyong205** [comment]
你可以尝试建一个表，不过也可以忽略掉。这个问题我记录下，后续fix下问题。

**Comment by duguyixiaono1** [comment]
遇到同样的问题，暂时先按照勇哥说的，创建一个表
