### ISSUE TITLE
客户端应用com.dianping.cat.message.io.TcpSocketSender对象过多，导致应用内存溢出，是怎么回事

### ISSUE THREAD

**Issue by zuxianghuang** [dianping/cat#1222]
![image](https://user-images.githubusercontent.com/7301534/36780288-859a04d2-1cad-11e8-9671-ee8977633d41.png)
![image](https://user-images.githubusercontent.com/7301534/36780295-8c9c26b6-1cad-11e8-9de6-17a5fa1d5b21.png)
![image](https://user-images.githubusercontent.com/7301534/36780304-8f783bea-1cad-11e8-9b5a-ff470f701063.png)

**Comment by youyong205** [comment]
是否存在transaction没有在finnaly里面关闭的情况

**Comment by zuxianghuang** [comment]
没有哦

**Comment by zuxianghuang** [comment]
如果cat服务是停止的就没有问题，如果服务是启动的，但是端口不通的情况就出现这个问题

**Comment by sun-jian** [comment]
应该是消息积压了吧，看看启动参数queue.size设置了多少

**Comment by zuxianghuang** [comment]
queue.size 是5000

**Comment by zuxianghuang** [comment]
![image](https://user-images.githubusercontent.com/7301534/37586080-34c065ea-2b96-11e8-9cce-4f28db44da1d.png)
客户端的cat日志
客服端的内存情况
![image](https://user-images.githubusercontent.com/7301534/37586115-4dc0eb64-2b96-11e8-8fc9-e29f23b81d0d.png)
![image](https://user-images.githubusercontent.com/7301534/37586119-53959bd4-2b96-11e8-9a3b-4785f1bede19.png)

**Comment by zuxianghuang** [comment]
我看代码，你们做了判断的，超过队列的max值，就不会加入了，我们用的默认值5000
按理来说不应该会有问题啊

**Comment by sun-jian** [comment]
确认下你用的CAT版本和启动参数吧

**Comment by sun-jian** [comment]
确认下启动参数吧，count只是统计数

**Comment by zuxianghuang** [comment]
启动参数是在哪，
我调试的时候，就是这个值
![image](https://user-images.githubusercontent.com/7301534/37589958-b4946d92-2ba1-11e8-8d5f-a59b35b1f194.png)

**Comment by zuxianghuang** [comment]
我现在的解决方法是修改这个StatusUpdateTask 类,
如果你们有好的解决方法，麻烦告知一下，

增加一个方法，判断是否能连接cat服务端。
private boolean isConnected = true;

	@Override
	public void run() {
		// try to wait cat client init success
		try {
			Thread.sleep(10 * 1000);
		} catch (InterruptedException e) {
			return;
		}

		while (true) {
			Calendar cal = Calendar.getInstance();
			int second = cal.get(Calendar.SECOND);

			// try to avoid send heartbeat at 59-01 second
			if (second < 2 || second > 58) {
				try {
					Thread.sleep(1000);
				} catch (InterruptedException e) {
					// ignore it
				}
			} else {
				break;
			}
		}

		try {
			buildClasspath();
		} catch (Exception e) {
			e.printStackTrace();
		}
		MessageProducer cat = Cat.getProducer();
		Transaction reboot = cat.newTransaction("System", "Reboot");

		reboot.setStatus(Message.SUCCESS);
		cat.logEvent("Reboot", NetworkInterfaceManager.INSTANCE.getLocalHostAddress(), Message.SUCCESS, null);
		reboot.complete();

		while (m_active) {
			long start = MilliSecondTimer.currentTimeMillis();

			if (m_manager.isCatEnabled() && isConnected) {
				Transaction t = cat.newTransaction("System", "Status");
				Heartbeat h = cat.newHeartbeat("Heartbeat", m_ipAddress);
				StatusInfo status = new StatusInfo();

				t.addData("dumpLocked", m_manager.isDumpLocked());
				try {
					StatusInfoCollector statusInfoCollector = new StatusInfoCollector(m_statistics, m_jars);

					status.accept(statusInfoCollector.setDumpLocked(m_manager.isDumpLocked()));

					buildExtensionData(status);
					h.addData(status.toString());
					h.setStatus(Message.SUCCESS);
				} catch (Throwable e) {
					h.setStatus(e);
					cat.logError(e);
				} finally {
					h.complete();
				}
				t.setStatus(Message.SUCCESS);
				t.complete();
			}
			long elapsed = MilliSecondTimer.currentTimeMillis() - start;

			if (elapsed < m_interval) {
				try {
					Thread.sleep(m_interval - elapsed);
				} catch (InterruptedException e) {
					break;
				}
				isConnected = isConnected();
			}
		}
	}

	private boolean isConnected(){
		String serverUrl = m_manager.getServerConfigUrl();
		try {
			URL url = new URL(serverUrl);
			URLConnection connection =  url.openConnection();
			connection.setConnectTimeout(10000);
			connection.connect();
			return true;
		} catch (Exception e) {
			//
			return false;
		}
	}

**Comment by youyong205** [comment]
你的情况大概还有一种可能性，就是单个请求消息size比较大，比如一个消息就快1M了，5000个也很大。

既然dump出来了，可以看到了每个消息的内容，看看5000个队列里面是啥，一般情况下要么transaction没有关闭，要么单个消息的size很大

**Comment by zuxianghuang** [comment]
Transaction t = Cat.newTransaction("URLHandle", uri);
Transaction t = Cat.newTransaction("View", viewName);

我们就拦截路径，和页面，没有其他的处理，
这个 消息应该不会很大，

**Comment by youyong205** [comment]
还有可能是不是transaction关闭顺序不对？5000个消息，无论如何，都不会撑死那么大内存。

除非个别很大，个别很大的原因就可能在一些极端情况下，transaction没有关闭，transaction关闭逻辑不是在finnaly里面

**Comment by zuxianghuang** [comment]
我们都是在拦截器的
afterCompletion方法里
调用Transaction的.complete(); 
afterCompletion 这个方法如果不执行 ，那就说明我们的程序有问题。

而我们程序没有问题 ，就说明afterCompletion  这个肯定执行了，.complete(); 这个也执行了
我们都有异常捕获，没有发现关于Transaction 的异常。

前面我说过的
如果cat服务是停止的就没有问题，如果cat服务是启动的，但是端口不通的情况就出现这个问题
是不是从这里去找原因

**Comment by youyong205** [comment]
cat 服务端停止和cat服务端端口不通，对于客户端逻辑没什么区别，客户端都是异步上报

**Comment by youyong205** [comment]
既然抓了现场了，可以用mat看看，每个消息是什么，为什么这么大，应该就找到线索了吧。

**Comment by zuxianghuang** [comment]
我那样改后，经过测试没有再那样的问题，现在过去这么长时间也没有再出现问题，
不管了，我就这么处理了

**Comment by wgqazll** [comment]
没有complete，message是不会加入到queue里的吧，那queue为什么那么大

**Comment by qmwu2000** [comment]
- 如果root transaction没有complete，消息不会放到queue中
- 如果所有transaction都不complete，在同一线程内可能会构造出一个很深的消息树，会占用大量内存
- 如果queue中有很多大的消息（如心跳消息）没有及时发出去，也会占用大量内存


发自我的 iPhone

**Comment by wgqazll** [comment]
如果root transaction complete了，但是中间有一个嵌套的transaction没有complete，这是message会被放到队列，但是整个树是不完整的，cat会内存溢出吗？ @qmwu2000

**Comment by qmwu2000** [comment]
会。cat会处理好这种场景的，消息树还是完整的，不会产生内存溢出。


发自我的 iPhone
