### ISSUE TITLE
可疑的空指针解引用

### ISSUE THREAD

**Issue by ddj0509** [dianping/cat#1225]
Hi，
   我们的源代码静态分析工具 Pinpoint 检测到一处可疑的空指针解引用：

https://github.com/dianping/cat/blob/6f5204bf4704ae91c75750b27a750b5a12df992d/cat-home/src/main/java/com/dianping/cat/report/page/heartbeat/service/LocalHeartbeatService.java#L54-L70

在Line 54 report被赋值为null，在Line 65 report == null 并且 period.isLast()的值为false时，不会进入 Line 65的branch，导致report依然为null，传递给Line 70 filterReport的第二个参数，在Line 40 filterReport里面会触发NPD.
https://github.com/dianping/cat/blob/6f5204bf4704ae91c75750b27a750b5a12df992d/cat-home/src/main/java/com/dianping/cat/report/page/heartbeat/service/LocalHeartbeatService.java#L36-L40

祝好，
Sourcebrella Inc.

**Comment by youyong205** [comment]
看起来是的~

**Comment by ddj0509** [comment]
嗯嗯，欢迎试用一下我们的产品，协助修复更多的bugs~
