### ISSUE TITLE
实时数据不显示，可显示1小时的数据。

### ISSUE THREAD

**Issue by sizeof1234** [dianping/cat#1227]
如题，实时数据（点击【now】）没有数据展示，但是点击上一小时有数据，可能是什么原因？谢谢。

**Comment by zhuhuogeng** [comment]
应该是当前小时client没有数据上报，可以看看client是不是挂了

**Comment by sizeof1234** [comment]
应该不是client挂了，因为1小时后历史数据是可以出来的。后来重启了一下整个服务器好了。

**Comment by Lovnx** [comment]
也被这个问题困扰了许久，最初以为是动源码加功能把东西改坏了，后面做了两件事情就恢复如初：
1）集群里面tomcat不要以debug模式启动
2）集群war包保持一致，不要一个是初始版本，一个又是你的改动版本
