### ISSUE TITLE
已经接入，就是没数据

### ISSUE THREAD

**Issue by jinyingone** [dianping/cat#1228]

**Comment by biantech** [comment]
我也遇到这个问题，在server 端看不到接入的数据。代码如下 
public class App 
{
	static String appName="AppCatNameTest";
	static String serverIP="";
	public static void main( String[] args ) throws InterruptedException
    {
		App app= new App();
		for(int i=0;i<1000;i++) {
			app.testFunc();
			Thread.sleep(1000);
		}
		//System.in.read();
		//System.in.read();
    }
	
	public void testFunc() {
		Transaction tran=null;
		try {
			tran=Cat.newTransaction("CatAppName", appName);
			System.out.println( "Hello World!" );			
			Cat.logEvent("URLTest.TestServer", "127.0.0.1",Event.SUCCESS,"ip=server"+serverIP+"&test");
			Cat.logMetricForCount("TestMetric", 1);
			tran.setStatus(Message.SUCCESS);						
		}finally {
			if(tran!=null) {
				tran.complete();
			}
		}
	}
}

**Comment by youyong205** [comment]
你在test最后面sleep一段时间，cat是异步线程发送，这样主线程结束了，来不及发送就结束了
