### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 2 ，com.dianping.cat.service.IpService.initAreaMap(IpService.java:162

### ISSUE THREAD

**Issue by biantech** [dianping/cat#1229]
| java.lang.ArrayIndexOutOfBoundsException: 2 	at com.dianping.cat.service.IpService.initAreaMap(IpService.java:162) 	at com.dianping.cat.service.IpService.initialize(IpService.java:257) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) 	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) 	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) 	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) 	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) 	at org.unidal.lookup.container.ComponentManager.lookupMap(ComponentManager.java:118) 	at org.unidal.lookup.container.MyPlexusContainer.lookupMap(MyPlexusContainer.java:98) 	at org.unidal.lookup.ContainerHolder.lookupMap(ContainerHolder.java:53) 	at com.dianping.cat.report.page.model.Handler.initialize(Handler.java:92) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) 	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) 	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) 	at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:83) 	at org.unidal.lookup.ContainerHolder.lookup(ContainerHolder.java:33) 	at org.unidal.lookup.ContainerHolder.lookup(ContainerHolder.java:28) 	at org.unidal.web.mvc.model.ModelManager.buildModuleFromHandlers(ModelManager.java:181) 	at org.unidal.web.mvc.model.ModelManager.buildModule(ModelManager.java:173) 	at org.unidal.web.mvc.model.ModelManager.build(ModelManager.java:79) 	at org.unidal.web.mvc.model.ModelManager.register(ModelManager.java:337) 	at org.unidal.web.mvc.model.ModelManager.initialize(ModelManager.java:320) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$4.handleStart(ComponentHandlers.java:88) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) 	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) 	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) 	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) 	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle$ComponentContext.lookup(ComponentLifecycle.java:90) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.injectField(ComponentHandlers.java:336) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$RequirementInjector.inject(ComponentHandlers.java:262) 	at org.unidal.lookup.container.lifecycle.ComponentHandlers$1.handleStart(ComponentHandlers.java:36) 	at org.unidal.lookup.container.lifecycle.ComponentLifecycle.start(ComponentLifecycle.java:47) 	at org.unidal.lookup.container.ComponentBox.lookup(ComponentBox.java:103) 	at org.unidal.lookup.container.ComponentManager.lookup(ComponentManager.java:94) 	at org.unidal.lookup.container.MyPlexusContainer.lookup(MyPlexusContainer.java:83) 	at org.unidal.web.AbstractContainerServlet.lookup(AbstractContainerServlet.java:68) 	at org.unidal.web.MVC.initComponents(MVC.java:36) 	at org.unidal.web.AbstractContainerServlet.init(AbstractContainerServlet.java:47) 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091) 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:983) 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4939) 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5249) 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1141) 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)
-- | --

比较好的解决方案是判断一下。 
``
private void initAreaMap(InputStream areaFile) {
		try {
			BufferedReader areaReader = new BufferedReader(new InputStreamReader(areaFile));
			String line;
			String[] strs;
			int id;
			m_areas = new LinkedHashMap<Integer, Area>();

			while ((line = areaReader.readLine()) != null) {
				strs = line.split(":");
				id = Integer.parseInt(strs[1]);

				String[] areaStr = strs[0].split("\\|");
				Area area = new Area();
				**if(areaStr.length>=3) {**
					area.setAreaId(id);
					area.setNation(areaStr[0]);
					area.setProvince(areaStr[1]);
					area.setCity(areaStr[2]);
					m_areas.put(id, area);
				**}**
			}
			areaReader.close();
		} catch (Exception e) {
			Cat.logError(e);
		}
	}

**Comment by youyong205** [comment]
麻烦提交个PR看看~不过这部分代码也用不到了~服务端端相关监控用不到这个
