### ISSUE TITLE
中智上海www.ciicsh.com

### ISSUE THREAD

**Issue by uncarman2017** [dianping/cat#1236]
部署好三个服务节点tomcat 8.5+cat war包。
客户端配置文件：/data/appdatas/cat/client.xml
服务端配置文件：/data/appdatas/cat/client.xml, server.xml, datasource.xml

**client.xml内容如下：**
<?xml version="1.0" encoding="utf-8"?>
<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
        <servers>
                
                <server ip="172.16.9.12" port="2280" http-port="8080" />
                <server ip="172.16.9.23" port="2280" http-port="8080" />
                <server ip="172.16.9.28" port="2280" http-port="8080" />
        </servers>
</config>

**server.xml内容如下：**
<?xml version="1.0" encoding="utf-8"?>
<config local-mode="false" hdfs-machine="false" job-machine="false" alert-machine="false">
        <storage local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
        </storage>
        <console default-domain="Cat" show-cat-domain="true">
                <remote-servers>172.16.9.12:8080,172.16.9.23:8080,172.16.9.28:8080</remote-servers>
        </console>
        
</config>

**datasource.xml内容如下：**
<?xml version="1.0" encoding="utf-8"?>
<data-sources>
        <data-source id="cat">
                <maximum-pool-size>3</maximum-pool-size>
                <connection-timeout>1s</connection-timeout>
                <idle-timeout>10m</idle-timeout>
                <statement-cache-size>1000</statement-cache-size>
                <properties>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url><![CDATA[jdbc:mysql://172.16.9.23:3306/cat]]></url>
                        <user>root</user>
                        <password>123456</password>
                        <connectionProperties><![CDATA[useUnicode=true&autoReconnect=true]]></connectionProperties>
                </properties>
        </data-source>
        <data-source id="app">
                <maximum-pool-size>3</maximum-pool-size>
                <connection-timeout>1s</connection-timeout>
                <idle-timeout>10m</idle-timeout>
                <statement-cache-size>1000</statement-cache-size>
                <properties>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url><![CDATA[jdbc:mysql://172.16.9.23:3306/cat]]></url>
                        <user>root</user>
                        <password>123456</password>
                        <connectionProperties><![CDATA[useUnicode=true&autoReconnect=true]]></connectionProperties>
                </properties>
        </data-source>
</data-sources>

客户端调用CAT api的代码如下，执行多次，在cat界面查不到任何记录，请教原因。

`String serverIp = "172.16.4.128";
        double amount = 1000;
        Transaction t = Cat.newTransaction("TestURL",msg);

        try{

            Cat.logEvent("TestURL.Server",serverIp);
            Cat.logMetricForCount("PayCount");
            Cat.logMetricForSum("PayAmount",amount);
            t.setStatus(Transaction.SUCCESS);
        }
        catch (Exception ex){
            t.setStatus(ex);
            return "KO";
        }
        finally {
            t.complete();
        }`

**Comment by uncarman2017** [comment]
tail -f /data/applogs/cat/cat_20180504.log
有如下warning
[05-04 19:01:46.967] [WARN] [TcpSocketSender] Netty write buffer is full! Attempts: 16628000
[05-04 19:01:54.231] [WARN] [TcpSocketSender] Netty write buffer is full! Attempts: 16543000
[05-04 19:01:57.281] [WARN] [TcpSocketSender] Netty write buffer is full! Attempts: 16629000
[05-04 19:02:04.531] [WARN] [TcpSocketSender] Netty write buffer is full! Attempts: 16544000
[05-04 19:02:05.746] [INFO] [TcpSocketSender] close channel /172.16.9.28:2280

**Comment by youyong205** [comment]
xml 内容看不到，另外先可以确认下cat这个domain是不是有数据。确保服务端没问题。

另外集成的时候也需要看下有没有app.properties文件指定项目名

**Comment by youyong205** [comment]
之前还遇到过一些服务端因为linux版本太老，nio 2280端口都开启不了的情况

**Comment by youyong205** [comment]
检查下服务端2280端口开启情况，telnet serverip 2280试试

**Comment by uncarman2017** [comment]
我这边cat部署在cent OS 7 下。
之前在windows10下跑java程序(cat客户端), 刚用telnet 172.16.9.12:2280 失败。是通讯故障。
另外想确认3个问题如下：
1. cat客户端（即打包了cat client jar包的应用）的/data/appdatas/cat目录下是否放置client.xml即可，另外两个配置文件 server.xml和datasource.xml是否放在服务端/data/appdatas/cat目录下？

2. cat的界面和ws服务是放在一个war部署的，tomcat 8.5是否能支持？

3. server.xml 中是否可以配置多个服务节点？

**Comment by uncarman2017** [comment]
已经搞定了多节点cat部署。现在还有1个问题：
server.xml中config节点的job-machine和alert-machine的用途？
