### ISSUE TITLE
最新版本报错： PluginResolutionException

### ISSUE THREAD

**Issue by kenWu-github** [dianping/cat#1237]
Failed to execute goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model (generate data model) on project cat-client: Execution generate data model of goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model failed: Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.5.8 or one of its dependencies could not be resolved: Could not find artifact org.codehaus.plexus:plexus-container-default:jar:3.1.0 in CN

**Comment by youyong205** [comment]
Could not find artifact org.codehaus.plexus:plexus-container-default:jar:3.1.0  是你本地的mvn环境配置问题吧。

**Comment by dreamyteam** [comment]
@youyong205 我觉得你可以找一台新的电脑按照提供的文档俩试试，的确会报上面的错

**Comment by dreamyteam** [comment]
在自己的nexus里面增加一个到http://unidal.org/nexus/content/repositories/releases/的proxy就可以了

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/40774672-c876969c-64f8-11e8-813d-88b45f22f8ed.png)

我本地重新弄了settings 以及 新download的，没啥问题。

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/40774714-e466b5ee-64f8-11e8-90a2-f309f34dd264.png)

相关的jar都是从pom里面配置的cat自己搭建的公网仓库里面下载的。
