### ISSUE TITLE
配置中的项目分组配置如何填写

### ISSUE THREAD

**Issue by uncarman2017** [dianping/cat#1243]
点击右上方配置按钮，进入系统配置模块。 有3个问题如下：
1.点击左侧导航栏的项目基本信息，在这个页面是否可以填入应用信息，也就是出现在首页最上方搜索框的信息？
2.点击左侧导航栏的项目分组配置，进入项目分组配置页面。
出现了业务监控，外部监控，应用监控，网络监控，系统监控，数据库监控，CDN监控7个页签，请问这7个页签中的内容如何填写。
3.在这些页面中提交的中文信息，在页面呈现时出现乱码，如何解决? 服务器环境是Cent OS 7, Web容器为Tomcat 8.5.

**Comment by youyong205** [comment]
1.项目信息会后台根据自动加入的项目，自动插入到数据库
2.业务监控需要把一些项目设置为产品线，其他的都不需要，之前是内部的一些分组
3.乱码问题自己看看下吧，和cat没关系

**Comment by youyong205** [comment]
另外可以拉下最新代码，已经把一些干扰项排除掉
