### ISSUE TITLE
关于菜单配置-全局告警配置-告警服务端中的配置

### ISSUE THREAD

**Issue by uncarman2017** [dianping/cat#1250]
进入配置-全局告警配置-告警服务端，如下为邮件，微信，短信的告警配置，如果我没有理解错的话，这三种告警都要调用一个外部的web服务来实现。我的问题是，比如邮件告警服务接口，其请求报文而是是否和以下<sender id="mail">区段的信息一一对应，请问请求报文的格式具体怎样的，JSON格式？
`<?xml version="1.0" encoding="utf-8"?>
<sender-config>
   <sender id="mail" url="http://mail.ciicsh.com/" type="post" successCode="200" batchSend="true">
      <par id="type=1500"/>
      <par id="key=title,body"/>
      <par id="re=yujiawei@ciicsh.com"/>
      <par id="to=${receiver}"/>
      <par id="value=${title},${content}"/>
   </sender>
   <sender id="weixin" url="http://test/" type="post" successCode="success" batchSend="true">
      <par id="domain=${domain}"/>
      <par id="email=${receiver}"/>
      <par id="title=${title}"/>
      <par id="content=${content}"/>
      <par id="type=${type}"/>
   </sender>
   <sender id="sms" url="http://test/" type="post" successCode="200" batchSend="false">
      <par id="jsonm={type:808,mobile:'${receiver}',pair:{body='${content}'}}"/>
   </sender>
</sender-config>`

**Comment by youyong205** [comment]
请看下源码的类 MailSender，其实就是把几个关键的内容替换，key-value post或者get

**Comment by uncarman2017** [comment]
已解决

**Comment by luis-wang** [comment]
这个sender的url属性里，是要自己写的发送邮件的服务呢还是已经有的？没有看懂
