### ISSUE TITLE
项目配置信息无法提交保存

### ISSUE THREAD

**Issue by yangzhilong** [dianping/cat#1252]
操作路径：项目配置信息-项目分组配置-新增。
经过查看网页HTML源码发现隐藏属性TYPE的值乱码了。
### <tr>
	<td style="width:20%;text-align: right" class="text-success">产品线名称（全英文）</td>
	<td><input type="text" name="productLine.id" value="" required="">
		<input name="type" value="ä¸å¡çæ§" type="hidden">	
	</td>
</tr>
该文件为git直接下来后未编辑的，看了文件编码是utf-8，jsp里的charset也是utf-8，
我去http://unidal.org/cat上操作发现也是无法保存的，通过浏览器F12把那个hidden的input里的值乱码修正成正常文本<业务监控>后可以保存成功，但是编辑的时候那个页面也还是空白的。

不知道这个需要调整哪些地方来解决？期望回答，谢谢

**Comment by youyong205** [comment]
这个乱码问题，tomcat一些参数什么不太对吧。搜索下tomcat乱码

**Comment by yangzhilong** [comment]
恩，是需要调整tomcat的编码
