### ISSUE TITLE
cat-client无法初始化加载

### ISSUE THREAD

**Issue by asreal** [dianping/cat#1253]
各位大神好，

目前正在测试接入cat，服务端能正常启动并登录，但客户端无法初始化加载。

具体现象如下：
项目正常启动，但在/data/applogs/cat/下没有生成日志文件，在tomcat日志里可以看到CatFilterConfigure正常加载了，但没有看到关于cat-client的加载信息。
11:48:07,303 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:48:07,304 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5ab6c766 - Registering current configuration as safe fallback point

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.4.RELEASE)

###################CatFilter###############
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
31-May-2018 11:48:14.879 信息 [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/develop/tomcat-app-front/webapps/app-front.war] has finished in [10,780] ms
31-May-2018 11:48:14.883 信息 [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8060"]
31-May-2018 11:48:14.895 信息 [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8069"]
31-May-2018 11:48:14.897 信息 [main] org.apache.catalina.startup.Catalina.start Server startup in 10860 ms

pom.xml里正常引用了cat-client，打包后也看到了已经打入lib。
`<dependency>
<groupId>com.dianping.cat</groupId>
<artifactId>cat-client</artifactId>
<version>2.0.0</version>
</dependency>`

也配置了/data/appdatas/cat/client.xml和META/INF/app.properties，但配不配置这2个应该都不影响cat-client在项目里初始化加载和cat日志文件生成吧。

请各位大神帮忙看看是什么原因造成的。
谢谢。

**Comment by youyong205** [comment]
你这个看起来是没有调用到任何cat的api吧。

都没有走到cat的代码逻辑

**Comment by asreal** [comment]
我是参考的集成文档里方式来做的。
按道理来说，起码启动后应该会在/data/applogs/cat下生成一个日志文件吧，现在连这个日志文件都没有 T_T

**Comment by asreal** [comment]
额。。再说明一下，我在本地IDEA跑没问题，部署上linux服务器就没反应了。。

**Comment by youyong205** [comment]
那你检查下linux环境问题看看，本地和linux理论没什么区别。

**Comment by asreal** [comment]
换了一台linux服务器也一样没有加载。。我再瞅瞅看吧，谢谢指导。

**Comment by jjeejj** [comment]
@asreal /data/applogs/cat下应该生成一个日志文件 , 但是实际没有生成，我也遇到这样的问题了，请问你的问题解决了吗？

**Comment by yangBin666** [comment]
同样遇到这个问题，springboot 的应用，本地无法加载cat，日志也未生成，该有的配置都有，jar也有
cat-client-3.0.0
