### ISSUE TITLE
源代码缺少ClientConfig、Domain、Server、DefaultValidator等类

### ISSUE THREAD

**Issue by 435242634** [dianping/cat#1255]
cat-client 模块下少了代码com.dianping.cat.configuration.client.entity.ClientConfig、com.dianping.cat.configuration.client.entity.Domain、com.dianping.cat.configuration.client.entity.Server、com.dianping.cat.configuration.client.transform.DefaultValidator这些类源代码里都没有

**Comment by youyong205** [comment]
请参考下首页说明

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/41187783-59975b9c-6be4-11e8-9984-b12784a30e94.png)
