### ISSUE TITLE
localhost和127.0.0.1返回结果不一样

### ISSUE THREAD

**Issue by OopsVIP** [dianping/cat#1256]
如图，为啥两个返回结果不一样呢？ping可以发现localhost就是127.0.0.1啊
![image](https://user-images.githubusercontent.com/29219681/41027756-7de364d2-69aa-11e8-859e-a76e64d31f4e.png)
![image](https://user-images.githubusercontent.com/29219681/41027771-88fc658a-69aa-11e8-810b-b6196b4132b1.png)
![image](https://user-images.githubusercontent.com/29219681/41027841-ab2c8b58-69aa-11e8-9266-125b26c0bdff.png)

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/41187777-3c6b6e5a-6be4-11e8-9731-19727a049fc2.png)

**Comment by youyong205** [comment]
你这个看的时间片段都不是一个时间段~
