### ISSUE TITLE
配置-应用监控配置-Transaction告警保存新记录异常

### ISSUE THREAD

**Issue by uncarman2017** [dianping/cat#1259]
配置-应用监控配置-Transaction告警页面保存新记录异常，页面跳转到
http://172.16.9.23:8080/cat/s/config?op=transactionRuleSubmit&configs=[{%22conditions%22:[{%22sub-conditions%22:[{%22type%22:%22SumMaxVal%22,%22text%22:%22200%22}],%22minute%22:%222%22,%22alertType%22:%22error%22}],%22starttime%22:%2200:00%22,%22endtime%22:%2224:00%22}]&ruleId=10000001;URL;All;avg
报http 400错误
打开浏览器调试窗口-Network:
Headers信息如下：
Request URL: http://172.16.9.23:8080/cat/s/config?op=transactionRuleSubmit&configs=[{%22conditions%22:[{%22sub-conditions%22:[{%22type%22:%22SumMaxVal%22,%22text%22:%22200%22}],%22minute%22:%222%22,%22alertType%22:%22error%22}],%22starttime%22:%2200:00%22,%22endtime%22:%2224:00%22}]&ruleId=10000001;URL;All;avg
Request Method: GET
Status Code: 400 
**Remote Address: 127.0.0.1:41579**
Referrer Policy: no-referrer-when-downgrade

**Comment by owenliang** [comment]
+1，不明真相

**Comment by youyong205** [comment]
400的错误，说明还没有到服务端。
应该是tomcat的版本或者配置问题，请按照首页文档，J2EE容器建议使用tomcat，建议版本7.0.70

**Comment by 839284824** [comment]
遇到了同样的问题，楼主解决没？
