### ISSUE TITLE
配置-应用监控配置-业务监控配置异常

### ISSUE THREAD

**Issue by uncarman2017** [dianping/cat#1260]
进入业务监控配置页面，左侧出现产品线导航栏，右侧居然空白一片，没有出现说明文档中的业务监控配置界面。

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/41818908-220b5108-77ea-11e8-9012-fd4408c4e03a.png)

文档就是在首页里面文档里面
