### ISSUE TITLE
CAT中应用项目的Transaction指标只出现了System类型记录

### ISSUE THREAD

**Issue by uncarman2017** [dianping/cat#1261]
点击CAT中各个应用项目的Transaction指标，居然只只出现了System类型记录。自己埋点的URL.Method指标都没有出现。这可能是什么错误原因导致的？

**Comment by qmwu2000** [comment]
URL.Method应该是Event吧，在event报表中可以找到。


发自我的 iPhone

**Comment by uncarman2017** [comment]
前面搞错了，URL.Method,URL.Host都是我们埋下来的自定义event指标。
但现在遇到的问题是，项目内置的Transaction指标如URL, MVC, SQL都没有了，现在只剩下System一个指标。
不过内置的cat这个项目的Transaction，Event指标是全的。我这边也不知道什么原因。

**Comment by youyong205** [comment]
这个可能你项目里面的transaction没有关闭吧，没有在finnaly里面关闭。

**Comment by youyong205** [comment]
你这个可以debug下客户端的埋点部分，看看是否把消息放到队列里面，一般在最外层的transaction关闭会放入队列。
