### ISSUE TITLE
cat-client 在netty  4.1.24 出现内存泄漏

### ISSUE THREAD

**Issue by xmh51** [dianping/cat#1266]
升级netty  版本后，系统报netty内存分配失败的错误，追踪下来 可能是  ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer(10 * 1024);    .....   TcpSocketSender  channel.writeAndFlush(buf);  有问题，未释放buf导致的

**Comment by youyong205** [comment]
你check下/data/applogs/cat/*.log  是否存在异常log

**Comment by youyong205** [comment]
4.1.24 netty的官方版本有个小bug，但是出现的概率比较低，如果碰到的话，你可以升级4.1.25 try

**Comment by youyong205** [comment]
升级netty 版本后，你之前本身就用netty，是不是其他地方内存也有泄露的问题。这个版本我们在生产验证很多次了。

**Comment by youyong205** [comment]
我们生产4.0.24  4.1版本没有正式测试过，内部都是4.0.24

**Comment by xmh51** [comment]
我猜测是这样的。 4.1 netty 修改了 ByteBuff 的底层实现  之前是依赖 jdk的回收的，现在改成需要手动回收了。详见 
  https://lishoubo.github.io/2017/11/03/%E5%85%B3%E4%BA%8ENetty%E7%9A%84OutOfDirectMemoryError/

而PooledByteBufAllocator 会产生一个ThreadLocal cache ByteBuff 对象再加上 channel.writeAndFlush 是异步过程。导致里面即使释放，也不能释放ByteBuff

**Comment by visionsky1986** [comment]
你把所有使用ByteBuf的地方显式释放掉试试~

**Comment by tongfeifan** [comment]
我也遇到了同样的情况，我是将netty版本升到了 4.1.33.Final 后出现的。

**Comment by xmh51** [comment]
> 我也遇到了同样的情况，我是将netty版本升到了 4.1.33.Final 后出现的。

可能是netty升级版本后切换了默认DirectMemory实现方式，解决方案是  -附加 
 io.netty.recycler.maxCapacity=0  指定DirectMemory分配类，指定后的类会自带cleaner，释放DirectMemory

**Comment by tongfeifan** [comment]
> > 我也遇到了同样的情况，我是将netty版本升到了 4.1.33.Final 后出现的。
> 
> 可能是netty升级版本后切换了默认DirectMemory实现方式，解决方案是 -附加
> io.netty.recycler.maxCapacity=0 指定DirectMemory分配类，指定后的类会自带cleaner，释放DirectMemory

嗯，我也定位到这个地方了，我验证一下。
