### ISSUE TITLE
源码里为什么好多类找不到？

### ISSUE THREAD

**Issue by gavinage** [dianping/cat#1267]
比如如下的：
import com.dianping.cat.consumer.storage.model.entity.Operation;
import com.dianping.cat.consumer.storage.model.entity.Segment;
import com.dianping.cat.consumer.storage.model.entity.StorageReport;
import com.dianping.cat.helper.TimeHelper;
import com.dianping.cat.home.rule.entity.Condition;
import com.dianping.cat.home.rule.entity.Config;
import com.dianping.cat.home.rule.entity.Rule;

**Comment by qmwu2000** [comment]
请在命令行下用mvn命令做构建

发自我的 iPhone

**Comment by youyong205** [comment]
这段文字在首页的readme里面

6、导入eclipse发现找不到类
请先执行mvn eclipse:eclipse 会自动生成相关的类文件
作为普通项目导入eclipse，不要用作为maven项目导入eclipse
