### ISSUE TITLE
Cat这几年没有大的版本升级，是很稳定了还是？

### ISSUE THREAD

**Issue by JaryZhen** [dianping/cat#1269]

**Comment by qmwu2000** [comment]
- CAT本身是非常稳定的，与之前在大众点评内部用的版本基本是一致的
- 事实上CAT一直在快速演进，尤其是在点评和携程内部。但是它们是在自己的仓库内进行，很难合并到master分支
- 由于CAT的公司覆盖越来越广，我们会对CAT使用体验相关的问题做一些跟踪和优化，欢迎大家提issue
- 将来我们还是会将其他仓库/分支内的受欢迎的功能合并进来

谢谢关注！

发自我的 iPhone
