### ISSUE TITLE
problem报表中的samplelinks是按时间升序排列的吗？

### ISSUE THREAD

**Issue by duguyixiaono1** [dianping/cat#1275]
![wechatimg79](https://user-images.githubusercontent.com/2703461/42370301-fdd16f62-813e-11e8-9343-75773428e645.jpeg)

如图，samplelinks是按照时间升序排列的吗？
看代码只有按照type name/status count排序，links中的时间信息已丢，比如多台机器的samplelinks合并后，是不是就不是按照时间排序了？

**Comment by youyong205** [comment]
没有规律，内部实现就是list的合并。
如果想看单台机器，可以选择一台机器的IP选择看一台机器的错误信息

**Comment by duguyixiaono1** [comment]
勇哥，美团点评内部用户没有反馈过这个问题吗？
用户场景：
异常告警触发，用户习惯找最后一个samplelink，但是进去发现，时间戳不对。
这种场景，美团点评内部，是教育用户？还是有什么方案重构？

**Comment by youyong205** [comment]
最多给60个samplelink，不会给太多的链接的。
同样的异常，在同一个小时，往往错误都是一样的，没什么区别的。

另外可以选择单台机器的page，弄到最下方，有个thread相关，可以根据分钟就看problem数据，注意，需要选择确定的IP

**Comment by duguyixiaono1** [comment]
ok 谢谢勇哥 明白了
