### ISSUE TITLE
“Database报表-系统指标” 怎么才能搞出来？

### ISSUE THREAD

**Issue by duguyixiaono1** [dianping/cat#1276]
![image](https://user-images.githubusercontent.com/2703461/42624083-14fd98e8-85f7-11e8-8055-af453c06241d.png)

通过productline和group查的逻辑大致明白，但没看到写报表的逻辑，不在MetricAnalyzer里吧？
怎么才能搞出来呢？

**Comment by youyong205** [comment]
系统指标不在cat的范围内，另外可以pull下最新的版本。

之前是把db一些内部系统指标和cat做了集成，这部分不适合开源。
