### ISSUE TITLE
Transaction url 概况total数量和明细total数量对不上

### ISSUE THREAD

**Issue by 839284824** [dianping/cat#1277]
URL概况total数量有12,274条，点开URL的明细发现只有10,779条。相差的条数为什么没有展示呢？求解答

**Comment by qmwu2000** [comment]
一般应该是一样的，除非由于URL的个数太多，只展示了一部分。


发自我的 iPhone

**Comment by 839284824** [comment]
想请问下有的domain的历史数据正常，但是有的domain的历史数据概况只 显示一个总条数，点进去全部是空，这种问题一般有什么排查思路么？

**Comment by youyong205** [comment]
cat埋点不支持中文，如果是中文的会被全部过滤掉，不知道是不是这个原因

**Comment by 839284824** [comment]
埋点是用的中文的，但是当前一个小时的实时数据时可以显示中文的，但是历史数据不可以显示，定时任务合同报表的时候会把中文的全部过滤掉吗？求解答，谢谢！

**Comment by youyong205** [comment]
存储时候会过滤掉所有的中文。

**Comment by 839284824** [comment]
好的，多谢反馈！我把中文去掉试一下！

**Comment by 839284824** [comment]
果然是中文埋点的问题！谢谢指导
