### ISSUE TITLE
关系back-server的疑问

### ISSUE THREAD

**Issue by spenxu** [dianping/cat#1282]
如果10.1.1.1作为back-server,按照文档说的10.1.1.1将不作为消费机消费messagetree,但是如果我在client.xml中配置了10.1.1.1。这时候客户端会连接到10.1.1.1吗？会上报messageTree到10.1.1.1吗？10.1.1.1会处理吗？如果会的话配置back-server有什么意义？

**Comment by duguyixiaono1** [comment]
client.xml的作用：
1）用来选一台服务器去读客户端路由配置
2）如果客户端路由没有配置，选择的那台作为所有domain的消费机

**Comment by youyong205** [comment]
cat服务端会返回三个服务节点给业务，最后一个是backup-server~一般情况用不到。

另外通过client.xml 里面的ip会在拿一次路由，并不是以client.xml 为准。
