### ISSUE TITLE
谁有压测数据可以分享吗？

### ISSUE THREAD

**Issue by duguyixiaono1** [dianping/cat#1283]
有以下压测数据可以分享吗？
1）单台server处理消息qps、天级消息总量、连接数
2）单台server处理消息量和磁盘空间的关系
3）mysql容量和消息量之前的关系

或者，
1）如何规划server 的磁盘容量？可同时处理多少业务？可同时处理多大的消息qps？
2）如何规划mysql的容量增长？

**Comment by youyong205** [comment]
这个东西其实和很多东西相关，不好一概而论。
包括机器也有性能差异，大公司内部同一批次机器都有差异。
这个和业务项目打点也有很大关系等。

最好根据实际的线上运营经验来做一些压测，比如说把多个项目导流到一台catserver，来测试下极限。
