### ISSUE TITLE
美团cat源码检出配置pom文件${releases.repo}报错

### ISSUE THREAD

**Issue by hoofungson** [dianping/cat#1284]
检出项目源码后在idea中报错，具体报错源码行：
`<distributionManagement>
        <repository>
            <id>releases</id>
            <url>${releases.repo}</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            <url>${snapshots.repo}</url>
        </snapshotRepository>
    </distributionManagement>`
其中的${releases.repo} 和 ${snapshots.repo} 提示没有声明，找不到该配置。

**Comment by youyong205** [comment]
请拉取最新master代码~
