### ISSUE TITLE
最新的版本logview无法显示

### ISSUE THREAD

**Issue by justciffer** [dianping/cat#1285]
把ByteBuf相关的代码回滚后就能正常显示

**Comment by guoqing228** [comment]
下载最新的代码logview提示：“Sorry, the message is not there. It could be missing or archived.“
能详细说一下怎么做吗？
初学者，多包涵！

**Comment by drone789** [comment]
点击logview 同样遇到"Sorry, the message is not there. It could be missing or archived." 这个问题。

**Comment by youyong205** [comment]
我来check下，之前合并了一个commit。

**Comment by youyong205** [comment]
代码我已经回滚，sry，麻烦拉下最新的code~
