### ISSUE TITLE
mysql数据量什么时候需要考虑分库分表？

### ISSUE THREAD

**Issue by duguyixiaono1** [dianping/cat#1286]
几个T的数据量，单个数据库能抗住吗？
有经验可以分享下吗？

**Comment by youyong205** [comment]
看看具体业务场景，我们这边是分库的。

**Comment by duguyixiaono1** [comment]
勇哥 开源版本的大表也就那几张 场景可能比较普遍 
能分享一下经验吗？比如，多大量级时会出现什么问题？然后怎么优化解决的吗？数据量更大之后又如何之类的吗？

**Comment by duguyixiaono1** [comment]
主要是出于大规模推广到线上前的考虑 求分享经验

**Comment by youyong205** [comment]
刚刚开始就是删除数据，后面我们就是按照时间进行切分。一个月一张表。其实也简单
