### ISSUE TITLE
历史模式下problem报表没有内容

### ISSUE THREAD

**Issue by usc** [dianping/cat#1288]
btw. job-machine="true" 已经设置

**Comment by youyong205** [comment]
这个需要过一天才有数据的，历史模式

**Comment by usc** [comment]
已经很多天了，
看看官方的cat，也是一样没有的 <http://unidal.org/cat/r/p?op=history&domain=cat&ip=All>

**Comment by yuweibo** [comment]
看一个日报计算的时间可能比较长，过了一个多小时计算好了，有办法解决么

**Comment by youyong205** [comment]
这个一般是夜里计算吧，这个设计上就是延迟出日报表，至于好办法，就多弄点task机器算了。

**Comment by yuweibo** [comment]
get,thanks
