### ISSUE TITLE
problem页面的 long-cache查询不起作用

### ISSUE THREAD

**Issue by zhanghao001** [dianping/cat#1289]
如题
<img width="982" alt="2018-08-17 11 15 10" src="https://user-images.githubusercontent.com/12950169/44246116-09f41380-a20f-11e8-97f0-ad9f8426c15c.png">
我测了下,其他都是ok的..还有一个小问题, type=Service时,左边的颜色块没有,看了下代码,是/cat-home/webapps/css/bady.css下少了 a.service的class配置

**Comment by youyong205** [comment]
transaction的type只有一部分，业务最后打印的transaction type可能非常多，没有办法都加css。

就一些常用有一些格式。
