### ISSUE TITLE
否支持Nginx日志收集

### ISSUE THREAD

**Issue by ycy1991** [dianping/cat#1292]
你好，通过查阅文档，和其他使用者分享的使用博客，都没有看到关于搜集Nginx日志的信息，请教一下
CAT目前是否支持对Nginx日志的搜集与分析？

**Comment by youyong205** [comment]
不支持

**Comment by ycy1991** [comment]
你好，是否有其他替代方案进行Nginx日志的采集和分析

**Comment by youyong205** [comment]
这个不是cat的讨论的范围，你找找其他的相关比如说elk这类的解决方案
