### ISSUE TITLE
framework-bom版本

### ISSUE THREAD

**Issue by duguyixiaono1** [dianping/cat#1293]
[master分支](https://github.com/dianping/cat/blob/master/pom.xml)上使用的framework-bom版本：
<framework.version>4.0.0</framework.version>
我看中央仓库里没有4.0.0，有其他版本，为什么不放一个呢？
![image](https://user-images.githubusercontent.com/2703461/44440745-1bb52c80-a5fc-11e8-8b37-0cfb9ec106e8.png)

**Comment by duguyixiaono1** [comment]
提出这个疑问的出发点是遇到这个异常：
https://github.com/unidal/frameworks/issues/18

**Comment by youyong205** [comment]
后续使用cat client可以直接使用lib下的java，这个版本不依赖任何任何框架。
