### ISSUE TITLE
client信息上报

### ISSUE THREAD

**Issue by ycy1991** [dianping/cat#1297]
麻烦请教一下
       使用cat过程中发现客户端采集的数据不能实时在cat-home中展示，观察到的现象是当前时间递减一小时可以查看到相应的信息，如当前12：00 那么只能查看到11：00的数据，请问采集周期是一小时采集一次吗？

**Comment by loseyou** [comment]
本来就是实时显示的啊，你看下页面上显示的当前时间（cat数据的时间）？

**Comment by ycy1991** [comment]
你好，我看了源代码，底层用的是netty的异步推送，确实时间差不会很大，不过我自己接入了spring boot项目让后访问相应的接口，确实没有发现home里面有数据变化，过一个小时候有时候能查到数据，有时候却查不到数据，是我部署的问题吗？

**Comment by youyong205** [comment]
应该是你部署哪里有问题吧。

**Comment by ycy1991** [comment]
非常感谢，已经找到原因了，我部署的机器路由问题，客户端找不到正确的channel了
