### ISSUE TITLE
remove cat-maven-plugin

### ISSUE THREAD

**Issue by zhyang0918** [dianping/cat#1298]
最新版本移除了这个，mvn cat:install 一直不成功，提示：
No plugin found for prefix 'cat' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local
需要怎么解决呢？谢谢

**Comment by youyong205** [comment]
请按照首页最新的文档进行安装说明

**Comment by Shaun2016** [comment]
> 请按照首页最新的文档进行安装说明

按照最新的安装也报这个错，这个是自动回复的吗
