### ISSUE TITLE
cat如何查看所有的数据？

### ISSUE THREAD

**Issue by loseyou** [dianping/cat#1300]
以小时报表展示的时候，如果同一个tranction或者event发生多次，logview只能显示其中某一次的记录，
如何能够查看其它的记录信息呢？还是说在日志中打印messageId 然后通过url的形式访问数据？

**Comment by youyong205** [comment]
cat本身定位就是监控系统，transaction的logview只是一个sample的展示。

problem里面有更多有问题的logview。

**Comment by youyong205** [comment]
另外你说的日志打印messageId，然后url访问cat也可以，logview页面本身就可以有id的
