### ISSUE TITLE
Hearrbeat ParNewTime监控项时间显示不正确

### ISSUE THREAD

**Issue by llx206** [dianping/cat#1301]
你好，帮忙看下，这个时间单位是毫秒ms，0.2表示0.2毫秒吗，我自己统计算了下GC平均时间是20多毫秒，请问这个时间单位是不是显示的不对啊。下图所示：
![image](https://user-images.githubusercontent.com/39985288/44980326-1f549600-afa2-11e8-9a16-bfa1d62728db.png)

[gc_20180903.log](https://github.com/dianping/cat/files/2345301/gc_20180903.log)

以上是我自己收集的gc日志，ygc平均时间为20多毫秒

ohter:在cat-home工程中，并没有找到ParNewTime设置的地方，请问这个值是在哪里设置的呢？
![image](https://user-images.githubusercontent.com/39985288/44984222-8e37ec00-afae-11e8-90c3-355082a3c94e.png)
配置文件如下所示：
![image](https://user-images.githubusercontent.com/39985288/44984317-deaf4980-afae-11e8-83f3-ab6b6f28d3c7.png)

**Comment by llx206** [comment]
[gc_20180903.log](https://github.com/dianping/cat/files/2345091/gc_20180903.log)
以上是我自己收集的gc日志，ygc平均时间为20多毫秒

**Comment by visionsky1986** [comment]
就是你框起来的中的unit项

**Comment by llx206** [comment]
@youyong205 ,你看下gc_20180903.log,这里面的gc日志平均是20多毫秒，在下面这张图片显示是0.2毫秒左右，
https://user-images.githubusercontent.com/39985288/44980326-1f549600-afa2-11e8-9a16-bfa1d62728db.png

**Comment by youyong205** [comment]
麻烦在仔细看下源码以及核对下数据吧。这个地方不会有错的，如果有错，早出问题了
