### ISSUE TITLE
timeout at awaitAvailable()

### ISSUE THREAD

**Issue by liruizi** [dianping/cat#1307]
请问 从官网上当下最新 CAT 进行部署的时候 报错：A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@5eefa415 -- timeout at awaitAvailable()； 这个怎么解决

**Comment by qmwu2000** [comment]
检查一下网络联通性和连接权限。


发自我的 iPhone

**Comment by youyong205** [comment]
这个是数据库配置没弄好吧。
