### ISSUE TITLE
异步模型集成方案

### ISSUE THREAD

**Issue by carl10086** [dianping/cat#1311]
有一些全异步化的框架比如说 Spring Webflux 、请求和响应在不同的 thread 中、使用基于 ThreadLocal的 Cat 有没有集成方案

**Comment by carl10086** [comment]
有路子了，我异步回调的时候伪装一个 Transaction 过去..

**Comment by Lovnx** [comment]
new一个新的Transaction吗？两次线程处理如何关联成一次请求？

**Comment by LucasDove** [comment]
@carl10086 能分享一下代码吗？

**Comment by carl10086** [comment]
> @carl10086 能分享一下代码吗？

代码不记得了，当时使用的是 Cat 2.0 的版本, 要用反射改 Transaction 字段

public void oneThread () {

    final  long startTime = System.cu //.. or System.nano...

    new AnotherThread () {
        Transaction transaction = ... ;
        // 用发射修改了 Transaction 创建的开始时间和持续时间
        
    }

}

**Comment by LucasDove** [comment]
@carl10086 参考了你的代码，确实可以hack一下。请求开始时记录一个startTime, 请求结束时再创建Transaction，向上转型为DefaultTransaction，通过它提供的setDurationStart方法重置开始时间。勉强能用
