### ISSUE TITLE
cat URL统计时，请求出错Failure值未改变

### ISSUE THREAD

**Issue by ycy1991** [dianping/cat#1312]
您好！
     请教一下Transaction中，统计MVC URL信息，当请求的URL出现异常时，发现Failure值没有增加次数，
查看problem信息，可以查看到改接口确实已经报错，请问是我哪里没配置对吗？

**Comment by ycy1991** [comment]
mod

**Comment by ycy1991** [comment]
非常感谢您能抽空解答我的问题，查了我自己的拦截器确实没有设置异常状态，这是我的设置麻烦帮忙看一下，有什么问题
1、刚开始配置
![image](https://user-images.githubusercontent.com/16506338/46064457-0787c080-c1a2-11e8-87e8-46050c3bf5e7.png)


2、依据您给的建议，修改为
![image](https://user-images.githubusercontent.com/16506338/46064483-18d0cd00-c1a2-11e8-97a8-55e66eddf2b8.png)
测试后发现确实有Failure值，不过Total与Failure相等，不对
3、接着改为，参照配置文档配置为CatFilter，进行测试后，可以统计出有ServletException继承过来的异常
却无法统计项NPE这样的异常
4、项目使用的spring MVC

**Comment by youyong205** [comment]
1.这个你看看异常是否抛到了catfilter里面。debug看下就知道了。
2.检查下异常被你spring MVC吃掉了。
3.比如struts会吃掉URL中的ERROR信息，请在配置中加
<constant name="struts.handle.exception" value="false"/>
