### ISSUE TITLE
Java8 环境下cat 生产机OOM

### ISSUE THREAD

**Issue by WestGG** [dianping/cat#1354]
原因：[ERROR] [DumpAnalyzer] Uncaught exception thrown out of thread(cat-DumpAnalyzer-Checkpoint)
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;

**Comment by youyong205** [comment]
请使用jdk8打包cat，然后用jdk8代码运行。
你使用的jdk7打包，然后在jdk8上运行
你这个情况jdk7的ConcurrentHashMap，和jdk8的ConcurrentHashMap 不一样导致。

**Comment by WestGG** [comment]
是可以通过你说的方法来解决这个问题，但这违反了JDK的版本向下兼容特性。另外，可以通过接口编程的方式来增强CAT的版本兼容性
