### ISSUE TITLE
CatMybatisPlugin 插件无法显示出正确的数据库URL

### ISSUE THREAD

**Issue by WestGG** [dianping/cat#1355]
原因：CatMybatisPlugin 称支持 RoutingDataSource和Druid组合配置的数据源，但使用Druid数据源时无法显示出正确的URL,在监控日志中，所有的数据库URL显示为：jdbc:mysql://unknown:3306/%s?useUnicode=true

**Comment by youyong205** [comment]
建议你拉取下最新的master代码。

然后提交两个PR，在PR里面写清楚这个。

**Comment by youyong205** [comment]
把jdk7 以及jdk8 以及  CatMybatisPlugin 这个两个问题分别PR下，感谢
