### ISSUE TITLE
golang client编译报错

### ISSUE THREAD

**Issue by sjatsh** [dianping/cat#1359]
libcatclientstatic.a(client.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC

**Comment by stdrickforce** [comment]
能说一下是哪个系统吗？

**Comment by sjatsh** [comment]
sys: ubuntu18.04
arch: amd64

**Comment by LeoLi921** [comment]
基于centos系统编译就可以了，ccat是用glibc编译的，不能用musllibc编译

**Comment by LeoLi921** [comment]
@sjatsh 基于centos系统编译就可以成功了，ccat是基于glibc编译的，不能用musllibc编译

**Comment by stdrickforce** [comment]
musl libc 可以尝试下我们新的纯 go 写的客户端，在 lib 目录下面 go.v2 里面

**Comment by stdrickforce** [comment]
我意思是 alpine 系统的话，因为 v1 的 gocat 是不支持 musl libc 的
