### ISSUE TITLE
部署CAT除了8080端口，tomcat修改成其他端口会出错，比如打开Transaction等菜单会500错误

### ISSUE THREAD

**Issue by TaoWithLan** [dianping/cat#1360]
配置如下，有劳看下
`<?xml version="1.0" encoding="utf-8"?>
<server-config>
   <server id="default">
      <properties>
         <property name="local-mode" value="false"/>
         <property name="job-machine" value="false"/>
         <property name="send-machine" value="false"/>
         <property name="alarm-machine" value="false"/>
         <property name="hdfs-enabled" value="false"/>
         <property name="remote-servers" value="127.0.0.1:8082"/>
      </properties>
      <storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
      	<hdfs id="logview" max-size="128M" server-uri="hdfs://10.1.77.86/user/cat" base-dir="logview"/>
      	<hdfs id="dump" max-size="128M" server-uri="hdfs://10.1.77.86/user/cat" base-dir="dump"/>
      	<hdfs id="remote" max-size="128M" server-uri="hdfs://10.1.77.86/user/cat" base-dir="remote"/>
      </storage>
      <consumer>
         <long-config default-url-threshold="1000" default-sql-threshold="100" default-service-threshold="50">
            <domain name="cat" url-threshold="500" sql-threshold="500"/>
            <domain name="OpenPlatformWeb" url-threshold="100" sql-threshold="500"/>
         </long-config>
      </consumer>
   </server>
   <server id="127.0.0.1">
      <properties>
         <property name="job-machine" value="true"/>
         <property name="alert-machine" value="true"/>
	     <property name="send-machine" value="true"/>
      </properties>
   </server>
</server-config>`

log报错有如下片段
[10-18 00:00:15.716] [WARN] [DefaultClientConfigManager] error when connect cat server config url http://127.0.0.1:8082/cat/s/router?domain=cat&ip=192.168.200.103&op=json
[10-18 00:00:15.716] [INFO] [DefaultTransportManager] Remote CAT servers: [/127.0.0.1:2280]
[10-18 00:00:17.826] [WARN] [DefaultClientConfigManager] error when connect cat server config url http://127.0.0.1:8082/cat/s/router?domain=cat&ip=192.168.200.103&op=json

**Comment by duguyixiaono1** [comment]
cat server config url 和端口是从client.xml中选出来的，通常是第一个

**Comment by TaoWithLan** [comment]
> cat server config url 和端口是从client.xml中选出来的，通常是第一个
clinet配置如下，看样子没啥不对的呀
`<server ip="127.0.0.1" port="2280" http-port="8082" />`

**Comment by TaoWithLan** [comment]
> cat server config url 和端口是从client.xml中选出来的，通常是第一个

**Comment by TaoWithLan** [comment]
有没有大神看下呢，公司服务器不能用8080端口，不能将就使用。

**Comment by youyong205** [comment]
版本是3.0么，3.0版本server.xml 挪到数据库配置了，修改server.xml 是没有用的

**Comment by youyong205** [comment]
tomcat该端口应该是支持的，之前的也有公司改过，你先本地搭建一个，看看具体报错

**Comment by TaoWithLan** [comment]
> tomcat该端口应该是支持的，之前的也有公司改过，你先本地搭建一个，看看具体报错

是的，我确实发现了cat数据库里面有个server-config里的内容每次都在打印，每次配置的sercer.xml都不生效。谢谢了

**Comment by lingodan** [comment]
> 版本是3.0么，3.0版本server.xml 挪到数据库配置了，修改server.xml 是没有用的

启动后报这个错误怎么办？怎么初始化数据库配置呢？

**Comment by ddwla4** [comment]
[ERROR] [CatLogger] error when connect cat server config url http://10.128.0.52:8080/cat/s/router?domain=appadmin&ip=10.129.1.117&op=xml&env=unknown&hostname=pre-release1
这个提示是找不到8080端口吗？

**Comment by MistRay** [comment]
同样踩到这个坑里了,请问您是怎么解决的? @TaoWithLan

**Comment by zhouyang-bigdata** [comment]
可能改下这个： <property name="remote-servers" value="10.1.1.1:8080,10.1.1.2:8080,10.1.1.3:8080"/>
在菜单：全局系统配置->服务端配置
