### ISSUE TITLE
单机一直跑不起来，持续报错

### ISSUE THREAD

**Issue by lingjiaju** [dianping/cat#1369]
按照集群部署的文档，只设置一台机器，单机一直跑不起来。
[10-21 13:41:26.537] [ERROR] [ServerConfigManager] Error when executing query(SELECT c.id,c.`name`,c.content,c.creation_date,c.modify_date FROM config c WHERE c.name = ?) failed, proto: Config[content: null, creation-date: null, id: 0, key-id: 0, modify-date: null, name: server-config], message: java.lang.IllegalStateException: Error when loading data sources file: /data/appdatas/cat/datasources.xml.
[10-21 13:41:26.559] [INFO] [ServerConfigManager] init cat server with cat server xml /data/appdatas/cat/server.xml
[10-21 13:41:26.560] [INFO] [ServerConfigManager] Loading configuration file(/data/appdatas/cat/server.xml) ...
[10-21 13:41:26.572] [ERROR] [ServerConfigManager] Unknown root element(config) found!
[10-21 13:41:26.600] [INFO] [ServerConfigManager] CAT server is running with hdfs,false
[10-21 13:41:26.601] [INFO] [ServerConfigManager] CAT server is running with alert,false
[10-21 13:41:26.601] [INFO] [ServerConfigManager] CAT server is running with job,false
[10-21 13:41:26.602] [INFO] [ServerConfigManager] <?xml version="1.0" encoding="utf-8"?>
<server id="172.16.100.130">
   <storage local-base-dir="target/bucket" max-hdfs-storage-time="15" local-report-storage-time="3" local-logivew-storage-time="7" har-mode="true" upload-thread="5">
   </storage>
   <consumer>
      <long-config default-url-threshold="1000" default-sql-threshold="100" default-service-threshold="50">
      </long-config>
   </consumer>
</server>

以上信息为最开始的报错，后续会一直反复报错：
[10-21 13:41:29.191] [ERROR] [HttpServlet] Error occured when handling uri: /cat/s/router

按照步骤改动不是很多，就3个xml，然后设置下tomcat的utf-8，初始化下数据库，可就是跑不起来。
datasource故意写错mysql信息，是报错：Connections could not be acquired from the underlying database，感觉第一个报错跟datasource没关系。
tomcat用过9和7，结果都一样，linux是centos7.x的，麻烦看下这个可能是什么原因造成的？

**Comment by youyong205** [comment]
Error when loading data sources file: /data/appdatas/cat/datasources.xml.  这个xml内容贴下。
一般情况就是因为几个配置文件内容错了

**Comment by lingjiaju** [comment]
> Error when loading data sources file: /data/appdatas/cat/datasources.xml. 这个xml内容贴下。
> 一般情况就是因为几个配置文件内容错了

<?xml version="1.0" encoding="utf-8"?>
<data-sources>
	<data-source id="cat">
		<maximum-pool-size>3</maximum-pool-size>
		<connection-timeout>1s</connection-timeout>
		<idle-timeout>10m</idle-timeout>
		<statement-cache-size>1000</statement-cache-size>
		<properties>
			<driver>com.mysql.jdbc.Driver</driver>
			<url>
				jdbc:mysql://172.16.100.131:3306/cat
			</url>
			<user>mysql</user>
			<password>mysql</password>
			<connectionProperties>
				useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000
			</connectionProperties>
		</properties>
	</data-source>
	<data-source id="app">
		<maximum-pool-size>3</maximum-pool-size>
		<connection-timeout>1s</connection-timeout>
		<idle-timeout>10m</idle-timeout>
		<statement-cache-size>1000</statement-cache-size>
		<properties>
			<driver>com.mysql.jdbc.Driver</driver>
			<url>
				jdbc:mysql://172.16.100.131:3306/cat
			</url>
			<user>mysql</user>
			<password>mysql</password>
			<connectionProperties>
				useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000
			</connectionProperties>
		</properties>
	</data-source>
</data-sources>

**Comment by lingjiaju** [comment]
<?xml version="1.0" encoding="utf-8"?>
<data-sources>
	<data-source id="cat">
		<maximum-pool-size>3</maximum-pool-size>
		<connection-timeout>1s</connection-timeout>
		<idle-timeout>10m</idle-timeout>
		<statement-cache-size>1000</statement-cache-size>
		<properties>
			<driver>com.mysql.jdbc.Driver</driver>
			<url>
				jdbc:mysql://172.16.100.131:3306/cat
			</url>
			<user>mysql</user>
			<password>mysql</password>
			<connectionProperties>
				useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000
			</connectionProperties>
		</properties>
	</data-source>
	<data-source id="app">
		<maximum-pool-size>3</maximum-pool-size>
		<connection-timeout>1s</connection-timeout>
		<idle-timeout>10m</idle-timeout>
		<statement-cache-size>1000</statement-cache-size>
		<properties>
			<driver>com.mysql.jdbc.Driver</driver>
			<url>
				jdbc:mysql://172.16.100.131:3306/cat
			</url>
			<user>mysql</user>
			<password>mysql</password>
			<connectionProperties>
				useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000
			</connectionProperties>
		</properties>
	</data-source>
</data-sources>

**Comment by lingjiaju** [comment]
![image](https://user-images.githubusercontent.com/12277611/47267768-c5705580-d57a-11e8-87f4-667e083c5cae.png)

**Comment by lingjiaju** [comment]
不知道是否是因为cdata的问题，加了会直接提示连不上数据库，不加就是上面的报错信息了

**Comment by lingjiaju** [comment]
> Error when loading data sources file: /data/appdatas/cat/datasources.xml. 这个xml内容贴下。
> 一般情况就是因为几个配置文件内容错了

贴上在上面，按道理有&符号应该是要用cdata包起来，但用cdata包裹的话就会报Connections could not be acquired from the underlying database!，直接用上面的就是之前的报错信息，但是数据库用客户端工具确实是可以连接的。

**Comment by youyong205** [comment]
这类问题麻烦通过google或者其他方式解决吧，既然已经报了mysql层面的错误，肯定是数据库安装或者权限问题，以上问题可能有一下原因造成：

1，驱动配置有误：driver=com.mysql.jdbc.Driver
2，数据库连接地址有误：url=jdbc:mysql://localhost:3306/test?3useUnicode=true&characterEncoding=utf8
3，密码或帐号有误：username=root
      password=root
4，数据库未启动或无权访问
5，项目未引入对应的驱动jar包mysql-connector-java-5.1.6-bin.jar
6,mysql root没有远程访问的权限，需要增加权限，增加权限的步骤如下：
进入mysql数据库：
grant all privileges on *.* to 'root'@'%' identified by 'root' with grant option;
flush privileges;

**Comment by lingjiaju** [comment]
> 这类问题麻烦通过google或者其他方式解决吧，既然已经报了mysql层面的错误，肯定是数据库安装或者权限问题，以上问题可能有一下原因造成：
> 
> 1，驱动配置有误：driver=com.mysql.jdbc.Driver
> 2，数据库连接地址有误：url=jdbc:mysql://localhost:3306/test?3useUnicode=true&characterEncoding=utf8
> 3，密码或帐号有误：username=root
> password=root
> 4，数据库未启动或无权访问
> 5，项目未引入对应的驱动jar包mysql-connector-java-5.1.6-bin.jar
> 6,mysql root没有远程访问的权限，需要增加权限，增加权限的步骤如下：
> 进入mysql数据库：
> grant all privileges on _._ to 'root'@'%' identified by 'root' with grant option;
> flush privileges;

数据库的问题基本排除，131这台虚拟机的mysql库也有用于其他测试用途，不存在权限和其他问题，刚仔细看了下xml，url换行哪里改成不换行后解决问题了，就是xml里面url节点换行的问题。
