### ISSUE TITLE
服务端tomcat启动2次的问题

### ISSUE THREAD

**Issue by andyoudear** [dianping/cat#1375]
今天早上你发的那个网址我也看了，我知道我启动tomcat服务端启动2次的问题，但是我服务端每次启动2次，这段日志才能打印出来
![image](https://user-images.githubusercontent.com/43236109/47539788-9f450f80-d904-11e8-9ccb-1c76064fec6b.png)
而我服务端启动1次的话，这段日志一直不打印
![1](https://user-images.githubusercontent.com/43236109/47539997-9a349000-d905-11e8-9cb9-d1cb77f776ba.jpg)
还有就是每次启动项目会报这个错误
![2](https://user-images.githubusercontent.com/43236109/47540003-a3256180-d905-11e8-9283-e2bae00b20aa.jpg)

**Comment by njkfei** [comment]
我要启动４次．

**Comment by njkfei** [comment]
启动２次．

root     18545 40.9 21.7 3938084 863392 pts/0  Sl   10:31   4:51 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/data/dubbo/cat/apache-tomcat-7.0.79/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.endorsed.dirs=/data/dubbo/cat/apache-tomcat-7.0.79/endorsed -classpath /data/dubbo/cat/apache-tomcat-7.0.79/bin/bootstrap.jar:/data/dubbo/cat/apache-tomcat-7.0.79/bin/tomcat-juli.jar -Dcatalina.base=/data/dubbo/cat/apache-tomcat-7.0.79 -Dcatalina.home=/data/dubbo/cat/apache-tomcat-7.0.79 -Djava.io.tmpdir=/data/dubbo/cat/apache-tomcat-7.0.79/temp org.apache.catalina.startup.Bootstrap start
root     19186 46.6 19.5 3911300 775852 pts/0  Sl   10:36   3:09 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/data/dubbo/cat/apache-tomcat-7.0.79/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.endorsed.dirs=/data/dubbo/cat/apache-tomcat-7.0.79/endorsed -classpath /data/dubbo/cat/apache-tomcat-7.0.79/bin/bootstrap.jar:/data/dubbo/cat/apache-tomcat-7.0.79/bin/tomcat-juli.jar -Dcatalina.base=/data/dubbo/cat/apache-tomcat-7.0.79 -Dcatalina.home=/data/dubbo/cat/apache-tomcat-7.0.79 -Djava.io.tmpdir=/data/dubbo/cat/apache-tomcat-7.0.79/temp org.apache.catalina.startup.Bootstrap start
root     20193  0.0  0.0  13572   828 pts/0    S+   10:43   0:00 grep --color=auto tomcat-

**Comment by andyoudear** [comment]
> 启动２次．
> 
> root 18545 40.9 21.7 3938084 863392 pts/0 Sl 10:31 4:51 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/data/dubbo/cat/apache-tomcat-7.0.79/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.endorsed.dirs=/data/dubbo/cat/apache-tomcat-7.0.79/endorsed -classpath /data/dubbo/cat/apache-tomcat-7.0.79/bin/bootstrap.jar:/data/dubbo/cat/apache-tomcat-7.0.79/bin/tomcat-juli.jar -Dcatalina.base=/data/dubbo/cat/apache-tomcat-7.0.79 -Dcatalina.home=/data/dubbo/cat/apache-tomcat-7.0.79 -Djava.io.tmpdir=/data/dubbo/cat/apache-tomcat-7.0.79/temp org.apache.catalina.startup.Bootstrap start
> root 19186 46.6 19.5 3911300 775852 pts/0 Sl 10:36 3:09 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/data/dubbo/cat/apache-tomcat-7.0.79/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.endorsed.dirs=/data/dubbo/cat/apache-tomcat-7.0.79/endorsed -classpath /data/dubbo/cat/apache-tomcat-7.0.79/bin/bootstrap.jar:/data/dubbo/cat/apache-tomcat-7.0.79/bin/tomcat-juli.jar -Dcatalina.base=/data/dubbo/cat/apache-tomcat-7.0.79 -Dcatalina.home=/data/dubbo/cat/apache-tomcat-7.0.79 -Djava.io.tmpdir=/data/dubbo/cat/apache-tomcat-7.0.79/temp org.apache.catalina.startup.Bootstrap start
> root 20193 0.0 0.0 13572 828 pts/0 S+ 10:43 0:00 grep --color=auto tomcat-

你怎么启动了4次啊，是不是tomcat加了什么东西，我感觉我启动2次都够多了、

**Comment by njkfei** [comment]
可能是tomcat的shutdown没有关，我shutdown.sh后，再sh startup.sh,然后就启动４次了．
