### ISSUE TITLE
spring-boot集成cat客户端异常

### ISSUE THREAD

**Issue by xqxyxchy** [dianping/cat#1377]
按照spring-boot集成配置类。
找不到类：
java.lang.NoClassDefFoundError: Could not initialize class com.dianping.cat.servlet.CatFilter$CatHandler
	at com.dianping.cat.servlet.CatFilter.init(CatFilter.java:90) ~[cat-client-3.0.0.jar:na]

**Comment by xqxyxchy** [comment]
org.unidal.helper.Joiners这个类在什么包？

**Comment by youyong205** [comment]
你使用master代码，cat lib下的java客户端。这个客户端不依赖 org.unidal.helper类

**Comment by xqxyxchy** [comment]
用的是http://unidal.org/nexus/content/repositories/releases/这个仓库里面的cat-client-3.0.0.jar；
我试一下用离线包，谢谢解答。

**Comment by youyong205** [comment]
这个包你检查下代码，哪里有依赖org.unidal.helper.Joiners？

**Comment by BlueShadows1** [comment]
> 用的是[http://unidal.org/nexus/content/repositories/releases/这个仓库里面的cat-client-3.0.0.jar；](http://unidal.org/nexus/content/repositories/releases/%E8%BF%99%E4%B8%AA%E4%BB%93%E5%BA%93%E9%87%8C%E9%9D%A2%E7%9A%84cat-client-3.0.0.jar%EF%BC%9B)
> 我试一下用离线包，谢谢解答。

你好  问下这个问题后来怎么解决的

**Comment by monkeyAlwaysWin** [comment]
cat-client 3.0 依赖这个jar,但是没有啊 
import org.unidal.helper.Properties;
import org.unidal.helper.Properties.PropertyAccessor;

import com.dianping.cat.CatPropertyProvider;

public class CatPropertyProviderDefaultImpl implements CatPropertyProvider {

**Comment by songlongkuan** [comment]
import org.unidal.helper.Joiners;
import org.unidal.helper.Joiners.IBuilder;

public class CatFilter implements Filter {


就是有依赖unidal啊
