### ISSUE TITLE
出问题CAT的服务端

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1378]
您好：
我搭建了一个服务端集群，但是大盘和state的页面，均提示 出问题CAT的服务端[a,b,c]，请问这个问题，一般是出在哪里呢？谢谢！

**Comment by lingodan** [comment]
遇到了同样的问题，提示“ 出问题CAT的服务端”,怎样才能进一步发现具体原因？

**Comment by lingodan** [comment]
我也遇到这个问题，重新检查配置参数，发现/data/appdatas/cat 路径下的server.xml配置错误。
<remote-servers>要配置成服务器地址和端口

**Comment by chen0401** [comment]
本人情况：客户端路由中的backup-server="[IP]"，其中IP为内网IP，不能是127.0.0.1

**Comment by youyong205** [comment]
cat优先选择内网IP，cat的使用场景应该绝大可能是内网
