### ISSUE TITLE
集成CAT的Golang 客户端日志中出现请求可用server 列表返回400 Bad Request

### ISSUE THREAD

**Issue by zdlIsIcePig** [dianping/cat#1381]
![image](https://user-images.githubusercontent.com/24838000/47695546-85c20180-dc3d-11e8-929b-69da101cf596.png)
上图是参照官方文档的配置,下图为日志中的错误信息
![image](https://user-images.githubusercontent.com/24838000/47695599-befa7180-dc3d-11e8-8cf1-490d835353f1.png)

**Comment by youyong205** [comment]
400 是不是服务端没有搭建好

**Comment by zdlIsIcePig** [comment]
> 400 是不是服务端没有搭建好

@stdrickforce 这个之前跟你们这位负责客户端SDK维护的同事沟通过了，php和java那边的同事集成客户端没有出现这种问题，我提供了些server的信息给到你们那位同事。

**Comment by zdlIsIcePig** [comment]
嗯 辛苦你们调整下了 感谢大锅
