### ISSUE TITLE
我想知道拼接成的URL为何含有特定协议

### ISSUE THREAD

**Issue by andyoudear** [dianping/cat#1383]
![image](https://user-images.githubusercontent.com/43236109/47772062-6ea81000-dd20-11e8-8939-eca9e36c8b35.png)
这个拼接URL含有特定的协议，转换成了string类型，在readForm的读取下，获得了我们页面Transaction里logview视图的数据，我想知道这个页面的这些数据是通过什么方式存起来的，然后这个拼成的URL为什么含有特定的协议。

**Comment by andyoudear** [comment]
> 每个domain的logview信息是存在各个消费机的磁盘上，需要广播到所有server，再聚合。

老哥，那这些logview的信息，是如何传过去的呢  主要是因为
![image](https://user-images.githubusercontent.com/43236109/47772666-63ee7a80-dd22-11e8-9841-7c556d42f0c8.png)
![Uploading image.png…]()

这2个图，相同的代码，但是这里分布式的logview 展示出来的效果不一样，第二个是我写的demo，用的http，第一个是我加到我们项目里的，出现的效果不一样，而且第一个明显在页面展示的table的值有问题。所以我想找下这个值的来源

**Comment by andyoudear** [comment]
> 每个domain的logview信息是存在各个消费机的磁盘上，需要广播到所有server，再聚合。
> 
> 老哥，那这些logview的信息，是如何传过去的呢 主要是因为
> 
> 
> 
> 这2个图，相同的代码，但是这里分布式的logview 展示出来的效果不一样，第二个是我写的demo，用的http，第一个是我加到我们项目里的，出现的效果不一样，而且第一个明显在页面展示的table的值有问题。所以我想找下这个值的来源

![image](https://user-images.githubusercontent.com/43236109/47772743-a912ac80-dd22-11e8-9dfb-0d3d869c2f6d.png)
这是第一个图，有问题的那个图

**Comment by duguyixiaono1** [comment]
你看下HtmlMessageCodec的encodeHeader方法

**Comment by andyoudear** [comment]
> 如果我没理解错，你想看看RootLogview页面元素，可以去看下HtmlMessageCodec的encodeHeader方法

谢谢，我先去看看，这个我刚才那个有问题的图，我就是想找下这个图这么展示的原因，它展示的效果和我用demo搭建的展示的效果不一样，不知道老哥看到了没。
