### ISSUE TITLE
打包cat 失败以及无法下载war

### ISSUE THREAD

**Issue by superpanda25** [dianping/cat#1389]
使用md文档链接无法下载http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/cat/cat-home/3.0.0/cat-home-3.0.0.war
另外自行打包的失败报
Failed to execute goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model (generate data model) on project cat-client: Execution generate data model of goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model failed: Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.5.8 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.unidal.maven.plugins:codegen:jar:2.5.8, org.unidal.framework:foundation-service:jar:3.1.0: Could not transfer artifact org.unidal.maven.plugins:codegen:jar:2.5.8 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/maven/plugins/codegen/2.5.8/codegen-2.5.8.jar from unidal.releases failed: Premature end of Content-Length delimited message body (expected: 410213; received: 65779 -> [Help 1]

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/47966572-e82c5f00-e08e-11e8-9697-a1c3dbd072fd.png)

请在重试试试。

**Comment by superpanda25** [comment]
> ![image](https://user-images.githubusercontent.com/1281552/47966572-e82c5f00-e08e-11e8-9697-a1c3dbd072fd.png)
> 
> 请在重试试试。

可以了，谢谢。

**Comment by zcc1234567** [comment]
http://unidal.org/nexus/service/local/repositories/releases/content/com/dianping/cat/cat-home/3.0.0/cat-home-3.0.0.war
使用这个链接不能下载啊,看了下到releases这一级之后都不能访问了

**Comment by Jacksonary** [comment]
能分享一个 war 不，直接 403 了，打包各种依赖缺失。。。

**Comment by qmwu2000** [comment]
https://github.com/dianping/cat/wiki/上有war包的


发自我的iPhone

**Comment by Jacksonary** [comment]
> [https://github.com/dianping/cat/wiki/上有war包的](https://github.com/dianping/cat/wiki/%E4%B8%8A%E6%9C%89war%E5%8C%85%E7%9A%84) 发自我的iPhone
> […](#)
> 在 2022年3月16日，13:07，jacksonary ***@***.***> 写道： ﻿ 能分享一个 war 不，直接 403 了，打包各种依赖缺失。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.
并没有，远程仓库好像加了权限没法下载，另外提供的 plugin 代码仓库也是无法打包的：

https://github.com/unidal/maven-plugins
https://github.com/unidal/frameworks
，官方的 docker 打包也是 139 自动终止了进程
