### ISSUE TITLE
MessageId getIpAddressValue实现相关疑问

### ISSUE THREAD

**Issue by inversionhourglass** [dianping/cat#1407]
MessageId中[getIpAddressValue](https://github.com/dianping/cat/blob/master/cat-client/src/main/java/com/dianping/cat/message/internal/MessageId.java#LC162)的代码实现中，对于ip组成包含进程ID的时候采用高15位存储进程ID，低17位存储IP，使用17位存储IP是有什么特殊用途吗？2byte用来存储IP后两段主机部分应该就够了，虽说大部分linux系统默认最大线程数是32768（2^16），使用15位保存就足够了，但是也存在突破2^16的可能，使用更多位（16位）来存储进程ID是否更好？
另外，虽然概率很低，但也可能出现同一应用同机器多进程运行时，刚好它们的进程ID的低17位相同（前提进程ID数上限溢出15位，比如一个进程ID**47463**，另一个进程ID**14695**），此时他们的IP计算值相同（getIpAddressValue），最终数据写入会相互覆盖。虽说概率很低，但是如果出现，现在来说是难以发现的，是不是在客户端或服务端在发现进程ID>=2^16时记录一个异常信息，方便在极端情况下进行排错。

**Comment by wangyapu0714** [comment]
这个只有像python、nodejs多进程模式启动的时候对同一个机器消息id进行区分，其他正常单机单实例的是不加入pid进行运算的。当时考虑也是进程id已经完全够用，这是考虑系统兼容性成本加入的。你说的情况问题确实有低概率存在，目前可以加入一些事件记录一下或者采用更多位数存储也都ok。


在 2018年11月9日 下午2:44:00, inversionhourglass (notifications@github.com) 写到:

MessageId中getIpAddressValue的代码实现中，对于ip组成包含进程ID的时候采用高15位存储进程ID，低17位存储IP，使用17位存储IP是有什么特殊用途吗？2byte用来存储IP后两段主机部分应该就够了，虽说大部分linux系统默认最大线程数是32768（2^16），使用15位保存就足够了，但是也存在突破2^16的可能，使用更多位（16位）来存储进程ID是否更好？
另外，虽然概率很低，但也可能出现同一应用同机器多进程运行时，刚好它们的进程ID的低17位相同（前提进程ID数上限溢出15位，比如一个进程ID47463，另一个进程ID14695），此时他们的IP计算值相同（getIpAddressValue），最终数据写入会相互覆盖。虽说概率很低，但是如果出现，现在来说是难以发现的，是不是在客户端或服务端在发现进程ID>=2^16时记录一个异常信息，方便在极端情况下进行排错。

**Comment by inversionhourglass** [comment]
好的，了解了，我们是windows IIS可以开启多进程模式，不过看了一下线上进程情况是不会超出32768，只是有这样的一个疑问。
