### ISSUE TITLE
项目源代码竟然有两个cat-client项目，且大部代码都相同，以后以哪个为准?

### ISSUE THREAD

**Issue by qxo** [dianping/cat#1409]
cat-client和lib/java pom.xml文件中groupId和artifactId都相同，发布maven仓库会相互覆盖!!!
且大部代码都相同,同一代码库这样复制代码...

lib/java的代码外部依赖少一些, 而且支持logback和druid

但cat-core项目依赖于根目录下cat-client

建议合并成一种项目，或拆分出一个公共项目

**Comment by wangyapu0714** [comment]
以 lib/java 下面的为准，下个大版本会把cat-client统一，cat-core移除，业务方应该不使用cat-core。
