### ISSUE TITLE
更新了最新的代码后，heartbeat报表出不来

### ISSUE THREAD

**Issue by cwei001** [dianping/cat#1412]
更新之前【10月30号之前的代码】，heartbeat是可以出来的。
客户端引用的cat-client是在更新代码后编译lib/java下的源码打出的jar包

**Comment by radishlee** [comment]
ping 功能也没有了

**Comment by cwei001** [comment]
> 更新客户端之前，服务端你们更新了吗？

更新了

**Comment by borisbao** [comment]
我现在也不展示了

**Comment by wangyapu0714** [comment]
@borisbao #1437 这个问题已经fix，麻烦更新下master的代码，以及cat-client-3.0.0.

**Comment by dzhai** [comment]
@wangyapu0714  用的你们maven私服的war包和cat-client，是否需要自己打包才能行？
