### ISSUE TITLE
Matrix和Dependency实时报表

### ISSUE THREAD

**Issue by cwei001** [dianping/cat#1413]
3.0版本的Matrix和Dependency实时报表为啥没有了？当初选cat作为监控平台，很大部分原因就是因为提供了这些报表呀

**Comment by wangyapu0714** [comment]
依赖分析相关的报表内部已经全部重新设计了。cat这块内容的处理逻辑还保留，展示端入口去掉了，你可以把入口打开再试下。

**Comment by cwei001** [comment]
> 依赖分析相关的报表内部已经全部重新设计了。cat这块内容的处理逻辑还保留，展示端入口去掉了，你可以把入口打开再试下。

Matrix报表我能看到了，Dependency报表能给个URL地址吗

**Comment by wangyapu0714** [comment]
#1426 
拉取下最新代码，我把dependency入口放开了，管理端没有展示，/cat/r/dependency
