### ISSUE TITLE
新版客户端的使用疑问

### ISSUE THREAD

**Issue by TaoWithLan** [dianping/cat#1414]
3.0的新版客户端，如果改了源码，怎么重新导成jar呢，是不是项目名先改成client-3.0.0，然后全部内容导出jar就行了？有劳教教小弟，谢谢。

**Comment by wangyapu0714** [comment]
不需要改项目名。
1. 如果使用maven的话，可以直接用lib/java打包3.0.0的jar，通过maven进行引用。
2. 如果是直接使用jar的方式，可以直接使用我们打包好的jar，lib/java/jar目录下。
