### ISSUE TITLE
3.0windows idea调试springboot cat中没有出现主机请求帮助

### ISSUE THREAD

**Issue by fuhao009** [dianping/cat#1417]
package com.example.demo;

import com.dianping.cat.servlet.CatFilter;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Created by zhengwenzhu on 2017/1/17.
 */

// 增加了拦截器
@Configuration
public class CatFilterConfigure {

    @Bean
    public FilterRegistrationBean catFilter() {
        FilterRegistrationBean registration = new FilterRegistrationBean();
        CatFilter filter = new CatFilter();
        registration.setFilter(filter);
        registration.addUrlPatterns("/*");
        registration.setName("cat");
        registration.setOrder(1);
        return registration;
    }
}
// 在springboot的磁盘下也创建了data目录，并且目录下面已经有cache文件产生了，但是跟server端出现ip

**Comment by wangyapu0714** [comment]
1. /data/applogs/cat下面有日志，看下路由请求是否出现错误。检查路由机器是否配置正确。
2. 拦截器没有生效？这个启动看下是否正常初始化。

**Comment by wangyapu0714** [comment]
1. /data/applogs/cat下面有日志，看下路由请求是否出现错误。检查路由机器是否配置正确。
2. 拦截器没有生效？这个启动看下是否正常初始化。
