### ISSUE TITLE
cat-client 3.0.0还没有推送到maven库么？

### ISSUE THREAD

**Issue by superpanda25** [dianping/cat#1421]
从http://unidal.org/nexus/#welcome里都没看到……

**Comment by jumping656** [comment]
同问
https://mvnrepository.com/artifact/com.dianping.cat/cat-client 这里也没有

**Comment by wangyapu0714** [comment]
![image](https://user-images.githubusercontent.com/5910252/48421784-2238e780-e798-11e8-8845-2d59d2879d75.png)

pom配置上仓库地址：

```xml
<repositories>
      <repository>
         <id>unidal.releases</id>
         <url>http://unidal.org/nexus/content/repositories/releases/</url>
      </repository>
   </repositories>
```

**Comment by GeekDaniel** [comment]
It seems that the repository is not available any more . 
![image](https://user-images.githubusercontent.com/13143797/76244486-20404500-6275-11ea-9929-f7175fdf1fcc.png)

**Comment by bianlizuozishu** [comment]
http://unidal.org/nexus/content/repositories/releases/ 这地址下载的3.0和代码仓库里的代码不一样啊
