### ISSUE TITLE
windows客户端发送消息，linux服务端没接收到

### ISSUE THREAD

**Issue by TaoWithLan** [dianping/cat#1428]
遇到个很奇怪的问题，两台window系统，或者是两台linux系统机器，分别都部署了服务端和客户端，消息都能发送成功。但是在window发到linux服务端，则没有反应，没看到有window客户端的任何调用信息，请教下这是什么问题？

**Comment by stdrickforce** [comment]
请问一下是什么语言客户端呢？
以及 Cat 服务端和客户端分别是哪个版本的。

**Comment by TaoWithLan** [comment]
> 请问一下是什么语言客户端呢？
> 以及 Cat 服务端和客户端分别是哪个版本的。

java，lib/java下的jar，服务端是3.0的master，最后产生的war。不过master当时下载是半个月前了，java客户端是最新的

**Comment by TaoWithLan** [comment]
@stdrickforce
