### ISSUE TITLE
关于客户端发送heartbeat到服务端，没有详细信息

### ISSUE THREAD

**Issue by TaoWithLan** [dianping/cat#1434]
[
![image](https://user-images.githubusercontent.com/44239400/48464357-43dab300-e81a-11e8-809d-917398b56e2d.png)
](url)

如上图，这是我的埋点服务器每分钟发送的心跳消息，发现跟cat服务器自己的心跳消息差很多，几乎没什么内容，是不是就是导致cat web端看不到该机器健康信息的原因。有劳大神解救，这个非常急。。。

**Comment by wangyapu0714** [comment]
意思你用Heartbeat消息类型自己上报了心跳相关埋点？可以给个demo对比下吗？cat自己上报的心跳应该是一大串xml文本。

**Comment by TaoWithLan** [comment]
> 意思你用Heartbeat消息类型自己上报了心跳相关埋点？可以给个demo对比下吗？cat自己上报的心跳应该是一大串xml文本。
@wangyapu0714 
不是的，就是客户端自动上报的，但是没有一大串xml文本。服务端的有XML文本。
