### ISSUE TITLE
删除项目报空指针异常

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1436]

**Comment by 578394545** [comment]
删除项目时，项目删除成功但提示操作失败，problem监控发现是空指针异常：
ERROR | delete project error java.lang.NullPointerException at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106) at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097) at com.dianping.cat.service.ProjectService.delete(ProjectService.java:84) at com.dianping.cat.system.page.config.processor.GlobalConfigProcessor.deleteProject(GlobalConfigProcessor.java:89) at com.dianping.cat.system.page.config.processor.GlobalConfigProcessor.process(GlobalConfigProcessor.java:120) at com.dianping.cat.system.page.config.Handler.handleOutbound(Handler.java:116) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

具体报错地方是：m_cmdbToProjects.remove(project.getCmdbDomain());（ProjectService.java:84行）

**Comment by wangyapu0714** [comment]
#1442 这个问题已经fix，可以更新下最新代码。
