### ISSUE TITLE
count distinct 算子需求

### ISSUE THREAD

**Issue by duguyixiaono1** [dianping/cat#1439]
请教下，监控UV之类的count distinct操作是否会考虑放入CAT中？

**Comment by wangyapu0714** [comment]
这个暂时没有计划

**Comment by duguyixiaono1** [comment]
> 这个暂时没有计划

美团点评内部没有这种需求场景吗？

**Comment by wangyapu0714** [comment]
cat目前的功能有些可以达到你类似需求，例如统计不同维度的数据指标。count distinct等等更复杂的一些数据操作还是更偏向于BI系统。
