### ISSUE TITLE
SPI方式初始化,能和spring boot的配置整合么？

### ISSUE THREAD

**Issue by majintao** [dianping/cat#1443]
https://github.com/dianping/cat/blob/master/lib/java/README.zh-CN.md#spi%E6%96%B9%E5%BC%8F%E5%88%9D%E5%A7%8B%E5%8C%96

我想整合 spring boot 配置统一管理

**Comment by wangyapu0714** [comment]
这个cat默认不支持，用户自己可以扩展。
