### ISSUE TITLE
cat-client nodejs版本编译安装失败

### ISSUE THREAD

**Issue by w493549442** [dianping/cat#1445]
使用cat-client中nodejs版本有限几个问题，请教一下
1、使用开源库cat-master/lib/node.js下lib文件，ccat.js文件中“../../build/Release/nodecat”依赖没找到。

2、使用make编译生成libcatclient.so文件，提示/usr/bin/ld: cannot find -lcatclient
![image](https://user-images.githubusercontent.com/7703507/48697914-c6031700-ec20-11e8-89ad-bce9f592b061.png)

**Comment by stdrickforce** [comment]
make 和 make install 是让你在 ccat 目录下面执行的。。并不是 nodecat 这个目录
