### ISSUE TITLE
项目编译报Connect to unidal.org:80

### ISSUE THREAD

**Issue by xiaobianchen** [dianping/cat#1446]
项目拉下来以后报[ERROR] Failed to execute goal on project cat-client: Could not resolve dependencies for project com.dianping.cat:cat-client:jar:3.0.0: Failed to collect dependencies at org.unidal.framework:test-framework:jar:2.4.0: Failed to read artifact descriptor for org.unidal.framework:test-framework:jar:2.4.0: Could not transfer artifact org.unidal.framework:test-framework:pom:2.4.0 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): Connect to unidal.org:80 [unidal.org/103.37.150.30] failed: Operation timed out -> [Help 1]

提供的jar依赖地址也无法打开 http://unidal.org/nexus/,请问应该怎么编译通过呢？

**Comment by kercu** [comment]
最新版的，已经改好了。
