### ISSUE TITLE
[文档]多机房间部署配置有没有示范。

### ISSUE THREAD

**Issue by awayings** [dianping/cat#1448]
常见的问题。
1. 是否要求机房内网打通。
2. 客户端路由配置。networkpolicy和server group的配置。
3. 服务端配置。remote servers配置。

**Comment by wangyapu0714** [comment]
这块等我们整理个文档贴出来。

**Comment by wangyapu0714** [comment]
@awayings https://github.com/dianping/cat/wiki/router_config
