### ISSUE TITLE
problem SampleLinks 中文乱码

### ISSUE THREAD

**Issue by bigfanofcpp** [dianping/cat#1449]
mysql已经是utf-8：
[mysqld]
max_allowed_packet = 1000M
bind-address = 0.0.0.0
collation-server=utf8_general_ci
character-set-server=utf8
init_connect='SET collation_connection = utf8_unicode_ci'
init_connect='SET NAMES utf8'
[client]
default-character-set=utf8
[mysql]
default-character-set=utf8

tomcat已经是utf-8：
    <Connector port="8080" URIEncoding="utf-8" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />
<Connector URIEncoding="utf-8" port="8009" protocol="AJP/1.3" redirectPort="8443" />

但是还是乱码。。。求助

**Comment by bigfanofcpp** [comment]
tomcat配置：
<Connector port="8080" URIEncoding="utf-8" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />

<Connector URIEncoding="utf-8" port="8009" protocol="AJP/1.3" redirectPort="8443" />

**Comment by youyong205** [comment]
tomcat 的 server.xml里面改了吗
