### ISSUE TITLE
heartbeat报表单位问题

### ISSUE THREAD

**Issue by yangfanchuhai** [dianping/cat#1452]
heartbeat报表，cat自己的项目单位挺正常的，而自己的应用，单位有点乱。

**Comment by wangyapu0714** [comment]
可以截图看一下是什么问题。

**Comment by yangfanchuhai** [comment]
![image](https://user-images.githubusercontent.com/11494672/48784879-83bfff80-ed1e-11e8-9b6e-066c72435b5c.png)
这个是我们自己应用的，下面是CAT本身的：
![image](https://user-images.githubusercontent.com/11494672/48784937-9f2b0a80-ed1e-11e8-910c-b4c8135c4460.png)

**Comment by yangfanchuhai** [comment]
感觉应用用的client和CAT的client上报的数据格式不太一样，所以导致报表格式有差异。影响可读性

**Comment by youyong205** [comment]
单位问题记录一个issue统一优化下

**Comment by yangfanchuhai** [comment]
感觉这个是因为新的client上报的心跳和老的不一致，而服务器统计的时候没兼容，最近在做告警的时候，发现心跳的告警也只有CAT自身可以生效。

**Comment by xiaolei-fu** [comment]
老版本在配置里有一个  心跳报表展示页面可以配置，新版本貌似没找到，可以去数据库 config表 heartbeat-display-policy 配置
