### ISSUE TITLE
python malloc error

### ISSUE THREAD

**Issue by flycash** [dianping/cat#1455]
环境：
MacOS和Ubuntu16.04
python 2.7.14和python3.7.1
cat-sdk 3.0.1
有时候报出来的异常是：
python(34247,0x700003f9f000) malloc: *** error for object 0x7ff2a382f800: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
[1]    34247 abort      python run.py

有时候报出来的异常是：
python(14063,0x70000dffc000) malloc: *** error for object 0x7fb7b6b51e00: pointer being realloc'd was not allocated
python(14063,0x70000dffc000) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    14063 abort      APP_NAME=web APP_DEV=dev python run.py
                                                                                                                    
Broadcast Message from root@flycash                                       
        (no tty) at 17:44 CST...                                               
                                                                               
python(14063,0x70000dffc000) malloc: *** error for object 0x7fb7b6b51e00: point
er being realloc'd was not allocated 

观察下来是C库里面分配内存的时候出错。有时候将插入的数据削减长度能够避免这个问题，比如t.add_data，或者log_event(..., data)调用将原本长字符串削减到几百个字符，就能减少出现的频率。
但是我在写代码想要稳定复现这个bug的时候出现了困难，使用长字符串并不能确保一定复现。实际使用中，构建的消息树的深度也不会很大。

**Comment by flycash** [comment]
实际上，偶尔还会出现：
[1]    27423 segmentation fault  python 

如果我们把cat打点全部去掉，就不会出现这个malloc错误

**Comment by flycash** [comment]
我补充一点情况。在将logView设置为False之后，malloc error就没出现了。但是在使用python lock的时候，segmentation fault依旧会出现。在一台linux机器上，将cat打点代码放在lock.acquire和release之间，就出了segmentation fault。可惜的是，在别的机器上都未能重现，即便代码是一样的。
希望这个信息能有帮助。

**Comment by stdrickforce** [comment]
#1465

**Comment by alexKeleon** [comment]
这个错误依然存在
