### ISSUE TITLE
http://unidal.org/nexus/content/repositories/releases/ 无法访问

### ISSUE THREAD

**Issue by levicode** [dianping/cat#1456]

**Comment by kercu** [comment]
最新版的，已经把这个改好了。

**Comment by liuwawa** [comment]
unidal.org域名无法ping通，这个域名站被放弃了吧
ping unidal.org
PING unidal.org (103.37.150.30) 56(84) bytes of data.
^C
--- unidal.org ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 3999ms

**Comment by youyong205** [comment]
这个域名到期了，请换为cat.meituan.com  看下首页最新文档
