### ISSUE TITLE
最新版本的服务端无法登陆

### ISSUE THREAD

**Issue by mr-jinming** [dianping/cat#1460]
catadmin登陆无反应

**Comment by wangyapu0714** [comment]
默认密码是admin、admin

**Comment by wengjs** [comment]
请问密码有办法改吗？
是否能创建新的用户帐号？

**Comment by billowqiu** [comment]
"需要用户名密码登陆，如果配置ldap即可直接登陆，或者用默认账号catadmin/catadmin登陆。"
这个有点误导啊，刚刚才试了半天。。。
