### ISSUE TITLE
新版本的   repos 也加到本地了

### ISSUE THREAD

**Issue by xubihui** [dianping/cat#1466]
[ERROR] No plugin found for prefix 'cat' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/xubihui/.m2/repository), central (http://repo1.maven.org/maven2), unidal.releases (http://cat.meituan.com/nexus/content/repositories/releases/)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by youyong205** [comment]
环境问题你参考安装文档更新下pom
