### ISSUE TITLE
完全按照readme文档部署集群，一直报错

### ISSUE THREAD

**Issue by ch0ice** [dianping/cat#1469]
如下三台机器：
192.168.145.61
192.168.145.62
192.168.145.63

部署版本：
3.0

每台机器包含如下配置文件：
client.xml
datasources.xml
客户端路由配置：
```xml
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="192.168.145.61" backup-server-port="2280">
   <default-server id="192.168.145.61" weight="1.0" port="2280" enable="false"/>
   <default-server id="192.168.145.62" weight="1.0" port="2280" enable="true"/>
   <default-server id="192.168.145.63" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="default" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="192.168.145.62"/>
      <group-server id="192.168.145.63"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="192.168.145.62" port="2280" weight="1.0"/>
         <server id="192.168.145.63" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>
```
服务端配置：
```xml
<?xml version="1.0" encoding="utf-8"?>
<server-config>
   <server id="default">
      <properties>
         <property name="local-mode" value="false"/>
         <property name="job-machine" value="false"/>
         <property name="send-machine" value="false"/>
         <property name="alarm-machine" value="false"/>
         <property name="hdfs-enabled" value="false"/>
         <property name="remote-servers" value="192.168.145.61:8080,192.168.145.62:8080,192.168.145.63:8080"/>
      </properties>
      <storage local-base-dir="target/bucket" max-hdfs-storage-time="15" local-report-storage-time="3" local-logivew-storage-time="7" har-mode="true" upload-thread="5">
      </storage>
      <consumer>
         <long-config default-url-threshold="1000" default-sql-threshold="100" default-service-threshold="50">
            <domain name="cat" url-threshold="500" sql-threshold="500"/>
            <domain name="OpenPlatformWeb" url-threshold="100" sql-threshold="500"/>
         </long-config>
      </consumer>
   </server>
   <server id="192.168.145.61">
      <properties>
         <property name="job-machine" value="true"/>
         <property name="send-machine" value="true"/>
         <property name="alarm-machine" value="true"/>
      </properties>
   </server>
```
现状：
每台机器都可以打开 cat页面，都报错 “出问题CAT的服务端:[192.168.145.63, 192.168.145.62]”
错误信息：
CAT client was disabled due to no CAT servers configured!
然后我把每台机器都放了一个client.xml 这个错误解决了，但是页面还是显示
“出问题CAT的服务端:[192.168.145.63, 192.168.145.62]”

最后说一下，readme 写的真的烂

**Comment by youyong205** [comment]
要不你来写个吧，你牛逼~

**Comment by ch0ice** [comment]
我配的要是不对，你给我怼回来就好了，骂我我也接受，而且我觉得文档写的的确有问题，犯不着回我这么句话，等我 commit  -。-
不是一个人说有问题了，，，
#1268
#1026
#989
#855

**Comment by ch0ice** [comment]
> 要不你来写个吧，你牛逼~

我配的要是不对，你给我怼回来就好了，骂我我也接受，而且我觉得文档写的的确有问题，犯不着回我这么句话，等我 commit -。-
而且不是一个人说有问题了
#1268
#1026
#989
#855

**Comment by youyong205** [comment]
你看到所有的issue都是2015以及2016年的issue 
![image](https://user-images.githubusercontent.com/1281552/49273750-fa909180-f4b0-11e8-96c2-abcba380d67f.png)
![image](https://user-images.githubusercontent.com/1281552/49273757-00867280-f4b1-11e8-889d-8b1e5d1e1dcb.png)
![image](https://user-images.githubusercontent.com/1281552/49273768-067c5380-f4b1-11e8-834f-9d625af168dd.png)
![image](https://user-images.githubusercontent.com/1281552/49273782-1136e880-f4b1-11e8-9eee-292d520b17e5.png)
其中一个近期也做了详细的回复

也别commit了，这么烂的东西不值得有劳大神。

**Comment by ch0ice** [comment]
> 你看到所有的issue一共四个，三个是2015以及2016年的issue
> ![image](https://user-images.githubusercontent.com/1281552/49273750-fa909180-f4b0-11e8-96c2-abcba380d67f.png)
> ![image](https://user-images.githubusercontent.com/1281552/49273757-00867280-f4b1-11e8-889d-8b1e5d1e1dcb.png)
> ![image](https://user-images.githubusercontent.com/1281552/49273768-067c5380-f4b1-11e8-834f-9d625af168dd.png)
> ![image](https://user-images.githubusercontent.com/1281552/49273782-1136e880-f4b1-11e8-9eee-292d520b17e5.png)
> 其中一个近期也做了详细的回复
> 
> 也别commit了，这么烂的东西不值得有劳大神。
我从没说过cat写得烂，您别和我较劲了，是我用词不当，我删了，向您道歉，对不起！！！但我依旧认为它不够清晰。
