### ISSUE TITLE
cat-client更新后没有ClientConfigProvider类了。

### ISSUE THREAD

**Issue by mr-jinming** [dianping/cat#1474]

**Comment by wangyapu0714** [comment]
是没有了，你需要解决的问题是？

**Comment by mr-jinming** [comment]
我之前一直是通过ClientConfigProvider来初始化Cat的。怎么突然删掉了，什么原因呢？

**Comment by wangyapu0714** [comment]
java客户端是不需要手动初始化的，可以参考客户端集成文档 https://github.com/dianping/cat/blob/master/lib/java/README.zh-CN.md
