### ISSUE TITLE
python malloc和segmentation错误依旧存在

### ISSUE THREAD

**Issue by flycash** [dianping/cat#1478]
#1455 里面的问题，现在依旧存在，表现也是类似。之前的那个pull request并未解决该问题

**Comment by flycash** [comment]
补充一点是，该问题在linux平台上没有再现，但是在Mac上依旧存在，使用的Python版本是3.7.1, 操作系统是10.14

**Comment by stdrickforce** [comment]
我没发版，你现在用的是 pip 安装的还是自己安装的？

**Comment by flycash** [comment]
我将源码拉下来之后安装的。。。

**Comment by stdrickforce** [comment]
#1533 看下这个 issue，可能是退出的时候没有 sleep 导致的，不影响使用。

我们也会考虑如何优雅的解决这个问题。
