### ISSUE TITLE
has already been called for this response 

### ISSUE THREAD

**Issue by erstens** [dianping/cat#1479]
`java.lang.IllegalStateException: getOutputStream() has already been called for this response at org.apache.catalina.connector.Response.getWriter(Response.java:662) at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:213) at com.aixuexi.thor.util.ResultUtil.writeResponse(ResultUtil.java:28) at com.aixuexi.thor.except.handler.DefaultExceptionHandler.handler(DefaultExceptionHandler.java:41) at com.aixuexi.thor.except.ExceptionFilter.doFilter(ExceptionFilter.java:74) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:332) at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:120) at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330) at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:137) at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330) at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:266) at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330) at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:73) at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:330) at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:40) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)`
偶现的错误，请求正常访问，没有异常，但localhost.xxxxxxxxxx.log报错，
线上配置了4个服务，两个170的vpc，和两个经典的云。
其它项目没有问题，配置了catFilter，和import dianping client包。
cat client 1.4.2
server 1.2.8

**Comment by wangyapu0714** [comment]
应该是 out.write()  getOutputStream() 冲突问题。

**Comment by youyong205** [comment]
IllegalStateException 自己百度下
