### ISSUE TITLE
最新cat-client不支持jdk1.6

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1482]
cat/lib/java中的cat-client，在文件com.dianping.cat.log.CatLogger中，使用到了类java.nio.charset.StandardCharsets;此类是jdk1.7中加入的，故无法在jdk1.6环境下使用cat-client

**Comment by wangyapu0714** [comment]
这个我改一下，晚点重新发个包。

**Comment by wangyapu0714** [comment]
@578394545 更新下代码，再试下。
