### ISSUE TITLE
采样率设置没有起作用

### ISSUE THREAD

**Issue by yangfanchuhai** [dianping/cat#1484]
设置了采样率，但是发现客户端从来没有拉到过。
![image](https://user-images.githubusercontent.com/11494672/49713305-19e2a800-fc83-11e8-9b15-8ecdbeddc0c5.png)
![image](https://user-images.githubusercontent.com/11494672/49713333-3c74c100-fc83-11e8-95c9-886503541814.png)
![image](https://user-images.githubusercontent.com/11494672/49713353-4ac2dd00-fc83-11e8-9a87-2443bbd6fc74.png)

**Comment by wangyapu0714** [comment]
服务端和客户端的版本是？

**Comment by yangfanchuhai** [comment]
需要重启才生效，都是用的最新的版本

**Comment by wangyapu0714** [comment]
/data/applogs/cat 下面有日志，看看是否出现拉取路由失败
