### ISSUE TITLE
Cat部署启动后提示no datasource(cat) defined!

### ISSUE THREAD

**Issue by TaobaoPlayer** [dianping/cat#1486]
cat version:v3.0.0
Tomcat:v8.5.35
MySQL:8.0.13.0
JDK:1.8
问题描述：
             单机部署，按照wiki上面部署后启动Tomcat，config标签页的应用监控配置tab打开提示500错误，查看Tomcat日志提示message: java.lang.RuntimeException: No data source(cat) defined!.
 /data/cat/appdatas下的client.xml:
                  <?xml version="1.0" encoding="utf-8"?>
                       <config mode="client">
                              <servers>
                                  <server ip="127.0.0.1" port="2280" http-port="8080"/>
                             </servers>
                        </config>
/data/cat/appdatas下的server.xml:
               <?xml version="1.0" encoding="utf-8"?>
<server-config>
   <server id="default">
      <properties>
         <property name="local-mode" value="false"/>
         <property name="job-machine" value="false"/>
         <property name="send-machine" value="false"/>
         <property name="alarm-machine" value="false"/>
         <property name="hdfs-enabled" value="false"/>
         <property name="remote-servers" value="192.168.70.1:8080"/>
      </properties>
      <storage local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="2" local-logivew-storage-time="1" har-mode="true" upload-thread="5">
         <hdfs id="dump" max-size="128M" server-uri="hdfs://127.0.0.1/" base-dir="/user/cat/dump"/>
         <harfs id="dump" max-size="128M" server-uri="har://127.0.0.1/" base-dir="/user/cat/dump"/>
         <properties>
            <property name="hadoop.security.authentication" value="false"/>
            <property name="dfs.namenode.kerberos.principal" value="hadoop/dev80.hadoop@testserver.com"/>
            <property name="dfs.cat.kerberos.principal" value="cat@testserver.com"/>
            <property name="dfs.cat.keytab.file" value="/data/appdatas/cat/cat.keytab"/>
            <property name="java.security.krb5.realm" value="value1"/>
            <property name="java.security.krb5.kdc" value="value2"/>
         </properties>
      </storage>
      <consumer>
         <long-config default-url-threshold="1000" default-sql-threshold="100" default-service-threshold="50">
            <domain name="cat" url-threshold="500" sql-threshold="500"/>
            <domain name="OpenPlatformWeb" url-threshold="100" sql-threshold="500"/>
         </long-config>
      </consumer>
   </server>
   <server id="192.168.70.1">
      <properties>
         <property name="job-machine" value="true"/>
         <property name="send-machine" value="true"/>
         <property name="alarm-machine" value="true"/>
      </properties>
   </server>
</server-config>
/data/cat/appdatas下的datasource.xml:
  <?xml version="1.0" encoding="utf-8"?>

<data-sources>
    <data-source id="cat">
        <maximum-pool-size>3</maximum-pool-size>
        <connection-timeout>1s</connection-timeout>
        <idle-timeout>10m</idle-timeout>
        <statement-cache-size>1000</statement-cache-size>
        <properties>
            <driver>com.mysql.jdbc.Driver</driver>
            <url><![CDATA[jdbc:mysql://127.0.0.1:3306/cat]]></url>
            <user>xxx</user>
            <password>xxx</password>
            <connectionProperties><![CDATA[useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000]]></connectionProperties>
        </properties>
    </data-source>
</data-sources>

      MySQL使用用户名和密码命令行可以正常登陆，cat数据库也已创建，在WEB页面修改路由信息等操作也显示提交失败。不知是什么原因导致这个问题，还麻烦有了解问题原因的朋友指教，谢谢。

**Comment by wangyapu0714** [comment]
文件名是 datasources.xml ？

**Comment by TaobaoPlayer** [comment]
> 文件名是 datasources.xml ？

恩，是datasources.xml,wiki上的部署文档上是这样命名的

**Comment by youyong205** [comment]
/data/cat/appdatas下的datasource.xml:

注意这个后面有一个s   你自己的是datasource

**Comment by TaobaoPlayer** [comment]
> /data/cat/appdatas下的datasource.xml:
> 
> 注意这个后面有一个s 你自己的是datasource

不好意思，是我帖子中写的有误，真实的部署环境中文件名是:datasources.xml.但启动Tomcat还是会报no datasource(cat) defined!

**Comment by youyong205** [comment]
检查下是不是windows的盘弄错了，C盘，D盘，E盘都弄一个看看，另外把datasources.xml 重新删掉，重新弄一个新的，xml也重新改个

**Comment by TaobaoPlayer** [comment]
> 检查下是不是windows的盘弄错了，C盘，D盘，E盘都弄一个看看，另外把datasources.xml 重新删掉，重新弄一个新的，xml也重新改个

谢谢答复，是Tomcat运行目录和代码不在一个盘，所以配置文件导致找不到。不过在Tomcat所在盘正确配置了配置文件后，日志还是会显示连接不上MySQL数据库，查看pom.xml文件中mysql-connector-java版本为5.1.20.将版本号改为8.0.11后编译,但还是连接不上.后卸载了mysql8改为安装了mysql5.7.42后,cat可以正常启动通过浏览器访问了.希望我遇到的问题对以后使cat的人有帮助,再次谢谢你的解答。

**Comment by sgmseb8pn** [comment]
> > 检查下是不是windows的盘弄错了，C盘，D盘，E盘都弄一个看看，另外把datasources.xml 重新删掉，重新弄一个新的，xml也重新改个
> 
> 谢谢答复，是Tomcat运行目录和代码不在一个盘，所以配置文件导致找不到。不过在Tomcat所在盘正确配置了配置文件后，日志还是会显示连接不上MySQL数据库，查看pom.xml文件中mysql-connector-java版本为5.1.20.将版本号改为8.0.11后编译,但还是连接不上.后卸载了mysql8改为安装了mysql5.7.42后,cat可以正常启动通过浏览器访问了.希望我遇到的问题对以后使cat的人有帮助,再次谢谢你的解答。

我的5.7.26不行，mysql5.7.42可以吗？

**Comment by betaberry** [comment]
> > > 检查下是不是windows的盘弄错了，C盘，D盘，E盘都弄一个看看，另外把datasources.xml 重新删掉，重新弄一个新的，xml也重新改个
> > 
> > 
> > 谢谢答复，是Tomcat运行目录和代码不在一个盘，所以配置文件导致找不到。不过在Tomcat所在盘正确配置了配置文件后，日志还是会显示连接不上MySQL数据库，查看pom.xml文件中mysql-connector-java版本为5.1.20.将版本号改为8.0.11后编译,但还是连接不上.后卸载了mysql8改为安装了mysql5.7.42后,cat可以正常启动通过浏览器访问了.希望我遇到的问题对以后使cat的人有帮助,再次谢谢你的解答。
> 
> 我的5.7.26不行，mysql5.7.42可以吗？

5.7.37也不行
