### ISSUE TITLE
cat 在zuul路由中如何埋点

### ISSUE THREAD

**Issue by top3372** [dianping/cat#1488]
cat 在zuul路由中如何埋点

**Comment by top3372** [comment]
在zuul feign 中如何埋点...

**Comment by top3372** [comment]
我现在是通过继承ZuulFilter 自己写一个filter 在route的时候,进行埋点

**Comment by dzhai** [comment]
@top3372 能说一下实现逻辑吗？我也遇到这个问题了，zuul 写个route，转发后的服务需要额外操作吗？
