### ISSUE TITLE
client config 路径问题

### ISSUE THREAD

**Issue by wengjs** [dianping/cat#1489]
环境: python
请问是否有参数可以修改 client config 位子？
一定要放在`/ data / appdatas / cat / client.xml`下吗？
一路追到这，好像没看到
```
    def __init_ccat(self, encoder=ENCODER_BINARY, sampling=True, debug=False, logview=True):
        config = ffi.new("CatClientConfig*", [
            encoder,            # encoder
            0,                  # heartbeat
            int(sampling),      # sampling
            1,                  # multiprocessing
            1 if debug else 0,  # debug log
        ])
        self.cat.catClientInitWithConfig(_(self.appkey), config)
```

**Comment by hgkmail** [comment]
这个是可以设置的，在接入的应用配置环境变量CAT_HOME=/path，可以改变client config 路径

**Comment by hgkmail** [comment]
![image](https://user-images.githubusercontent.com/6395889/95673561-2a943a00-0bdc-11eb-96b2-5e1b57924be0.png)
亲测有效！

**Comment by hgkmail** [comment]
![image](https://user-images.githubusercontent.com/6395889/95673571-51eb0700-0bdc-11eb-8668-44a60e84a7d7.png)
![image](https://user-images.githubusercontent.com/6395889/95673573-5fa08c80-0bdc-11eb-8072-7f9f46ec7200.png)
从CAT源码也可以看到，是读环境变量CAT_HOME的
