### ISSUE TITLE
路由均衡的问题

### ISSUE THREAD

**Issue by awayings** [dianping/cat#1492]
3台机器的集群。磁盘消耗分别是 4G, 10G, 50G。请问有什么方法可以均衡一下负载吗。路由配置里面可以设置具体domain的服务。这个是强制指定的么

**Comment by wangyapu0714** [comment]
路由配置的作用：
1. 针对domian不同机房的机器，CAT 会根据路由策略下发不同的ip list。
2. 根据自身需求，路由配置里面可以设置具体domain的路由策略。

更好的流量均衡可以自己进行扩展，然后变更路由配置，例如根据网卡流量、机器负载等作为依据，将某些流量分配到其他低负载机器。
