### ISSUE TITLE
合并报表配置及业务标签配置是否没用？

### ISSUE THREAD

**Issue by luffyace** [dianping/cat#1493]
合并报表配置是配置什么的？怎么配置？
业务标签配置里面的tag是不用了么？我看Cat里面的方法备注是要删掉的

**Comment by lenaryfun** [comment]
已经没用，我也被坑了

**Comment by wangyapu0714** [comment]
业务标签配置目前还是有用的，后面会有新版本会废弃。合并报表配置已废弃，链接下次更新会删掉。抱歉。
