### ISSUE TITLE
cat3 源码编译

### ISSUE THREAD

**Issue by RS1201** [dianping/cat#1494]
Could not transfer artifact org.unidal.maven.plugins:codegen-maven-plugin:pom:2.5.8 from/to unidal.releases (http
://cat.meituan.com/nexus/content/repositories/releases/): cat.meituan.com

**Comment by wangyapu0714** [comment]
cat.meituan.com已经不再使用，辛苦切换 http://unidal.org/nexus/content/repositories/releases/
