### ISSUE TITLE
cat-server本地存储问题

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1495]
请教一下，目前cat-server的report报告存储，是在各自server服务器本地磁盘的/data/appdatas/cat/bucket中，若使用nas盘，将多台server报告存储指向nas盘同一个目录的话，是否会出现server2报告覆盖掉server1报告的情况呢？谢谢！

**Comment by wangyapu0714** [comment]
1. logview存储应该是没问题的。
2. 在机器重启使用磁盘做备份的情况下，使用nas盘是会出现覆盖冲突的情况。
建议目前不要切nas盘。

**Comment by 578394545** [comment]
> 1. logview存储应该是没问题的。
> 2. 在机器重启使用磁盘做备份的情况下，使用nas盘是会出现覆盖冲突的情况。
>    建议目前不要切nas盘。

OK,了解了，那给nas盘创建多个目录，分别挂给各个服务器的data目录，这样应该可以解决覆盖冲突的问题了
