### ISSUE TITLE
有方案支持druid监控接入么？

### ISSUE THREAD

**Issue by majintao** [dianping/cat#1497]

**Comment by ZhaoFJ** [comment]
我写的
datasource中新增配置
`<property name="proxyFilters"> 
    <list> 
	    <ref bean="stat-filter" />
	    <ref bean="cat-filter" />  // 新增cat-filter过滤器
    </list> 
</property>`


`package com.dianping.cat;

import com.alibaba.druid.filter.FilterChain;
import com.alibaba.druid.filter.FilterEventAdapter;
import com.alibaba.druid.proxy.jdbc.ConnectionProxy;
import com.alibaba.druid.proxy.jdbc.ResultSetProxy;
import com.alibaba.druid.proxy.jdbc.StatementProxy;
import com.dianping.cat.message.Transaction;

import java.sql.SQLException;
import java.util.Properties;

public class CatDataSourceFilter extends FilterEventAdapter {


    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        boolean firstResult = false;
        try {
            firstResult = super.statement_execute(chain, statement, sql);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return firstResult;
    }

    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql, int autoGeneratedKeys) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        boolean firstResult = false;
        try {
            firstResult = super.statement_execute(chain, statement, sql, autoGeneratedKeys);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return firstResult;
    }

    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql, int[] columnIndexes) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        boolean firstResult = false;
        try {
            firstResult = super.statement_execute(chain, statement, sql, columnIndexes);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return firstResult;
    }


    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql, String[] columnNames) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        boolean firstResult = false;
        try {
            firstResult = super.statement_execute(chain, statement, sql, columnNames);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return firstResult;
    }

    @Override
    public int[] statement_executeBatch(FilterChain chain, StatementProxy statement) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", statement.getBatchSql());
        int[] result = null;
        try {
            result = super.statement_executeBatch(chain, statement);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return result;
    }



    public ResultSetProxy statement_executeQuery(FilterChain chain, StatementProxy statement, String sql) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        ResultSetProxy resultSet = null;
        try {
            resultSet = super.statement_executeQuery(chain, statement, sql);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return resultSet;
    }

    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        int updateCount = 0;
        try {
            updateCount = super.statement_executeUpdate(chain, statement, sql);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return updateCount;
    }

    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql, int autoGeneratedKeys) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        int updateCount = 0;
        try {
            updateCount = super.statement_executeUpdate(chain, statement, sql, autoGeneratedKeys);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return updateCount;
    }

    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql, int[] columnIndexes) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        int updateCount = 0;
        try {
            updateCount = super.statement_executeUpdate(chain, statement, sql, columnIndexes);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return updateCount;
    }

    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql, String[] columnNames) throws SQLException {
        Transaction t = Cat.newTransaction("SQL", sql);
        int updateCount = 0;
        try {
            updateCount = super.statement_executeUpdate(chain, statement, sql, columnNames);
            t.setStatus(Transaction.SUCCESS);
        } catch (SQLException e) {
            t.setStatus(e);
            Cat.logError(e);
            throw e;
        } finally {
            t.complete();
        }

        return updateCount;
    }

}
`

**Comment by majintao** [comment]
@ZhaoFJ   上过生产验证过么？ 哈哈.

**Comment by ZhaoFJ** [comment]
上了的，但是只能监控到jdbc template，不能监控到mybatis

**Comment by majintao** [comment]
https://github.com/dianping/cat/blob/master/integration/mybatis/CatMybatisPlugin.java   mybatis 不是已经有现成方案了么？

**Comment by ZhaoFJ** [comment]
@majintao 是的，所以我2个一起用

**Comment by majintao** [comment]
@ZhaoFJ   我整合 mybatis和druid 加上你这个拦截器，执行 selectAll();   cat 没有统计到信息

**Comment by majintao** [comment]
@ZhaoFJ  qq: 578051996  加个好友交流下  哈哈
