### ISSUE TITLE
docker-compose安装报错

### ISSUE THREAD

**Issue by ZhaoFJ** [dianping/cat#1498]
![image](https://user-images.githubusercontent.com/4726024/50142697-ac1f2780-02e5-11e9-8b66-9c26463f8090.png)

**Comment by ZhaoFJ** [comment]
我是这么修改的，可以运行，希望有帮助

`#MAVEN
ENV MAVEN_VERSION_MAJOR 3
ENV MAVEN_VERSION_MINOR 5.2

RUN wget http://archive.apache.org/dist/maven/maven-${MAVEN_VERSION_MAJOR}/${MAVEN_VERSION_MAJOR}.${MAVEN_VERSION_MINOR}/binaries/apache-maven-${MAVEN_VERSION_MAJOR}.${MAVEN_VERSION_MINOR}-bin.tar.gz
RUN tar xvf apache-maven-${MAVEN_VERSION_MAJOR}.${MAVEN_VERSION_MINOR}-bin.tar.gz
RUN rm apache-maven-${MAVEN_VERSION_MAJOR}.${MAVEN_VERSION_MINOR}-bin.tar.gz
ENV M2_HOME=$CATALINA_HOME/apache-maven-${MAVEN_VERSION_MAJOR}.${MAVEN_VERSION_MINOR}
ENV M2=$M2_HOME/bin
ENV PATH=$M2:$PATH
CMD java -version && mvn -version
`

**Comment by wangyapu0714** [comment]
在另外一个issue讨论吧，目前你这面看上去遇到sed mv类似这种把新文件替换原有文件的操作都会出现问题。
