### ISSUE TITLE
docker-compose安装，执行datasource.sh时报错

### ISSUE THREAD

**Issue by ZhaoFJ** [dianping/cat#1499]
![image](https://user-images.githubusercontent.com/4726024/50145731-2c955680-02ed-11e9-9598-acf74b12ef53.png)

**Comment by wangyapu0714** [comment]
docker什么版本？我试一下。

**Comment by ZhaoFJ** [comment]
@wangyapu0714  Docker version 1.13.1,

**Comment by ZhaoFJ** [comment]
@wangyapu0714  docker-compose version 1.23.2

**Comment by wangyapu0714** [comment]
应该是跟docker和sed的版本有关，我这面没有复现。后面我们把sed去掉，这个是容易出问题。目前你可以先把datasouces.xml的配置固定写好，sed部分删掉即可。

**Comment by ZhaoFJ** [comment]
@wangyapu0714  好的，多谢
