### ISSUE TITLE
我的监控条件是，两小时持续监控才报警，可是cat限制了10分钟，可以怎么处理？

### ISSUE THREAD

**Issue by majintao** [dianping/cat#1500]

**Comment by ZhaoFJ** [comment]
老哥请教下你的告警怎么配置的，可否留个联系方式

**Comment by majintao** [comment]
按官网配置，然后测试...

**Comment by ZhaoFJ** [comment]
配了url和项目负责人手机号，监控了一个业务指标，发不出。。

**Comment by majintao** [comment]
我定义了 metric count 来统计我的业务指标，而我的 业务指标统计是每隔30分钟一次； 我想监控 这个业务指标是否2个小时内 都没统计到数据，就报警；  数据量也就几次，不多

**Comment by majintao** [comment]
我直接修改提交的接口，目测可行；后端没做限制....  哈哈

**Comment by wangyapu0714** [comment]
> 我直接修改提交的接口，目测可行；后端没做限制.... 哈哈

👍自己修改是可以的，我们内部也只支持的30分钟。
