### ISSUE TITLE
咨询：应用监控中的应用大盘配置、应用节点阀值以及应用告警中部分功能被注释掉了？

### ISSUE THREAD

**Issue by kcysk** [dianping/cat#1502]
在应用监控中的应用大盘配置、应用节点阀值以及应用告警中的数据库访问告警、缓存访问告警等功能被屏蔽掉了，这些功能暂时没有开源么？还是需要手动调整？在wiki上也没有提及这些配置的介绍

**Comment by wangyapu0714** [comment]
有些链接被注释掉了，希望做的完善之后再开放相关功能。
