### ISSUE TITLE
不报错，没数据

### ISSUE THREAD

**Issue by jiangjian87** [dianping/cat#1503]
服务端启动正常，能正常访问cat控制台，也能看到访问cat的记录。被监控的应用启动正常，也正常打出“Logger file D:\data\applogs\cat\cat_20181219.log”。但无论我访问被监控应用多少次，cat控制台里都看不到访问记录，cat日志里也没有任何报错信息。

**Comment by wangyapu0714** [comment]
日志里的内容是什么？与服务器2280端口是否建立成功？

**Comment by jiangjian87** [comment]
问题解决了，操作错误！新加入的被监控服务器默认不显示。在全部里面找到了
