### ISSUE TITLE
Heartbeat报表出不来

### ISSUE THREAD

**Issue by dzhai** [dianping/cat#1505]
war包和cat-client 都是用的http://unidal.org/nexus/ maven服务的，如果修改这个问题是不是需要自己打war和cat-client，cat-client打包是打cat-client包，还是lib/java下的？？？

**Comment by wangyapu0714** [comment]
cat-client用lib/java下最新的代码

**Comment by dzhai** [comment]
cat-client用lib/java下master的代码，Heartbeat报表只有cat-home的可以出来，其他项目机器的出不来。
用cat-clinet 的master代码可以处理

**Comment by dzhai** [comment]
sorry, 分支不对

**Comment by sunguagua** [comment]
我的是自己打最新的没问题，打lib下的cat-client就不出Heartbeat。看了下是StatusUpdateTask这个类不一样。
