### ISSUE TITLE
cat-client.jar+zuul埋点问题请教

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1507]
在zuul的三个filter，pre、route、post三个阶段埋点时，在pre中创建两个Transaction，t1、t2，并将t1,t2对象放入request的header中，带给route filter，在router filter中将t2关闭，并创建transaction t3，将t1、t3对象放入request的header中，带给post filter，在post filter中，先关闭t3，再关闭t1，完成整个zuul各个阶段的埋点。
此使用方法，有两点疑问想请教一下：
1、通过header直接传transaction的用法，是否会有隐患？
2、关掉所有cat-server，对zuul进行压测（200并发，约100w数据），压测完成后，启动cat-server，发现收到zuul压测数据约60W条（这意味着client端可能积压了60W的埋点数据？），且显示混乱，具体表现为：一个根Transaction，下面包含了大量的子Transaction，其中有部分被认为是异端请求（显示show/hide），想求助帮忙分析一下可能是哪里出现了问题。注：在cat-server正常运行的状态下进行压测，则不会出现上述情况。
由于发生在公司内网环境，故无法上传截图，仅能文字描述，请谅解，谢谢！

**Comment by wangyapu0714** [comment]
Cat 对于全异步化的工作模式，这样打点是会嵌套错乱的，客户端使用的是threadlocal存储的消息上下文，这点你可以确认下。目前你可以对请求计时，在回调时使用newCompletedTransactionWithDuration上报。

**Comment by 578394545** [comment]
> Cat 对于全异步化的工作模式，这样打点是会嵌套错乱的，客户端使用的是threadlocal存储的消息上下文，这点你可以确认下。目前你可以对请求计时，在回调时使用newCompletedTransactionWithDuration上报。

嗯，确实发生了嵌套错乱的问题，已看到源码，尝试提供的方案，谢谢
