### ISSUE TITLE
接入Cat时遇到的几个问题

### ISSUE THREAD

**Issue by WarranHu** [dianping/cat#1508]
1. 如果一笔普通请求，在调用数据库时（因为没有配置socketTimeout）一直hang住不返回，正常开启的Transaction监控，可以抓取到吗？稍微测了下，感觉这笔监控消息不会上送！
2. Cat控制台是否有页面，可以查看最近一段时间的（比如1天）的所有URL请求明细吗？目前看，logview里面可以看到一笔，或最近60笔(每分钟有一笔) 错误的明细日志
3. 普通应用的JVM信息会上送到Cat服务端，但不能在heartbeat菜单查看，在Transaction下看到的报表维度不合适。而cat服务端部署的三台机器则可以在heartbeat查看，报表丰富。请问如何解决更合适？

**Comment by wangyapu0714** [comment]
1. 最开始的Transaction 如果一直没有compelte是不会上报的。
2. 没有展示1段时间所有logview的功能，logview没有全量展示。
3. 是指除了cat的其他应用看不到心跳报表吗？应该是所有java应用的jvm信息都可以在heartbeat报表看到的，是不是项目哪里出现了异常？

**Comment by 578394545** [comment]
> 1. 最开始的Transaction 如果一直没有compelte是不会上报的。
> 2. 没有展示1段时间所有logview的功能，logview没有全量展示。
> 3. 是指除了cat的其他应用看不到心跳报表吗？应该是所有java应用的jvm信息都可以在heartbeat报表看到的，是不是项目哪里出现了异常？

对于问题1，如果最开始的transaction（T1）一直不Complete，具体会出现怎样的情况呢？ 目前发现一个情况，没有Complete的话，T1会一直存放在该线程的Threadlocal中，当该线程被再次重用（T2）时，T1会被当做根Transaction，在T2关闭时，是先关闭的T1（收集了consume方法中的数据，发现T1的关闭时间比T2早），这种情况，应该不合理吧？
另外，有没有一个Transaction Complete方法的逻辑详细说明呢？有些地方没看太明白……谢谢！

**Comment by stdrickforce** [comment]
我们 Transaction 是用一个栈来存的，先加入的 Transaction 会在栈底，如果 T1 一直没有 complete，那这个栈就不会被清空，也就不会上报到服务端。T2 complete 不会影响 T1，反之 T1 complete 会把 T2 complete 掉（Transaction 在 complete 的时候，会把在他上面的 transaction 都 complete 掉）

**Comment by stdrickforce** [comment]
方法的详细说明文档我们不会提供，可以自行看代码了解一下。
也欢迎了解后，写一篇介绍文章提交到我们仓库里。

**Comment by wangyapu0714** [comment]
@578394545 http://techblog.ppdai.com/2018/07/16/20180716/ 拍拍贷有个博客文章可以看下。
