### ISSUE TITLE
Try Catch捕获打印的log.error日志没在cat展示

### ISSUE THREAD

**Issue by w493549442** [dianping/cat#1511]
Log4j加入Cat的appender，发现：
1、没有捕获的错误日志，能够在Cat Service中展示，
2、如果是通过try catch中捕获后，然后通过logger.error打印的错误日志没有在Cat Service上展示，

想问下如果需要把调用链路中自己用log4j打印的error级别日志，也在Cat Service也展示出来，怎么处理？

**Comment by wangyapu0714** [comment]
appender只会收集带有堆栈的异常，普通的字符串日志是不收集上报的。
> 没有捕获的错误日志，能够在Cat Service中展示

有具体使用的code demo吗？
