### ISSUE TITLE
客户端代码使用System.setProperty在web容器部署多应用情况会有问题

### ISSUE THREAD

**Issue by mccxj** [dianping/cat#1512]
java客户端通过SPI来初始化的，我在研究如果使用spring来接管这个spi。
不过我看到初始化会走到类似System.setProperty(Cat.CLIENT_CONFIG, config.toString());的代码，这样的话，如果一个web容器部署多个应用，那可能会相互覆盖。

**Comment by wangyapu0714** [comment]
目前公司标准是一个机器一个实例，如果一定要多实例的话，你要改下这个配置的名字扩展一下。
