### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by square-knight** [dianping/cat#1514]
问题：
1.cat服务端的邮件模版中的域名是写死的“cat-web-server”，当我只有一个环境时还好，只要在hosts里边配置一下就好了。假如我想部署两套以上的cat服务，要求不同环境的邮件都可以转到正确的后台，就不得不改代码不同环境部署不同代码！
2.现在cat的配置还有些不方便，比如我想对某些name配置相同的告警策略，那我就要每个name配置一条。如果name很多，不但配置和修改都会相当麻烦，而且这些应用了相同策略的和其他的配置混淆在一起难以区分。
建议
1.给cat邮件模版中的域名增加一个配置项
2.建议增加更灵活的通配符功能，比如增加“或”通配符。还可以为这些具有通配符功能的配置项增加别名。
我的实现：https://github.com/square-knight/cat/blob/v3.0.0/README.md

**Comment by wangyapu0714** [comment]
谢谢你的建议，下个版本告警有特别大的重构，可以解决你的问题。
