### ISSUE TITLE
Python multiprocessing会导致Cat采集不到数据

### ISSUE THREAD

**Issue by flycash** [dianping/cat#1516]
在使用python的多进程的时候，会出现cat无法收集到子进程里面的打点数据。如：
`
import unittest
import cat
import time
import multiprocessing

class TestMulitProcess(unittest.TestCase):

    def test_a(self):
        cat.init("MultiTest")
        t = cat.Transaction("TestA", "Out")
        pool = multiprocessing.Pool(processes=3)
        t.complete()
        for i in range(0, 4):
            pool.apply(_sub_fun)
        pool.close()
        pool.join()

def _sub_fun():
    t = cat.Transaction("TestB", "Sub")
    time.sleep(2)
    t.complete()
`
最终只能看到TestA的transaction。
即便在代码里面强制初始化cat：
`
# -*- encoding: utf-8 -*-
import unittest
import cat
import time
import multiprocessing

class TestMulitProcess(unittest.TestCase):

    def test_a(self):
        cat.init("MultiTest")
        t = cat.Transaction("TestA", "Out")
        pool = multiprocessing.Pool(processes=3)
        t.complete()
        for i in range(0, 4):
            pool.apply(_sub_fun)
        pool.close()
        pool.join()

def _sub_fun():
    import cat
    from cat.sdk import catSdk as catSdkDefault
    sdk = catSdkDefault("TestASub", debug=True)
    cat.container.put("catsdk", sdk)
    t = cat.Transaction("TestB", "Sub")
    time.sleep(2)
    t.complete()
`
也毫无效果。但是并未输出任何异常，只是采集不到数据。
我们这边的猜测是cat在系统fork一个进程地方都无法正确工作。然而，在读cat的源码的时候，发现这么一个东西：
`
    def __init_ccat(self, encoder=ENCODER_BINARY, sampling=True, debug=False, logview=True):
        config = ffi.new("CatClientConfig*", [
            encoder,            # encoder
            0,                  # heartbeat
            int(sampling),      # sampling
            1,                  # multiprocessing
            1 if debug else 0,  # debug log
        ])
        self.cat.catClientInitWithConfig(_(self.appkey), config)
`
然而这个东西，从C库上来看，只是在消息上加了一个pid部分而已。似乎不能叫做multiprocessing支持……
求问，如何能够快速解决这种问题？

**Comment by stdrickforce** [comment]
目前开源版本不支持 fork 前 init（因为 fork 后没有清除相应的标志位）
我看看这两天把内部这块的代码搬过来吧。
