### ISSUE TITLE
Nodejs 客户端 问题

### ISSUE THREAD

**Issue by hijackthegit** [dianping/cat#1517]
https://github.com/dianping/cat/tree/master/lib/node.js

写着需要 
```
npm install nodecat
```
但是照做后发现nodecat是另一个library, 然后example用法却是
```
cat = require('../lib')
```
请问我是哪里搞错了么？

**Comment by stdrickforce** [comment]
我们这两天会有个 Node 版本的中版本更新，会解决一些文档上的问题。

**Comment by jjeejj** [comment]
我现在也有个问题的就是，我按照文档写的
```
var cat = require('nodecat')

cat.init({
    appkey: 'your-appkey'
})
```

然后部署上去提示 没有 **init** 函数
![catinit](https://user-images.githubusercontent.com/15176971/51156135-21feba80-18b5-11e9-9dd2-930cdc3c4631.png)

**Comment by hijackthegit** [comment]
看样子nodecat在npm是另一个lib, 除非你在package.json 里dependency定义nodecat指向这个github地址，我现在做法是整个node client 放到项目git里

**Comment by jjeejj** [comment]
文档更新了，下上午遇到的问题，下午文档就更新了，很及时 :+1:

**Comment by jjeejj** [comment]
@stdrickforce 明天去用一下，不过文档有个错别字
![image](https://user-images.githubusercontent.com/15176971/51185139-4ab49d80-1911-11e9-96cd-7e768d70f639.png)

这里应该是**nodecat**

**Comment by jjeejj** [comment]
还是不行，这个 node 客户端 就是使用 node-gyp 编译一下的，但是启动之后 cat 后台管理页面，没有这个node 项目， 有搭建成功的吗？ 按照文档来的，这个过程需要注意什么的吗？ 

在 `/data/appdatas/cat/client.xml` 配置服务信息，然后在项目中使用 `@dp-cat/client`  初始化后 ，cat后台管理界面应该有这个 appkey 命名的项目了了么？

**Comment by hijackthegit** [comment]
我还没用最新的lib, 但是appkey我认为就是个identifier （你项目的名字）, 不是真正意义上的api app key这样的东西，我local docker 试过是可以的, 你必须保证以下几个必要条件

1. /usr/local/lib 有编译好的.so
2. npm的lib有编译好的nodecat.node
3. /data/appdatas/cat/client.xml 正确配置ip
4. /data/applogs 已经创建

如果不行， 就要看看文件权限, 具体要看你的log

**Comment by stdrickforce** [comment]
文档已经修改 #1549
