### ISSUE TITLE
logview 里外对不上

### ISSUE THREAD

**Issue by lianghm** [dianping/cat#1524]
transaction:
<img width="1021" alt="default" src="https://user-images.githubusercontent.com/4319127/50767565-4c9ab300-12b8-11e9-99ba-54972eabd462.png">
logview点进去：
<img width="926" alt="default" src="https://user-images.githubusercontent.com/4319127/50767587-5fad8300-12b8-11e9-8e57-cf45a97c9d37.png">

里外不相关，对不上

**Comment by lianghm** [comment]
problem:
<img width="911" alt="default" src="https://user-images.githubusercontent.com/4319127/50767687-b915b200-12b8-11e9-9dd7-4bc9acf5ce06.png">
点进去：
<img width="1102" alt="default" src="https://user-images.githubusercontent.com/4319127/50767729-dfd3e880-12b8-11e9-9505-4f43ea42b7b9.png">

不相关

**Comment by wangyapu0714** [comment]
看截图应该是两个应用的消息，之间是否有联系？所有的消息都是这种情况吗？有重启的情况吗？

**Comment by lianghm** [comment]
> 看截图应该是两个应用的消息，之间是否有联系？所有的消息都是这种情况吗？有重启的情况吗？

是单个应用的多项指标logview对不上（transaction、problem等）。大约有三分之一的概率会对不上

**Comment by xionlylovesisi** [comment]
请问这个问题解决了吗? 容器化部署服务也出现了这种情况,不存在一台机器有多个同一应用进程
