### ISSUE TITLE
python cat client 无url打点。"high queue is full, message has been discarded!"

### ISSUE THREAD

**Issue by awayings** [dianping/cat#1526]
python客户端 2.7 && cffi 111.5  &&c的客户端。cat.Transaction埋点url。使用的时候心跳的消息能够看到。埋点url的消息看不到。客户端一直报错  "high queue is full, message has been discarded!"

**Comment by stdrickforce** [comment]
操作系统版本和样例代码给我一下，我无法复现你说的问题。
