### ISSUE TITLE
Transaction面板下全部项目列表不全

### ISSUE THREAD

**Issue by dzhai** [dianping/cat#1527]
Transaction下的全部项目
![image](https://user-images.githubusercontent.com/2869559/50869831-a4d4d080-13f0-11e9-8b47-f079409b90e4.png)

项目配置
![image](https://user-images.githubusercontent.com/2869559/50869879-d3eb4200-13f0-11e9-9f4d-baffef4cae9a.png)

**Comment by dzhai** [comment]
chrome 浏览器

**Comment by youyong205** [comment]
这个是一个小时更新一次，并不是实时
