### ISSUE TITLE
新版默认使用的是 localBucket 来读写存储？

### ISSUE THREAD

**Issue by lisong2010** [dianping/cat#1528]
新版默认使用的是 localBucket 来读写存储？
这个类里面的实现没看到压缩，而且索引存储的地址 是一个64位字节，后面24位存储offset，前面存储 data 地址，跟文档上完全不一致？还是我理解错了~

**Comment by wangyapu0714** [comment]
是使用 localBucket 来读写存储。可以参考这篇文章https://tech.meituan.com/cat_pr.html。文档服务端设计这块我们再更新下。

**Comment by lisong2010** [comment]
@wangyapu0714 感谢， 
看了下你发的文章链接，没提到压缩，现在存储的数据不进行压缩吗？

**Comment by wangyapu0714** [comment]
可以关注下MessageProcessor，Block打包的时候用的snappy压缩，已经没有用Gzip了。
