### ISSUE TITLE
部署使用域名而非IP失败，不支持域名吗？

### ISSUE THREAD

**Issue by flycash** [dianping/cat#1530]
在最开始部署的时候，我直接使用ip来配置client.xml，类似于：
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="10.1.1.1" port="2280" http-port="8080"/>
        <server ip="10.1.1.2" port="2280" http-port="8080"/>
        <server ip="10.1.1.3" port="2280" http-port="8080"/>
    </servers>
</config>

因为直接写ip不太方便扩展，替换成了域名，类似：
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="machine1.com" port="2280" http-port="8080"/>
        <server ip="machine2.com" port="2280" http-port="8080"/>
        <server ip="machine3.com" port="2280" http-port="8080"/>
    </servers>
</config>

这种部署方式就失败了。

是不支持这种部署吗？还是我可能别的地方出了问题？

**Comment by wangyapu0714** [comment]
这方面是有计划的：
1. 内部使用方式是有个域名去兜底，这个后面把这个改成可配置的一个参数，支持配上你们自己的域名。
2. 后续的方向是提供单独的路由服务，会优先读取路由服务，这个文件只作为兜底或者本机快速调试。
谢谢你的建议！
