### ISSUE TITLE
我的监控报表在正常模式是有数据，但是为啥切换到历史模式之后就没有数据？时间段是一致的

### ISSUE THREAD

**Issue by Fusheng** [dianping/cat#1531]
这个URL有数据，/cat/r/t?domain=xxx&date=2019010710&ip=All&type=URL
但是这个为啥就没有数据？/cat/r/t?op=history&domain=xxx&date=20190107

**Comment by youyong205** [comment]
你看下需要开启历史模式，job-machine=true，另外历史模式要隔一天才可以看到，后端离线任务做的

**Comment by Fusheng** [comment]
配置过之后，现在OK了，多谢

**Comment by cywang4** [comment]
我的报错如下：
[ERROR] [ReportFacade] Task[consumer: 172.31.83.156, count: 0, creation-date: 2021-04-18 22:03:01.0, end-date: null, end-limit: 0, failure-count: 0, id: 1812428, key-id: 1812428, producer: 172.31.16.108, report-domain: cat, report-name: heavy, report-period: 2021-04-18 21:00:00.0, start-date: 2021-04-19 06:48:47.0, start-limit: 0, status: 2, task-type: 0]
小时模式下没有问题，一切到历史模式下就没有任何数据，然后上面的报错就出来了，请问哪位大神知道啥原因啊，以前历史模式数据是可以出来的，这个参数job-machine=true也都配了的

**Comment by flyingglass** [comment]
> 我的报错如下：
> [ERROR] [ReportFacade] Task[consumer: 172.31.83.156, count: 0, creation-date: 2021-04-18 22:03:01.0, end-date: null, end-limit: 0, failure-count: 0, id: 1812428, key-id: 1812428, producer: 172.31.16.108, report-domain: cat, report-name: heavy, report-period: 2021-04-18 21:00:00.0, start-date: 2021-04-19 06:48:47.0, start-limit: 0, status: 2, task-type: 0]
> 小时模式下没有问题，一切到历史模式下就没有任何数据，然后上面的报错就出来了，请问哪位大神知道啥原因啊，以前历史模式数据是可以出来的，这个参数job-machine=true也都配了的

在cat的server日志获取报错的时间可以在172.31.83.156这台机的查看domain为cat的报错情况，一般都是sql的问题：

1. mysql的max_allowed_packet设置过小，会抛出packet too big exception，修改配置，在task找到id为1812428这条记录，设置status为1(packet导致的插入失败，还需要先删除dailyreport对应的heavy和cat这条记录)，1分钟后task会重跑
2. 其他错误也是先在problem标签查到错误，参考步骤1处理task重跑
