### ISSUE TITLE
Heartbeat报表出不来

### ISSUE THREAD

**Issue by evancyz** [dianping/cat#1532]
Server是用docker 装的 

Client 用的是lib最新的 client3.0

cat客户端heart-beat是好的 应用服务器出不来

**Comment by dzhai** [comment]
docker里面的那个cat版本不是3.0的，最好自己用master分支自己打包，client用/lib/java下面的打

**Comment by wangyapu0714** [comment]
@evancyz 手动将/lib/java打一个新的jar包试试呢？如果还有问题，看看日志是否有报错。

**Comment by wubins** [comment]
> 你好
> 我docker容器里里传了最新master打的包
> client用的是lib的最新cat-client
> heart-beat还是出不来

@evancyz 我也是docker 单机模式，我的应用服务器出不来，其他的指标也出不来，也不报错。。。

**Comment by evancyz** [comment]
我客户端切换成了1.3.6旧版本，现在可以了
看来3.0.0的版本有回滚过啊，
/lib/java 里是最新的3.0.0吧，我拿这个当client之后，Heart-Beat出不来
然后换成master打包的3.0 的client 还是没用。
没办法只能切成旧的了

**Comment by wubins** [comment]
> @evancyz @wubins 感谢你们的反馈，docker单机模式我再验证下。如果你们不使用docker的话，是否正常呢？

我这边可能有2个问题导致，一个是时区问题，服务器和客户端时区不一致，服务器是UTC，客户端是中国东八区，当时的现象是服务器端不展示任何的上报数据，可能被丢弃了，我当时没有注意时区的问题，只是怀疑docker，后来换成了非docker模式同时把时区调一致就OK了，我也没有回过头去弄成docker的模式再验证。有一个问题：如果用docker模式，那么cat web 控制台 中 “服务端配置菜单”里面的remote-servers 该如何配置？因为docker的ip地址在重启的时候会变化，请教，谢谢。

**Comment by wangyapu0714** [comment]
1. docker容器启动可以把时区挂载为东八区。
2. remote-servers可以配置为对应的服务端docker容器ip。
3. docker的ip地址在重启的时候会变化，现在Cat目前没办法很好支持服务端频繁更换ip的场景。

**Comment by wuji1mol** [comment]
非docker环境也无法显示heartbeat报表，其它数据能正常显示，运行的项目是springboot2，JDK8，使用的是3.0.0版本java-client.jar

**Comment by lsfff** [comment]
我也遇到了相同的问题 docker部署后Heartbeat无法显示 请问有解决方案了吗

**Comment by evancyz** [comment]
> 我也遇到了相同的问题 docker部署后Heartbeat无法显示 请问有解决方案了吗

我这里是客户端降级，降级成1.3.几了
