### ISSUE TITLE
python 客户端上报信息丢失

### ISSUE THREAD

**Issue by zeyu203** [dianping/cat#1533]
在一台服务器A上本地通过搭建的方法搭建 cat，通过 python 客户端调用 t = cat.Transaction("justfortest", "hello world") 打点，多次执行，在页面上看到仅记录3次，并且客户端执行时常常抛出 段错误
![image](https://user-images.githubusercontent.com/5253434/51015658-08552e80-15a8-11e9-96c5-639fef6a6220.png)

代码如下：
```python
import cat

cat.init("testapp")

trans = cat.Transaction("justfortest", "hello world")
trans.complete()
```

**Comment by zeyu203** [comment]
python 版本是 3.6，系统版本是 centos 7.5

**Comment by zeyu203** [comment]
我尝试按照中文文档，安装 pycat
https://github.com/dianping/cat/blob/master/lib/python/README.zh-CN.md
但提示找不到 pycat 包

**Comment by zeyu203** [comment]
我尝试按照中文文档，安装 pycat，但是安装后里面并没有 cat 包，只有 cli.py 和 talk.py
![image](https://user-images.githubusercontent.com/5253434/51297258-8eff8500-1a5a-11e9-8614-86fbeb3d56e9.png)

**Comment by stdrickforce** [comment]
这个是因为我们异步发送，最后需要 time.sleep(1) 防止主进程退出了之后子线程也跟着退出，正常使用不受影响，脚本的话最后加个 time.sleep(1) 就行了。

我们也会考虑下比较优雅的解决办法。

**Comment by stdrickforce** [comment]
这个是因为我们异步发送，最后需要 time.sleep(1) 防止主进程退出了之后子线程也跟着退出，正常使用不受影响，脚本的话最后加个 time.sleep(1) 就行了。

我们也会考虑下比较优雅的解决办法。
