### ISSUE TITLE
Business视图如何下钻查看主机上报视图？

### ISSUE THREAD

**Issue by lonelili** [dianping/cat#1535]
# 环境
cat-sdk 3.0.1
pycat 0.1.1
python 2.7.5

# 问题
多主机埋点上报同一个业务指标，如何查看具体每一台主机的上报数据？
当业务指标下跌时，需要通过下钻到具体的主机视图，来找到是哪台主机故障了。

# 截图
![image](https://user-images.githubusercontent.com/4277623/51094536-e39bc980-17e8-11e9-954f-2ccff2a4170c.png)

**Comment by youyong205** [comment]
不支持这个功能
