### ISSUE TITLE
cat 启动日志文件的问题

### ISSUE THREAD

**Issue by jjeejj** [dianping/cat#1536]
当启动 tomcat 成功后 ，在 **/data/appdatas/cat** 没有生产日志文件的呢？ 这个是什么原因呢？

**Comment by youyong205** [comment]
你在仔细检查吧，对照文档在看下，这个提供不出线索。

**Comment by jjeejj** [comment]
嗯 好的。 就是现在cat 服务 已经起来了,可以使用了，就是日志文件没有出来，我在排查一下
