### ISSUE TITLE
如何设置客户端日志按大小滚动并限制日志个数

### ISSUE THREAD

**Issue by shikai2013** [dianping/cat#1541]
如题，客户端日志如果想按大小滚动并限制日志个数，默认支持吗，初步看了下代码好像并没有地方直接提供配置，有好的解决方案吗

**Comment by wangyapu0714** [comment]
客户端日志是每天生成一个，不支持按大小滚动并限制日志个数，正常情况下客户端的日志内容应该不是很多，如果需要可以自行扩展 CatLogger。
另外问下想解决的核心问题是什么？仅仅只是想限制下日志个数吗？
