### ISSUE TITLE
这些异常error有没有影响

### ISSUE THREAD

**Issue by albertflyer** [dianping/cat#1548]
第一个error 
HT2 cat localhost.localdomain 192.168.104.164 Cat-ConfigSyncTask 2203 Cat-ConfigSyncTask-1 cat-c0a868a4-429925-10 null null
--
t21:00:01.713 | TimerSync | base |   |  
t21:00:01.713 | SQL | business-config.findByName |   |  
E21:00:01.714 | SQL.Method | SELECT |   | ["base"]
E21:00:01.714 | SQL.Database | jdbc:mysql://192.168.104.101:3306/cat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000 |   |  
T21:00:01.714 | SQL | business-config.findByName |   | 1.06ms SELECT bc.id,bc.`name`,bc.domain,bc.content,bc.updatetime FROM business_config bc WHERE bc.name = ?
E21:00:01.714 | RuntimeException | java.lang.NullPointerException | ERROR | java.lang.NullPointerException
T21:00:01.714 | TimerSync | base |   | 1.21ms

第二个error 

t20:09:01.713 | TimerSync | remote-server-updater |   |  
-- | -- | -- | -- | --
t20:09:01.713 | ModelService | CompositeStateService |   |  
A20:09:01.713 | ModelService | RemoteStateService | java.lang.NullPointerException | 4.62ms http://192.168.104.164:8080/cat/r/model/state/cat/CURRENT?op=xml&length=2694
A20:09:01.713 | ModelService | RemoteStateService | java.lang.NullPointerException | 1.66ms http://192.168.104.165:8080/cat/r/model/state/cat/CURRENT?op=xml&length=4539
A20:09:01.713 | ModelService | RemoteStateService | java.lang.NullPointerException | 1.77ms http://192.168.104.166:8080/cat/r/model/state/cat/CURRENT?op=xml&length=3681
T20:09:01.718 | ModelService | CompositeStateService |   | 5.27ms request=ModelRequest[domain=cat, period=CURRENT, properties={}]&thread=Thread[Cat-ConfigSyncTask-1,5,Cat-ConfigSyncTask]
E20:09:01.718 | RuntimeException | java.lang.NullPointerException | ERROR | java.lang.NullPointerException at com.dianping.cat.consumer.state.model.transform.BaseVisitor.visitStateReport(BaseVisitor.java:39) at com.dianping.cat.report.task.DefaultRemoteServersUpdater.buildServers(DefaultRemoteServersUpdater.java:53) at com.dianping.cat.report.server.ServersUpdaterManager$1.handle(ServersUpdaterManager.java:57) at com.dianping.cat.task.TimerSyncTask$1.run(TimerSyncTask.java:82) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294)
T20:09:01.718 | TimerSync | remote-server-updater |   | 5.49ms

第三个
20:10:30.504	Task	jar		
  t20:10:30.505	SQL	report.findAllByPeriodName		
    E20:10:30.513	SQL.Method	SELECT	 	["2019-01-17 06:00:00", "heartbeat"]
    E20:10:30.513	SQL.Database	jdbc:mysql://192.168.104.101:3306/cat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000	 	
  T20:10:30.515	SQL	report.findAllByPeriodName	 	10ms SELECT r.domain,r.`name` FROM hourlyreport r WHERE r.period = ? AND r.name = ?
  E20:10:30.515	FindDomain	2019-01-17 06:00:heartbeat	 	[cat, omp-service, omp-web]
  E20:10:30.515	Error	java.lang.NoClassDefFoundError	ERROR	java.lang.NoClassDefFoundError: com/dianping/cat/home/jar/entity/JarReport 
at com.dianping.cat.report.page.statistics.task.jar.JarReportBuilder.buildHourlyTask(JarReportBuilder.java:77) 
at com.dianping.cat.report.task.ReportFacade.builderReport(ReportFacade.java:61) 
at com.dianping.cat.report.task.DefaultTaskConsumer.processTask(DefaultTaskConsumer.java:79) 
at com.dianping.cat.report.task.TaskConsumer.run(TaskConsumer.java:90) 
at java.lang.Thread.run(Thread.java:745) 
at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294) 
T20:10:30.514	Task	jar	java.lang.NoClassDefFoundError	10ms Task[consumer: 192.168.104.164, count: 0, creation-date: 2019-01-17 07:03:00.0, end-date: null, end-limit: 0, failure-count: 0, id: 155877, key-id: 155877, producer: 192.168.104.164, report-domain: cat, report-name: jar, report-period: 2019-01-17 06:00:00.0, start-date: Thu Jan 17 07:10:30 EST 2019, start-limit: 0, status: 2, task-type: 0]

修改了一下cat的html的某个页面 不知道和这个有没有关系

**Comment by wangyapu0714** [comment]
什么版本？
1. 第一个异常debug看下
2. 远程数据获取存在问题，导致获取的报表是null。检车下路由的配置，其他报表是否也都能正常读取。
3. 项目启动应该就有问题。 

仅仅修改html不会影响启动，可以把改动去掉再试下。
