### ISSUE TITLE
cat transaction历史报表显示时间段问题

### ISSUE THREAD

**Issue by fxltsbl3855** [dianping/cat#1551]
![image](https://user-images.githubusercontent.com/8154045/51370757-2506de80-1b33-11e9-821e-38eb1a54d55d.png)

transaction历史报表显示时间段跟实际不一致，多谢答疑

cat版本3.0

**Comment by fxltsbl3855** [comment]
> 周报表的周期是固定的。你查询数据当天是17号，19号的数据暂未生成。

查询当天是18号，今天是1月22号，我再查一次，结果如下：
17号的日报数据：
![image](https://user-images.githubusercontent.com/8154045/51506592-f6854e00-1e27-11e9-9523-4ea6231505fe.png)

12号到18号23点多的周报数据（条件一样，但是url总数竟然比17号的数据少）
![image](https://user-images.githubusercontent.com/8154045/51506634-35b39f00-1e28-11e9-9175-194dfb8f6ae7.png)

**Comment by fxltsbl3855** [comment]
帮忙给看看上述是什么问题(还是我设置哪里出了问题)，谢了

另外再提供一个线索，上条回复中第二幅图（周报）点击后面URL 记录的“LogView” 链接：
![image](https://user-images.githubusercontent.com/8154045/51506842-49abd080-1e29-11e9-8101-07d8d0c62f22.png)

(点击上条回复中第一幅图（日报）后面URL 记录的“LogView” 链接，能正常显示数据) 谢谢，
帮忙看看是什么原因

**Comment by IReallyWantYou** [comment]
同问：logView后，显示信息丢失？请大佬解答

**Comment by wangyapu0714** [comment]
@fxltsbl3855 点show看下周报表每天的数据是多少，看上去周报表没有构建完全。可以把周任务本地执行debug看一下。

**Comment by wangyapu0714** [comment]
@IReallyWantYou 是否有详细场景？logview默认只保存6小时，历史数据需要上传到hdfs。

**Comment by fxltsbl3855** [comment]
> @fxltsbl3855 点show看下周报表每天的数据是多少，看上去周报表没有构建完全。可以把周任务本地执行debug看一下。

![image](https://user-images.githubusercontent.com/8154045/52544232-73359780-2dea-11e9-8ce7-ddca2c0087d9.png)
周报表曲线上显示的起止时间是12号0点到17号0点的；   这情况是说明周任务没正确执行？
周任务本地执行怎么执行？ 谢谢

**Comment by wangyapu0714** [comment]
@fxltsbl3855 周报表曲线上显示的起止时间是12号0点到17号0点的，这个周任务应该执行结束了。你现在看应该也是存在问题的吧？对应每天的报表都是否成功存入mysql？如果天报表都没问题，建议把数据库任务状态变更一下，让任务重新做一下。

**Comment by fxltsbl3855** [comment]
（12号到19号）对应的日报数据：
![image](https://user-images.githubusercontent.com/8154045/52757840-18e24400-3041-11e9-8de4-496285e37ddf.png)

（12号到19号）周报数据：
![image](https://user-images.githubusercontent.com/8154045/52757923-5a72ef00-3041-11e9-8326-29b8f9bd65e9.png)

根据mysql数据推论：
（因为数据出入主要是周报数据不包括17号的日报数据，所以咱们就只关注17号的数据）
17号日报创建时间：18号11点
(12号到19号)周报创建时间：18号4点
17号日报的创建  是在  (12号到19号)周报 之后，所以周报数据肯定不包括17号日报的数据，这个推论跟界面数据是相符合的（是否正确？）

疑惑1：
17号的日报数据到18号11点才创建？（这个时间点是不是符合设计？）
疑惑2：
(12号到19号)周报 的创建时间提前了，一周没结束就开始创建了， 貌似不合理？（这个如何解决）

多谢大神跟进这个问题，非常感谢，继续麻烦看下？

**Comment by fxltsbl3855** [comment]
![image](https://user-images.githubusercontent.com/8154045/52758823-b1c68e80-3044-11e9-9e48-27c8076b0ce8.png)

再提供个线索，tks

**Comment by youyong205** [comment]
那你可以把这天的报表删除，然后在task找到对应的周报表记录，重新执行下。

你这个问题可能情况下，是不是开启了多个task任务机器，合并周任务的时候，其实某一天天任务还没有执行好。目前cat这块并没有一个完善依赖机制，任务串行执行

**Comment by zyl19880411** [comment]
您好，单台机器部署测试，发现历史报表中默认的项目cat-home日报表正常显示，但是自己的项目在日报表中的tran和event中都没有数据，目前只能按照小时的粒度能看到数据，请问如何解决

**Comment by xiaohuasheng** [comment]
可能是mysql机器的时区不对，可在shell用 date （shell）或在mysql命令行 select now();看看
