### ISSUE TITLE
Springcloud+feign+hystrix整合CAT无法设置messageId

### ISSUE THREAD

**Issue by chenhong0129** [dianping/cat#1552]
我们项目启用了hystrix，由于跨线程问题造成在FeignRequestInterceptor中调用Cat.logRemoteCallClient()方法:
context.addProperty(Cat.Context.ROOT, root.toString());
        context.addProperty(Cat.Context.PARENT, child.toString());
        Cat.logRemoteCallClient(context);
得到的context是全新的，而不是按照传入property生成，这个应该怎么解决，谢谢

**Comment by wangyapu0714** [comment]
logRemoteCallClient 中会获取当前tree的消息id以及root和parent，所以你传入的参数会被覆盖。logRemoteCallClient 的作用就是记录这些消息 id，你的需求是已知一些消息id然后进行串接，这样可以用你构建好的 context 直接调用logRemoteCallServer进行记录。

**Comment by loroxxx** [comment]
同问，我也遇到这个问题

**Comment by chenhong0129** [comment]
我现在FeignRequestInterceptor中直接实现Cat.logRemoteCallClient()方法的操作，手动setMessageId等信息，还是无法串接，能告知下原因吗：
![default](https://user-images.githubusercontent.com/26050948/51666894-b675c500-1ff9-11e9-8f6e-5f43f7b8ef4a.png)
非常感谢！

**Comment by 578394545** [comment]
feign+hystrix，在FeignRequestInterceptor中时，已经是在子线程中了，和主线程已经不是同一个messageTree，所以调用Cat.logRemoteCallClient()，是关联不上的（在console中的event报表中，可以看到一个Type为RemoteCall ，和主线程的messageId，是不同的），应该在主线程中调用Cat.logRemoteCallClient()，将生成的context参数传给子线程，子线程再放入http header中传给下游

**Comment by chenhong0129** [comment]
开始我是按照 @578394545 您的办法操作的，但是有个问题，我们业务中存在连续调用feign接口的情况，就是A调用完B接口（feign）后继续调用C接口（feign），这样在主线程中调用Cat.logRemoteCallClient()，将生成的context参数传给子线程，就会造成调用点丢失，C调用覆盖了B调用记录，这种情况应该怎么修改呢，谢谢

**Comment by youyong205** [comment]
cat本质上一个监控系统，主要体现在监控报表Transaction、event、problem、heartbeat等。logview是cat原始的log采集方式，但是cat并不是一个标准的全链路系统，全链路系统参考dapper的论文，业内比较知名的鹰眼，zipkin。cat的logview使用的技术是threadlocal，将一个thread里面的打点聚合上报，有一点弱化版本的链路功能，但在异步线程等等一些场景下，其实不合适。我美团点评内部，有mtrace专门做全链路分析。

**Comment by chenhong0129** [comment]
后面我看到源码有新增ForkedTransaction 相关的，是不是针对跨线程的调用捕捉？

**Comment by youyong205** [comment]
ForkedTransaction只能说是会考虑加一点点功能，不能完全解决跨线程调用问题。

**Comment by oldinaction** [comment]
可考虑使用HystrixRequestVariableDefault传递Cat.Context

**Comment by monkeyAlwaysWin** [comment]
重写了HystrixConcurrencyStrategy,并且通过它的构造方法将已经生成的CatContext传递进去,并且在feign拦截器中构建requestTemplate的header,但是调用链路无法显示,值和对象都已经是正确的了,不知道从哪里入手解决.
