### ISSUE TITLE
tomcat 启动正常，但是浏览器访问地址失败 报500

### ISSUE THREAD

**Issue by jjeejj** [dianping/cat#1554]
现在情况就是 tomcat 启动正常，但是访问配置的url的时候报500的错误
![temp](https://user-images.githubusercontent.com/15176971/51372940-c3963e00-1b39-11e9-8fcf-6c78ba15fbd9.png)

![temp](https://user-images.githubusercontent.com/15176971/51372979-dd378580-1b39-11e9-88e8-cb7a6ebb1600.png)

**Comment by youyong205** [comment]
也建议检查jdk tomcat的版本，如果是用官方默认的war，请使用jdk1.8 以及tomcat8.
这个都验证过没问题的
