### ISSUE TITLE
python 客户端上报一段时间后，会导致内存数据给修改的情况，导致服务异常。

### ISSUE THREAD

**Issue by outshow** [dianping/cat#1557]
系统信息：
CentOS release 6.9 (Final)
Linux version 2.6.32-696.el6.x86_64
由于glibc比较旧，运行是报错，所以手动更新了glibc
OSError: cannot load library '*****/python2.7/site-packages/cat/lib/linux-glibc/libcatclient.so': /lib64/libc.so.6: version `GLIBC_2.14' not found (required by *****/python2.7/site-packages/cat/lib/linux-glibc/libcatclient.so).  Additionally, ctypes.util.find_library() did not manage to locate a library called '*****/python2.7/site-packages/cat/lib/linux-glibc/libcatclient.so'

问题：服务运行一段时间后（不固定，随机），有些内存数据给修改
![image](https://user-images.githubusercontent.com/6645609/51507909-0e5fd080-1e2e-11e9-8a77-e61b5e63ab25.png)
![image](https://user-images.githubusercontent.com/6645609/51507944-3f400580-1e2e-11e9-9eb5-e940a63bcd70.png)
导致服务异常，去掉cat上报后，服务恢复正常，不会出现。

**Comment by stdrickforce** [comment]
#1564

**Comment by stdrickforce** [comment]
有没有可能提供一个能够复现的代码段，协助我们排查一下这个问题？
