### ISSUE TITLE
php 客户端有开发计划吗？

### ISSUE THREAD

**Issue by trensy** [dianping/cat#1560]
你好，php 客户端有开发计划吗？目前用swoole应该可以实现的吧

**Comment by wangyapu0714** [comment]
php暂时没有开发计划

**Comment by trensy** [comment]
@wangyapu0714   有相关开发资料吗？我们php项目有计划上cat，如果没有我们就自己开发了

**Comment by stdrickforce** [comment]
没有，不过我觉得一个比较可行的思路是通过本地 agent 转发上去，否则每个进程开一个连接到 cat-server 有点受不了，而且聚合的效果也不好。

**Comment by yuanlj-tea** [comment]
> @wangyapu0714 有相关开发资料吗？我们php项目有计划上cat，如果没有我们就自己开发了

你们实现好了吗

**Comment by wuli07101** [comment]
该项目已支持php：https://www.catphp.com/
