### ISSUE TITLE
获取 transaction 失败

### ISSUE THREAD

**Issue by songlei0827** [dianping/cat#1561]
cat2.0 版本；

请求 /cat/r/model/transaction/learning-homepage/CURRENT?op=xml&ip=All

偶发报错 导致页面展示失败，报错如下：
       
java.util.ConcurrentModificationException at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711) at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:739) at com.dianping.cat.consumer.transaction.model.transform.DefaultMerger.visitTypeChildren(DefaultMerger.java:230) at com.dianping.cat.consumer.transaction.model.transform.DefaultMerger.visitType(DefaultMerger.java:226) at com.dianping.cat.consumer.transaction.model.entity.TransactionType.accept(TransactionType.java:60) at com.dianping.cat.consumer.transaction.model.transform.DefaultMerger.visitMachineChildren(DefaultMerger.java:122) at com.dianping.cat.consumer.transaction.model.transform.DefaultMerger.visitMachine(DefaultMerger.java:109) at com.dianping.cat.consumer.transaction.model.entity.Machine.accept(Machine.java:26) at com.dianping.cat.consumer.transaction.model.transform.DefaultMerger.visitTransactionReportChildren(DefaultMerger.java:216) at com.dianping.cat.consumer.transaction.model.transform.DefaultMerger.visitTransactionReport(DefaultMerger.java:203) at com.dianping.cat.consumer.transaction.TransactionReportMerger.visitTransactionReport(TransactionReportMerger.java:150) at com.dianping.cat.consumer.transaction.model.entity.TransactionReport.accept(TransactionReport.java:36) at com.dianping.cat.report.page.transaction.service.LocalTransactionService.buildReport(LocalTransactionService.java:68) at com.dianping.cat.report.service.LocalModelService.getReport(LocalModelService.java:76) at com.dianping.cat.report.page.model.Handler.handleOutbound(Handler.java:72) at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
--

**Comment by wangyapu0714** [comment]
可以升级到最新的master代码
