### ISSUE TITLE
CAT 客户端模型讨论

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1563]
虽然这个是使用上不当导致的问题，不过我对这个还挺感兴趣的。
能再详细描述一下如何复现吗？最好能给我一个能够直接复现的场景，我来理一下逻辑。

_Originally posted by @stdrickforce in https://github.com/dianping/cat/issues/1520#issuecomment-453889240_
不好意思，前几天一直在忙，没来得及回复~

埋点描述：
      一个项目A、B两个接口做了埋点，其中A接口由于开发人员没有try catch，故异常发生时 会出现A 只newTransaction，没有Complete，B接口埋点正确无误。
复现场景描述:
     复现的话，可以准备两个接口A,B，埋点情况如上（可以直接将接口A，newTransaction后直接抛异常，并将线程释放掉，使A接口的Transaction begin在线程的ThreadLocal中存着），同时，按照前后顺序请求A、B两个接口，令其使用的是同一条线程（线程复用），会有概率复现（messageTree的结构，可能是A的begin、B，也可能是A、B、B…）。
    根据client的设计，A接口出现异常的Transaction，应该永远不会再关闭，也不可能发送给server端才对，所以server端会接收到这个MessageTree，就很奇怪了，可能是我还有哪里没有理解到位。

**Comment by xiaolei-fu** [comment]
Cat.getManager().reset() 在线程执行前可以调用一下，把ThreadLocal清空

**Comment by wangyapu0714** [comment]
可以提供一个demo code
