### ISSUE TITLE
javaagent-client-agent只显示部分监控类型

### ISSUE THREAD

**Issue by zhouyoulin12** [dianping/cat#1566]
您好：
根据文档描述，添加javaagent，客户端启动成功，但是实际cat管理平台只能看到：URL，Filter，org.apache.Method，Cache.Redis等监控，另外多了一个System的监控类型，但是mysql，spring controller，spring service的监控都没有，请问还需要什么配置吗

**Comment by youyong205** [comment]
这个请参考其他集成文档。
mysql如果用ibatis可以参考ibatis的集成。spring可以用URL的filter集成等
