### ISSUE TITLE
无法显示heartbeat报表

### ISSUE THREAD

**Issue by wuji1mol** [dianping/cat#1568]
其它数据能正常显示，运行的项目是springboot2，JDK8，使用的是3.0.0版本java-client.jar

**Comment by wangyapu0714** [comment]
服务端代码是什么版本的？3.0.0版本java-client.jar 必须要用3.0的服务端版本。

**Comment by wuji1mol** [comment]
我用mvn打出的包可以正常显示了，你们可以替换下链接上的war包，有这个bug
