### ISSUE TITLE
系统集成cat-client后，在docker环境下运行的问题

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1571]
系统集成了cat-client并打入一些埋点，在云主机的docker容器中运行，cat-server获取到的是docker容器的ip（172.xx.xx.xx），这样不便于定位问题，是否能获取到docker容器所在云主机的ip呢？谢谢！

**Comment by youyong205** [comment]
这个需要你自己扩展，cat默认就是获取本机的ip，优先使用内网ip。
可以在java启动参数加上-Dhost.ip=*.*.*.*

**Comment by youyong205** [comment]
https://github.com/dianping/cat/wiki/cat_faq 参考faq里面
