### ISSUE TITLE
heartbeat报表没有client监控数据

### ISSUE THREAD

**Issue by LiKai5412** [dianping/cat#1572]
heartbeat报表能够显示server端的监控数据
![image](https://user-images.githubusercontent.com/34589006/52684810-795e7c00-2f82-11e9-9777-8a8da6f7aebf.png)
但是client端的监控数据为空白
![image](https://user-images.githubusercontent.com/34589006/52684840-92ffc380-2f82-11e9-8005-d51f68525391.png)
请问这是什么问题，是我哪配置的不对吗？
另外在Problem报表页里是有heartbeat这项的，且logview为下图
![image](https://user-images.githubusercontent.com/34589006/52685037-33ee7e80-2f83-11e9-8801-a439f6d8c2ea.png)

**Comment by youyong205** [comment]
麻烦升级下最新的lib下java客户端。这个java客户端做个版本更新，你在试试
