### ISSUE TITLE
有没有考虑支持.net呢

### ISSUE THREAD

**Issue by mrtylerzhou** [dianping/cat#1573]
公司java项目在使用cat,就来到github上关注一下,发现支持的客户端挺丰富的,但是没有.net,有没有考虑支持.net或者.net core呢

**Comment by SizakeYang** [comment]
.net实现可能有,我看到的培训文档上携程有对应的客户端实现

**Comment by youyong205** [comment]
携程开源的有，我补充到多语言客户端版本里面

**Comment by mrtylerzhou** [comment]
好的,谢谢说明,谢谢携程

**Comment by wangyapu0714** [comment]
@mrtylerzhou https://github.com/ctripcorp/cat.net
