### ISSUE TITLE
历史模式没有数据

### ISSUE THREAD

**Issue by LiKai5412** [dianping/cat#1575]
请问，我的报表在小时模式里有数据，但在历史模式下没有数据是什么原因，是我配置问题吗？需要配置什么?还是有什么生成规则
![image](https://user-images.githubusercontent.com/34589006/52772797-5dd39e00-3074-11e9-8fa3-eaf1cb4843b0.png)

![image](https://user-images.githubusercontent.com/34589006/52772756-44caed00-3074-11e9-90a0-ad07d135cc53.png)

**Comment by wangyapu0714** [comment]
https://github.com/dianping/cat/wiki/global 需要配置job-machine，这样才会执行历史任务。

**Comment by LiKai5412** [comment]
> https://github.com/dianping/cat/wiki/global 需要配置job-machine，这样才会执行历史任务。

我已经配置了job-matchine
![image](https://user-images.githubusercontent.com/34589006/52829216-d84cfe00-3106-11e9-93b2-d14fc1cd8e41.png)
其中server的id属性为当前cat-home项目的ip地址。

**Comment by LiKai5412** [comment]
问题已解决，修改完配置后一定要重启服务，我以为修改配置能自动生效。
