### ISSUE TITLE
查看历史数据丢失问题

### ISSUE THREAD

**Issue by IReallyWantYou** [dianping/cat#1577]
1、查看历史数据（大概两周前），不管是transcation、problem等，点击logview时，出现：Sorry, the message is not there. It could be missing or archived.   场景：本地起服务并且cat服务器只有白天才会跑。
2、生产环境下，若不配置hdfs服务，单机模式的cat服务器每天会处理多少数据？能给一些生产环境服务器的需求参数做参考吗？

**Comment by slankka** [comment]
关闭CAT 服务之前，有没有访问 /cat/r/home?op=checkpoint？

**Comment by youyong205** [comment]
参考下文档，有本地存储的时间配置，单机服务每天处理数据和服务器本身有关系，也和消息大小等相关，这个并没有实际的参考值。

实际的服务端能力衡量，可以参考state报表里面消息丢失以及结合一些系统指标
