### ISSUE TITLE
cat配置了业务监控报警，但是没有发送请求

### ISSUE THREAD

**Issue by luffyace** [dianping/cat#1580]
![1550284382751](https://user-images.githubusercontent.com/13696180/52893445-1f0a2900-31d7-11e9-987d-3637b0d01192.jpg)
![1550285045632](https://user-images.githubusercontent.com/13696180/52893516-ffbfcb80-31d7-11e9-9f10-3583d4f76025.jpg)

![1550284956525](https://user-images.githubusercontent.com/13696180/52893496-c38c6b00-31d7-11e9-8d10-6b723c46fda7.jpg)

为什么没有报警？

**Comment by wangyapu0714** [comment]
是否已经开启告警机器角色？可以debug跟下BusinessAlert看看。

**Comment by luffyace** [comment]
是看服务端配置里面是否开启了么？
<server id="127.0.0.1">
      <properties>
         <property name="job-machine" value="true"/>
         <property name="send-machine" value="true"/>
         <property name="alarm-machine" value="true"/>
      </properties>
   </server>
我这边配置开启了，debug没有进入到BusinessAlert

**Comment by luffyace** [comment]
知道了，告警人没有配置
