### ISSUE TITLE
State报表中的default项目占用空间较大

### ISSUE THREAD

**Issue by awayings** [dianping/cat#1581]
![image](https://user-images.githubusercontent.com/688149/52947881-ed4db980-33b2-11e9-8cc5-3308e04154bc.png)

如图所示，我们没有default的项目，为什么会显示，而且占用空间较大

**Comment by youyong205** [comment]
看看下项目是否使用远程rpc调用，cat.logRemoteCallClient 这里面需要传入服务端的appkey，如果不传，默认是default
