### ISSUE TITLE
CAT是否支持小时级别或者天级别的监控报警

### ISSUE THREAD

**Issue by bug1024** [dianping/cat#1583]
业务上有些指标可能不是连续的，但只要某个小时内的总数达到某个阈值就视为正常。
一个常见的场景：凌晨跑脚本，脚本处理一条数据会上报到CAT，但是上报的时间不是固定的，第一天上报时间可能在1点10分到1点12分，第二天上报时间可能在1点40分到1点50分，如果某一天这个小时内上报的数据没有达到阈值则需要报警。
同理可推广到“天”的场景

**Comment by wangyapu0714** [comment]
这个不支持，目前是倾向于实时告警，最大限制是30分钟，实时去拉取一天24小时的数据开销很大。可以针对具体场景自己做一些二次开发。
