### ISSUE TITLE
CAT 有提供查询监控数据的 API ？

### ISSUE THREAD

**Issue by ishouwen** [dianping/cat#1584]
公司现在有很多监控 zabbix，cat，容器的监控 等等
现在我们有自己的统一监控平台，查询各个子监控系统的的数据，展示到统一监控平台的页面。
请问 CAT 有提供这种查询监控数据的 API ？

**Comment by ruochen** [comment]
+1

**Comment by wangyapu0714** [comment]
公司内部是有提供大量API供用户拉取数据做二次开发的，开源版本暂时还不支持这块内容。

**Comment by ishouwen** [comment]
> 公司内部是有提供大量API供用户拉取数据做二次开发的，开源版本暂时还不支持这块内容。

开源版本拉取数据的API，有计划支持？大概什么时候会有，期待

**Comment by youyong205** [comment]
开源版本在当前url下加上 &forceDownload=xml，可以看到当前数据页面模型，这个性能稍微差一些

**Comment by youyong205** [comment]
开源版本拉取数据的API，有计划支持？我们内部在做一个大版本迭代，包括整体技术栈替换到springboot等，这个版本时间有点长，暂时不好估计。

**Comment by ChinaLHR** [comment]
mark，希望开源版本能得到更多支持

**Comment by chenyyyang** [comment]
mark
