### ISSUE TITLE
请问各位大神，我们现在想基于cat的数据做一个问题记录表

### ISSUE THREAD

**Issue by RyanBow** [dianping/cat#1585]
基于cat的数据，做一个类似于巡检表的Excel表，请问怎么从cat中获取数据呢

**Comment by ishouwen** [comment]
类似问题
https://github.com/dianping/cat/issues/1584

**Comment by youyong205** [comment]
开源版本在当前url下加上 &forceDownload=xml，可以看到当前数据页面模型，这个性能稍微差一些。

可以看下wiki里面的faq部分，也有说明哦

**Comment by RyanBow** [comment]
> 类似问题
> #1584

嗯嗯，了解，谢谢

**Comment by RyanBow** [comment]
> 开源版本在当前url下加上 &forceDownload=xml，可以看到当前数据页面模型，这个性能稍微差一些。
> 
> 可以看下wiki里面的faq部分，也有说明哦

是的，但是我在problem代码的详细页加上这个参数后只给了我一个空白页面
<?xml version="1.0"?>
<logview> </logview>

**Comment by wangyapu0714** [comment]
可以提供相关url链接吗，以方便排查。

**Comment by RyanBow** [comment]
> 可以提供相关url链接吗，以方便排查。

cat/r/m/webapi-fourS-0a1eb663-431119-11920?domain=webapi-fourS  就是problem的详细页

**Comment by youyong205** [comment]
logview原始是没有api的。
