### ISSUE TITLE
在WebLogic 容器,能正常接收Cat 埋点数据,但是没有心跳信息

### ISSUE THREAD

**Issue by w493549442** [dianping/cat#1586]
在WebLogic 容器,能正常接收Cat 埋点数据,但是没有心跳信息,在心跳报表 也没有,而在 Transaction 中的 System类型只有一个 name 为 EventAggregator 的transaction,显示内容如下:
t10:48:09.657                       System                 EventAggregator
  E10:48:09.657                     Reboot                  172.29.32.1                                    @1;0
T10:48:09.657                       System                 EventAggregator                            0.11ms
想问下一般这个是什么原因?

**Comment by stdrickforce** [comment]
WebLogic 是什么？有官网的链接提供一下吗？

**Comment by wangyapu0714** [comment]
使用的SDK是什么语言？

**Comment by w493549442** [comment]
weblogic是类似 tomcat 的服务容器部署组件,是 oracle 的产品,使用的 1.6 的 JDK.weblogic官网地址:https://www.oracle.com/middleware/technologies/weblogic.html

**Comment by wangyapu0714** [comment]
这个客户端已经兼容，你可以升级到最新的代码试下。

**Comment by w493549442** [comment]
> 这个客户端已经兼容，你可以升级到最新的代码试下。
      使用新的代码后,在 Transaction中 System能看到 Status相关的的 Transaction 信息,点开 LogView 能看到 xml 文件的系统相关信息,但是在 Heartbeat只显示主机 ip,其他都是空白.
      同时查看源码,发现心跳有一分钟发送机制,但是运行后,未发现有发送,只有在Cat 第一次初始化时,有传系统相关信息数据到 Cat 的 Transaction 中.

**Comment by w493549442** [comment]
> 这个客户端已经兼容，你可以升级到最新的代码试下。

使用新的代码后,在 Transaction中 System能看到 Status相关的的 Transaction 信息,点开 LogView 能看到 xml 文件的系统相关信息,但是在 Heartbeat只显示主机 ip,其他都是空白.
同时查看源码,发现心跳有一分钟发送机制,但是运行后,未发现有发送,只有在Cat 第一次初始化时,有传系统相关信息数据到 Cat 的 Transaction 中.

**Comment by youyong205** [comment]
你这个更新最新的war服务端以及客户端，应该早就解决了，不知道你解决了没
