### ISSUE TITLE
heartbeat 异常的评定规则是什么？

### ISSUE THREAD

**Issue by seewoo** [dianping/cat#1593]
在ploblem中long-url long-sql long-service long-cache long-call都有判断问题的基本依据（时间）， 但是在出现的heartbeat异常中点开一个日志，发现基本都是线程，堆栈和GC的信息，因此请问一下heartbeat默认异常出现在这里的判断依据是什么？谢谢

**Comment by wangyapu0714** [comment]
这块设计有点歧义，heartbeat消息放在了problem报表中目前为了方便查看，并不是异常消息。后续产品设计中已经改进了这块。

**Comment by seewoo** [comment]
> 这块设计有点歧义，heartbeat消息放在了problem报表中目前为了方便查看，并不是异常消息。后续产品设计中已经改进了这块。

了解了，谢谢.
