### ISSUE TITLE
dump能配置自动删除吗，否则越来越大？

### ISSUE THREAD

**Issue by IcyLemon** [dianping/cat#1596]
每天都会产生一个较大的dump文件，如下图：
![image](https://user-images.githubusercontent.com/19788374/53463879-396bbe80-3a83-11e9-8f6a-7fc22f3afe18.png)
能否配置自动清除？还是需要手工删除？

**Comment by wangyapu0714** [comment]
可以看下LogviewProcessor逻辑，应该是hdfs模式关闭状态，而且删除路径没有匹配正确。
