### ISSUE TITLE
Cat如何查看全部的logview

### ISSUE THREAD

**Issue by yalunwang** [dianping/cat#1600]
你好，我想问一下cat里如何查看全部的logview而不只是查看报表里统计的日志？

**Comment by wangyapu0714** [comment]
logview的数据都是全量存储的，现在没法支持定位到某个时间段或者某类指标的全部logview（除了遍历数据文件，开销很大）。讨论下你的核心需求？

**Comment by stenio2011** [comment]
cat为什么没有把数据存储至ES里面？这样可以支持检索了。是考虑存储性能问题么？

**Comment by wangyapu0714** [comment]
@stenio2011 可以采集相应特征的消息存入es或者hbase，全量存储到es的话流量是扛不住的。

**Comment by yalunwang** [comment]
@wangyapu0714 感谢回复，我是想把cat定位为分布式调用链了，所以想看看能不能看到每一条日志以及调用链的全部日志。
