### ISSUE TITLE
Cat 2.0版本 告警配置失效问题

### ISSUE THREAD

**Issue by ChinaLHR** [dianping/cat#1604]
![image](https://user-images.githubusercontent.com/19829495/53715351-7de4c900-3e8c-11e9-8a65-65580d5edf25.png)
![image](https://user-images.githubusercontent.com/19829495/53715358-80472300-3e8c-11e9-9209-c38a6d0d6755.png)

配置了项目的信息，包括联系人电话，邮箱，但是Transaction告警的时候传过来的值只有默认告警人的，没有项目组里面配置的邮件/电话。配置如上图，项目名是一致的。

**Comment by ChinaLHR** [comment]
我知道原因了

**Comment by chenyu9390** [comment]
请求这个告警配置是怎么配置，有没有具体的配置文档
