### ISSUE TITLE
chmod 777 /data/ -R 命令错误

### ISSUE THREAD

**Issue by AlphaWang** [dianping/cat#1616]
https://github.com/dianping/cat/wiki/readme_server#%E6%AD%A5%E9%AA%A42-%E7%A8%8B%E5%BA%8F%E5%AF%B9%E4%BA%8Edata%E7%9B%AE%E5%BD%95%E5%85%B7%E4%BD%93%E8%AF%BB%E5%86%99%E6%9D%83%E9%99%90%E9%87%8D%E8%A6%81

步骤2： 程序对于/data/目录具体读写权限（重要）
`chmod 777 /data/ -R`

这条命令执行会提示chmod: -R: No such file or directory
 是否应该是 `chmod -R 777 /data/ ` ？

**Comment by slankka** [comment]
OK，这只是文档错误，有空你可以改为`chmod -R 777 /data/`，提交一个PR
