### ISSUE TITLE
cat-server端消费能力评估

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1617]
请问一下，怎样评估cat-server的消费能力呢？比如一台8核32G的服务器，按每条信息约1K左右，那么这台cat服务器的处理极限是多少呢？想根据消息数量，评估一下大约需要多少台机器，不知怎么评估，望赐教，多谢！

**Comment by youyong205** [comment]
这个确实很难评估，内部评估一般看丢失消息数state里面关键数据。
应用消息也不一样。
