### ISSUE TITLE
分布式调用链logRemoteCallClient方法没有向后兼容

### ISSUE THREAD

**Issue by zhaohaiying** [dianping/cat#1621]
1.4.0版本的logRemoteCallClient方法内部的domain取的是当前项目的app.name
3.0.0版本的logRemoteCallClient方法内部的domain是default
public static void logRemoteCallClient(Context ctx) {
	logRemoteCallClient(ctx, "default");
}
业务项目之前用的是1.4.0版本的cat，分布式调用链都正常显示，升级为3.0.0版本的cat时，由于logRemoteCallClient方法内部的domain是default导致调用链异常，这个有点太坑了吧？？
业务代码必须从Cat.logRemoteCallClient(catContext)改为Cat.logRemoteCallClient(catContext,Cat.getManager().getDomain());才可以正常显示调用链
代码没有向后兼容。。。。

**Comment by youyong205** [comment]
这个是做存储的优化，解决一些文件空洞问题。

**Comment by youyong205** [comment]
API上保证之前不报错，但是要升级下domain，我们写到Faq里面

**Comment by youyong205** [comment]
https://github.com/dianping/cat/wiki/cat_faq
请看下最后一个解释，你这个写法会导致存储的空洞，磁盘空间变大
