### ISSUE TITLE
idea 启动cat

### ISSUE THREAD

**Issue by rongyingjie** [dianping/cat#1623]
我在idea上使用tomcat启动 cat ,提示编译错误，lombak 插件已经安装了，采用命令行打包没有问题。请问有什么解决办法吗？

**Comment by rongyingjie** [comment]
cat-core 提示类找不到 CatClientModule， com.dianping.cat.message.io.DefaultMessageQueue

**Comment by youyong205** [comment]
这个你自己编译环境问题吧。
文档写到，先执行mvn eclipse:eclipse 在导入项目
