### ISSUE TITLE
自己项目下的报警为什么跑到默认项目cat下面去了。

### ISSUE THREAD

**Issue by zyl19880411** [dianping/cat#1624]
自己的app.key，测试报警的时候，在当前项目的app.key下面看不到报警的信息，只能在默认项目cat下面才能看到，这个是怎么回事 怎么串项目了。？
数据路的报警信息，项目是zyl.test,但是只能在默认项目cat的problem里面才能看到

[CAT Event告警] [项目: zyl.test] [监控项: Eventtest-123456-count]<br/>[CAT Event告警: zyl.test Eventtest 123456] : [实际值:200 ] [最大阈值: 10 ][告警时间:2019-03-14 14:34:00]<br/>[时间: 2019-03-14 14:34]

**Comment by youyong205** [comment]
麻烦你好好仔细检查下，不存在这个问题。
