### ISSUE TITLE
关于同一调用链下的事务采样统一问题探讨

### ISSUE THREAD

**Issue by yangfanchuhai** [dianping/cat#1630]
之前在群里提过的，如果相同调用链下的transaction，由于应用设置采样率，经过目前的采样算法采样后，有的应用被采样而导致调用链断掉的问题，如果基于rootMessageId采样，针对同一rootMessageId采样后，同一链下的transaction的采样结果是可以保证相同的，不知道这个思路可以实现这一需求。

**Comment by youyong205** [comment]
cat本质是一个监控产品，链路只是一个附带弱化版本，重点还是监控。
