### ISSUE TITLE
去掉plexus

### ISSUE THREAD

**Issue by wuchaojing** [dianping/cat#1637]
client去掉plexus之后易读性有很高的提升，想请问一下，有没有计划去掉其他模块的plexus依赖，比较容易维护

**Comment by youyong205** [comment]
内部服务端版本已经在做，但是整体周期会很长。

**Comment by slankka** [comment]
@youyong205 请问是指将unidal-framework 2.5.0 升级至高版本(unidal-framework 高版本已经完全去掉plexus)？

**Comment by wangyapu0714** [comment]
@slankka 是整体技术栈向spring迁移。
