### ISSUE TITLE
cat默认登陆用户名密码（cat-alpha-2.0.0版本）

### ISSUE THREAD

**Issue by stoneLee81** [dianping/cat#1641]
![Snip20190322_53](https://user-images.githubusercontent.com/18001708/54815672-7b2c0580-4ccd-11e9-8f5c-43aeab1020a2.png)

cat的登陆用户名，密码忘记了，怎么都不能登陆
catadmin catadmin试了也不行，cat-alpha-2.0.0 版本

**Comment by youyong205** [comment]
admin admin ，或者在源码里面搜索下 SessionManager.java 看下源码吧
