### ISSUE TITLE
docker 部署  构建项目报错

### ISSUE THREAD

**Issue by fushiqinghuan111** [dianping/cat#1642]
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [ 46.765 s]
[INFO] cat-client ......................................... SUCCESS [02:37 min]
[INFO] cat-core ........................................... SUCCESS [  9.520 s]
[INFO] cat-hadoop ......................................... SUCCESS [01:10 min]
[INFO] cat-consumer ....................................... SUCCESS [ 11.629 s]
[INFO] cat-alarm .......................................... SUCCESS [  3.781 s]
[INFO] cat-home ........................................... FAILURE [ 21.959 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:21 min
[INFO] Finished at: 2019-03-22T12:47:53Z
[INFO] Final Memory: 40M/352M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cat-home: Could not resolve dependencies for project com.dianping.cat:cat-home:war:3.0.0: Could not transfer artifact org.unidal.webres:WebResRuntime:jar:1.2.1 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/webres/WebResRuntime/1.2.1/WebResRuntime-1.2.1.jar from unidal.releases failed: Premature end of Content-Length delimited message body (expected: 457136; received: 72230 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cat-home
ERROR: Service 'cat' failed to build: The command '/bin/sh -c set -ex && mvn clean install -DskipTests' returned a non-zero code: 1
[root@Bitbucket docker]#

**Comment by wangyapu** [comment]
这个是仓库链接网络有问题

**Comment by chshawkn** [comment]
使用我做的镜像吧 https://cloud.docker.com/u/cloudready/repository/docker/cloudready/cat

docker-compose 用这个 https://github.com/cloud-ready/docker-cat

war包已经构建好，pull下来直接用

**Comment by Bird56** [comment]
> 使用我做的镜像吧 https://cloud.docker.com/u/cloudready/repository/docker/cloudready/cat
> 
> docker-compose 用这个 https://github.com/cloud-ready/docker-cat
> 
> war包已经构建好，pull下来直接用

操作步骤 能分享下吗
