### ISSUE TITLE
docker方式部署客户端

### ISSUE THREAD

**Issue by stoneLee81** [dianping/cat#1643]
client.xml在容器路径 /data/appdatas/cat,启动服务，cat启动异常；如果我将client.xml，挂载到容器外，启动一切正常；是因为cat不支持client.xml在容器里面么？
cat:cat-alpha-2.0.0版本

**Comment by wangyapu0714** [comment]
我们提供的dockerfile demo也是挂在到容器内部的，应该不是这个关系，可以提供你的dockerfile一起看下。
