### ISSUE TITLE
cat 3.0版本，性能差的问题

### ISSUE THREAD

**Issue by ishouwen** [dianping/cat#1645]
LocalTransactionService.getReportFromLocalDisk	 	8426ms      
ReportBucket.findById	 	740ms
3.0版本感觉report数据存储和查询这一快没设计好， 先从Disk读这个时间段所有数据在根据domain找数据。对于页面展示而言不是按需索取，导致页面太卡。 
mysql中的数据也是一样，所有数据聚合在 _report_content (longblob) 字段，不能按需索取
返回这段时间的数据，应用层解析mergeAllMachines， 耗时执行太久。
优化建议：存储分散，按需索取

**Comment by wangyapu0714** [comment]
感谢你的建议，这些点在新的设计里都有所考虑。
1. 关于查询设计cat2.0和3.0应该是没有太大变化的，getReportFromLocalDisk这块逻辑是要改掉的。
2. 数据不能按需索取是设计上的一个弊端，后面会通过引入hbase或者es存储对架构做升级调整来解决类似问题。

**Comment by zcc1234567** [comment]
> 感谢你的建议，这些点在新的设计里都有所考虑。
> 
> 1. 关于查询设计cat2.0和3.0应该是没有太大变化的，getReportFromLocalDisk这块逻辑是要改掉的。
> 2. 数据不能按需索取是设计上的一个弊端，后面会通过引入hbase或者es存储对架构做升级调整来解决类似问题。

引入hbase或es存储这块预计什么时候能出来?

**Comment by wangyapu** [comment]
@zcc1234567 还有挺久一段时间，后面会把内部好的实践慢慢放出来。
