### ISSUE TITLE
报警配置过大的问题

### ISSUE THREAD

**Issue by bug1024** [dianping/cat#1646]
目前cat的报警区分Transaction Event Problem等，每个类型的报警配置相应config表的一条记录。美团内部接入cat的项目有几千个，如果每个项目配置报警规则多了，那么就可能达到上万条，比较好奇美团内部是如何处理的，也是使用一条记录存储某一类报警吗？还是说每个项目单独有一套报警配置？

**Comment by youyong205** [comment]
这个内部已经是下个版本了，预计会在下个版本opensource出来
