### ISSUE TITLE
Cat.logMetricForCount(String name, Map<String, String> tags)请教

### ISSUE THREAD

**Issue by tengzhexiao** [dianping/cat#1647]
请问这个tags怎么用？有具体例子吗，试了半天没试出来，无数据上报。
业务标签配置：
<?xml version="1.0" encoding="utf-8"?>
<business-tag-config>
   <tag id="Android">
      <business-item domain="hn-webhook2" item-id="qps"/>
   </tag>
   <tag id="IOS">
      <business-item domain="hn-webhook2" item-id="qps"/>
   </tag>
</business-tag-config>

代码：
Map tags = new HashMap<String,String>();
        tags.put("Android","25");
        tags.put("IOS","23");
        Cat.logMetricForCount("qps",tags);

这么用哪里有误？
Business报表，曲线可以有多维吗？我看例子上都是单曲线的，如果要多曲线该如何实现？

**Comment by wangyapu0714** [comment]
多维度的业务指标功能服务端还没开放出来，目前tags传入是不起作用的。

**Comment by tengzhexiao** [comment]
好的，谢谢!
