### ISSUE TITLE
机器分组配置返回HTTP:400错误

### ISSUE THREAD

**Issue by yanhuichao** [dianping/cat#1648]
版本:2.0 管理后台配置机器分组时报HTTP STATUS：400错误。
原因：
提交表单请求：cat/s/config?op=domainGroupConfigSubmit&domain=core&content={"id":"core","groups":{}}
请求中：content数据未encode。

请确认。

**Comment by wangyapu** [comment]
建议升级下3.0，2.0版本已经不再维护，这面不好复现。
