### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by benyVip** [dianping/cat#1649]
Could not resolve dependencies for project com.dianping.cat:cat-client:jar:3.0.0: Failure to find org.unidal.framework:test-framework:jar:2.4.0

**Comment by benyVip** [comment]
主干的代码

**Comment by slankka** [comment]
要添加unidal的仓库，但注意有时候unidal仓库会不可用。
```
http://unidal.org/nexus/content/repositories/releases/
```

**Comment by kid3028** [comment]
> 要添加unidal的仓库，但注意有时候unidal仓库会不可用。
> 
> ```
> http://unidal.org/nexus/content/repositories/releases/
> ```

添加了之后还是没有2.4.0的jar，mvn-repo中也只有2.5.0和2.3.0

**Comment by kid3028** [comment]
> > 要添加unidal的仓库，但注意有时候unidal仓库会不可用。
> > ```
> > http://unidal.org/nexus/content/repositories/releases/
> > ```
> 
> 添加了之后还是没有2.4.0的jar，mvn-repo中也只有2.5.0和2.3.0

已解决。
