### ISSUE TITLE
编译失败。codegen-2.5.8.jar或者WebResRuntime-1.2.1.jar老是下载不下来。

### ISSUE THREAD

**Issue by vxzhong** [dianping/cat#1650]
错误信息如下：
[ERROR] Failed to execute goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model (generate data model) on project cat-client: Execution generate data model of goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model failed: Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.5.8 or one of its dependencies could not be resolved: Could not transfer artifact org.unidal.maven.plugins:codegen:jar:2.5.8 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/maven/plugins/codegen/2.5.8/codegen-2.5.8.jar from unidal.releases failed: Premature end of Content-Length delimited message body (expected: 410213; received: 70778 -> [Help 1]
或者
[ERROR] Failed to execute goal on project cat-home: Could not resolve dependencies for project com.dianping.cat:cat-home:war:3.0.0: Could not transfer artifact org.unidal.webres:WebResRuntime:jar:1.2.1 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): GET request of: org/unidal/webres/WebResRuntime/1.2.1/WebResRuntime-1.2.1.jar from unidal.releases failed: Premature end of Content-Length delimited message body (expected: 457136; received: 70778 -> [Help 1]

用wget直接下载，会出现重试的情况：

wget http://unidal.org/nexus/content/repositories/releases/org/unidal/webres/WebResRuntime/1.2.1/WebResRuntime-1.2.1.jar
--2019-03-28 16:35:00--  http://unidal.org/nexus/content/repositories/releases/org/unidal/webres/WebResRuntime/1.2.1/WebResRuntime-1.2.1.jar
Resolving unidal.org (unidal.org)... 203.76.218.13
Connecting to unidal.org (unidal.org)|203.76.218.13|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 457136 (446K) [application/java-archive]
Saving to: ‘WebResRuntime-1.2.1.jar.2’

WebResRuntime-1.2.1.jar.2                      15%[==============>                                                                                  ]  70.54K  --.-KB/s   in 0.04s

2019-03-28 16:35:00 (1.71 MB/s) - Connection closed at byte 72230. Retrying.

--2019-03-28 16:35:01--  (try: 2)  http://unidal.org/nexus/content/repositories/releases/org/unidal/webres/WebResRuntime/1.2.1/WebResRuntime-1.2.1.jar
Connecting to unidal.org (unidal.org)|203.76.218.13|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 457136 (446K), 384906 (376K) remaining [application/java-archive]
Saving to: ‘WebResRuntime-1.2.1.jar.2’

WebResRuntime-1.2.1.jar.2                     100%[+++++++++++++++=================================================================================>] 446.42K  --.-KB/s   in 0.1s

2019-03-28 16:35:02 (2.54 MB/s) - ‘WebResRuntime-1.2.1.jar.2’ saved [457136/457136]

**Comment by vxzhong** [comment]
http://unidal.org/nexus/content/repositories/releases 已经无法访问了。

![image](https://user-images.githubusercontent.com/86217/55207959-4fea6e80-5217-11e9-91c2-4eaf945c76e7.png)

**Comment by wangyapu** [comment]
仓库已经修复，再试下

**Comment by vxzhong** [comment]
好了。谢谢。
