### ISSUE TITLE
关于cat服务端启动报错，客户端接入springboot demo 收集不到数据

### ISSUE THREAD

**Issue by zhangshuang2962** [dianping/cat#1651]
我服务端搭建后cat自身监控OK，但是服务端启动的时候仍然会有错误
[03-28 17:44:17.196] [ERROR] [ChannelManager] Error when try connecting to /192.168.3.93:2280
[03-28 17:44:17.197] [INFO] [ChannelManager] Error when init CAT server /192.168.3.93:2280;
[03-28 17:44:17.198] [ERROR] [ChannelManager] error when init cat module due to error config xml in client.xml
客户端我打的jar包是一个springboot的 demo  启动后也是报错
Logger file /cat/appdatas/cat/cat_20190328.log
[03-28 16:27:30.030] [WARN] [cat] CAT client was disabled due to no CAT servers configured!
[03-28 16:27:30.030] [INFO] [cat] Cat is lazy initialized!
 目前所有的配置文件我都经过检查，没有发现配置上有什么问题
我的部署环境是linux 暂时单台没有集群，用的cat3.0 其他配置jdk8 maven3.6  tomcat8
日志
![图片](https://user-images.githubusercontent.com/12509614/55202635-2a536a00-5203-11e9-9a46-3d967f01d6c9.png)

客户端启动
![图片](https://user-images.githubusercontent.com/12509614/55202646-3ccda380-5203-11e9-898e-2bb3eead9422.png)

服务端启动日志
![图片](https://user-images.githubusercontent.com/12509614/55202666-4ce58300-5203-11e9-84c1-5a09205cbcb4.png)

**Comment by zhangshuang2962** [comment]
this is client.xml
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="192.168.3.93" port="2280" http-port="8080"/>
    </servers>
</config>

this is server.xml
<?xml version="1.0" encoding="utf-8"?>
<config local-mode="true" hdfs-machine="false" job-machine="true" alert-machine="true">
	<storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
	</storage>
	<console default-domain="Cat" show-cat-domain="true">
		<remote-servers>192.168.3.93:8080</remote-servers>
	</console>
</config>

this is datasources.xml
<?xml version="1.0" encoding="utf-8"?>
   <data-sources>
       <data-source id="cat">
           <maximum-pool-size>3</maximum-pool-size>
           <connection-timeout>1s</connection-timeout>
           <idle-timeout>10m</idle-timeout>
           <statement-cache-size>1000</statement-cache-size>
           <properties>
               <driver>com.mysql.jdbc.Driver</driver>
              <url><![CDATA[jdbc:mysql://********:3306/cat]]></url>  
              <user>root</user>  
              <password>******</password>  
              <connectionProperties><![CDATA[useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000]]></connectionProperties>
          </properties>
      </data-source>
      <data-source id="app">
                  <maximum-pool-size>3</maximum-pool-size>
                  <connection-timeout>1s</connection-timeout>
                  <idle-timeout>10m</idle-timeout>
                  <statement-cache-size>1000</statement-cache-size>
                  <properties>
                          <driver>com.mysql.jdbc.Driver</driver>
                          <url><![CDATA[jdbc:mysql://*********:3306/cat]]></url>  
                          <user>root</user>
                          <password>******</password>
                          <connectionProperties><![CDATA[useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&socketTimeout=120000]]></connectionProperties>
                      </properties>
             </data-source>
  </data-sources>     
下面是配置文件的路径
![图片](https://user-images.githubusercontent.com/12509614/55203845-e31ba800-5207-11e9-9d0e-ba917a6fb8a9.png)
![图片](https://user-images.githubusercontent.com/12509614/55203850-e9aa1f80-5207-11e9-9140-55ec13933f7d.png)
我的client  server  和数据源配置不在并不是都在/data/appdatas/cat 路径下  ，因为client.xml 在/data/appdatas/cat路径下的话 服务端启动报错找不到client ，并且服务端日志报错的查找的文件是catclient.xml，而且加载catclient.xml 的路径是/data/appdatas ， 所以目前我的配置文件路径是图片中的路径  ，我用的cat3.0 jar   希望可以尽快得到同学的回复

**Comment by zhangshuang2962** [comment]
补充client.xml
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="192.168.3.93" port="2280" http-port="8080"/>
    </servers>
</config>


server.xml
<?xml version="1.0" encoding="utf-8"?>
<config local-mode="true" hdfs-machine="false" job-machine="true" alert-machine="true">
	<storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
	</storage>
	<console default-domain="Cat" show-cat-domain="true">
		<remote-servers>192.168.3.93:8080</remote-servers>
	</console>
</config>

**Comment by slankka** [comment]
/lib/java模块的Cat-client 会根据CAT_HOME + client.xml寻找文件。但是CAT_HOME 一定要以`/` 结尾。

如果我没有猜错的话，你一定是用JVM参数指定了 CAT_HOME=/data/appdatas/cat。注意要改成
```
CAT_HOME=/data/appdatas/cat/
```
另外：
```
[03-28 16:27:30.030] [WARN] [cat] CAT client was disabled due to no CAT servers configured!
```
说明CAT找不到 server.xml。

cat-client模块的没有这个问题，目前/lib/java模块的和cat-client模块没有统一。

**Comment by youyong205** [comment]
[03-28 17:44:17.198] [ERROR] [ChannelManager] error when init cat module due to error config xml in client.xml

这个写的比较清楚，error config.xml  就是xml格式非法

**Comment by youyong205** [comment]
你可以搜索下源码，due to error config
