### ISSUE TITLE
请问集群模式可以使用磁盘模式存储吗？如果可以，多台服务器的数据一致性是怎么保证的？

### ISSUE THREAD

**Issue by ChinaLHR** [dianping/cat#1652]
如题

**Comment by wangyapu** [comment]
集群每台机器处理的流量是不一样，没有数据一致性问题。磁盘具体存储什么内容？磁盘当然也可以设计存储，不过最终展示都需要进行数据汇总。

**Comment by ChinaLHR** [comment]
Cat路由是基于Domain，部分Domain监控数据量大导致集群的Cat入网流量很不平均，请问有什么较好优化方法吗？ @wangyapu

**Comment by ChinaLHR** [comment]
目前较高入网流量的Cat是其他的3倍多

**Comment by youyong205** [comment]
这个目前两方面考虑，选择最大的domain，做采样处理。
第二个可以修改下router路由接口的逻辑，部分大的domain返回多中路由顺序。这部分需要定制开发下。

当客户端体量整体较少时候，容易产生一些不均衡
