### ISSUE TITLE
maven无法导入

### ISSUE THREAD

**Issue by declife** [dianping/cat#1656]
<dependency>
			<groupId>com.dianping.cat</groupId>
			<artifactId>cat-client</artifactId>
			<version>2.0.0</version>
		</dependency>

用的阿里云的源，不管是2.0.0还是3.0.0都是只能得到.lastUpdate文件

**Comment by wangyapu** [comment]
需要添加下私服地址
<repositories>
  <repository>
     <id>central</id>
     <name>Maven2 Central Repository</name>
     <layout>default</layout>
     <url>http://repo1.maven.org/maven2</url>
  </repository>
  <repository>
     <id>unidal.releases</id>
     <url>http://unidal.org/nexus/content/repositories/releases/</url>
  </repository>
</repositories>

**Comment by declife** [comment]
> 需要添加下私服地址
> 
> ```
> <repositories>
>   <repository>
>      <id>central</id>
>      <name>Maven2 Central Repository</name>
>      <layout>default</layout>
>      <url>http://repo1.maven.org/maven2</url>
>   </repository>
>   <repository>
>      <id>unidal.releases</id>
>      <url>http://unidal.org/nexus/content/repositories/releases/</url>
>   </repository>
> </repositories>
> ```

这个私服地址也是添加在里面了的，maven一样无法导入；之前是可以导入的，昨天怎都导入不成功，最后用了本地备份的库

**Comment by declife** [comment]
<repositories>
  <repository>
     <id>central</id>
     <name>Maven2 Central Repository</name>
     <layout>default</layout>
     <url>http://repo1.maven.org/maven2</url>
  </repository>
  <repository>
     <id>unidal.releases</id>
     <url>http://unidal.org/nexus/content/repositories/releases/</url>
  </repository>
</repositories>

这个私服地址可以，之前使用的私服地址失效了

**Comment by declife** [comment]
<repository>
	         <id>central</id>
	         <name>Maven2 Central Repository</name>
	         <layout>default</layout>
	         <url>http://repo1.maven.org/maven2</url>
	      </repository>
	      <repository>
	         <id>unidal.releases</id>
             <url>http://unidal.org/nexus/content/repositories/releases/</url>
	      </repository>
之前的私服挂了，这个私服可以

**Comment by wonderomg** [comment]
私服也用不了了，只能将client导入本地仓库了，
```shell
mvn install:install-file -Dfile=path/to/cat-client-3.0.0.jar -DgroupId=com.dianping.cat -DartifactId=cat-client -Dversion=3.0.0 -Dpackaging=jar
```
