### ISSUE TITLE
logView数据展示不正常

### ISSUE THREAD

**Issue by bigfanofcpp** [dianping/cat#1658]
![image](https://user-images.githubusercontent.com/2186555/55461863-173c0200-5628-11e9-80ac-4fbc2ea5b557.png)

请问这是怎么回事。。。

**Comment by bigfanofcpp** [comment]
![image](https://user-images.githubusercontent.com/2186555/55462310-063fc080-5629-11e9-8823-2ecc6c8a7cbd.png)

我在写logEvent的时候，最后的那个参数，都是k=v&k=v这样写的啊

**Comment by wangyapu** [comment]
这是新版消息聚合上报的格式，可以理解为1s内相同类型埋点聚合之后上报，减少消息量。有兴趣可以看下代码。
