### ISSUE TITLE
cat-client不支持JDK8以下（与wiki描述自相矛盾）

### ISSUE THREAD

**Issue by a45578725** [dianping/cat#1660]
wiki中描述，cat-client接入指南：
Cat Client for Java
Cat Java 客户端支持 JDK 1.6 及以上版本

但是下下来的cat-client是通过jdk8编译，无法通过jdk8以下使用，且目前maven 仓库中只有3.0.0可用，无法做到向下兼容，烦请更新版本支持jdk8以下

**Comment by 15215138270** [comment]
我就jdk7 可以用~~~你那里可能有毒~~

**Comment by a45578725** [comment]
> 
> 
> 我就jdk7 可以用~~~你那里可能有毒~~

你项目里有引用cat-client-3.0.0这个包，从maven仓库宕下来的cat-client-3.0.0.jar包是通过jdk8编译的，如果你也是从maven仓库宕下来的，用jdk7不太可能能跑起来
![图片](https://user-images.githubusercontent.com/1683773/55926539-51b72780-5c44-11e9-880c-97740056b597.png)

**Comment by wangyapu** [comment]
jar包是我用1.8编译的，可以用源码自行编译下。
