### ISSUE TITLE
nodejs 客户端 在node10下 编译安装出错

### ISSUE THREAD

**Issue by 15215138270** [dianping/cat#1661]
核心 错误 是 node-gyp rebuild    Command failed.
错误行 为
ld: library not found for -lcatclient

错误信息 如下 
yarn add v1.13.0
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@dp-cat/client" that matches "3.0.0"
? Please choose a version of "@dp-cat/client" from this list: 3.1.2
[2/4] 🚚  Fetching packages...
warning Pattern ["co@latest"] is trying to unpack in the same destination "/Users/dongbin/Library/Caches/Yarn/v4/npm-co-4.6.0-6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184/node_modules/co" as pattern ["co@^4.6.0","co@^4.6.0"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > @nestjs/typeorm@6.0.0" has incorrect peer dependency "reflect-metadata@0.1.12".
[4/4] 🔨  Building fresh packages...
[-/4] ⠁ waiting...
[4/4] ⠁ nodemon
[3/4] ⠁ @dp-cat/client
error /Users/dongbin/work/app-board-socket/node_modules/@dp-cat/client: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/dongbin/work/app-board-socket/node_modules/@dp-cat/client
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dongbin/work/app-board-socket/node_modules/@dp-cat/client/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dongbin/.node-gyp/10.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/dongbin/.node-gyp/10.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/dongbin/.node-gyp/10.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/dongbin/work/app-board-socket/node_modules/@dp-cat/client',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/nodecat/src/nodecat.o
../src/nodecat.cc:21:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
        String::Utf8Value str(args[0]->ToString());
                          ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:42:27: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
        String::Utf8Value messageType((node->Get(String::NewFromUtf8(isolate, "messageType")))->ToString());
                          ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:44:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value type((node->Get(String::NewFromUtf8(isolate, "type")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:45:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value name((node->Get(String::NewFromUtf8(isolate, "name")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:46:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value status((node->Get(String::NewFromUtf8(isolate, "status")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:47:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value data((node->Get(String::NewFromUtf8(isolate, "data")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:48:87: warning: 'NumberValue' is deprecated [-Wdeprecated-declarations]
            double begin = node->Get(String::NewFromUtf8(isolate, "beginTimestamp"))->NumberValue();
                                                                                      ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2475:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:49:83: warning: 'NumberValue' is deprecated [-Wdeprecated-declarations]
            double end = node->Get(String::NewFromUtf8(isolate, "endTimestamp"))->NumberValue();
                                                                                  ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2475:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:66:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value type((node->Get(String::NewFromUtf8(isolate, "type")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:67:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value name((node->Get(String::NewFromUtf8(isolate, "name")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:68:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value status((node->Get(String::NewFromUtf8(isolate, "status")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:69:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value data((node->Get(String::NewFromUtf8(isolate, "data")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:70:87: warning: 'NumberValue' is deprecated [-Wdeprecated-declarations]
            double begin((node->Get(String::NewFromUtf8(isolate, "beginTimestamp")))->NumberValue());
                                                                                      ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2475:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:78:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value type((node->Get(String::NewFromUtf8(isolate, "type")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:79:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value name((node->Get(String::NewFromUtf8(isolate, "name")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:80:31: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
            String::Utf8Value data((node->Get(String::NewFromUtf8(isolate, "data")))->ToString());
                              ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8.h:2891:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/dongbin/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/nodecat.cc:60:37: warning: comparison of integers of different signs: 'u_int32_t' (aka 'unsigned int') and 'int' [-Wsign-compare]
            for (u_int32_t i = 0; i < count; i++) {
                                  ~ ^ ~~~~~
17 warnings generated.
  SOLINK_MODULE(target) Release/nodecat.node
ld: library not found for -lcatclient
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/nodecat.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dongbin/work/app-board-socket/node_modules/@dp-cat/client
gyp ERR! node -v v10.15.0

**Comment by Fnxxxxo** [comment]
@15215138270 你怎么解决的？node降级么？
