### ISSUE TITLE
服务间调用时，父MessageTree与两个子MessageTree拼接问题

### ISSUE THREAD

**Issue by codeamateur** [dianping/cat#1663]
场景是：服务A调用服务B,A服务有熔断策略，A请求发送到B，在B服务未返回时A服务熔断，我在URL有链路埋点，熔断触发那块也有埋点，两个MessageTree有相同的_catRootMessageId，_catParentMessageId，_catChildMessageId。在cat服务端的logview上能随机看到两个子MessageTree信息中的一个，我想在logview上看到服务间调用的真实情况，就是只显示熔断那块的埋点信息，改如何处理；如果不好处理，那两者都展示能否可以。
不知是否描述清楚。
显示A调B链路
![A调B](https://user-images.githubusercontent.com/11286897/56077455-00a75f00-5e0f-11e9-80ac-7ab9f52d3c21.png)
显示A熔断
![A熔断](https://user-images.githubusercontent.com/11286897/56077457-0604a980-5e0f-11e9-8797-367e3a4ce826.png)
以上两个截图会随机显示。

**Comment by youyong205** [comment]
cat本质上一个实时监控系统，主要体现在监控报表Transaction、event、problem、heartbeat等，cat系统定制的监控模型以及定制的实时分析报表也是cat系统核心优势。
logview是cat原始的log采集方式，cat的logview使用的技术是threadlocal，将一个thread里面的打点聚合上报，有一点弱化版本的链路功能，但是cat并不是一个标准的全链路系统，全链路系统参考dapper的论文，业内比较知名的鹰眼，zipkin等，其实经常拿cat和这类系统进行比较其实是不合适的。cat的logview在异步线程等等一些场景下，其实不合适，cat本身模型并不适合这个。在美团点评内部，有mtrace专门做全链路分析。

如果你要做链路串联，你可以参考下dubbo客户端埋点的方式串联。实现上稍微麻烦一些。
