### ISSUE TITLE
cat-home 会调用所有的消费机聚合数据吗？

### ISSUE THREAD

**Issue by jacky1193610322** [dianping/cat#1668]
因为看cat未深，想知道cat-home 一台机器会调用所有消费机聚合数据吗，但是大多数机器上是没有查询的domain

**Comment by wangyapu** [comment]
根据domain的路由去相应机器上查询，然后聚合

**Comment by jacky1193610322** [comment]
这边可以帮忙指示一下在哪查询机器的路由，然后查询对应的机器吗，我看代码是直接取的配置中的remote-servers 去查询的，谢谢了，目前这边没有看见

**Comment by mouseDH** [comment]
会的，参考com.dianping.cat.report.service.BaseCompositeModelService#invoke，com.dianping.cat.report.service.ModelService的一个实现（这个接口多个实现）不过这块应该有机制判断采用那种调用方式。
