### ISSUE TITLE
CatAopService返回值问题

### ISSUE THREAD

**Issue by KnightOfWind** [dianping/cat#1669]
当CatAnnotation注解标注在一个返回值为基本类型方法上时，会抛出异常：org.springframework.aop.AopInvocationException: Null return value from advice does not match primitive return type；当CatAnnotation被标注在一个返回类类型的方法时，方法调用方会接受到null

**Comment by youyong205** [comment]
能表达更加准确一些吗，或者自己写一个AOP？
