### ISSUE TITLE
docker部署报错

### ISSUE THREAD

**Issue by xiguizi** [dianping/cat#1671]
停止容器，重新启动报如下错误
Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"//cat/docker/client.xml\\\" to rootfs \\\"/var/lib/docker/overlay2/caf8dc5574cd13c3d3e5dbe200c82352d264d41c38969ab2bc258393329d9d53/merged\\\" at \\\"/var/lib/docker/overlay2/caf8dc5574cd13c3d3e5dbe200c82352d264d41c38969ab2bc258393329d9d53/merged/data/appdatas/cat/client.xml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: d146c214dd11

**Comment by chshawkn** [comment]
使用我做的镜像吧 https://cloud.docker.com/u/cloudready/repository/docker/cloudready/cat

docker-compose 用这个 https://github.com/cloud-ready/docker-cat
