### ISSUE TITLE
这个others是怎么来的？

### ISSUE THREAD

**Issue by luffyace** [dianping/cat#1674]
![image](https://user-images.githubusercontent.com/13696180/56494833-31317c00-6526-11e9-877c-0b1ad3cc0462.png)
   newTransaction 为什么会出现一个others?

**Comment by youyong205** [comment]
transaction Name最多200个，超过200个会自动归类到others

**Comment by luffyace** [comment]
> transaction Name最多200个，超过200个会自动归类到others

这个可以修改么？会引起什么问题？哪里修改？

**Comment by LouisGuo** [comment]
> > transaction Name最多200个，超过200个会自动归类到others
> 
> 这个可以修改么？会引起什么问题？哪里修改？

数据库cat.config表中的name等于atomic-message-config的项，content内容增加max-api-count-threshold,max-name-threshold,max-business-item-count三项配置即可

<atomic-message-config>
	<domain id="default">
		<start-types>Cache.;Squirrel.</start-types>
		<match-types>SQL</match-types>
		<max-api-count-threshold>1000</max-api-count-threshold>
		<max-name-threshold>2000</max-name-threshold>
		<max-business-item-count>2000</max-business-item-count>
	</domain>
	<domain id="cat">
		<start-types>Cache.;Squirrel.</start-types>
		<match-types>SQL</match-types>
	</domain>
</atomic-message-config>
