### ISSUE TITLE
当大量报错的时候是否考虑合并相同类型的错误，只上报一些拥有全部信息的，其他汇聚成错误数量上报

### ISSUE THREAD

**Issue by jacky1193610322** [dianping/cat#1675]
因为如果大量上报 这么多信息也没有办法看，比如dubbo或者cache这种流量很高的错误，那么短时间内上报几万，其实可以保留前面几个完整的错误，其他合并成数量上报

**Comment by youyong205** [comment]
新版本客户端就是这样的吧，每分钟保留最开始的60个。

**Comment by jacky1193610322** [comment]
ok，谢谢

**Comment by jacky1193610322** [comment]
但是我看代码合并后的异常走的正常的event聚合上报，但是这样的话，这个错误的个数就不能统计到problem上，因为正常上报的event的status是sucess，不满足problem handler的判断条件
