### ISSUE TITLE
docker-compose部署服务端报错

### ISSUE THREAD

**Issue by vince002** [dianping/cat#1676]
Step 27/32 : RUN set -ex && mvn clean install -DskipTests
 ---> Running in bbd4f43a5c9b
+ mvn clean install -DskipTests
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.078 s
[INFO] Finished at: 2019-04-23T14:00:15Z
[INFO] Final Memory: 7M/301M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root/workspace/cat). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
ERROR: Service 'cat' failed to build: The command '/bin/sh -c set -ex && mvn clean install -DskipTests' returned a non-zero code: 1

**Comment by chshawkn** [comment]
使用我做的镜像吧 https://cloud.docker.com/u/cloudready/repository/docker/cloudready/cat

docker-compose 用这个 https://github.com/cloud-ready/docker-cat
