### ISSUE TITLE
cat-client-3.0.0.jar的源码包能推送到maven远程仓库吗？

### ISSUE THREAD

**Issue by nisiyong** [dianping/cat#1678]
我发现cat-client-3.0.0.jar没有源码包，其他到模块有。请问这个是不是可以补一下？

![image](https://user-images.githubusercontent.com/8198862/56638054-b9875c80-669f-11e9-9b08-0e570d619f55.png)

**Comment by youyong205** [comment]
源码就是在github源码有的吧。

**Comment by nisiyong** [comment]
**2019-03-06**  cat 3.0.0的版本正式发布
**2018-11-14**  cat-client-3.0.0.jar却早已经发布到unidal远程仓库

被这个问题坑了！因为我对unidal仓库做了代理，导致获取的jar不是真正的版本。
除了远程仓库没有源码外，还发现`Heartbeat报表出不来`问题 #1505

## 解决方法
先切换到tag v3.0.0
```shell
git checkout v3.0.0
```
1. 使用lib/java/jar/cat-client-3.0.0.jar，自己upload到私服（还是没有源码）
2. 或者修改lib/java/pom.xml，添加`<distributionManagement>`，配置自己的私服地址，执行`mvn clean deploy -DskipTests`（推荐）

## 相关截图

![image](https://user-images.githubusercontent.com/8198862/57499548-a10b7900-7312-11e9-97db-5654fa0fe984.png)
![image](https://user-images.githubusercontent.com/8198862/57499478-70c3da80-7312-11e9-8032-a05e3b4af630.png)
![image](https://user-images.githubusercontent.com/8198862/57499525-8afdb880-7312-11e9-9fa4-bd8fea145413.png)
