### ISSUE TITLE
如何优化cat数据库存储，每天好几G的增长，有自清理功能么？最小部署数据库磁盘大小为多少合适

### ISSUE THREAD

**Issue by jizhongliang** [dianping/cat#1681]

**Comment by jizhongliang** [comment]
有没有同学遇到过这样的问题

**Comment by Liubey** [comment]
我估计官方CAT应该是有分库分表的，开源版本木有这个特性，你可以定期归档吧

**Comment by jizhongliang** [comment]
应该是实际应用中都会去改造的，使用的都是阉割版的，把weekly_report_content,monthly_report_content都不入库，这样就会少很多容量，就是改造有点糊。。

**Comment by youyong205** [comment]
监控数据可以按照时间来切割。
我们内部是多个库，轮流来写。
