### ISSUE TITLE
TransactionAnalyzer和TransactionStatisticsComputer里面的range、sum、sum2疑问

### ISSUE THREAD

**Issue by Liubey** [dianping/cat#1686]
1.sum2这个字段是什么意思，还有个range2，没太看懂
2.TransactionAnalyzer.processNameGraph里面计算dk那段逻辑应该怎么理解呢
3.还有就是TransactionAnalyzer.computeDuration 这个
最后还有一个问题就是TransactionStatisticsComputer里面的name、range、type都会算的90、95线最终都会存到数据库里是吗？理论上是可以随时拿出来展示的对吗？
最后，非常佩服CAT的代码生成里面的各种visit模式，五体投地，对设计出来的人~
最最后，感谢解答，谢谢

**Comment by Liubey** [comment]
update：看代码，好像是并没有在存储的时候计算90、95线，而是在取出来的时候再算，看描述，这就是90，95稍微有点失真的原因所在对吗

**Comment by Liubey** [comment]
double sum = duration * duration; 这个计算逻辑没想明白

**Comment by youyong205** [comment]
sum2 以及 range2 是一些建模的历史遗留问题，主要这个模型一旦确定不能删除，有一些历史包袱。

dk值的计算是按照2的幂次方叠加的，这样能有效控制区间。

并不是每次来一个数据都来算，而是展示和存储会算一次。

TP90 95 都可以来展示，下个版本就会有。
