### ISSUE TITLE
docker 部署Step 20/32报错

### ISSUE THREAD

**Issue by zhangyanglei** [dianping/cat#1692]
Step 20/32
mv: cannot move `apache-maven-3.5.2' to a subdirectory of itself, `/usr/local/apache-maven'

**Comment by wangyapu** [comment]
检查下执行这步目录是非空吗？把docker环境清理下，重新试下看看。

**Comment by zhangyanglei** [comment]
这个目录在我开发机上不存在 倒是有个/usr/local/apache-maven-3.6.0 是否有影响

**Comment by wangyapu** [comment]
没有影响，我目前无法复现你的问题，后面我们直接提供一个打包好的镜像吧。

**Comment by zhangyanglei** [comment]
嗯 好的 谢谢 那我关啦
