### ISSUE TITLE
docker动态获取客户端配置问题

### ISSUE THREAD

**Issue by nisiyong** [dianping/cat#1698]
我想请问下，我的应用集成了CAT，并想在容器内运行。我需要在制作docker image时将client.xml添加到镜像里。

但是cat服务端分了测试和生产，并且域名不同，镜像只构建一次。

请问有什么方法可以动态加载client.xml配置吗？看了源码的loadRemoteClientConfig()好像没什么用，这个需要自己起服务来响应吗？

```
xml = ApplicationEnvironment.loadRemoteClientConfig();
```

![image](https://user-images.githubusercontent.com/8198862/57382343-5d642280-71df-11e9-9fae-911388fd882d.png)

**Comment by lalagou** [comment]
可以将client.xml放在项目的dockerfile同一个目录下。项目运行时创建目录，拷贝client.xml。效果一样

**Comment by nisiyong** [comment]
@lalagou 这不符合我想要的，代码本身无需关注client.xml

**Comment by nisiyong** [comment]
最后决定修改源码的`com.dianping.cat.configuration.ApplicationEnvironment#loadClientConfig`，添加从环境变量`CAT_SERVERS_ADDR`获取IP:PORT的方式，直接解析后返回xml string。达到动态获取的效果

**Comment by CTU1000** [comment]
大家可以参考这篇文章自己覆盖重写源码
https://blog.csdn.net/lemon89/article/details/71171146

**Comment by CTU1000** [comment]
大家可以参考这篇文章自己覆盖重写加载方法
https://blog.csdn.net/lemon89/article/details/71171146

**Comment by CTU1000** [comment]
顺便吐槽一句 ，连个文档全网都搜不到 搞毛

**Comment by nisiyong** [comment]
> 顺便吐槽一句 ，连个文档全网都搜不到 搞毛

哈哈，CAT现在没怎么维护了，有点可惜。
使用文档差不多了，还想继续使用就只能扒扒源码了

**Comment by aiaiya** [comment]
如果客户端是k8s环境，可以用configMap挂载client.xml
