### ISSUE TITLE
cat3.0  接入hdfs存储 开关 " hdfs-enabled " OR   "hdfs-machine"  区别

### ISSUE THREAD

**Issue by hellojd2018** [dianping/cat#1703]
如题。
配置如下，数据怎么也达不到hdfs文件系统里。最主要没有任何异常输出。cat*.log和cat prolem表盘都没显示异常。无从分析
`
      <storage local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="2" local-logivew-storage-time="1" har-mode="true" upload-thread="5">
         <hdfs id="logview" max-size="128M" server-uri="hdfs://192.168.5.57:8020" base-dir="cat/logview"/>
         <hdfs id="dump" max-size="128M" server-uri="hdfs://192.168.5.57:8020" base-dir="cat/dump"/>
         <hdfs id="remote" max-size="128M" server-uri="hdfs://192.168.5.57:8020" base-dir="cat/remote"/>
      </storage>
`
接下来怎么解决。
1. 想调整日志级别，不知道怎么调
2.啃源代码，代价有点高啊

**Comment by zhengxuca** [comment]
同问

**Comment by youyong205** [comment]
有一个hdfs的接入的文档，你们看了吗

**Comment by mobile664042** [comment]
> 有一个hdfs的接入的文档，你们看了吗

你说的这个文档在哪，没有看到啊
是不是 https://github.com/dianping/cat/wiki/global 这个
我在default里面设置了hdfs-machine=true hdfs-enabled=true 不生效啊

**Comment by mobile664042** [comment]
https://github.com/dianping/cat/issues/1703#issuecomment-508363149

有个疑问，https://github.com/dianping/cat/wiki/readme_server

我的cat 与 hdfs部署在不同的机器上，为啥cat的环境变量classpath需要加上core-site.xml的路径

**Comment by koqizhao** [comment]
CAT 3.0 通过配置hdfs-enabled=true开启hdfs上传。
如果hdfs开启，会定期（1小时1次，每小时的第10分钟）把2小时之前的老数据上传到hdfs（dump目录），上传后删除老数据。刚部署后，没有老数据，所以不会立即上传数据到hdfs。
