### ISSUE TITLE
master

### ISSUE THREAD

**Issue by kangzye** [dianping/cat#1707]
我在master分支怎么导入工程，居然是找不到类。
com.dianping.cat.home.dal.report._INDEX 这类是在哪里的呢？ 在你们给的 nexus上也没找到次类

**Comment by kangzye** [comment]
我搜索看到只有在 target 目录里，存在_INDEX.java，这是该如何使用上？？

**Comment by youyong205** [comment]
请参考下https://github.com/dianping/cat/wiki/readme_server 看下本地开发环境的安装。

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/58227647-459fa900-7d5e-11e9-8989-1bd3082d45ab.png)
