### ISSUE TITLE
多维度业务指标功能咨询

### ISSUE THREAD

**Issue by bug1024** [dianping/cat#1708]
看最新的客户端是开放了多tag功能，之前也有人咨询过，具体见：https://github.com/dianping/cat/issues/1647

但服务端目前并没有开放这个功能，有计划的时间点吗？或者能否提供一下实现思路？

**Comment by youyong205** [comment]
计划下个大版本。准备中。具体时间可能到Q3，目前内部的事情比较多。
具体实现思路存储使用es来做的

**Comment by VICI-Gong** [comment]
具体啥时候，有计划么
