### ISSUE TITLE
源码是完整的吗，怎么到处都是不存在的类

### ISSUE THREAD

**Issue by xiaobashagua** [dianping/cat#1709]
下载到本地，无论是提供的执行命令打包还是加载到IED工具中，全是报错，好多类根本就不存在，是什么原因？

**Comment by xiaobashagua** [comment]
![image](https://user-images.githubusercontent.com/40980902/57963416-72b31c80-7956-11e9-9580-beddac915610.png)
谁能解释一下，源码和直接下载的war包文件居然代码有差别同一个版本，源码中好多类都是不存在的

**Comment by MistRay** [comment]
根据ide的类型，在cat目录中执行 mvn eclipse:eclipse 或者 mvn idea:idea，此步骤会生成一些代码文件，直接导入到工程会发现找不到类

**Comment by youyong205** [comment]
可以看下首页文档，本地开发环境写了这部分。
