### ISSUE TITLE
客户端消息队列监控是否存在逻辑上的bug

### ISSUE THREAD

**Issue by mouseDH** [dianping/cat#1713]
cat-client会注册一个StatusExtension用于监控监控消息队列的大小。现在遇到这么个场景，StatusExtension在正常情况下监控的数据为0（应该是消息很快被消费了），在异常情况（消息无法发送到服务端时，从无法发送的第一条开始）下，监控到的消息队列数据无法发送到服务端，该情况下，cat是无法搜集客户端消息无法发送时的相关监控信息的。这时通过admin的heartbeat看板查看到的消息队列数量要么没有要没啥也看不到。

**Comment by youyong205** [comment]
这个监控是取得是一分钟某个时刻的值。
就好比cpu监控一样，是每分钟固定时候采点监控

**Comment by mouseDH** [comment]
非常感谢及时回复。我遇到了下面的情况，对于无法发送消息至消费机失败的情况，cat是无法监控到的，只能在正常情况下，监控消息队列中的条数。如果发送时发生异常，cat本身没有做更多的本地日志，监控的信息又无法送到消费机，那么如何查看异常信息呢？

**Comment by mouseDH** [comment]
@youyong205

**Comment by youyong205** [comment]
你说的情况是存在这种可能性，监控的监控怎么保证，但是一般系统设计中，监控可以认为一个旁路系统。监控绝大部分场景稳定性是能保证的。为了监控自身情况在做一套其他的监控这地方ROI的产出很低。

**Comment by mouseDH** [comment]
> 你说的情况是存在这种可能性，监控的监控怎么保证，但是一般系统设计中，监控可以认为一个旁路系统。监控绝大部分场景稳定性是能保证的。为了监控自身情况在做一套其他的监控这地方ROI的产出很低。

考虑到对整个系统做本地日志不太合适，是否可以在关键的地方做一些本地日志记录呢，比如发送消息这块。我们测试环境发生了direct memery的oom，由于参考的信息不多，定位问题很慢，最后发现是jvm参数设置的有问题。

**Comment by mouseDH** [comment]
@youyong205
