### ISSUE TITLE
cat中的error只显示NestedServletException异常，并没有显示真实的异常或者Business业务异常

### ISSUE THREAD

**Issue by TinChiWay** [dianping/cat#1714]
https://github.com/dianping/cat/blob/c8e74502e19e2e9f98a94aff05f4467b03ee9e42/lib/java/src/main/java/com/dianping/cat/servlet/CatFilter.java#L252-L262

springboot2中的异常在抛到catfilter时被转化为NestedServletException，真实的异常信息被包装起来，error界面看不到其他异常报错

这里是否需要改进或者有什么特殊的设计需求吗？

![image](https://user-images.githubusercontent.com/16657705/58227368-1a688a00-7d5d-11e9-9958-a58f208ca85a.png)

![image](https://user-images.githubusercontent.com/16657705/58225489-ce194c00-7d54-11e9-9746-d4eb212f6c38.png)

**Comment by youyong205** [comment]
那你这个得研究下这个框架，在哪个地方能拿到真实的异常。然后在真实的异常进行打点上报。
这个其实不是cat需要考虑的问题

**Comment by TinChiWay** [comment]
> 那你这个得研究下这个框架，在哪个地方能拿到真实的异常。然后在真实的异常进行打点上报。
> 这个其实不是cat需要考虑的问题

所以这里需要手动打点了吗，我在这个filter上上层fillter进行了手动打入exception.getCause();这样做的话cat会对这一次异常产生两个error记录（分别是NestedServletException与RuntimeException）,这样也对查看error记录也会疑惑的

**Comment by youyong205** [comment]
你可以根据实际的自己需求，稍微修改下CatFilter源码嘛。
很多场景都是根据自己要求，稍微做下定制的。

**Comment by TinChiWay** [comment]
是的呢，我目前打算重写这个CatFilter，其他部分不变，只改变try catch的行为

**Comment by youyong205** [comment]
恩，一般情况下，catfilter能满足大部分的需求。遇到一些特殊情况，稍微要改改满足要求。
