### ISSUE TITLE
client 启动的时候，log 的名称应该修改一下cat_client_{0,date,yyyyMMdd}.log

### ISSUE THREAD

**Issue by biantech** [dianping/cat#1718]
在cat-client module 中，需要修改一下 main\resources\META-INF\plexus\plexus.xml
<logFilePattern>cat_{0,date,yyyyMMdd}.log</logFilePattern> 修改为
<logFilePattern>cat_client_{0,date,yyyyMMdd}.log</logFilePattern>

**Comment by iDube** [comment]
加个pid更好

**Comment by youyong205** [comment]
新版本的3.0，源码并不是这样吧，直接可以java代码里面改就行了。

**Comment by biantech** [comment]
java 代码中如何修改，你们统一修改好了不是更好吗
