### ISSUE TITLE
SpringBoot客户端连接问题

### ISSUE THREAD

**Issue by wangdefeng** [dianping/cat#1720]
开发环境
CAT Home在服务器192.168.1.129上，本地开发配置 client.xml:

<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="192.168.1.129" port="2280" http-port="8080"/>
    </servers>
</config>
本地应用基于Spring Boot 开发，通过CatFilter配置Filter的形式整合Cat客户端。
本地客户端在启动的时候，Cat相关日志会有一个错误提示：
[05-27 17:27:31.090] [ERROR] [CatLogger] error when connect cat server config url http://192.168.1.129:8080/cat/s/router?domain=edu-admin&ip=192.168.1.111&op=xml&env=unknown&hostname=wangdf-PC

无论本地如何调用Controller，CAT服务上均没有任何的记录。

被监控应用在启动的时候所报出的错误会不会导致监控应用相关数据无法上报？

**Comment by wangdefeng** [comment]
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="192.168.1.129" port="2280" http-port="8080"/>
    </servers>
</config>
开发环境client.xml配置

**Comment by wangdefeng** [comment]
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="192.168.1.129" port="2280" http-port="8080"/>
    </servers>
</config>

**Comment by wangdefeng** [comment]
<?xml version="1.0" encoding="utf-8"?>
<config mode="client">
    <servers>
        <server ip="192.168.1.129" port="2280" http-port="8080"/>
    </servers>
</config>
开发机器client.xml配置

**Comment by auqtfqiqpl** [comment]
老铁 我也是遇到这样的问题，解决了嘛

**Comment by wangyapu** [comment]
这个错误是定时拉取路由失败，不影响数据上报。可以定位下TCP连接是否正常，2280端口是否正常建立。
