### ISSUE TITLE
服务端的机器是否能通过跳板机，监测客户端相关信息

### ISSUE THREAD

**Issue by MaskerZheng** [dianping/cat#1721]
部署服务端的机器，与部署客户端的机器不能直接连接，中间有一层跳板机，那么服务端的机器怎么去监测客户端的相关信息，客户端路由那块怎么去配置

**Comment by wangyapu** [comment]
不支持你说的场景。你描述的网络架构是不是有些问题，应该很少有这么设计的吧？

**Comment by youyong205** [comment]
网络不通
