### ISSUE TITLE
mvn cat：install    error

### ISSUE THREAD

**Issue by xiongshiyan** [dianping/cat#1722]
when I exe "mvn cat：install" ,  It reports this error:
` No plugin found for prefix 'cat' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\xiongshiyan\.m2\repository), alimaven (http://maven.aliyun.com/nexus/content/groups/public/), unidal.releases (http://unidal.org/nexus/content/repositories/releases/)] -> [Help 1]`

I can not find the dir "cat-maven-plugin" also

**Comment by hellojd2018** [comment]
用 -X 诊断

**Comment by xiongshiyan** [comment]
thanks , i have solved it Manually

**Comment by qianlimaboy** [comment]
> thanks , i have solved it Manually

how did you do ?
