### ISSUE TITLE
Cat只能查看到一小时之前的调用数据

### ISSUE THREAD

**Issue by hellojd2018** [dianping/cat#1724]
当前时间只能看到1小时之前的数据。 比如【20:50】只能看到【20:00】之前的记录。
配置什么参数能实时看到报表数据呢？
![image002](https://user-images.githubusercontent.com/50145526/58707115-8fcffc80-83e6-11e9-80a9-81a4d038dbe2.jpg)
![img01](https://user-images.githubusercontent.com/50145526/58707116-8fcffc80-83e6-11e9-8f38-fb42d8ab7fc9.jpg)

**Comment by wangyapu** [comment]
实时报表需要根据路由去拉取的，是不是机房路由配置有误？

**Comment by hellojd2018** [comment]
> 实时报表需要根据路由去拉取的，是不是机房路由配置有误？
`<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="192.168.3.35" backup-server-port="2280">
   <default-server id="192.168.3.35" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="default" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="192.168.3.35"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="192.168.3.35" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>`
这是我的路由配置

**Comment by hellojd2018** [comment]
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="192.168.3.35" backup-server-port="2280">
   <default-server id="192.168.3.35" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="default" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="192.168.3.35"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="192.168.3.35" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>

**Comment by hellojd2018** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="192.168.3.35" backup-server-port="2280">
   <default-server id="192.168.3.35" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="default" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="192.168.3.35"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="192.168.3.35" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>`

**Comment by hellojd2018** [comment]
> 是不是机房路由配置有误

就是重启了一下

**Comment by wangyapu** [comment]
实时数据需要根据你配置的一些机器远程发起http请求去拉取数据，确保这些ip是可用的，可以debug看下BaseRemoteModelService相关的代码看下URL请求是否可以正常访问。

**Comment by hellojd2018** [comment]
> 实时数据需要根据你配置的一些机器远程发起http请求去拉取数据，确保这些ip是可用的，可以debug看下BaseRemoteModelService相关的代码看下URL请求是否可以正常访问。

谢谢，明天我和运维同学一块看看。我们用的是docker, 微服务部署所在网段[ 172.20.8.*]是变化的。和cat部署不是一个网段。

我有个疑问： 刚部署完成时，报表查询是正常的，可以实时查看。 重启了一下服务，就不能查看了。奇怪的很
