### ISSUE TITLE
vmware 启动服务端成功，客户端也成功了，控制台就是搜不到数据

### ISSUE THREAD

**Issue by auqtfqiqpl** [dianping/cat#1725]
服务端日志 ：
![image](https://user-images.githubusercontent.com/39790134/58747127-3aa0f300-8499-11e9-8697-6a4f01a8bc00.png)
客户端启动日志 ：
![image](https://user-images.githubusercontent.com/39790134/58747128-5dcba280-8499-11e9-9259-5e5a8ead3985.png)
访问日志 ：
![image](https://user-images.githubusercontent.com/39790134/58747136-7f2c8e80-8499-11e9-87f9-2eb26f57924d.png)
用本地服务测试日志 也这样，但是可以接入进去能查询的到

**Comment by auqtfqiqpl** [comment]
close

**Comment by lele123456** [comment]
@auqtfqiqpl 您解决了吗，我也遇到了这个问题，我是在本地单机测试的，能说下您是怎么解决的吗
