### ISSUE TITLE
关于集群部署单点问题的咨询

### ISSUE THREAD

**Issue by bug1024** [dianping/cat#1726]
https://github.com/dianping/cat/wiki/readme_server 中关于集群部署的有如下说明：

> 假设有10.1.1.1，10.1.1.2，10.1.1.3这三台机器
> 建议选取一台10.1.1.1 负责角色有控制台、告警端、任务机，建议配置域名访问CAT，就配置一台机器10.1.1.1一台机器挂在域名下面
> 10.1.1.2，10.1.1.3 负责消费机处理，这样能做到有效隔离，任务机、告警等问题不影响实时数据处理

**我的想法：**
这样做的话有明显的单点问题，假如10.1.1.1在上线或者因为其他原因挂了，那么控制台就完全不可用了，甚至连报警也用不了，这样感觉对用户不是很友好。

不过看wiki里描述应该是这3台机器都能作为控制台或者任务机，但告警机只能配置其中某一台，所以告警机还是存在单点问题，关于这点美团点评内部是如何解决的？也是单机部署？

**Comment by youyong205** [comment]
内部任务、告警、展示台、消费机等都是独立集群。

针对告警今年会开放一个内部版本出来，这里面工作稍微多了一些。

**Comment by youyong205** [comment]
开源版本还是偏简单一些，至少目前的是。和内部都是两个分支。

**Comment by bug1024** [comment]
> 内部任务、告警、展示台、消费机等都是独立集群。
> 
> 针对告警今年会开放一个内部版本出来，这里面工作稍微多了一些。

实际上开源的版本应该只有告警存在单点，像任务、展示台配置多台机器也是没问题的，我理解的对吧？

**Comment by youyong205** [comment]
展示配置多个，有一个小风险，就是很多配置1分钟同步，最好在路由层配置一个用户ip的hash。
任务可以配置多个。
