### ISSUE TITLE
进主页能设置密码访问吗？

### ISSUE THREAD

**Issue by xiongshiyan** [dianping/cat#1730]
1.部署好cat的服务端之后，我能直接进主页，可以设置密码访问吗？
2.从cat-home的主页进Configs就需要密码，这个默认用户名和密码是什么，怎么修改？
![image](https://user-images.githubusercontent.com/39974039/59335689-a9027280-8d2f-11e9-8337-498dd0a12294.png)

**Comment by xiongshiyan** [comment]
第二个问题知道了，从源码知道是 admin/admin，请问第一个问题怎么解决？

**Comment by youyong205** [comment]
1.自己修改源码解决。可以搜索admin的关键字。
