### ISSUE TITLE
没用hdfs，数据保存多久，怎么昨天的数据今天就看不见了？

### ISSUE THREAD

**Issue by xiongshiyan** [dianping/cat#1731]
1.为什么昨天的所有数据都看不见了？切换到历史模式也看不见。
2.数据保存时间设置的7天，server.xml中local-logivew-storage-time="7"

**Comment by youyong205** [comment]
昨天所有的数据？具体指的报表数据还是logview的数据？
如果是报表的数据，检查下数据库里面具体的写入，小时报表是否写入到数据库里面。

**Comment by xiongshiyan** [comment]
logview的数据

**Comment by xiongshiyan** [comment]
数据库里貌似都没有

**Comment by xiongshiyan** [comment]
@youyong205 
现在调用能查看到，但是昨天的或者之前的就看不见了。
![image](https://user-images.githubusercontent.com/39974039/59498159-6f646f80-8ec7-11e9-824d-f2ab650ff0ac.png)

**Comment by youyong205** [comment]
你这个情况是report都没有存储到数据库里面。你看看数据库report以及report_content表是否有数据？

**Comment by xiongshiyan** [comment]
![image](https://user-images.githubusercontent.com/39974039/59813416-f55b3d00-9343-11e9-82d8-cfddcf4490d0.png)
没有这两个表，是daily_report_content和dailyreport吗？没有数据

**Comment by youyong205** [comment]
hourlyreport & hourlyreport_content

**Comment by xiongshiyan** [comment]
这两个表有数据，现在请求现在查看能看到数据，但是想看昨天的数据就看不见了

**Comment by youyong205** [comment]
你看看对应小时的是否有数据，比如说昨天时间段是否有数据，还有就是对照文档在多检查下，哪里有不对。

**Comment by xiongshiyan** [comment]
好的，谢谢，我明天再看看。

**Comment by xiongshiyan** [comment]
![image](https://user-images.githubusercontent.com/39974039/59889854-ea1a1700-9400-11e9-9c15-e2a5df1e24ed.png)
hourlyreport表中有昨天的数据，但是展示不出来 @youyong205

**Comment by xiongshiyan** [comment]
应该检查哪些配置呢？我的配置基本上是按照文档配置的，相当于一个hello world都还没正常跑起来。有没有微信或者QQ群可以进去请教的？

**Comment by xiongshiyan** [comment]
好了，已经解决了，谢谢大拿

**Comment by yuanhuaiwang** [comment]
> 好了，已经解决了，谢谢大拿

怎么解决的，遇到相同的问题了，求救
