### ISSUE TITLE
docker部署Step 14/32报错

### ISSUE THREAD

**Issue by xulcdev** [dianping/cat#1732]
docker部署时出现如下异常：
ERROR: Service 'cat' failed to build: The command '/bin/sh -c wget -q https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz &&     wget -qO- https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.md5 | md5sum -c - &&     tar zxf apache-tomcat-*.tar.gz &&     mv apache-tomcat-${TOMCAT_MINOR_VERSION}/* . &&     rm -rf apache-tomcat-*' returned a non-zero code: 4

**Comment by zhangshuaiqiang-deepexi** [comment]
解决没有，我也遇到这个问题

**Comment by zhangshuaiqiang-deepexi** [comment]
已解决原因是 tomcat 和 maven 地址发生变化需要修改 参考 [https://www.cnblogs.com/provence666/p/11029329.html](url)
