### ISSUE TITLE
CAT中跨服务调用埋点规范及Cross报表的使用说明？

### ISSUE THREAD

**Issue by marqueeluo** [dianping/cat#1733]
问题：
（1）有没有跨服务调用的埋点规范？
（2）Cross报表该如何使用？
以上2个问题github上没有找到。
结合之前在网上找到的资料，实际在项目中跨服务调用埋点如下：
客户端：
HttpClient添加Request拦截器（埋点remoteCallClient 且 通过request.headers传递context）：

            /** 埋点cat remoteCallClient并构建相关trace信息 */
            CatTraceContext catTraceContext = new CatTraceContext();
            //catRemoteCallDomain为服务端domain
            Cat.logRemoteCallClient(catTraceContext, catRemoteCallDomain);
            //设置request.header且通过request.headers传递context
            req.addHeader(CatTraceContext.ROOT,catTraceContext.getProperty(CatTraceContext.ROOT));
            req.addHeader(CatTraceContext.PARENT, req.addHeader(CatTraceContext.PARENT));
            req.addHeader(CatTraceContext.CHILD, catTraceContext.getProperty(CatTraceContext.CHILD));

           

服务端：
改造CatFilter（获取request.headers）：

        /** 添加服务追踪（Server端）处理逻辑 */
        String rootHeader = req.getHeader(CatTraceContext.ROOT);
        String parentHeader = req.getHeader(CatTraceContext.PARENT);
        String childHeader = req.getHeader(CatTraceContext.CHILD);
        /** 埋点服务追踪服务端 */
        Cat.logRemoteCallServer(CatTraceContext.buildContext(rootHeader, parentHeader, childHeader));

不知道上述埋点是否符合规范，并且cross报表是否和上述埋点相关（是否需要符合特定埋点规则），以上，有问题请指正，希望提供CAT中跨服务调用埋点规范及Cross报表的使用说明（建议完善github文档）；

**Comment by xiongshiyan** [comment]
应该是这样做的，这样能查看到调用链的信息

**Comment by youyong205** [comment]
不是有一个dubbo客户端集成的源码的demo么。

**Comment by marqueeluo** [comment]
> 应该是这样做的，这样能查看到调用链的信息

收到 谢谢 能查看到调用链信息 但是不知道怎么和cross报表关联

**Comment by marqueeluo** [comment]
> 不是有一个dubbo客户端集成的源码的demo么。
收到 我再研究研究看看

**Comment by marqueeluo** [comment]
> 不是有一个dubbo客户端集成的源码的demo么。

收到 谢谢 我再研究研究
