### ISSUE TITLE
自定义实体使用代码生成插件后components.xml会少生成一个标签

### ISSUE THREAD

**Issue by MistRay** [dianping/cat#1734]
我在`cat-home`模块内创建了`test-codegen.xml`,`test-dal.xml`,`test-manifest.xml`,映射到我自己创建的test表.然后使用`mvn install`生成代码,`TestName`,`TestNameDao`,`TestNameEntity`生成成功.但components.xml中会缺少以下标签
```
		<component>
			<role>org.unidal.dal.jdbc.mapping.TableProvider</role>
			<role-hint>test-name</role-hint>
			<implementation>org.unidal.dal.jdbc.mapping.SimpleTableProvider</implementation>
			<configuration>
				<physical-table-name>test</physical-table-name>
				<data-source-name>cat</data-source-name>
			</configuration>
		</component>
```
手动添加后,可以正常操作数据库.但是,每次重新生成代码,components.xml的内容都会刷新,也就是之前手动添加的标签会消失.有什么解决方案么?

**Comment by MistRay** [comment]
把componet.xml替换了自己维护一份.(添加数据库配置后,这个生成插件有时候会生成正确的,有时候会生成错误的,还需要排查一下具体为什么,目前使用上面临时解决方案)

**Comment by sunwulovelove1** [comment]
解决了吗？我也遇到了   发现是使用代码生成的 components.xml，搜索对应的接口  /com/dianping/cat/bulid/
