### ISSUE TITLE
【源码问题咨询】EventReport中synchronized的使用

### ISSUE THREAD

**Issue by bug1024** [dianping/cat#1736]
通过阅读源码发现的几点：

- MessageAnalyzer会持有ReportManager，这两个类配置的是per-lookup，即每次lookup的时候都会创建新的实例
- 每个MessageAnalyzer实例都会持有单独的一个Queue进行消费计算
- 可以认为Analyzer都是单线程消费的，不存在并发问题

我的疑问：
以EventAnalyzer为例，通过ReportManager获取到EventReport后，进行计算操作时，EventReport的findOrCreateMachine方法内使用了synchronized
不大理解为什么要加synchronized，感觉没有必要加也行，因为都是在一个线程里面操作，不存在并发同步问题，求指教～

![image](https://user-images.githubusercontent.com/8141794/59545868-99657280-8f57-11e9-9bb6-ff899ee2b79e.png)

![image](https://user-images.githubusercontent.com/8141794/59545871-abdfac00-8f57-11e9-9142-caa1ec73e70f.png)

**Comment by youyong205** [comment]
EventReport 这个是用Codegen工具生成的，这个生成的类可能会用其他地方。Analyzer里面也没特别针对这个做改动。

单线程里面加了sync之后其实性能影响也很小。
