### ISSUE TITLE
文件大小增长很快，/data/appdatas/report

### ISSUE THREAD

**Issue by xiaohuasheng** [dianping/cat#1739]
线上发现这个目录/data/appdatas/report 增长很快，2G/min，目录里的文件是 数字.json ，比如 1.json, 2.json
在文档里没找到它的介绍
想搞清楚这个目录存放的是什么数据，能不能改哪里的配置降低它的大小
比如给项目配置采样？
有谁知道的解答一下？万分感谢！

**Comment by youyong205** [comment]
如果是report文件，是存储的报表的report，一个小时flush一次，2G/min 太夸张了，你在仔细检查检查吧

**Comment by xiaohuasheng** [comment]
> 如果是report文件，是存储的报表的report，一个小时flush一次，2G/min 太夸张了，你在仔细检查检查吧

嗯，有个服务被刷了，产生大量调用信息上报到CAT
