### ISSUE TITLE
cat集群,后台运行一段时间后卡顿问题  tag：3.0.0

### ISSUE THREAD

**Issue by l593067749** [dianping/cat#1740]
线上采用集群部署的方式，目前是4台机器，2台做web数据展示（4核8G），2台（8核16G）用于消息数据处理。war包是拉3.00tag版本编译生成的，地址：https://github.com/dianping/cat/tree/v3.0.0

客户端路由配置如下：

`<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="xx.xx.21.241" backup-server-port="2280">
   <default-server id="xx.xx.21.241" weight="1.0" port="2280" enable="true"/>
   <default-server id="xx.xx.21.242" weight="1.0" port="2280" enable="true"/>
   <default-server id="xx.xx.0.170" weight="1.0" port="2280" enable="false"/>
   <default-server id="xx.xx.0.171" weight="1.0" port="2280" enable="false"/>
   <network-policy id="default" title="默认" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="xx.xx.21.241"/>
      <group-server id="xx.xx.21.242"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="xx.xx.21.241" port="2280" weight="1.0"/>
         <server id="xx.xx.21.242" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>`

现在的问题是：运行一段时间后（1天），访问web后台能明显感到卡顿，重启后可以恢复一段时间。帮忙给看看原因是什么。

负载图如下：
![image](https://user-images.githubusercontent.com/11661289/59734141-da74c400-9282-11e9-91c9-c65495124c9c.png)

java参数：参考官方配置，只是修改了-Xms和-Xmx为5G

`/usr/bin/java -Djava.util.logging.config.file=/data/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms5120m -Xmx5120m -Dfile.encoding=utf-8 -server -DCAT_HOME=/data/appdatas/cat/ -Djava.awt.headless=true -DHADOOP_USER_NAME=hadoop -Xms5G -Xmx5G -XX:PermSize=256m -XX:MaxPermSize=256m -XX:NewSize=5120m -XX:MaxNewSize=5120m -XX:SurvivorRatio=10 -XX:+UseParNewGC -XX:ParallelGCThreads=4 -XX:MaxTenuringThreshold=13 -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:+UseCMSInitiatingOccupancyOnly -XX:+ScavengeBeforeFullGC -XX:+UseCMSCompactAtFullCollection -XX:+CMSParallelRemarkEnabled -XX:CMSFullGCsBeforeCompaction=9 -XX:CMSInitiatingOccupancyFraction=60 -XX:+CMSClassUnloadingEnabled -XX:SoftRefLRUPolicyMSPerMB=0 -XX:-ReduceInitialCardMarks -XX:+CMSPermGenSweepingEnabled -XX:CMSInitiatingPermOccupancyFraction=70 -XX:+ExplicitGCInvokesConcurrent -Djava.nio.channels.spi.SelectorProvider=sun.nio.ch.EPollSelectorProvider -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=/data/tomcat/conf/logging.properties -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationConcurrentTime -XX:+PrintHeapAtGC -Xloggc:/data/applogs/heap_trace.txt -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/applogs/HeapDumpOnOutOfMemoryError `

**Comment by youyong205** [comment]
按照这个描述还是挺难查的。结合cat监控看看heartbeat看看?另外看看cat报表的transaction的监控数据

**Comment by l593067749** [comment]
下图是我们预发布环境部署的cat服务的ransaction有几项确实响应很慢，烦请帮忙给看看是个什么情况
![image](https://user-images.githubusercontent.com/11661289/59986281-b4776700-9668-11e9-8a0c-bfe69db2d1a5.png)
下面是心跳信息：
![image](https://user-images.githubusercontent.com/11661289/59986400-51d29b00-9669-11e9-9fcf-c38845fefa47.png)

![image](https://user-images.githubusercontent.com/11661289/59986451-7a5a9500-9669-11e9-81fa-45c8026978d6.png)
![image](https://user-images.githubusercontent.com/11661289/59986466-88101a80-9669-11e9-9b74-2520eeceb24e.png)

**Comment by l593067749** [comment]
tomcat日志里有这样的错误，不过只有3条日志
![image](https://user-images.githubusercontent.com/11661289/59987219-8136d700-966c-11e9-9ef1-93a315c9bce0.png)

**Comment by l593067749** [comment]
> 按照这个描述还是挺难查的。结合cat监控看看heartbeat看看?另外看看cat报表的transaction的监控数据

嗯，谢谢大佬，生产这边刚把心跳放出来，观察一下。预发布环境的我也贴了出来，方便的话帮忙给瞅瞅。

**Comment by youyong205** [comment]
![image](https://user-images.githubusercontent.com/1281552/60644980-16ef1500-9e6a-11e9-90a5-f896db7d2157.png)
这个应该cms里面的old区gc吧，应该是jvm内存设置不够。

**Comment by l593067749** [comment]
> ![image](https://user-images.githubusercontent.com/1281552/60644980-16ef1500-9e6a-11e9-90a5-f896db7d2157.png)
> 这个应该cms里面的old区gc吧，应该是jvm内存设置不够。

问题在于目前还没有任何服务接上去，只是单起了服务，就出现了卡顿的。后来重新杀了进程，重启后目前为止看起来还正常。需要再观察一段时间。内存16G，出问题dump出来还不好分析。有问题了再沟通，谢谢。
