### ISSUE TITLE
修改routerConfigUpdate时出现java.lang.NoClassDefFoundError: com/mchange/v2/c3p0/ComboPooledDataSource

### ISSUE THREAD

**Issue by zhengxuca** [dianping/cat#1742]
java.lang.NoClassDefFoundError: com/mchange/v2/c3p0/ComboPooledDataSource

![image](https://user-images.githubusercontent.com/22671513/59820075-167c5780-935d-11e9-83c9-a1200cb3f244.png)

**Comment by youyong205** [comment]
这个问题自己检查吧，NoClassDefFoundError 是个很标准的部署环境问题。
