### ISSUE TITLE
RuleType FluctuateIncreasePercentage实现当前后值均为0时 没有波动上升但是由于是double类型是可以除以0成无限大的导致告警

### ISSUE THREAD

**Issue by wgqazll** [dianping/cat#1744]
测试用例：
       RuleType ruleType = RuleType.getByTypeId("FluAscPer");
        double[] values = {0, 0};
        Pair<Boolean, String> booleanStringPair = ruleType.executeRule(values, values, "22");

        System.out.println("booleanStringPair = " + jsonBuilder.toJson(booleanStringPair));

**Comment by youyong205** [comment]
这个建议在配置一个并行条件，比如是当前最小值超过100。
这个double的整除的问题，我们在看下
