### ISSUE TITLE
构建时报错,Could not find artifact org.unidal.framework:parent:pom:2.0.6 

### ISSUE THREAD

**Issue by wfs1994** [dianping/cat#1749]
Failed to collect dependencies at com.dianping.cat:cat-client:jar:1.3.6 -> org.unidal.framework:foundation-service:jar:2.2.0: Failed to read artifact descriptor for org.unidal.framework:foundation-service:jar:2.2.0: Could not find artifact org.unidal.framework:parent:pom:2.0.6

**Comment by youyong205** [comment]
建议是用master最新的代码，cat-client已经是3.0的version。

**Comment by wfs1994** [comment]
感谢您的帮助！




------------------ 原始邮件 ------------------
发件人: "youyong205"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 下午2:41
收件人: "dianping/cat"<cat@noreply.github.com>;
抄送: "王丰硕"<1109206195@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dianping/cat] 构建时报错,Could not find artifact org.unidal.framework:parent:pom:2.0.6  (#1749)




建议是用master最新的代码，cat-client已经是3.0的version。
