### ISSUE TITLE
nodejs 客户端如何显示消息树调用

### ISSUE THREAD

**Issue by davidinsuomi** [dianping/cat#1750]
nodejs 客户端会调用其他的服务， 其他服务有（java)也接了cat， 但是消息树显示不出来服务调用
<img width="828" alt="Screen Shot 2019-06-27 at 2 40 55 PM" src="https://user-images.githubusercontent.com/1399563/60243870-c452ad80-98eb-11e9-90e9-3552e4742e23.png">

请问远程url调用时messageid如何传递和设置， nodejs有没有方法可以实现？

**Comment by davidinsuomi** [comment]
nodejs 客户端没有LogRemoteCallServer，logRemoteCallClient这个两个方法， 请问如何实现跨机器的message id传递，以及消息树的构建？ 谢谢了

**Comment by youyong205** [comment]
cat本质上一个实时监控系统，主要体现在监控报表Transaction、event、problem、heartbeat等，cat系统定制的监控模型以及定制的实时分析报表也是cat系统核心优势。
logview是cat原始的log采集方式，cat的logview使用的技术是threadlocal，将一个thread里面的打点聚合上报，有一点弱化版本的链路功能，但是cat并不是一个标准的全链路系统，全链路系统参考dapper的论文，业内比较知名的鹰眼，zipkin等，其实经常拿cat和这类系统进行比较其实是不合适的。cat的logview在异步线程等等一些场景下，其实不合适，cat本身模型并不适合这个。在美团点评内部，有mtrace专门做全链路分析。

其他语言，我们默认就不会提供这类功能。还是提供cat的标准实时监控功能。

如果你要做链路串联，你可以参考下dubbo客户端埋点的方式串联。API，就是Cat.logRemoteCallClient 以及Cat.logRemoteCallServer ，可以参考java实现。
