### ISSUE TITLE
Problem里面Heartbeat-jstack堆栈信息显示格式问题

### ISSUE THREAD

**Issue by cookiejoo** [dianping/cat#1752]
一个问题:
之前Heartbeat图表不显示的问题原因是没有用代码包下面的lib-client打包,现在用lib下面的client打包后Heartbeat图表展示出来了(最新代码).
现在出现一个问题,Problem里面Heartbeat-jstack堆栈信息显示格式问题,和CAT服务器的格式不一样,而且变成一行很难看.这个怎么解决?
到客户端机器上jstack命令是和cat服务端那个格式的,我估计是client.jar的问题,要用什么client.jar代码吗?
![cat服务端](https://user-images.githubusercontent.com/3397316/60322857-16123b00-99b3-11e9-91cb-a62645d425f5.png)
![cat客户端](https://user-images.githubusercontent.com/3397316/60322858-16aad180-99b3-11e9-8bdd-0f13e6400f73.png)
![cat客户端jstack](https://user-images.githubusercontent.com/3397316/60322859-16aad180-99b3-11e9-9d2d-aee2588d19b2.png)

**Comment by youyong205** [comment]
你这个情况，第一个图是对的，第二个是不对的。我印象中fix过这个bug，但是代码版本号并没有更新。

master的代码应该更新过才对，你在check下？或者重新打个包在试试。lib下的java客户端

**Comment by cookiejoo** [comment]
> 你这个情况，第一个图是对的，第二个是不对的。我印象中fix过这个bug，但是代码版本号并没有更新。
> 
> master的代码应该更新过才对，你在check下？或者重新打个包在试试。lib下的java客户端

我并非用master里面的代码，我是fork3.0的release分支下来的。

**Comment by youyong205** [comment]
那你是用master代码，谢谢。一些bug fix我们都是master上fix的。

**Comment by cookiejoo** [comment]
> 你这个情况，第一个图是对的，第二个是不对的。我印象中fix过这个bug，但是代码版本号并没有更新。
> 
> master的代码应该更新过才对，你在check下？或者重新打个包在试试。lib下的java客户端

而且，cat里面的client是给服务端用的，打包都是用lib下面的，你fix代码没有合并到lib下吧，我看lib下面的代码4个月都没有更新过。

> 那是用下master代码试试，一些bug fix我们都是master上fix的。

而且，cat里面的client是给服务端用的，打包都是用lib下面的，你fix代码没有合并到lib下吧，我看lib下面的代码4个月都没有更新过。

**Comment by youyong205** [comment]
合并过的。这个刚刚推3.0就发现了，发现很久了就fix过。所以说你拿master里面lib下代码试试。

**Comment by cookiejoo** [comment]
> 合并过的。这个刚刚推3.0就发现了，发现很久了就fix过。所以说你拿master里面lib下代码试试。

不行，就是拿master上的代码打包成client.jar，还是一样的，我复制了client包下的StatusInfoCollector.java这个类到lib下使用才正常了.

**Comment by peng213** [comment]
我按你说的复制了client包下的StatusInfoCollector.java这个类到lib下使用 但是打包报错

**Comment by cookiejoo** [comment]
> 我按你说的复制了client包下的StatusInfoCollector.java这个类到lib下使用 但是打包报错

我这没有异常哦，不过我去掉了这个功能了，这个功能会引起STW，还容易把应用搞卡死，建议先别用吧。

**Comment by peng213** [comment]
你用的是master 3.0分支的吗

**Comment by peng213** [comment]
我的情况跟你一样 我用的是最新master 3.0分支  但是客户端Heartbeat-jstack堆栈信息显示格式和你之前一样的

**Comment by peng213** [comment]
可以加一下我的微信 帮忙解决一下嘛 很感谢 17395170797

**Comment by technologe12** [comment]
cat小白 遇到同样的问题请问怎么解决  （cat是master分支）

**Comment by cookiejoo** [comment]
> cat小白 遇到同样的问题请问怎么解决 （cat是master分支）

1：复制master里面的一个StatusInfoCollector.java类过来
2：修改client.jar下面的new StatusUpdateTask.java类
      buildHeartbeats方法，这里用到StatusInfoCollector类，try里面加status.accept(new StatusUpdateTask().serDumpLocked(true))
      Cat.logEvent(最后的参数换成new StatusUpdateTask().getJstackInfo())

只能帮你们到这了，这个东西会导致jstack执行时所有线程暂停，也就是STW问题。在重量级应用就会出现某些接口线程停下来了，导致调用超时什么的。
我们已经废弃这个方法了，加了参数判断，有需要的自己去开启

**Comment by cookiejoo** [comment]
> 可以加一下我的微信 帮忙解决一下嘛 很感谢 17395170797

看这里

**Comment by technologe12** [comment]
谢谢 所以说3.0并没有修复这个bug对吧

**Comment by cookiejoo** [comment]
> 谢谢 所以说3.0并没有修复这个bug对吧

是说，master上的cat服务端没问题，是客户端用的client.jar有问题
