### ISSUE TITLE
Transaction  历史报表问题

### ISSUE THREAD

**Issue by jiaxinxuan** [dianping/cat#1753]
我们介入了几个项目,其中一个项目的

**Comment by jiaxinxuan** [comment]
[06-29 01:10:59.172] [ERROR] [ReportFacade] Task[consumer: 172.19.1.232, count: 0, creation-date: 2019-06-29 01:03:03.0, end-date: null, end-limit: 0, failure-count: 0, id: 4473, key-id: 4473, producer: 172.19.1.232, report-domain: platon
, report-name: transaction, report-period: 2019-06-28 00:00:00.0, start-date: Sat Jun 29 01:10:54 CST 2019, start-limit: 0, status: 2, task-type: 1]  报错,其他项目正常,这是夜里运行报表统计时的报错

**Comment by jiaxinxuan** [comment]
hourlyreport和hourly_report_content有数据,小时模式都有,只不过daily_report_content和dailyreport联查事,daily_report_content表里没有数据

**Comment by jiaxinxuan** [comment]
![image](https://user-images.githubusercontent.com/12086677/60381331-b2a50d80-9a85-11e9-8ec2-390c310e8988.png)

**Comment by jiaxinxuan** [comment]
还有这个数据怎么让任务重新跑啊?

**Comment by youyong205** [comment]
可以在task表里面，根据domian，period等信息，把tast_status的状态设置为1，就可以自动重跑了。

**Comment by GKJMLvjisheng** [comment]
> 可以在task表里面，根据domian，period等信息，把tast_status的状态设置为1，就可以自动重跑了。

这个更改后多久能生效呢？

**Comment by flyingglass** [comment]
> > 可以在task表里面，根据domian，period等信息，把tast_status的状态设置为1，就可以自动重跑了。
> 
> 这个更改后多久能生效呢？

1分钟左右
