### ISSUE TITLE
transaction埋点时使用的参数是否可以为中文?

### ISSUE THREAD

**Issue by MistRay** [dianping/cat#1759]
```java
    /**
     * Create a new transaction with given type and name.
     *
     * @param type transaction type
     * @param name transaction name
     */
    public static Transaction newTransaction(String type, String name)
```
type/name是否支持中文?
如果不支持,建议在文档中做出警告或标识,减少其他同学的试错成本.  

---
如果支持,我的事务报表在展示中会出现乱码问题
例如:我设置的name为"测试",那么在事务报表就会展示为".."

症状细节为:
* 接收到监控内容开始展示为非乱码状态.
* 过了一段时间(1-5分钟)后,展示为一半乱码,一半正常的状态.
(cat将一个name识别为乱码和非乱码的两个name,分别聚合,甚至能分别得到两部分的tp95和tp999)
* 再过一段时间(1分钟左右)会全部刷新为乱码状态
* 乱码细节:中文会转换成等量的`.`.即一个中文字符会转变成`.`,两个中文会转变成`..`
* 在点进`Log View`内时,中文是可以正常显示的  
* 使用中英文组合的name,英文可以正常显示,中文依然会被替换成`.`

debug源码后,在`com.dianping.cat.report.page.transaction.DisplayNames.java`的41行的map中取到的就是"..".

```xml
<?xml version="1.0" encoding="utf-8"?>
<type id="test" totalCount="73" failCount="0" failPercent="0.00" min="0.00" max="0.00" avg="0.0" sum="0.0" sum2="0.0" std="0.0" tps="0.03" line95Value="1.00" line99Value="1.00" line999Value="1.00" line90Value="1.00" line50Value="1.00" line9999Value="1.00">
   <successMessageUrl>alarmplat-c0a81949-433974-141</successMessageUrl>
   <longestMessageUrl>alarmplat-c0a81949-433974-141</longestMessageUrl>
   <name id=".." totalCount="73" failCount="0" failPercent="0.00" min="0.00" max="0.00" avg="0.0" sum="0.0" sum2="0.0" std="0.0" tps="0.03" line95Value="1.00" line99Value="1.00" line999Value="1.00" line90Value="1.00" line50Value="1.00" line9999Value="1.00">
      <successMessageUrl>alarmplat-c0a81949-433974-141</successMessageUrl>
      <longestMessageUrl>alarmplat-c0a81949-433974-141</longestMessageUrl>
   </name>
</type>
```
希望碰到相同问题的同学帮忙提供下解决思路.

**Comment by bug1024** [comment]
type/name不支持中文的，在wiki里应该有说明的。你把type/name当成变量看待就行了，也要遵循变量命名的规则，即使用英文，同时不使用特殊符号，并且也不宜过长。

**Comment by MistRay** [comment]
> type/name不支持中文的，在wiki里应该有说明的。你把type/name当成变量看待就行了，也要遵循变量命名的规则，即使用英文，同时不使用特殊符号，并且也不宜过长。

我用chrome的检索了`中文,英文,name,type`关键字,wiki内并没有标明name/type不支持中文,.我觉得不支持中文没问题,但至少应该在文档中醒目位置标识出来.

**Comment by youyong205** [comment]
@MistRay 这个可以提个PR么，文档一些文档需要持续完善，开源有更多同学一起协助就更好了

**Comment by youyong205** [comment]
不建议在代码里写中文，非常不好的习惯。
