### ISSUE TITLE
更改ＣAT使用的Kerberos端口

### ISSUE THREAD

**Issue by zhengxuca** [dianping/cat#1765]
我用    <property name="java.security.krb5.kdc" value="AA.BB.CC.DD"/>　配置kdc.
CAT使用Kerberos的默认端口８８．但我的hdfs集群不接受88 port. 如何让ＣＡＴ访问用户定义的port?

**Comment by youyong205** [comment]
关于hdfs的这边目前仅仅提供简单的方式。如果有特殊配置需要做源码修改，用其他方式支持hdfs的访问。
