### ISSUE TITLE
 -> com.dianping.cat:cat-core:jar:2.0.0: Failed to read artifact descriptor for com.dianping.cat:cat-core:jar:2.0.0: Failure to find org.unidal.framework:framework-bom:pom:4.0.0

### ISSUE THREAD

**Issue by Alvin-Yao** [dianping/cat#1767]
-> com.dianping.cat:cat-core:jar:2.0.0: Failed to read artifact descriptor for com.dianping.cat:cat-core:jar:2.0.0: Failure to find org.unidal.framework:framework-bom:pom:4.0.0

**Comment by youyong205** [comment]
建议使用最新的cat-client 3.0

**Comment by xiehongji** [comment]
使用3.0.0版本安装吧，兄弟，网上太多2.0.0版本了，也有很多问题
