### ISSUE TITLE
CAT Go Client　port　不对

### ISSUE THREAD

**Issue by zhengxuca** [dianping/cat#1768]
我使用ＣＡＴ的golang client. 在client.xml文件里面，cat服务的http-port是8060．但是golang client使用的port为什么是8080？

![image](https://user-images.githubusercontent.com/22671513/61206402-0ae63b80-a725-11e9-944e-6ba33523829b.png)

**Comment by token01** [comment]
你可以看一下 你的 配置是不是配置错了

**Comment by youyong205** [comment]
应该是配置错了吧
