### ISSUE TITLE
应用 ip 获取问题请教

### ISSUE THREAD

**Issue by zhaojinfeng5** [dianping/cat#1770]
1. cat 监控页面上能显示到应用 ip 和端口粒度吗，如果一台 tomcat 上部署了多个同一应用怎么做区分？

2. 类似如下架构，cat 获取到的应用 ip 似乎并不是最底层 tomcat 的 ip，是吗？
![image](https://user-images.githubusercontent.com/11642831/61355561-4d378600-a8a7-11e9-8bd2-a5fe1149be43.png)

**Comment by youyong205** [comment]
1.cat不支持第一种场景。这两个统计会合并到一个。
2.cat获取的IP是 tomcat所在当前机器的IP
