### ISSUE TITLE
cat 服务端看不到连接池相关的数据,只能看到硬盘，内存，GC，线程相关的数据

### ISSUE THREAD

**Issue by guxsun** [dianping/cat#1771]
cat 服务端看不到连接池相关的数据,只能看到硬盘，内存，GC，线程相关的数据。
客户端版本:
cat-client:3.0.0
druid-spring-boot-starter:1.1.10

**Comment by youyong205** [comment]
连接池数据支持c3p0以及druid。java客户端需要使用最新版本3.0的客户端，在lib java目录下。
