### ISSUE TITLE
你好请问一下，Transaction堆栈信息丢失的问题

### ISSUE THREAD

**Issue by evancyz** [dianping/cat#1772]
最近看一个Problem的堆栈信息的时候，发现cat从头到尾是3s多，但是堆栈信息只显示了500ms，请问是以什么为准呢？ Cat是会丢堆栈信息吗？感谢~
![image](https://user-images.githubusercontent.com/22286097/61424416-fa60db80-a945-11e9-83e9-907fe689f94d.png)

**Comment by evancyz** [comment]
<img width="1208" alt="444" src="https://user-images.githubusercontent.com/22286097/61424553-76f3ba00-a946-11e9-8b52-ec0ddb084566.png">
比如这里，其实2s多的信息，就没了
我的理解这个请求应该是跑了3s吧？
我们这里想做性能优化。。想看具体什么地方慢，所以想参考下堆栈信息~

**Comment by wangyapu** [comment]
消息里面包含了太多的消息，被截断了，并不是丢失堆栈消息。
