### ISSUE TITLE
没有实时的数据展示，只有历史的，或者前一个小时的数据能看。

### ISSUE THREAD

**Issue by qiaolugithub** [dianping/cat#1773]
cat服务没有展示实时监控数据。只能看一个小时前的数据。之后重启修改配置好过一会，但是过一会还是没有实时数据。

**Comment by qiaolugithub** [comment]
实时的数据是空
![image](https://user-images.githubusercontent.com/18211761/61513072-80f0e800-aa2e-11e9-8236-949635f9e333.png)
一小时之前的确有
![image](https://user-images.githubusercontent.com/18211761/61513092-9239f480-aa2e-11e9-8061-85e9c2be9ce7.png)

**Comment by qiaolugithub** [comment]
排查几个点：
1.检查服务器配置的客户端路由看看是不是有问题，重新配置或者重启cat服务
2.检查是不是所有项目都是没有实时，如果是部分项目没有实时数据检查cat服务器/data/appdata/cat/dump文件的权限是不是和tomcat进程的角色一致。
3.检查客户端监控的项目/data/appdata/cat/client_cache.xml。如果有问题可以删了这个文件重启一下客户端项目。

**Comment by qiaolugithub** [comment]
cat提供的详细文档可能还不够覆盖全，有时候一些问题比较奇怪需要自己多想一下流程或者看一下代码。对cat要有一定的熟悉层度才更好解决这个问题。

**Comment by ZaynJiang** [comment]
重复启动了多个tomcat

**Comment by qiaolugithub** [comment]
> 重复启动了多个tomcat

对这个也会有影响，我这边也遇到过。

**Comment by smallze** [comment]
说下我的排查思路，先看服务端和客户端的cat日志，如果正常，看两边时间是否一致，最后排查发现服务端的cat的tomcat进行shutdown时没有将对应java线程杀死，我将所有线程杀死后，重新启动，监控数据及时正常显示
