### ISSUE TITLE
Transaction面板应用列表点击全部项目部分项目丢失

### ISSUE THREAD

**Issue by chengdongwei** [dianping/cat#1779]
- 第一种情况业务方接入META-INF/app.properties忘记写入app.id，Transaction面板应用列表不显示。后来指导业务方写好app.id可以在搜索框填写应用全名搜索出来，但是点击全部应用列表始终没有
- 第二种情况删除应用再添加应用，Transaction面板点击全部应用列表也显示不了

**Comment by chengdongwei** [comment]
@chengdongwei 
解决方案
`
	protected void refresh() {
		try {
			List<Project> projects = m_projectDao.findAll(ProjectEntity.READSET_FULL);
			ConcurrentHashMap<String, Project> tmpDomainProjects = new ConcurrentHashMap<String, Project>();
			ConcurrentHashMap<String, Project> tmpCmdbProjects = new ConcurrentHashMap<String, Project>();
			ConcurrentHashMap<String, String> tmpDomains = new ConcurrentHashMap<String, String>();

			for (Project project : projects) {
				String domain = project.getDomain();

				tmpDomains.put(domain, domain);
				tmpDomainProjects.put(domain, project);

				String cmdb = project.getCmdbDomain();

				if (cmdb != null) {
					tmpCmdbProjects.put(cmdb, project);
				}
			}
			m_domains = tmpDomains;
			m_domainToProjects = tmpDomainProjects;
			m_cmdbToProjects = tmpCmdbProjects;
		} catch (DalException e) {
			Cat.logError("initialize ProjectService error", e);
		}
	}
`
m_domains是类变量没有触发更新，当应用没有重启时这个m_domains变量map一直是原始值
重启cat-home解决

**Comment by chengdongwei** [comment]
已经解决

**Comment by lmx110522** [comment]
不可能我每次更改配置的时候都需要重启CAT吧 在监控线上的应用，怎么可能重启。
这个地方要开启，会去创建对应的TaskBuilder，然后去更新cmdbInfo,但是切记，
![image](https://user-images.githubusercontent.com/37907181/105029398-49cd1e00-5a8d-11eb-9f82-1e9586b1afd4.png)
![image](https://user-images.githubusercontent.com/37907181/105029850-d8419f80-5a8d-11eb-8e01-b972f2045b42.png)
