### ISSUE TITLE
请按照首页最新的文档进行安装说明

### ISSUE THREAD

**Issue by cabbagelml** [dianping/cat#1780]
请按照首页最新的文档进行安装说明

_Originally posted by @youyong205 in https://github.com/dianping/cat/issues/1298#issuecomment-417980351_
最新文档在哪里呢？连接能否粘一下，我也是同样的问题

**Comment by cabbagelml** [comment]
[ERROR] No plugin found for prefix 'cat' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/var/relx/cat/~/.m2/repository), central (http://repo1.maven.org/maven2), unidal.releases (http://unidal.org/nexus/content/repositories/releases/)] -> [Help 1]

**Comment by wangyapu** [comment]
https://github.com/dianping/cat/wiki
