### ISSUE TITLE
Dockerfile-cn中tomcat版本问题

### ISSUE THREAD

**Issue by luolizhi** [dianping/cat#1784]
tomcat版本问题，清华大学镜像[地址](https://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-7/)只有v7.0.96，Dockerfile-cn中
>ENV TOMCAT_MINOR_VERSION 7.0.94

建议修改下版本号。
![image](https://user-images.githubusercontent.com/14789043/62505651-18787800-b830-11e9-8688-d54d85d4e1a7.png)

**Comment by qmwu2000** [comment]
已修改
