### ISSUE TITLE
CAT告警如何获取异常的堆栈信息

### ISSUE THREAD

**Issue by ddwla4** [dianping/cat#1786]
CAT告警如何配置异常的堆栈信息 或者异常名称也可以。
不知道参数如何设置，请大家指导一下
<?xml version="1.0" encoding="utf-8"?>
<sender-config>
   <sender id="weixin" url="http://XXXX:8082/serviceuser/messagePush/alarmWeixin" type="post" successCode="200" batchSend="true">
      <par id="domain=${domain}"/>
      <par id="email=${receiver}"/>
      <par id="title=${title}"/>
      <par id="content=${content}"/>
      <par id="exception=${name}"/>
   </sender>
</sender-config>

例如这里exception=${name} 如何写能传入堆栈信息

**Comment by wangyapu** [comment]
告警是无法配置异常堆栈内容的，可以配置异常名称。
