### ISSUE TITLE
给个关于app.name的建议

### ISSUE THREAD

**Issue by tzxylao** [dianping/cat#1788]
app.name一定要从app.properties里取，一定要配这样个文件不觉的很麻烦吗，再给它添加个途径从环境变量里取不也是很好吗？比如说我现在有很多个子系统，需要添加Cat服务，现在我需要给每个子系统配上app.properties文件重新打包上传，如果使用环境变量我可以基于大家都依赖的读取配置jar包（比如我们用的apollo）读取过来放入环境变量不就可以统一管理了

**Comment by tzxylao** [comment]
还有客户端的client.xml文件，为什么要从文件取ip和端口地址？是历史遗留问题吗？这样导致的结果是一旦我的服务器地址发生变动，我就要该每个客户端的文件，而我的客户端分散在很多机器上很多怎么办呢

**Comment by xiehongji** [comment]
我这边cat是使用docker的方式，client.xml使用挂载的方式，客户端和服务端使用的是同一个client.xml目前没这个问题，不过确实不够友好，开发时，不方便

**Comment by Lovnx** [comment]
客户端优先不是连client.xml里面的地址，客户端先会轮询client.xml里面的地址端口，获取routers信息，这个routers信息才是客户端的首选连接方式，也就是我们只要保证client.xml里面至少有一个正确的服务端地址就行了。。。

**Comment by Lovnx** [comment]
这样服务端扩展后就不用去改client.xml了。。。

**Comment by youyong205** [comment]
一般情况，这类选择是综合了开发、运维以及未来面临大规模集群的运营治理的综合选择。

在规模较小的时候，可以根据实际需要做一些修改。
