### ISSUE TITLE
HeartBeat中没有如下图的信息

### ISSUE THREAD

**Issue by tzxylao** [dianping/cat#1789]
![image](https://user-images.githubusercontent.com/11553212/62695760-888e2600-ba09-11e9-8eaa-3cafb5720aec.png)
这个信息没有任何数据，这是需要自己扩展的接口吗？如果需要自己扩展，有参考例子或文档吗？

**Comment by kevinWuqisheng** [comment]
没有历史数据，解决了么？ @tzxylao

**Comment by youyong205** [comment]
这个要配置cat-filter吧。
