### ISSUE TITLE
如何配置监控每个服务状态？

### ISSUE THREAD

**Issue by luffyace** [dianping/cat#1793]
是否可以配置每一个服务的状态？比如一个机器上部署了多个服务器A，能否监控到每个服务A的健康状态？并且报警

**Comment by youyong205** [comment]
首先cat并不支持这种部署模式，一台机器部署多个domain相同的应用。
健康状态监控一般是使用，系统监控比如说faclon-agent方式来做。未来cat也会提供类似能力。
