### ISSUE TITLE
Cat支持接入grafana么？

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1795]
Cat支持和grafana整合使用吗？可视化展示数据

**Comment by spenxu** [comment]
我们是自己写exporter,通过prometheus pull 收集，然后在grafana 展示

**Comment by jialinsun** [comment]
可以进行一些二次开发，开源版本是不支持的。开发一个数据来源引擎，应该就是你们现在的做法。

**Comment by zyklon2** [comment]
没有直接支持，需二次开发，定制关注数据的搜集
