### ISSUE TITLE
ExceptionAlert&FrontEndExceptionAlert整点告警功能失效

### ISSUE THREAD

**Issue by MrCoderYu** [dianping/cat#1803]
ExceptionAlert&FrontEndExceptionAlert整点时刻出现异常之后告警功能失效

**Comment by MrCoderYu** [comment]
因为对于整点的异常数据如果用当前时间（整点01分钟）减2分钟会变为上一小时时段（上一小时59分钟），这样获取TopReport得到上一时段数据，会导致整点00分钟异常告警丢失

**Comment by youyong205** [comment]
已经已经有pr fix过这个case
