### ISSUE TITLE
进行rest风格url转换的算法

### ISSUE THREAD

**Issue by guozhenjiang01** [dianping/cat#1807]
为何在判断是否是数字的时候
1，还,要考虑'.'和','?
2，'-'是因为指数表示法吗？
可否举几个例子

**Comment by jialinsun** [comment]
具体是指哪部分逻辑？可以描述更加清楚一些吗？CatFilter里的逻辑？

**Comment by jialinsun** [comment]
没太明白，好像没有这个逻辑，能具体发下判断逻辑部分吗？
