### ISSUE TITLE
项目能正常启动，但是启动时有空指针

### ISSUE THREAD

**Issue by abelyliu** [dianping/cat#1809]
在cat log内有如下内容
`[08-27 14:59:07.055] [ERROR] [CatLogger] error when connect cat server config url http://10.3.1.231:8080/cat/s/router?domain=xxx&ip=172.16.1.247&op=xml&env=unknown&hostname=test-video-454754860-f9lgh`，调试看到，实际上异常地方是DefaultClientConfigService.refreshInnerConfig中
`boolean multiInstances = Boolean.parseBoolean(routerConfig.findProperty("multiInstances").getValue());`中routerConfig并没有multiInstances。

这个是客户端请求服务端返回的结果，并没有multiInstances
```xml
<?xml version="1.0" encoding="utf-8"?>
<property-config>
	<property id="startTransactionTypes" value="Cache.;Squirrel." />
	<property id="matchTransactionTypes" value="SQL" />
	<property id="block" value="false" />
	<property id="routers" value="10.3.1.231:2280;" />
	<property id="sample" value="1.0" />
</property-config>
```

在重试时，此时并不进入if，也不会重新配置
![image](https://user-images.githubusercontent.com/12029471/63821165-85d67f00-c97e-11e9-962a-9ba04c9341a3.png)。

本人的疑问是这样启动会不会导致某些配置无法生效。

**Comment by youyong205** [comment]
这个没有关系的，没有返回，使用默认false
