### ISSUE TITLE
没人发现delta 类型的心跳告警永远告不出来吗

### ISSUE THREAD

**Issue by spenxu** [dianping/cat#1810]
heartbeat 告警 只要是delta类型的都出不来，看了一下代码。
逻辑是取下一分钟的值减去上一分钟的值，但是因为取报表的时间窗口是开区间导致取值永远少了一个值，比如持续时间选2分钟，那么只会取两分钟的报表，所以最后计算的delta值只有一个。

**Comment by ZaynJiang** [comment]
试过了，心跳告警确实出不来

**Comment by 1978625177** [comment]
在后面版本我们修复一下
