### ISSUE TITLE
下载的项目，在client模块下，缺少import com.dianping.cat.configuration.client.entity.Domain;

### ISSUE THREAD

**Issue by liuyueting** [dianping/cat#1811]
下载的项目确实import com.dianping.cat.configuration.client.entity.Domain;无法启动

**Comment by jialinsun** [comment]
重新下载更新下cat-client版本呢？这个类是本身就在代码里的，不需要外部依赖

**Comment by youyong205** [comment]
mvn eclipse:eclipse 会生成一些自动的代码。
