### ISSUE TITLE
dubbo已经到2.7了   麻烦cat监控能否也更新下，已经变成apache工程了

### ISSUE THREAD

**Issue by chenquanzhen** [dianping/cat#1812]

**Comment by xiehongji** [comment]
下载好源码，进入对应dubbo的源码部分，将alibaba的包名改为apache的包名，然后重新打包，上传到私服，就可以使用了，我这边最近刚接入apache的dubbo，有疑问可以一起探讨qq 3233268172

**Comment by youyong205** [comment]
这个有兴趣提交另外一个PR吧。dubbo的高版本埋点。
很多人也用低版本，直接改也不太合适。
