### ISSUE TITLE
com.dianping.cat.analyzer.EventAggregator类中的getDomain方法实现问题

### ISSUE THREAD

**Issue by kai161** [dianping/cat#1814]
在 com.dianping.cat.analyzer.EventAggregator类中getDomain 源码如下：
   public String getDomain(MessageTree tree) {
		return Cat.getManager().getDomain();
}

这个方法是否应该使用 tree的domain，即：tree.getDomain()

**Comment by jialinsun** [comment]
其实是一样的，都可以
