### ISSUE TITLE
java客户端，idea显示有方法未找到。

### ISSUE THREAD

**Issue by CatchTheDog** [dianping/cat#1817]
java客户端导入到idea,显示有方法未找到。
![TIM图片20190910164509](https://user-images.githubusercontent.com/38939831/64598536-7b8a9b00-d3ea-11e9-90b7-25b1ea0663e4.png)

**Comment by Lovnx** [comment]
mvn idea:idea

**Comment by CatchTheDog** [comment]
> mvn idea:idea

在查看了文档之后解决了。谢谢及时回复。
