### ISSUE TITLE
cat的home模块为什么吧很多报表视图注释掉了

### ISSUE THREAD

**Issue by LesterDong** [dianping/cat#1818]
在看cat 源码发现home模块张的home.jsp还有home.tag文件中有很多结构比如service、Databse、Cache、Matrix、offline等模块都被注释掉了，还有Document里边很多页面链接都是被注释的，想知道原因，这块如果放开的话，能用么

**Comment by jialinsun** [comment]
有些模块去掉了，后续会有新的版本出来。
