### ISSUE TITLE
通过CatFilter无法生成多个分布式系统相互调用对应的分布式消息树

### ISSUE THREAD

**Issue by mnmlist** [dianping/cat#1819]
通过CatFilter无法生成多个分布式系统相互调用对应的分布式消息树
-------

![image](https://user-images.githubusercontent.com/5961090/65031773-742c3a00-d974-11e9-9e00-97d8d917f920.png)

![image](https://user-images.githubusercontent.com/5961090/65031840-9756e980-d974-11e9-9e3c-c1640de725b2.png)

- 分布式消息树【一台机器调用另外一台机器】
![image](https://user-images.githubusercontent.com/5961090/65031661-362f1600-d974-11e9-90d7-6cd6c2e53b77.png)

**Comment by zyklon2** [comment]
可通过logRemoteCallClient/logRemoteCallServer进行埋点，具体参考integration中相关组件埋点；
