### ISSUE TITLE
增加对 kubernetes 的支持

### ISSUE THREAD

**Issue by k0ngk0ng** [dianping/cat#1820]
希望能增加对kubernetes的支持
目前CAT服务端绑定IP在k8s环境中比较难部署，也不方便扩容

**Comment by wangyapu** [comment]
目前CAT暂时无法方便地使用k8s管理，感谢你的建议，会不断完善和优化。

**Comment by lovewuqiang** [comment]
> 希望能增加对kubernetes的支持
> 目前CAT服务端绑定IP在k8s环境中比较难部署，也不方便扩容

你用k8s部署好cat了吗？cat在k8s中部署有什么问题？
