### ISSUE TITLE
本地运行测试用例 报表结果不稳定

### ISSUE THREAD

**Issue by LesterDong** [dianping/cat#1824]
本地运行test case , Cat.logMetricForCount 结束前线程也睡了5s 但是可视化报表有时候能出来指标 有时候指标出不来 这个什么问题？

**Comment by LesterDong** [comment]
`@Test
    public void testMetric() {

        for (int i = 0; i < 50000; i++) {
            Cat.logMetricForCount("orderDemo2");
        }
        this.sleep();
    }`

代码就上边的，本地跑test case  服务端是部署到另外一台机器

**Comment by youyong205** [comment]
后端报表特别是metric 会延迟一分钟的。你这个sleep时间比较短。
