### ISSUE TITLE
数据库报表问题

### ISSUE THREAD

**Issue by xiehongji** [dianping/cat#1831]
![image](https://user-images.githubusercontent.com/47129889/65854120-455b8e00-e38e-11e9-88f9-290bc5d02253.png)
请问一下，这种内容里面看起来是乱码，正常吗，切换到历史模式完全没有数据

**Comment by Lovnx** [comment]
正常的，报表数据在数据库就是二进制格式存的

**Comment by xiehongji** [comment]
好的，谢谢，不过更头大了，切换到历史模式，没有任何数据

**Comment by Lovnx** [comment]
没有配置job-machine吧
