### ISSUE TITLE
3.0的客户端请推送到maven仓库

### ISSUE THREAD

**Issue by RickJou** [dianping/cat#1833]
3.0已经放出来了,java client也推上去呗

**Comment by Lovnx** [comment]
请查收：
<dependency>
    <groupId>com.dianping.cat</groupId>
    <artifactId>cat-client</artifactId>
    <version>3.0.0</version>
</dependency>

**Comment by Hunterfish** [comment]
试了几个仓库地址，下不下来

**Comment by RickJou** [comment]
https://github.com/dianping/cat/blob/v3.0.0/cat-client/src/main/java/com/dianping/cat/message/internal/DefaultMessageProducer.java
示例中有 public void logTrace(String type, String name, String status, String nameValuePairs) 这个方法

在私服:http://unidal.org/nexus/content/repositories/releases/
中下载的cat3.0.0总则没有这个方法

能不能把3.0.0推到maven 中央仓库呀

**Comment by youyong205** [comment]
我印象中已经有人推送上去了

**Comment by Sod-Momas** [comment]
您好,
使用 maven 管理依赖的时候发现无法从中央仓库下载到 Cat 依赖

```xml
<dependencies>
    <!-- https://mvnrepository.com/artifact/com.dianping.cat/cat-client -->
    <dependency>
        <groupId>com.dianping.cat</groupId>
        <artifactId>cat-client</artifactId>
        <version>3.0.0</version>
    </dependency>
</dependencies>
```

注意到提示重定向, 于是添加了 unidal 仓库, 则可以成功下载依赖.

```xml
<dependencies>
    <!-- https://mvnrepository.com/artifact/com.dianping.cat/cat-client -->
    <dependency>
        <groupId>com.dianping.cat</groupId>
        <artifactId>cat-client</artifactId>
        <version>3.0.0</version>
    </dependency>
</dependencies>

<repositories>
    <repository>
        <id>uni</id>
        <url>http://unidal.org/nexus/content/repositories/releases/</url>
    </repository>
</repositories>

```

也就是说这个项目不存在了 mave center, 请问未来有推上中央仓库的计划吗?
