### ISSUE TITLE
请教下，如果服务端节点消费扛不住，要新增节点了，不想改客户端的client.xml的ip,这个怎么做呢

### ISSUE THREAD

**Issue by ZaynJiang** [dianping/cat#1835]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Lovnx** [comment]
你可以看看客户端的源码，其实client.xml里面的节点并不是需要客户端去创建TCP的机器，而是优先会去拉取集群router配置的机器，新增机器其实无妨，只要能保证client.xml配置里面至少一个机器可用就行了

**Comment by ZaynJiang** [comment]
好的，谢谢
