### ISSUE TITLE
log4j集成配置 locationAppender 是哪儿来的

### ISSUE THREAD

**Issue by LesterDong** [dianping/cat#1838]

**Comment by wangyapu** [comment]
locationAppender？lib/java新版客户端支持log4j、log4j2、logback的错误日志收集。
![image](https://user-images.githubusercontent.com/5910252/67611119-f6a4e680-f7c9-11e9-8187-a63e20ce65ab.png)

**Comment by zyklon2** [comment]
如上回答，cat/cat-client/src/main/java/com/dianping/cat/log4j/
下默认实现，以及cat/integration/ 下相关扩展实现；
