### ISSUE TITLE
请教下，客户端同一个节点部署多个相同的应用，这样收集的数据是不是累加的

### ISSUE THREAD

**Issue by ZaynJiang** [dianping/cat#1842]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jialinsun** [comment]
是的，会出现这样的问题。一个节点下不建议部署多个相同的应用。
