### ISSUE TITLE
咨询一下,新加了一个节点,结果这个新节点不管是历史模式还是小时模式,都比其他的少5天

### ISSUE THREAD

**Issue by xieyang134** [dianping/cat#1843]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xieyang134** [comment]
而且这个5天还在不停的延长,今天变成6天了

**Comment by youyong205** [comment]
你这个看看新加的节点时钟问题吧。既然你之前部署都OK，新加一个检查比较下环境
