### ISSUE TITLE
cat的统计数据怎样导出到自定的文件中呢，比如xml json，这样可以利用cat的数据去做一些统计的事情

### ISSUE THREAD

**Issue by william-lg** [dianping/cat#1844]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Lovnx** [comment]
在CAT的URL后面加上参数forceDownload=json 或者 forceDownload=xml 可以看到当前页面的数据模型

**Comment by william-lg** [comment]
感谢
