### ISSUE TITLE
cat报no report builder for type错误

### ISSUE THREAD

**Issue by ljyrains** [dianping/cat#1845]
**Describe the bug**
每天凌晨0时10分时的定时任务报了3个错，
no report builder for type:appDatabasePruner ,metricGraphPruner ,webDatabasePruner 
其中一个详细错误信息：
t01:10:42.629	Task	appDatabasePruner		
  E01:10:42.629	RuntimeException	java.lang.RuntimeException	ERROR	java.lang.RuntimeException: no report builder for type: appDatabasePruner 
at com.dianping.cat.report.task.ReportFacade.builderReport(ReportFacade.java:55) 
at com.dianping.cat.report.task.DefaultTaskConsumer.processTask(DefaultTaskConsumer.java:79) 
at com.dianping.cat.report.task.TaskConsumer.run(TaskConsumer.java:90) 
at java.lang.Thread.run(Thread.java:748) 
at org.unidal.helper.Threads$RunnableThread.run(Threads.java:294) 
T01:10:42.629	Task	appDatabasePruner	 	0.35ms Task[consumer: 192.168.3.72, count: 0, creation-date: 2019-10-15 01:03:00.0, end-date: null, end-limit: 0, failure-count: 0, id: 184225, key-id: 184225, producer: 192.168.3.72, report-domain: cat, report-name: appDatabasePruner, report-period: 2019-10-14 00:00:00.0, start-date: Tue Oct 15 01:10:42 CST 2019, start-limit: 0, status: 2, task-type: 1]

**To Reproduce**
使用docker部署的cat，参照dockerfile进行部署的，唯一的改动就是java1.7升为1.8，部署成功
服务端配置完后，每天都会报错

**Expected behavior**
文档里没找到有关这个相关的配置
看了下报错的位置：
com.dianping.cat.report.task.ReportFacade
唯一出现关键字的类：
com.dianping.cat.Constants#APP_DATABASE_PRUNER
在任务初始化的地方用到该关键字：
com.dianping.cat.consumer.state.StateDelegate#createHourlyTask
目测是相关的TaskBuilder的实现类缺失（其他任务都有对应的TaskBuilder的实现类）
请问，要如何解决？

**Screenshots**
![image](https://user-images.githubusercontent.com/5886496/66994147-6565ae00-f0ff-11e9-83c2-fc0eee5f1aa4.png)

**Comment by jialinsun** [comment]
在创建任务的地方，把这个APP_DATABASE_PRUNER的任务删除，不要添加到task里就可以了。这个其实不太需要。

**Comment by ljyrains** [comment]
是这3个任务都不需要吗？
appDatabasePruner ,metricGraphPruner ,webDatabasePruner
