### ISSUE TITLE
DefaultMessageTree toString,调用 buf = ex.encode(this); 使用  UnpooledByteBufAllocator.DEFAULT.buffer分配内存，toString时候没有释放堆内存,会引起内存泄漏。

### ISSUE THREAD

**Issue by braveMind** [dianping/cat#1849]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 1978625177** [comment]
具体代码片段能贴一下吗

**Comment by 1978625177** [comment]
新版本应该不存在该问题啦
