### ISSUE TITLE
告警无效问题

### ISSUE THREAD

**Issue by xiehongji** [dianping/cat#1854]
![image](https://user-images.githubusercontent.com/47129889/67665134-10018a80-f9a4-11e9-8a65-666bb081d607.png)
这样子配置的话，告警都收不到，告警没触发，但是改为在default标签内内配置就可以收到告警，为什么
![image](https://user-images.githubusercontent.com/47129889/67665282-64a50580-f9a4-11e9-91aa-08078499b9aa.png)

**Comment by Lovnx** [comment]
看下源码吧

**Comment by jfly0902** [comment]
可以加个好友吗？最近在用cat，公司只能用docker部署，遇到了些问题可以跟你请教吗？方便的话可以加下我微信17607187792，谢谢啦☺️☺️☺️
