### ISSUE TITLE
在使用Java的CAT客户端时，怎么加载自己实现了ClientConfigManager接口的类？

### ISSUE THREAD

**Issue by heihaozi** [dianping/cat#1855]
在使用Java的CAT客户端时，自己实现了ClientConfigManager接口的类，目的是灵活的加载配置，比如：从Apollo中读取。原来的DefaultClientConfigManager类是通过components.xml配置注入到Plexus容器中的。除了修改CAT客户端的源码，有没有其他方法可以把DefaultClientConfigManager实例替换成自己实现的类的实例？谢谢

**Comment by jialinsun** [comment]
最新版的cat-client已经去除了plexus的依赖，完全单例方式来写的。可以尝试下。

**Comment by liutaihua** [comment]
maven里面cat-client 3.0.0的依然还是依赖plexus的默认DefaultClientConfigManager实现？
