### ISSUE TITLE
cat埋点没有按照文档上来操作没有实现

### ISSUE THREAD

**Issue by hemingrujiuhao** [dianping/cat#1858]
您好！按照文档上的操作，我的spring boot项目已经接入cat了，当我集成springboot以及log4j埋点的时候。cat上并没有显示，请问可能是什么原因造成的呢。
![1572447252(1)](https://user-images.githubusercontent.com/36373574/67869739-d7f77480-fb68-11e9-896f-4c539662ce0a.jpg)
![1572447322(1)](https://user-images.githubusercontent.com/36373574/67869760-dcbc2880-fb68-11e9-97f2-b3c44e2e8ff9.jpg)
![1572447416(1)](https://user-images.githubusercontent.com/36373574/67869782-e04faf80-fb68-11e9-81ff-c29fc4d8356c.jpg)

**Comment by q594054294** [comment]
我的问题和你一样   我的服务端什么也没没有显示，我还集成了mybatis也没用

**Comment by hemingrujiuhao** [comment]
你现在解决了吗

**Comment by youyong205** [comment]
log4j相关cat仅仅接受error的错误

**Comment by youyong205** [comment]
也没看到你代码里面有log4j相关埋点，log4j相关错误是在problem报表，并不是在transaction报表。
