### ISSUE TITLE
如何修改 /data/applogs/cat,/data/appdatas/cat,是否可以做成配置文件

### ISSUE THREAD

**Issue by MoneyHacker** [dianping/cat#1860]
1.如何修改 /data/applogs/cat,/data/appdatas/cat目录？
2.是否可以做成配置文件

**Comment by Lovnx** [comment]
可以自己改客户端源码

**Comment by wuQAQ** [comment]
vscode全局搜索你就知道怎么改了

**Comment by Likenttt** [comment]
同问。Macos Catalina 后 `/` 无法创建目录了，必须要修改到其他路径

**Comment by youyong205** [comment]
建议自己修改源码。

**Comment by xgqfrms-GitHub** [comment]
# shit docs

![image](https://user-images.githubusercontent.com/18028768/70969853-d4e42380-20d7-11ea-8aa1-4b2adc712e36.png)

**Comment by xgqfrms-GitHub** [comment]
# solution

![image](https://user-images.githubusercontent.com/18028768/70970789-46bd6c80-20da-11ea-9e82-68f1f36ffc2a.png)
