### ISSUE TITLE
如果服务器宕机了，会对客户端有影响吗？

### ISSUE THREAD

**Issue by MoneyHacker** [dianping/cat#1862]
如果服务器宕机了，会对客户端有影响吗？
比如：1.造成客户端OOM
           2.耗光TCP链接，造成业务服务不可用？

**Comment by jialinsun** [comment]
服务器宕机，会将上报通道切换到下一台备用通道里，不会造成客户端OOM。TCP链接，最多建立2个，不会耗光。
