### ISSUE TITLE
Cat的点击跳转后的logView消息跟原始报表内容不匹配

### ISSUE THREAD

**Issue by jcb123456** [dianping/cat#1867]
经常从problem报表那边error类型的SampleLinks列表里面点击跳转后，跳转到一个并没有报错其他不相关的logView。
![cat](https://user-images.githubusercontent.com/16344901/68261364-da7f3000-007a-11ea-844b-4719f3d14d0d.png)

**Comment by jialinsun** [comment]
看起来是消息id串掉了的情况，可以检查下/data/appdatas/cat/目录下是否可写，是否有一个XXX.mark的文件，这个文件是用来记录消息id的。

**Comment by youyong205** [comment]
一台机器存在有多个相同的domain应用
