### ISSUE TITLE
python 没有心跳信息

### ISSUE THREAD

**Issue by LostSymbol** [dianping/cat#1870]
python web应用 flask+gunicorn

环境

    OS: Cetos7.4
    Browser firefox
    Version cat-sdk==3.1.2
    python 3.7.4

问题：没有心跳信息

![image](https://user-images.githubusercontent.com/24261160/68378169-9b3e0580-0186-11ea-9c60-11e6ffd4fd48.png)

客户端log日志一直在重复这段信息

**Comment by youyong205** [comment]
python 版本没有实现心跳。
