### ISSUE TITLE
cat服务端支持微服务的部署方式吗

### ISSUE THREAD

**Issue by MrWnn** [dianping/cat#1872]
### **背景**
希望在k8s集群中以微服务的方式部署cat：监控k8s集群上的微服务

### **思路**
- 按TCP/2280 TCP/8080把cat服务区分为两个服务:
 1. cat-api
 1.pod=cat-api:2280 
 2.svc=cat-api:2280
 2. cat-proxy 
 1.pod=cat-proxy:8080
 2.svc=cat-proxy:8080

- 配置client.xml
 1. ```<server ip="cat-api" port="2280"/>```
 2. ```<server ip="cat-proxy" http-port="8080"/>```
- 配置ingress: 
 1. DomainName =>cat-proxy:8080
- 访问 DomainName

### **遇到的问题**
- 访问DomainName/cat/s/config?op=routerConfigUpdate 
1. 编辑配置=>cat-api:2280
2. 点击提交，提示操作失败
3. 点击重算路由，返回false
- 访问DomainName/cat/s/config?op=serverConfigUpdate
1. 编辑配置=>cat-proxy:8080
2. 编辑配置=>hdfs:cat-proxy
3. 点击提交，提示操作失败

### **提问**
- 目前cat服务端是否支持这种部署方式？
- 不支持的话，有没有别的思路呢
- 支持的话，有没有大佬帮忙查漏补缺。。感谢万分

**Comment by MrWnn** [comment]
最后靠nginx解决了。

**Comment by lizhiwei1025** [comment]
> 最后靠nginx解决了。

大佬，麻烦给讲下思路，我最近也在做这方面的调研
