### ISSUE TITLE
客户端路由更新提交失败

### ISSUE THREAD

**Issue by ljp-1119** [dianping/cat#1873]
我安装说明文档配置，启动tomcat之后，一直报提交失败，不知道 咋回事儿
![360截图20191112101927907](https://user-images.githubusercontent.com/34266908/68636315-1a8c5a00-0536-11ea-9ae3-d6748135a89a.jpg)

**Comment by jialinsun** [comment]
后端有一个提交后的validate操作，建议看下那部分代码的逻辑，应该是配置有些问题，可能是需要配置default集群。

**Comment by youyong205** [comment]
这个还有一个可能就是以及xml格式问题，3.0的官方文档xml格式你在检查下。

**Comment by chenli2017** [comment]
官方文档的datasources.xml中<connectionProperties>这一行不对，改一下，就可以了。

**Comment by Timilian** [comment]
一样的配置，仅ip不同，部署的两个服务，一个提交成功，一个提交失败
`<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="10.9.0.1" backup-server-port="2280">
   <default-server id="10.9.0.1" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="默认" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="10.9.0.1"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="10.9.0.1" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>
`

**Comment by Timilian** [comment]
我的已解决，是mysql密码带有‘&’，导致cat初始化配置到数据库时失败，改掉密码更新datasources.xml后部署成功。
