### ISSUE TITLE
客户端路由配置问题

### ISSUE THREAD

**Issue by HeRui2812** [dianping/cat#1874]
服务端部署在49.233.*.*这个ip上面，客户端在另外一台机器上面
客户端配置
`<?xml version="1.0" encoding="utf-8"?>
<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
    <servers>
        <server ip="49.233.*.*" port="2280" http-port="8080"/>
    </servers>
</config>
`

客户端路由配置：
`<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="172.21.0.6" backup-server-port="2280">
   <default-server id="172.21.0.6" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="默认" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="172.21.0.6"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="172.21.0.6" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>
`
172.21.0.6 是内网IP

把172.21.0.6替换为49.233.*.*服务机ip就可以，但是面板上面显示 `出问题CAT的服务端:[49.233.*.*]`错误；
这个配置需要怎么修改呢？望解答

**Comment by HeRui2812** [comment]
服务端部署在49.233.*.*这个ip上面，客户端在另外一台机器上面
客户端配置
```
<?xml version="1.0" encoding="utf-8"?>
<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
    <servers>
        <server ip="49.233.*.*" port="2280" [http-port="8080"/>](url)
    </servers>
</config>
```

客户端路由配置：
```
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="172.21.0.6" backup-server-port="2280">
   <default-server id="172.21.0.6" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="默认" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="172.21.0.6"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="172.21.0.6" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>
```
172.21.0.6 是内网IP

把172.21.0.6替换为49.233.*.*服务机ip就可以，但是面板上面显示 `出问题CAT的服务端:[49.233.*.*]`错误；
这个配置需要怎么修改呢？望解答

**Comment by youyong205** [comment]
这个问题，在FAQ里面有。可能是你这台机器多个网卡导致。
你看下cat transaction report里面自动识别的IP是什么，写这个即可。
出问题cat服务端，这个就是提示IP识别不对，不影响消息收发和监控。

**Comment by chenkang1990** [comment]
我遇到一样的问题，也是将客户端路由修改之后出现”出问题CAT的服务端:[10.46.208.xx]“;
而且改完之后，cat的报表就出不来了，原来是：
<domain id="cat">
      <group id="default">
         <server id="127.0.0.1" port="2280" weight="1.0"/>
      </group>
   </domain>
