### ISSUE TITLE
 Java进程内的调试分析工具

### ISSUE THREAD

**Issue by useraddZYB** [dianping/cat#1876]
分布式apm已经很成熟，方案很完善了；但是进程内，那些更多的非微服务架构的业务系统也需要得到帮助，也需要apm
https://github.com/useraddZYB/time-tracker
贡献一份力量，这工具极大的提高了我和我的团队查问题的效率及性能分析，希望更多人获益
是的，这是借楼打个广告

**Comment by youyong205** [comment]
学习学习
