### ISSUE TITLE
历史报表数据量过大问题

### ISSUE THREAD

**Issue by MrCoderYu** [dianping/cat#1890]
长期运行后，历史小时/天/周/月报表数据存于MySQL中，数据量过大，目前有没有解决方案？

**Comment by jialinsun** [comment]
可以尝试将报表按照ip拆分，每个ip存一条记录。相当于拆分了报表大小。
最简单做法就是将mysql的max-packet-size设置大一些，数据库可以插入更大的数据。

**Comment by zhangzc0419** [comment]
看历史数据是否有价值，可以定期清理归档，另外优化项目中的埋点，有时候打的一些event事件其实没有统计或者监控作用，增加了额外的报表内容，可以改成使用event或者transaction中的addData

**Comment by MrCoderYu** [comment]
> 可以尝试将报表按照ip拆分，每个ip存一条记录。相当于拆分了报表大小。
> 最简单做法就是将mysql的max-packet-size设置大一些，数据库可以插入更大的数据。

这样做了分表只是单张表的大小改变了，并不能从本质解决问题，整体大小不变，长期来看还是会有整体数据过大单张表过大的问题

**Comment by MrCoderYu** [comment]
> 看历史数据是否有价值，可以定期清理归档，另外优化项目中的埋点，有时候打的一些event事件其实没有统计或者监控作用，增加了额外的报表内容，可以改成使用event或者transaction中的addData

嗯嗯，目前也是打算仅保留近期的报表数据，历史数据直接清掉。另外优化这个事效果其实是有限的，问题还是会存在

**Comment by youyong205** [comment]
内部做法目前是多个数据库分片来做的。一段时间的数据存储到不同的mysql里面。

**Comment by MrCoderYu** [comment]
> 内部做法目前是多个数据库分片来做的。一段时间的数据存储到不同的mysql里面。

大佬 再请问下分片方案就是把数据存储到多台数据库上吧，这样需要代码上做分片吧？时间长了是不是还会有满的一天？是不是可以按period做分区，删除历史分区的数据？

**Comment by youyong205** [comment]
内部就是period来做的，period来映射到不同的mysql数据库实例。
分区其实还是一个库，可以方便做表的删除。

**Comment by MrCoderYu** [comment]
> 内部就是period来做的，period来映射到不同的mysql数据库实例。
> 分区其实还是一个库，可以方便做表的删除。

映射到不同的MySQL数据库实例 相当于把单库改为多库了，这样多库数据量多了还得有删除的操作吧。
