### ISSUE TITLE
里面的domain是怎么创建关联的？

### ISSUE THREAD

**Issue by luyufa** [dianping/cat#1892]
cat服务端搭建完成，成功启动后可以登录进入后台管理界面进行操作，但是无法创建新的项目、以及domain无法关联

客户端代码里已添加按文档配置完成，启动也没任何报错。java萌新 求教

**Comment by youyong205** [comment]
只要客户端埋点成功了，你按照客户端集成文档操作即可，就会自动上报数据，后台项目也会自动新增的。
