### ISSUE TITLE
cat客户端是否支持开关，配置启用cat或禁用cat

### ISSUE THREAD

**Issue by ZaynJiang** [dianping/cat#1894]

**Comment by zhangzc0419** [comment]
client.xml里有个enabled属性配置，可参考
`config.xsd和ClientConfig`

**Comment by ZaynJiang** [comment]
> client.xml里有个enabled属性配置，可参考
> `config.xsd和ClientConfig`

![image](https://user-images.githubusercontent.com/11373799/70213257-db87a800-1773-11ea-8c2b-2f6e6750bf6d.png)
这个ip是啥意思呢
