### ISSUE TITLE
构建消息内容空指针 java.lang.NullPointerException

### ISSUE THREAD

**Issue by 349443767** [dianping/cat#1896]
java.lang.NullPointerExceptionat com.dianping.cat.consumer.event.model.transform.DefaultXmlBuilder.buildXml(DefaultXmlBuilder.java:66)at com.dianping.cat.report.page.event.service.LocalEventService.filterReport(LocalEventService.java:60)at com.dianping.cat.report.page.event.service.LocalEventService.buildReport(LocalEventService.java:82)at com.dianping.cat.report.service.LocalModelService.getReport(LocalModelService.java:95)at com.dianping.cat.report.page.model.Handler.handleOutbound(Handler.java:89)at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.unidal.lookup.util.ReflectUtils.invokeMethod(ReflectUtils.java:49)at org.unidal.web.mvc.lifecycle.DefaultOutboundActionHandler.handle(DefaultOutboundActionHandler.java:29)at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleOutboundAction(DefaultRequestLifecycle.java:111)at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handleRequest(DefaultRequestLifecycle.java:188)at org.unidal.web.mvc.lifecycle.DefaultRequestLifecycle.handle(DefaultRequestLifecycle.java:63)at org.unidal.web.MVC.service(MVC.java:90)at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at com.dianping.cat.report.view.DomainFilter.doFilter(DomainFilter.java:105)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at com.dianping.cat.system.page.permission.PermissionFilter.doFilter(PermissionFilter.java:94)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:439)at com.dianping.cat.servlet.CatFilter$CatHandler$3.handle(CatFilter.java:236)at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)at com.dianping.cat.servlet.CatFilter$CatHandler$4.handle(CatFilter.java:329)at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)at com.dianping.cat.servlet.CatFilter$CatHandler$2.handle(CatFilter.java:219)at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)at com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:127)at com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:437)at com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:65)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)at java.lang.Thread.run(Thread.java:745)
-- | -- | --

集群情况
10.168.1.124
10.168.1.125
10.168.1.126

CAT版本3.0.0

出问题的机器为10.168.1.125，集群服务端配置和路由配置均按文档配置，异常开始出现的时间都在整点，同时该台还会存在java.io.EOFException异常。

![image](https://user-images.githubusercontent.com/8485782/71573318-37004800-2b1e-11ea-8088-f4a027326069.png)

![image](https://user-images.githubusercontent.com/8485782/71573232-b9d4d300-2b1d-11ea-967e-0815b17086be.png)

**Comment by 1978625177** [comment]
现在问题还存在吗
