### ISSUE TITLE
macOS catalina版本（v:10.15.1）/路径为只读路径，无法创建/data/appdatas/cat，导致本机调试cat失败

### ISSUE THREAD

**Issue by wukongcxy** [dianping/cat#1901]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhangzc0419** [comment]
sudo mount -uw /

**Comment by xgqfrms-GitHub** [comment]
# which relative path it is?

> `/data/appdatas/cat/client.xml` 这个是相对路径，是相对当前 app.js ；还是系统 root 下的路径

![image](https://user-images.githubusercontent.com/18028768/70969599-1d4f1180-20d7-11ea-8d1c-948410c0d7a9.png)

**Comment by xgqfrms-GitHub** [comment]
# can not find this file

![image](https://user-images.githubusercontent.com/18028768/70969885-f218f200-20d7-11ea-8ac4-8ad999ecc06a.png)

**Comment by Likenttt** [comment]
![image](https://user-images.githubusercontent.com/26034018/70981956-1e8d3800-20f1-11ea-9693-8796ce187791.png)cat默认配置了这个路径，也可以手动设置
![image](https://user-images.githubusercontent.com/26034018/70982097-5dbb8900-20f1-11ea-867a-be47fe4c5d73.png)
你懂的

**Comment by wukongcxy** [comment]
> ![image](https://user-images.githubusercontent.com/26034018/70981956-1e8d3800-20f1-11ea-9693-8796ce187791.png)cat默认配置了这个路径，也可以手动设置
> ![image](https://user-images.githubusercontent.com/26034018/70982097-5dbb8900-20f1-11ea-867a-be47fe4c5d73.png)
> 你懂的

嗯，可以的。多谢
