### ISSUE TITLE
下载源码，cat-core缺import com.dianping.cat.core.config下包

### ISSUE THREAD

**Issue by yuanjh1013** [dianping/cat#1902]
您好！，下载源码后发现，cat-core模块缺com.dianping.cat.core.config。
cat-client模块缺com.dianping.cat.configuration.property 类似的问题好几个，请问什么原因。

**Comment by zhangzc0419** [comment]
需要mvn install一下

**Comment by yuanjh1013** [comment]
idea 环境需求先 mvn idea:idea 生成缺的源码， eclipse 环境 mvn eclipse：eclipse
