### ISSUE TITLE
Application 左侧栏点击全部HTTP Status 500

### ISSUE THREAD

**Issue by imperio-wxm** [dianping/cat#1906]
![image](https://user-images.githubusercontent.com/8111349/71078171-ca9f5380-21c3-11ea-8fdc-2d54aa784b6a.png)

- /cat/r/t?domain=&ip=All&date=2019121818&reportType=day&op=view
![image](https://user-images.githubusercontent.com/8111349/71078204-d854d900-21c3-11ea-9695-b8f4ee171132.png)

- /cat/r/p?domain=&ip=All&date=2019121818&reportType=day&op=view
![image](https://user-images.githubusercontent.com/8111349/71078270-fde1e280-21c3-11ea-8f5e-6284d1f87c02.png)

**Comment by yuanjh1013** [comment]
去日志目录（window通常在运行工程的分区下\data\applogs\cat）下看下日志

**Comment by imperio-wxm** [comment]
@yuanjh1013  
一开始用的tomcat 8.5.x，换成7.x正常
