### ISSUE TITLE
为何日志要放在 /data/appdatas/cat/下而不是 /data/applogs/cat/下？

### ISSUE THREAD

**Issue by nangergong** [dianping/cat#1907]
cat_20191218.log 等日志被放在了/data/appdatas/cat/下而不是 /data/applogs/cat/下
做docker mount的时候不好处理啊
有什么方法可以让日志被放在 /data/applogs/cat/下？

**Comment by jialinsun** [comment]
日志应该是放在 /data/applogs/cat 才对，/data/appdatas/cat/是存放的配置文件等信息或元数据。
