### ISSUE TITLE
error when connect cat server config url

### ISSUE THREAD

**Issue by mhgz321** [dianping/cat#1908]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lymaimei** [comment]
same error

**Comment by jialinsun** [comment]
Maybe cat server hasn't started up yet

**Comment by tayanzhuifeng** [comment]
cat-home3.0.0 的path配置不对，修改Context path为/cat或者将war包名称修改为cat即可。
