### ISSUE TITLE
cat支持应用存活监控吗？

### ISSUE THREAD

**Issue by hanzhihua** [dianping/cat#1913]
问一下，cat支持应用存活监控吗？
谢谢

**Comment by zhangzc0419** [comment]
cat-client每分钟会有一次心跳上报，对应的的transaction type和name是System，Status

**Comment by hanzhihua** [comment]
这个能设置报警，你标准的玩法吗？

**Comment by zhangzc0419** [comment]
> 这个能设置报警，有标准的玩法吗？

就使用transaction告警去配置，Type为System，Name为Status，transaction告警支持最小执行次数的告警，可以看下告警的各个配置项

**Comment by hanzhihua** [comment]
你确认可以这样玩吗？我理解的是，如果节点crash的时候，就不会上报信息，服务端还做做处理吗？比如根据ActiveThread ==0 来判断吗？

**Comment by zhangzc0419** [comment]
> 你确认可以这样玩吗？我理解的是，如果节点crash的时候，就不会上报信息，服务端还做做处理吗？比如根据ActiveThread ==0 来判断吗？

服务端的监控任务不管客户端有没有上报都会执行和计算，具体可以看一下TransactionAlert这个类，当然要根据实际需求来看用什么方式监控

**Comment by ZaynJiang** [comment]
我试过，用心跳跌0和event跌0，无效。提过issue，说是不支持宕机监控

**Comment by jialinsun** [comment]
有心跳指标可以配置跌零告警，比如ActiveThread类似的指标。尝试下。
