### ISSUE TITLE
Transaction的SQL告警配置，比如配置耗时告警，name=All是指任意一个sql的耗时？还是指所有的SQL总的平均耗时呢？

### ISSUE THREAD

**Issue by ZaynJiang** [dianping/cat#1914]

**Comment by zhangzc0419** [comment]
这个Transaction type下所有的平均耗时

**Comment by ZaynJiang** [comment]
> 

> 这个Transaction type下所有的平均耗时

如果我想配值任意一个sql达到阈值就告警，请问这个该怎么配置呢

**Comment by zhangzc0419** [comment]
> > 
> 
> > 这个Transaction type下所有的平均耗时
> 
> 如果我想配值任意一个sql达到阈值就告警，请问这个该怎么配置呢

首先看你怎么埋的点，每个Transaction上报的时候都有一个Type和一个Name
告警都是基于Type和Name来分类
看一下你对应项目的Transaction报表，如果应用对sql埋的点type是SQL 那就配type=SQL,name=ALL，
如果埋的是123456，那就是type=123456，name=ALL

**Comment by ZaynJiang** [comment]
> Name

我的意思是某一个type下，任意个name触发阈值那么就告警，目前是需要一个name一个name配置，而配置all的话，是所有name的均值。

**Comment by ZaynJiang** [comment]
> 

> > > 
> > 
> > 
> > > 这个Transaction type下所有的平均耗时
> > 
> > 
> > 如果我想配值任意一个sql达到阈值就告警，请问这个该怎么配置呢
> 
> 首先看你怎么埋的点，每个Transaction上报的时候都有一个Type和一个Name
> 告警都是基于Type和Name来分类
> 看一下你对应项目的Transaction报表，如果应用对sql埋的点type是SQL 那就配type=SQL,name=ALL，
> 如果埋的是123456，那就是type=123456，name=ALL

我的意思是想要某一个type下的任意name触发阈值就告警，现在需要每个name都配置一遍，如果配置name为all，目前是所有name的均值。

**Comment by ZaynJiang** [comment]
有没有大神解答该问题

**Comment by jialinsun** [comment]
name配置*，语义应该是任意一个name触发阈值就告警。可以尝试下。
