### ISSUE TITLE
管理页面-配置需要多次添加

### ISSUE THREAD

**Issue by orclight** [dianping/cat#1919]
**Describe the bug**
环境：3台机器组成的集群，使用nginx 做负载均衡(域名)

**To Reproduce**
1. 配置页面：点击Config 卡片
2. 配置页面：点击 #项目基本信息页面#
3. 新增：添加项目
4.查询：再次点击#项目基本信息页面#，新添加的项目时有时无
(3台机器中，部分添加成功，部分没有添加，需要重新添加)

**Comment by zyklon2** [comment]
CAT中一些配置的信息会使用一些Manager缓存并定时刷新，在一台机器上配置后数据已经存储，其他机器上Manager刷新数据后就可以展示了；
