### ISSUE TITLE
控制台不能查看当前小时的数据，下一个小时才能看到

### ISSUE THREAD

**Issue by lele123456** [dianping/cat#1921]
控制台不能查看当前小时的数据，下一个小时才能看到，我是在本地运行的，是我配置有问题，还是本身就是这样的，因为我看到cat的简介上是48分钟40秒，基本上看到48分钟38秒数据

**Comment by wangyapu** [comment]
下小时能看到说明数据已经从内存成功持久化到数据库中，当前小时看不到应该是路由没有配置正确。

**Comment by lele123456** [comment]
路由是指客户端路由么，我是按照文档上面配置的

**Comment by lele123456** [comment]
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="192.168.199.187" backup-server-port="2280">
   <default-server id="192.168.199.187" weight="1.0" port="2280" enable="true"/>
   <default-server id="192.168.153.130" weight="1.0" port="2280" enable="true"/>
   <network-policy id="default" title="默认" block="false" server-group="default_group">
   </network-policy>
   <server-group id="default_group" title="default-group">
      <group-server id="192.168.199.187"/>
      <group-server id="192.168.153.130"/>
   </server-group>
   <domain id="cat">
      <group id="default">
         <server id="192.168.153.130" port="2280" weight="1.0"/>
      </group>
   </domain>
</router-config>

**Comment by lele123456** [comment]
@wangyapu 我找到原因了，用了maven上的war包就可以，用最新的代码打包就会出现这个问题，我对比了下发现代码不一致

**Comment by smallze** [comment]
说下我的排查思路，先看服务端和客户端的cat日志，如果正常，看两边时间是否一致，最后排查发现服务端的cat的tomcat进行shutdown时没有将对应java线程杀死，我将所有线程杀死后，重新启动，监控数据及时正常显示
