### ISSUE TITLE
Transaction is confusing in non-blocking thread reuse mode

### ISSUE THREAD

**Issue by zlm0125** [dianping/cat#1924]
**Describe the bug**
Because of the threadLocal, in non-blocking thread reuse mode, the transaction is confusing.
For example, there are two independent tasks, but they are reused by the same thread. In this case, the two transactions are confusing.

**To Reproduce**

**Expected behavior**
I think it should per transaction object store it`s context and decoupled from threadlocal

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zyklon2** [comment]
CAT通过ForkableTransaction解决跨线程问题，主线程forFork创建ForkableTransaction传递到子线程，子线程进行doFork；
ForkableTransaction会使用不同的Context，通过parentMessageId与原消息关联；

**Comment by zlm0125** [comment]
> CAT通过ForkableTransaction解决跨线程问题，主线程forFork创建ForkableTransaction传递到子线程，子线程进行doFork；
> ForkableTransaction会使用不同的Context，通过parentMessageId与原消息关联；

不是父子线程，是线程复用，同一个线程在不同的时间片交替进行多任务

**Comment by LucasDove** [comment]
我的问题与 @zlm0125 可能是一样的。我的需求是，要在一个线程内同时创建多个不同根节点的transaction，各自独立上报。而不是把后面创建的transaction作为之前创建的子节点
