### ISSUE TITLE
home机JVM老年代被打爆

### ISSUE THREAD

**Issue by Lovnx** [dianping/cat#1927]
浮现：应用接入CAT客户端，使用Cat.logMetricForCount("metric.key")埋点，metric.key是一个很长的URL且不断在变化，频繁上报可出现home机JVM老年代被打爆

建议官方解决：
1、限制每个应用的metric.key上报数量，超过数量直接丢弃
2、限制business key长度，超过长度直接丢弃，不能直接插入数据库

**Comment by jialinsun** [comment]
这些内部已经优化过，开源版本后续考虑优化下，感谢建议
