### ISSUE TITLE
cat filter能否区分GET POST请求

### ISSUE THREAD

**Issue by zhangyanglei** [dianping/cat#1935]
某些接口url可能是相同的 但是请求方式不同 在cat里会统计到一个transaction里面 不知道目前是否有区分方式

如果有 麻烦告知下解决方式 如果没有 是不是可以在上报的时候在name项把请求方式也带上

**Comment by fishstormX** [comment]
可以打点时写进去，应该是两个入口吧

**Comment by jialinsun** [comment]
这个可以尝试下，大概需要二次开发一下，目前内部版本没有这个需求。
