### ISSUE TITLE
docker image build error

### ISSUE THREAD

**Issue by huahhh** [dianping/cat#1938]
error log

[ERROR] Plugin org.apache.maven.plugins:maven-source-plugin:2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-source-plugin:jar:2.2: Could not transfer artifact org.apache.maven.plugins:maven-source-plugin:pom:2.2 from/to central (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-source-plugin/2.2/maven-source-plugin-2.2.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]

**Comment by jialinsun** [comment]
可以再试试，pom里已经改过https访问了
