### ISSUE TITLE
Heartbeat线程堆栈信息显示异常

### ISSUE THREAD

**Issue by horizen** [dianping/cat#1939]
**Heartbeat jstack线程堆栈信息显示不正常**

**Expected behavior**
格式化显示各个线程堆栈信息

**Screenshots**
![image](https://user-images.githubusercontent.com/4516205/72583295-a8af0300-3920-11ea-8778-fffc12d6815d.png)

**Desktop (please complete the following information):**
 - OS: [mac os]
 - Browser [chrome]
 - Version [3.0.0]

**Comment by jialinsun** [comment]
确认下客户端和服务端都是开源最新版本

**Comment by horizen** [comment]
是github上的最新版本（master）分支，帮忙看下是否是bug

姚尉

**Comment by peng213** [comment]
遇到了和你一样的问题  请问有解决掉嘛

**Comment by horizen** [comment]
目前还没有解决

姚尉

**Comment by peng213** [comment]
好的

**Comment by 1978625177** [comment]
新版本对heartbeat信息进行了编码，后面版本会解决该问题
