### ISSUE TITLE
cat源码找不到logTrace,文件报错

### ISSUE THREAD

**Issue by stoneLee81** [dianping/cat#1941]
![Snip20200208_28](https://user-images.githubusercontent.com/18001708/74083404-a6167800-4a9e-11ea-93bb-df9d18446189.png)

倒入了3.0.0的cat-client,发现没有Cat.logTrace这个函数，查看本地源码也没，很奇怪，不知道有没人遇到过

**Comment by jialinsun** [comment]
这个是一个废弃的API功能，已经不再支持。
