### ISSUE TITLE
transaction和event的logview只能看到最新一条，其他的怎么看？

### ISSUE THREAD

**Issue by esolve** [dianping/cat#1942]
http://chuantu.xyz/t6/715/1581387530x2890211674.png

譬如图中，各个调用totoal有7条的，5条的，2条的，点击logview进去一看只能看到最新一条的详情，其他的呢，能看吗？怎么看？

**Comment by MrZhouFor** [comment]
tong wen

**Comment by jialinsun** [comment]
其他的要看，目前只有在problem报表里看。目前cat的设计里，logview不支持全量或自定义查看，只能采样查看，或者有问题的时候，在problem报表里能看到部分。如果需要看到更多的，建议可以对logview id进行更多的记录存储，然后按照查询消息id的参数格式进行获取就可以了。
