### ISSUE TITLE
CAT服务端docker部署失败，卡在maven打包那一步，提示错误码501

### ISSUE THREAD

**Issue by cj506817364** [dianping/cat#1944]
<img width="1298" alt="截屏2020-02-1721 46 52" src="https://user-images.githubusercontent.com/33059555/74659957-3015bd80-51d0-11ea-9841-5008eba0dc32.png">

如上图所示，在执行docker-compose up 的时候，一直卡在
Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]

**Comment by FancierCoder** [comment]
这个我把 目录下的 pom.xml 文件里的 http://repo1.maven.org/maven2 都改成 https://repo1.maven.org/maven2 就可以了
