### ISSUE TITLE
cat的用户名和密码修改

### ISSUE THREAD

**Issue by gold-fisher** [dianping/cat#1946]
你好，请问cat的用户名和密码在哪里修改？

**Comment by spyvip** [comment]
启动参数里加上`-DCAT_ADMIN_PWD="123456"`
用户名好像不支持修改


参考这个文件`com.dianping.cat.system.page.login.service.SessionManager`

**Comment by zhangzc0419** [comment]
user表里直接改

**Comment by zyklon2** [comment]
参考SessionManager类，可启动参数添加-DCAT_ADMIN_PWD变更密码
