### ISSUE TITLE
分布式消息树的支持找不到文档说明

### ISSUE THREAD

**Issue by xy-github-issue** [dianping/cat#1949]
1.   是不是几个消息树要同一个 domain  才可以有如模型设计文档里展示的那种支持
![image](https://user-images.githubusercontent.com/61449802/75311690-9c5c8500-5892-11ea-9558-705d4ced7a1d.png)

2.   协议文档，现在还是只能看代码？

**Comment by zhangzc0419** [comment]
你看一下CAT类里的logRemoteCallClient和logRemoteCallServer

**Comment by zyklon2** [comment]
跨系统传递通过logRemoteCallClient/logRemoteCallServer实现，使用参照https://github.com/dianping/cat/tree/master/integration；
