### ISSUE TITLE
http://unidal.org/nexus/content/repositories/releases/ 这个仓库已经失效。

### ISSUE THREAD

**Issue by 9fbankwk** [dianping/cat#1956]
http://unidal.org这个域名已经过期了。。。
![image](https://user-images.githubusercontent.com/40495767/76164760-64a3e600-618c-11ea-8e6b-5d489def762a.png)

**Comment by liuxinbao1** [comment]
我一度以为是我改hosts文件覆盖了。弄了半天才发现域名过期了。。。不知道有没有大佬弄下，maven中心仓库也没有。

**Comment by XiongMMaq** [comment]
我install的时候也遇到了问题:
[ERROR] Failed to execute goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model (generate data model) on project cat-client: Execution generate data model of goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model failed: Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.5.8 or one of its dependencies could not be resolved: Failed to collect dependencies at org.unidal.maven.plugins:codegen-maven-plugin:jar:2.5.8 -> org.unidal.maven.plugins:codegen:jar:2.5.8 -> org.unidal.framework:foundation-service:jar:3.1.0: Failed to read artifact descriptor for org.unidal.framework:foundation-service:jar:3.1.0: Could not transfer artifact org.unidal.framework:foundation-service:pom:3.1.0 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): Connect to unidal.org:80 [unidal.org/209.99.40.221] failed: Operation timed out (Connection timed out) -> [Help 1]

**Comment by Gangchao** [comment]
[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could
 not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to nexus-my (http://unidal.org/nexus/service/local/repositories/releases/content/): Connect to unidal.org:80 [unidal.org/209.99.40
.221] failed: Connection timed out: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by Gangchao** [comment]
网络通了，域名应该续费了，效率给力
