### ISSUE TITLE
如何增加cat的服务端http请求数据时的吞吐量呢？

### ISSUE THREAD

**Issue by ZaynJiang** [dianping/cat#1963]
cat接入的项目多了后，给每个项目配置了告警，但是http请求就会有错误率，可能会告警：

![image](https://user-images.githubusercontent.com/11373799/77313684-42d76100-6d3f-11ea-896e-6e6379af4c75.png)
![image](https://user-images.githubusercontent.com/11373799/77313727-58e52180-6d3f-11ea-89ac-f695b35b1c82.png)

**Comment by jialinsun** [comment]
看下机器配置 tomcat配置等等分析下，这个要多方面考虑，单单看这个也没太大什么思路哇。

**Comment by ZaynJiang** [comment]
> 看下机器配置 tomcat配置等等分析下，这个要多方面考虑，单单看这个也没太大什么思路哇。

cat会在http调用各个节点的数据，调用的频次多了会有这个问题，从cat的本身角度有什么优化的空间没，比如增加内部的线程啥的，tomcat和机器性能已经无法优化了。

**Comment by jialinsun** [comment]
> > 看下机器配置 tomcat配置等等分析下，这个要多方面考虑，单单看这个也没太大什么思路哇。
> 
> cat会在http调用各个节点的数据，调用的频次多了会有这个问题，从cat的本身角度有什么优化的空间没，比如增加内部的线程啥的，tomcat和机器性能已经无法优化了。

调用各个节点数据，应该会根据应用所在路由机器进行按需拉取，不是所有节点都拉取。还有可能是报表太大，如果一个应用机器很多，可以考虑拆分。

**Comment by ZaynJiang** [comment]
> > > 看下机器配置 tomcat配置等等分析下，这个要多方面考虑，单单看这个也没太大什么思路哇。
> > 
> > 
> > cat会在http调用各个节点的数据，调用的频次多了会有这个问题，从cat的本身角度有什么优化的空间没，比如增加内部的线程啥的，tomcat和机器性能已经无法优化了。
> 
> 调用各个节点数据，应该会根据应用所在路由机器进行按需拉取，不是所有节点都拉取。还有可能是报表太大，如果一个应用机器很多，可以考虑拆分。

我看了下代码，貌似是直接向各个消费机拉取，然后再merge的；应用的节点多的话确实可能导致报表大
