### ISSUE TITLE
cat客户端ThreadInfoWriter.java类ThreadDump信息写入疑问

### ISSUE THREAD

**Issue by 578394545** [dianping/cat#1966]
在client端ThreadInfoWriter.java类中，写入了获取到的应用的ThreadDump信息，但在buildThreadsInfo方法和processThread方法中，将很多信息如threaSize、threadId、stateCode等信息做格式化，转成“一定位数的数字+#”的这种格式存到消息树中。

_请问这种做法的具体作用和好处什么呢？这些加工过的信息，可以怎么用呢？谢谢！_

类地址：[ThreadInfoWriter.java](https://github.com/dianping/cat/blob/master/lib/java/src/main/java/com/dianping/cat/status/jvm/ThreadInfoWriter.java)
相关代码如下：
public String buildThreadsInfo(ThreadInfo[] threads) {
        StringBuilder result = new StringBuilder();
        StringBuilder codeResult = new StringBuilder();
        result.append(PROTOCOL_ID);
        result.append("1");

        int threadSize;
        for (ThreadInfo thread : threads) {
            threadSize = processThread(thread, codeResult);
            codeResult.insert(codeResult.length() - threadSize, String.format("%04d", threadSize));
        }

        appendWordTable(result);
        result.append(String.format("%08d", threads.length));
        result.append(codeResult);
        return result.toString();
    }

    private int processThread(ThreadInfo thread, StringBuilder codeResult) {
        int lastSize = codeResult.length();
        codeResult.append(String.format("%08d", thread.getThreadId()));
        String stateCode = getStateCode(thread.getThreadState());
        codeResult.append(stateCode);

        String name = thread.getThreadName();
        addToWordTable(name);
        String code = encode(name);
        codeResult.append(code);
        codeResult.append(buildExternalFlag(thread));

        name = thread.getLockName();
        if (name != null) {
            addToWordTable(name);
            code = encode(name);
            codeResult.append(code);
        }

        name = thread.getLockOwnerName();
        if (name != null) {
            addToWordTable(name);
            code = encode(name);
            codeResult.append(code);
            String ownerId = String.valueOf(thread.getLockOwnerId());
            codeResult.append(ownerId).append("#");
        }

        StackTraceElement[] stackTrace = thread.getStackTrace();
        byte stackSize = (byte) (stackTrace.length < MAX_FRAMES ? stackTrace.length : MAX_FRAMES);
        codeResult.append(String.format("%04d", stackSize));

        StackTraceElement stack;
        for (int i = 0; i < stackTrace.length && i < MAX_FRAMES; i++) {
            stack = stackTrace[i];
            processStack(stack, codeResult);
        }

        return codeResult.length() - lastSize;
    }

**Comment by jialinsun** [comment]
常量编码处理，可以减少消息体的大小。在服务端收到消息后，会按照响应的常量编码，再解析成字符串
