### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by binksShaw** [dianping/cat#1976]
master上com.dianping.cat.consumer.state.StateReportMerger引用的好多类找不到。
是我编译方式不对吗？
如：
import com.dianping.cat.consumer.state.model.entity.Detail;
import com.dianping.cat.consumer.state.model.entity.Machine;
import com.dianping.cat.consumer.state.model.entity.Message;
import com.dianping.cat.consumer.state.model.entity.ProcessDomain;
import com.dianping.cat.consumer.state.model.entity.StateReport;
import com.dianping.cat.consumer.state.model.transform.DefaultMerger;

**Comment by slankka** [comment]
https://github.com/dianping/cat/wiki/cat_faq
![generate sources](https://user-images.githubusercontent.com/8142133/80332526-a5130c80-887d-11ea-99e4-50e5e88260e0.png)

**Comment by b306pkqcun** [comment]
> https://github.com/dianping/cat/wiki/cat_faq
thanks  已解决
