### ISSUE TITLE
cat transaction报表[小时模式]有数据,[历史模式]没有数据

### ISSUE THREAD

**Issue by chenkaishuaigege** [dianping/cat#1982]
**[小时模式]有数据,[历史模式]没有数据**
是需要配置,还是需要怎么处理呢

**Comment by zyklon2** [comment]
需要配置job-machine用于生产历史报表，具体见如下文档：
https://github.com/dianping/cat/wiki/readme_server
![图片](https://user-images.githubusercontent.com/31680391/86434970-6abc6480-bd31-11ea-8c67-c19a920bd867.png)

**Comment by Luoganggang** [comment]
![image](https://user-images.githubusercontent.com/39610717/114484515-f3f7b480-9c3c-11eb-985a-0dd3f28e1db1.png)

我遇到的情况是用着用着就看不到历史模式的数据了之前一直都能看，配置参数没有错job-machine="true"
