### ISSUE TITLE
500 Error occured when handling uri: /cat/r/t

### ISSUE THREAD

**Issue by IamFMYS** [dianping/cat#1992]
怎么打开错误堆栈鸭，新手求求了。

**Comment by pd876750619** [comment]
/data/appdatas/cat下有cat服务端日志

**Comment by pd876750619** [comment]
> 怎么打开错误堆栈鸭，新手求求了。

/data/appdatas/cat下有cat服务端日志

**Comment by zyklon2** [comment]
可以在Problem查看项目对应的Error；CAT应用的一些异常也可以在/data/appdatas/cat下查看

**Comment by zhengzhenning** [comment]
CAT的活跃度停留在18年，往后基本都是问题贴，如此看来，这个CAT已经被淘汰了，而且在实际的部署过程中会有各种未知的问题
