### ISSUE TITLE
springboot集成后，可以正常启动，但是dubbo调用失败

### ISSUE THREAD

**Issue by lschanchan** [dianping/cat#2006]
![image](https://user-images.githubusercontent.com/6651440/86248754-e22eae80-bbe0-11ea-8b84-3f998fd34e8e.png)
按照指引集成，希望监控dubbo服务的调用情况
但是调用时报错
![image](https://user-images.githubusercontent.com/6651440/86248900-1a35f180-bbe1-11ea-9021-b7bae899b10d.png)

个人感觉是不正确的包引起的
请问正确的集成方式是怎样，谢谢

**Comment by fisheuler** [comment]
2.7.5以上的apache包，应该引用apache-dubbo的那个集成cat的版本吧？apache-dubbo的这个集成版本的版本号还没有。
