### ISSUE TITLE
client.xml 是必须的么，能远程加载么，CAT_HOST用法

### ISSUE THREAD

**Issue by lazeyliu** [dianping/cat#2010]
hi
   我看client 代码com.dianping.cat.configuration.ApplicationEnvironment#loadRemoteClientConfig
  可以配置CAT_HOST 可以远程加载配置，然而配置后 断点到对应位置，这时 ENVIRONMENT 为UNKNOWN，如下
    http://192.168.2.11:8080/cat/s/launch?ip=172.20.32.138&env=unknown&hostname=MacBook-Pro.local
  关于CAT_HOST 哪里用的不对，或者有教程么

**Comment by jialinsun** [comment]
unknown是读取/data/appdatas/appenv这个路径下的配置的，可以看看代码里的property设置

**Comment by lazeyliu** [comment]
> unknown是读取/data/appdatas/appenv这个路径下的配置的，可以看看代码里的property设置

嗯 就是不想依赖文件，因为要打docker镜像，如果依赖这个文件 就需要打不同的镜像，或者volumes 引用实体机器的client.xml
这样就不好实现弹性增加实体机了，整理实体机 就麻烦了

我找到了办法 spi的方式 实现：com.dianping.cat.configuration.ClientConfigProvider
先粗略的下面的办法实现，依赖环境变量
···
import com.dianping.cat.configuration.ClientConfigProvider;
import com.dianping.cat.configuration.client.entity.ClientConfig;
import com.dianping.cat.configuration.client.entity.Server;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class CatClientConfigProvider implements ClientConfigProvider {
    private static final Logger logger = LoggerFactory.getLogger(CatClientConfigProvider.class);

    @Override
    public ClientConfig getClientConfig() {
        ClientConfig config = new ClientConfig();
        String hosts = System.getProperty("CAT_SERVERS");
        hosts = hosts != null ? hosts : System.getenv("CAT_SERVERS");
        String domain = System.getProperty("CAT_DOMAIN");
        domain = domain != null ? domain : System.getenv("CAT_SERVERS");

        List<Server> servers = Arrays.stream(StringUtils.trim(hosts).split(","))
                .filter(StringUtils::isNotBlank)
                .map(address -> {
                    String[] parts = address.split(":");
                    Server server = new Server(parts[0]);
                    if (parts.length > 1) {
                        String[] ports = parts[1].split("/");
                        server.setPort(Integer.parseInt(ports[0]));
                        if (ports.length > 1) {
                            server.setHttpPort(Integer.parseInt(ports[1]));
                        }
                    }
                    return server;
                })
                .collect(Collectors.toList());
        config.setServers(servers);
        config.setDomain(domain);
        return config;
    }
}
···

**Comment by lazeyliu** [comment]
emmm... 如果cat 能天然支持  系统属性/环境变量 配置就更好了，毕竟自己配置的话 还要用spi，打包的时候 还要注意这点

**Comment by CTU1000** [comment]
大家可以参考这篇文章自己的覆盖重组原始资源
https://blog.csdn.net/lemon89/article/details/71171146

**Comment by CTU1000** [comment]
大家可以参考这篇文章自己覆盖重写加载方法
https://blog.csdn.net/lemon89/article/details/71171146
