### ISSUE TITLE
数据库的日志怎么定期清理

### ISSUE THREAD

**Issue by WHYSOS** [dianping/cat#2012]
如果数据库日志，怎么定期清理合适

**Comment by jialinsun** [comment]
根据业务需求、业务存储规模量和成本预算，选取一个合理的存储周期。定期进行数据库磁盘清理即可。

**Comment by jialinsun** [comment]
根据业务需求、业务存储规模量和成本预算，选取一个合理的存储周期。定期进行数据库磁盘清理即可。

**Comment by Sirlinna** [comment]
@jialinsun 

> 根据业务需求、业务存储规模量和成本预算，选取一个合理的存储周期。定期进行数据库磁盘清理即可。

磁盘清理的话，是不是还要重新初始化数据库，是不是有点麻烦了？
