### ISSUE TITLE
Dockerfile tomcat not found

### ISSUE THREAD

**Issue by lianghappy** [dianping/cat#2014]
TOMCAT_MINOR_VERSION 7.0.96   
file https://mirrors.tuna.tsinghua.edu.cn/apache/tomcat/tomcat-7/v7.0.96/bin/apache-tomcat-7.0.96.tar.gz  not found

fix TOMCAT_MINOR_VERSION 7.0.105

**Comment by jialinsun** [comment]
[https://github.com/dianping/cat/commit/801f0b7b358814f8176dd2c47e25a85a9c83e6bc](url) DONE
