### ISSUE TITLE
Java | Sorry, the message is not there. It could be missing or archived.

### ISSUE THREAD

**Issue by woshishitou** [dianping/cat#2022]
Java 应用，查看Logview时，报这个错。Python 应用，不报。找不到原因。

**Comment by jialinsun** [comment]
应该没有查到这个logview，可能是删除了，也可能某些原因没有上传到hadoop上。可以查查hadoop上有没有那个消息文件，确认下哪一步的问题。

**Comment by woshishitou** [comment]
> 应该没有查到这个logview，可能是删除了，也可能某些原因没有上传到hadoop上。可以查查hadoop上有没有那个消息文件，确认下哪一步的问题。

您好。我详细描述一下。应用本身服务在我的笔记本（windows）上，服务端部署在笔记本的虚拟机（linux）上。然后hdfs-enabled是设置成false的，即没有启用hadoop。

**Comment by woshishitou** [comment]
补充一下，我尝试过把应用部署到虚拟机上（即，客户端与服务端在同一台机器上）。也没有作用，看logview的时候，还是一样的报错。
