### ISSUE TITLE
golang1.14.7 导入gocat 报错：package not in goroot

### ISSUE THREAD

**Issue by CoderXv** [dianping/cat#2024]
环境：macOS mojave + golang 1.14.7
安装步骤：
`go get github.com/dianping/cat/lib/go/...`
安装完成之后编写demo函数运行报错
```
main.go:3:8: package gocat is not in GOROOT (/usr/local/Cellar/go/1.14.7/libexec/src/gocat)
```
请教下有同学遇到过这种问题吗，应该怎么调整

**Comment by alexandnpu** [comment]
你有没有使用go mod呢？

go env的输出贴出来看看？

**Comment by CoderXv** [comment]
基于最新的v2 gocat https://github.com/Meituan-Dianping/cat-go/blob/master/DIFFERENCES.md 部署成功，v1这边后来就没再试了，请问现在v1版本的go-cat是处于depricated的状态了嘛
