### ISSUE TITLE
日志或者数据如何定期清理

### ISSUE THREAD

**Issue by lingdaotianxia** [dianping/cat#2025]
日志或者数据如何定期清理

**Comment by lingdaotianxia** [comment]
用的官网的war包直接部署，日志文件可以用脚本定期清理，但是数据库中的数据关联比较紧密，该如何定期清理

**Comment by jialinsun** [comment]
数据库数据，可以运维手段解决下，一般在存储量够的情况下，默认不删。如果存储量有限，可以在运维手段上自行维护一些删除逻辑，也可以类似写个清理任务。

**Comment by lingdaotianxia** [comment]
> 数据库数据，可以运维手段解决下，一般在存储量够的情况下，默认不删。如果存储量有限，可以在运维手段上自行维护一些删除逻辑，也可以类似写个清理任务。

谢了
