### ISSUE TITLE
CAT上项目名称为中文时跳转报错

### ISSUE THREAD

**Issue by zhutie8111** [dianping/cat#2035]
在CATA 3.0 配置页面 
![image](https://user-images.githubusercontent.com/11254513/92228290-3c4a3980-eeda-11ea-832b-7c22e9c57499.png)
![image](https://user-images.githubusercontent.com/11254513/92228340-4ff5a000-eeda-11ea-96d5-4bd7652be9a8.png)
跳转
![image](https://user-images.githubusercontent.com/11254513/92228375-613eac80-eeda-11ea-9c4e-5f78c60f3824.png)
cookie报错

**Comment by qiaoshuai0729** [comment]
应该是不支持中文名称吧~方便加个VX探讨一下吗！我是个人在学习这个框架

**Comment by zhutie8111** [comment]
> 应该是不支持中文名称吧~方便加个VX探讨一下吗！我是个人在学习这个框架

你们公司也在用这个CAT 框架吗？
