### ISSUE TITLE
任务消费太慢，原因是task表查询太慢

### ISSUE THREAD

**Issue by zhangkang1521** [dianping/cat#2043]
https://github.com/dianping/cat/blob/801f0b7b358814f8176dd2c47e25a85a9c83e6bc/cat-home/src/main/java/com/dianping/cat/report/task/TaskConsumer.java#L80-L83
以上代码会执行如下sql，表里有几千万数据，查询较慢，导致报表没有生成，如何解决。
SELECT * FROM task t WHERE t.status = 3  AND t.consumer = 'xxx'  LIMIT 1
SELECT * FROM task WHERE STATUS = 1 LIMIT 1

**Comment by GKJMLvjisheng** [comment]
请问是如何解决的？

**Comment by zhangkang1521** [comment]
定期清空task表就行了，另外再加个索引
