### ISSUE TITLE
告警方式是否支持添加钉钉机器人

### ISSUE THREAD

**Issue by zhengfei123** [dianping/cat#2069]

**Comment by lmx110522** [comment]
CAT不具备告警服务，需要你去开发告警的项目 然后需要你去配置你的告警的HTTP地址，你的告警项目随便发给谁，钉钉飞书企业微信都可以
![image](https://user-images.githubusercontent.com/37907181/105028675-4be2ad00-5a8c-11eb-8ee3-f2918917bd8e.png)

**Comment by lmx110522** [comment]
一定记得你开发的接口接受后告警之后，返回给CAT的信息中包含200字符串，必须是字符串200

**Comment by cealiu** [comment]
可以自己添加告警方式的，实现告警方法的，pull request里有人做了，你可以找找看
