### ISSUE TITLE
Cat 会延迟发送数据吗

### ISSUE THREAD

**Issue by young47** [dianping/cat#2093]
Cat client 不停的发送数据，但监控页面上某些 app只能看到 1 个 多小时前的数据，有些可以立刻看到，是有什么延迟聚合的机制吗？

**Comment by Macgrady4Ever** [comment]
@young47 @jialinsun  请问解决了吗, 我这也出现了数据只能看到一小时前的问题, 当前实时的永远看不到, 所有不同的服务都是只能看到一小时前的.

**Comment by qmwu2000** [comment]
CAT是实时系统，延时一般在秒级，从来没有碰到过你说的情况。

你可以想办法debug一下，看看到底是什么原因导致当前小时报表看不了。
