### ISSUE TITLE
引入了DruidCatFilter后，problem中的long-sql出现的判断标准是？

### ISSUE THREAD

**Issue by ChanJianxun** [dianping/cat#2111]
**Describe the bug**
引入了DruidCatFilter后，problem中的long-sql百分百出现，不管是查得慢还是秒查，每条sql都被认为是long-sql。

![image](https://user-images.githubusercontent.com/40854567/115674491-47c27600-a380-11eb-8a8b-350caeaf70d3.png)
![image](https://user-images.githubusercontent.com/40854567/115674582-632d8100-a380-11eb-9e9a-972380ae109a.png)

**Comment by flyingglass** [comment]
sql默认是100ms以上就会记录，参考ProblemLongType.java
