### ISSUE TITLE
测试环境没有cat服务端，导致内存泄露，代码中有埋点，能通过配置显示关闭吗

### ISSUE THREAD

**Issue by bigcoder84** [dianping/cat#2112]
测试环境没有cat服务端，导致内存泄露，代码中有埋点，能通过配置全局关闭Cat吗

**Comment by bigcoder84** [comment]
测试环境没有cat服务端，导致内存泄露，代码中有埋点，能通过配置全局关闭Cat吗
![image](https://user-images.githubusercontent.com/41669762/115844239-38abf880-a452-11eb-9aac-8e7cf3549fab.png)

**Comment by flyingglass** [comment]
> 测试环境没有cat服务端，导致内存泄露，代码中有埋点，能通过配置全局关闭Cat吗
> ![image](https://user-images.githubusercontent.com/41669762/115844239-38abf880-a452-11eb-9aac-8e7cf3549fab.png)

看起来像transaction没有complete导致的
