### ISSUE TITLE
test-framework2.4.0 is missing

### ISSUE THREAD

**Issue by city2011** [dianping/cat#2120]
**Describe the bug**
The POM for org.unidal.framework:test-framework:jar:2.4.0 is missing, no dependency information available

and in mvn-repo branch , there is no 2.4.0
![image](https://user-images.githubusercontent.com/6259816/122030968-d4c60080-ce00-11eb-95cd-525f1b2d73e9.png)

2 
is there not exists 
import com.dianping.cat.configuration.client.entity
import com.dianping.cat.configuration.client.transform
two package?
![image](https://user-images.githubusercontent.com/6259816/122030882-bf50d680-ce00-11eb-9f4d-6d35e532a1e7.png)

**To Reproduce**
build, then error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by slankka** [comment]
1. test-framework可以直接修改版本，不影响构建。
2. 找不到entity相关类的说明这个也可以在WIKI中找到。为了方便阅读，欢迎阅读这部分[Cat-Cookbook](https://www.slankka.com/CatCookbook/zh/guide/development-ide.html)，
