### ISSUE TITLE
CAT3.0支持业务标签吗？logMetric(String name, Map<String, String> tags) 中的 tags的值要如何传递

### ISSUE THREAD

**Issue by RainkingTriu** [dianping/cat#2135]
CAT3.0我看服务端是支持业务标签的配置的，看git文档有标签配置说明，但是我本地用 Cat.logMetricForCount(String name, Map<String, String> tags)这个API进行标签上报，一直上报不上去。
    想问下上面API中的 tags值应该如何传递？

**Comment by JiaRG** [comment]
#2078

**Comment by duishancunzhang** [comment]
> 这个还未支持，下个版本会支持

请问下个版本指的是哪个版本呢，我现在使用的3.1.0，支持自定义tag传递不
