### ISSUE TITLE
 jar 依赖在仓库中查找不存在

### ISSUE THREAD

**Issue by ningmengwork** [dianping/cat#2139]
**Describe the bug**
master 分支上的一些 jar 依赖在仓库中查找不存在
![Uploading image.png…]()
![jar没有依赖](https://user-images.githubusercontent.com/37521861/134890623-5a378fa6-2793-44d8-bce1-3f2bece623e9.png)

**Comment by yanhuahayi** [comment]
按照教程根本搭不起来了

**Comment by stq957023588** [comment]
依赖缺失很严重,尝试过各种方法,修改依赖版本,直接下载JAR导入到本地,但是总有新的提示,告诉我依赖失败

**Comment by stq957023588** [comment]
依赖问题在尝试多次后,发现将mvn-repo分支下的依赖下载下来,放进本地仓库,修改cat目录下(根目录)的pom.xml中的test-framework,codegen-maven-plugin,,plexus-maven-plugin的版本即可,具体修改如下  `			<dependency>
				<groupId>org.unidal.framework</groupId>
				<artifactId>test-framework</artifactId>

				<version>2.5.0</version>
			</dependency>   				<plugin>
					<groupId>org.unidal.maven.plugins</groupId>
					<artifactId>codegen-maven-plugin</artifactId>

					<version>3.0.1</version>
				</plugin>
				<plugin>
					<groupId>org.unidal.maven.plugins</groupId>
					<artifactId>plexus-maven-plugin</artifactId>

					<version>3.0.1</version>
				</plugin>`                          然后尝试编译打包,应该就可以了

**Comment by zhisrc** [comment]
目前相关依赖可能下载不了，mvn私服有点问题，正在解决
如果大家着急使用，可以从下面仓库获取代码，自己编译
https://github.com/unidal/maven-plugins
https://github.com/unidal/frameworks
