### ISSUE TITLE
cat这个依赖是真的骚

### ISSUE THREAD

**Issue by zhaoqiang1024** [dianping/cat#2151]
美团这个依赖是真骚，自己封装了一部分依赖，还搞的org的，搞的跟公共依赖包一样，东西是好东西

**Comment by Liubey** [comment]
蛤蛤蛤，是这样

**Comment by xiao-guqing** [comment]
是真的骚，我都跑不起来，

**Comment by 1978625177** [comment]
现在大家还有问题吗？相关依赖我们后续会处理好。
如果大家着急使用，可以从下面仓库获取代码，自己编译
https://github.com/unidal/maven-plugins
https://github.com/unidal/frameworks

**Comment by jialinsun** [comment]
这些框架的诞生背景是在10年前，当时不像现在这么丰富开箱即用的开发框架等，所以老吴架构师开发了自己的一套工具。
