### ISSUE TITLE
关于MemoryInformation数据问题

### ISSUE THREAD

**Issue by 18205097282** [dianping/cat#2169]
你好 我用Cat监控着200多个应用的内存使用指标。
其中，`nonHeapMemoryUsed`和`directBufferUsed ` 这两个指标的值总是基本平坦不变的。
`nonHeapMemoryUsed`的值大约在150MB左右（每个应用不一样，但是基本不随时间变化）。
`directBufferUsed`的值，所有应用基本都是16MB左右。

![1644224810(1)](https://user-images.githubusercontent.com/53631755/152757920-57f88fd9-3c11-43d8-aa4f-087525ee9db7.png)

请问，`nonHeapMemoryUsed`和`directBufferUsed`这两个指标随时间变化极小，基本平坦的曲线是正常的吗。

**Comment by qmwu2000** [comment]
如果数据采集是正确的话，出现这种情况可能是你的应用日志数据量太小，没有对CAT构成大的挑战，



发自我的iPhone

**Comment by 18205097282** [comment]
> 如果数据采集是正确的话，出现这种情况可能是你的应用日志数据量太小，没有对CAT构成大的挑战， 发自我的iPhone
> […](#)
> 在 2022年2月7日，17:07，18205097282 ***@***.***> 写道： ﻿ 你好 我用Cat监控着200多个应用的内存使用指标。 其中，nonHeapMemoryUsed和directBufferUsed 这两个指标的值总是基本平坦不变的。 nonHeapMemoryUsed的值大约在150MB左右（每个应用不一样，但是基本不随时间变化）。 directBufferUsed的值，所有应用基本都是16MB左右。 请问，nonHeapMemoryUsed和directBufferUsed这两个指标随时间变化极小，基本平坦的曲线是正常的吗。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.

请问，这个两个指标是描述该应用的堆外内存的使用情况的吧，和您说的应用日志数据量有啥关系呢

**Comment by huangUser** [comment]
no

**Comment by 18205097282** [comment]
> no
@huangUser @qmwu2000 
原来“nonHeapMemoryUsed”不是表示的堆外内存吗？
恳请大佬帮忙解释一下`nonHeapMemoryUsed`和`directBufferUsed`这两个指标的含义是什么呀，和什么相关？
感谢

**Comment by 1978625177** [comment]
directBufferUsed：表示堆外内存。如果没有使用过堆外，基本固定在几M，cat-client使用到了固定大小，应该是1M
nonHeapMemoryUsed：表示非堆内存，比如 栈、永久代
