### ISSUE TITLE
Failed to execute goal org.unidal.maven.plugins:codegen-maven-plugin:2.5.8:dal-model (generate data model) on project cat-client

### ISSUE THREAD

**Issue by dlts26** [dianping/cat#2172]
**Describe the bug**
Failed to read artifact descriptor

**To Reproduce**
mvn clean install -DskipTests

**Screenshots**

![微信截图_20220212122703](https://user-images.githubusercontent.com/6983809/153696459-8894c87d-2e35-42e9-b417-3e42502223f7.png)

**Comment by 1978625177** [comment]
感觉是 没有将一些依赖jar包下载下来。看一下本地~/.m2 文件夹下有没有对应的 codegen-maven-plugin.jar等文件

**Comment by jialinsun** [comment]
再重试下，已经上传相关缺失jar包。
