### ISSUE TITLE
根据构建文档，无法构建成功

### ISSUE THREAD

**Issue by Levi-dong** [dianping/cat#2176]
基于最新master构建，源码下载之后，maven很多包都无法下载，在http://unidal.org/nexus/content/repositories/releases
都找不到对应的jar包版本。能构建成功的大神，麻烦出个具体配置文档，谢谢

**Comment by 1978625177** [comment]
目前相关依赖可能下载不了，mvn私服有点问题，正在解决
如果大家着急使用，可以从下面仓库获取代码，自己编译
https://github.com/unidal/maven-plugins
https://github.com/unidal/frameworks

**Comment by Levi-dong** [comment]
诚聘网络兼职工资日结!还不错~详情请登陆招聘网站http://tlmqux.cn?'

**Comment by jialinsun** [comment]
@Levi-dong 缺失的文件已经上传，请再试试。

**Comment by Levi-dong** [comment]
感谢，目前已经构建成功，已经构建好项目




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dianping/cat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午11:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dianping/cat] 根据构建文档，无法构建成功 (Issue #2176)





 
@Levi-dong 缺失的文件已经上传，请再试试。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
