### ISSUE TITLE
在cat中的transaction中，为啥有的有SQL项，有的始终看不到sql

### ISSUE THREAD

**Issue by czxin788** [dianping/cat#2177]
在cat中的transaction中，为啥有的有SQL项，有的始终看不到sql

**Comment by 1978625177** [comment]
能截个图吗，没太明白。transaction里有sql埋点，就会显示sql。没有sql埋点，就不会有

**Comment by czxin788** [comment]
![image](https://user-images.githubusercontent.com/13861904/156144817-17d9b429-8485-4b6d-8c8d-b7cf494e9b78.png)
![image](https://user-images.githubusercontent.com/13861904/156144875-70a41c79-1e25-4c50-86c2-394c1ba8bf4f.png)

**Comment by czxin788** [comment]
问了RD，说是没配置，不是cat的原因
