### ISSUE TITLE
mvn打包403错误

### ISSUE THREAD

**Issue by qing-root** [dianping/cat#2183]
**Describe the bug**
mvn打包发现403错误
http://unidal.org/nexus/content/repositories/releases/org/unidal/maven/plugins/codegen-maven-plugin/2.5.8/

[ERROR] Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.5.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.unidal.maven.plugins:codegen-maven-plugin:jar:2.5.8: Could not transfer artifact org.unidal.maven.plugins:codegen-maven-plugin:pom:2.5.8 from/to unidal.releases (http://unidal.org/nexus/content/repositories/releases/): authorization failed for http://unidal.org/nexus/content/repositories/releases/org/unidal/maven/plugins/codegen-maven-plugin/2.5.8/codegen-maven-plugin-2.5.8.pom, status: 403 Forbidden -> [Help 1]
![image](https://user-images.githubusercontent.com/30001685/159221270-08b4bc3f-73cc-42c2-8764-6ca64dbff575.png)

**Comment by power-lin** [comment]
地址已修复，请按照服务端部署（https://github.com/dianping/cat/wiki/readme_server），配置maven的配置文件后，再试试看

**Comment by power-lin** [comment]
最新版本自v3.0.1开始，已经不需要maven做任何配置了，可以直接从中央仓库获取，可以尝试下
