### ISSUE TITLE
能不能开个pr给client端的unidal框架去了？

### ISSUE THREAD

**Issue by Liubey** [dianping/cat#2198]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Liubey** [comment]
有没有这个需求？我想搞一下

**Comment by power-lin** [comment]
这边是有去掉unidal重新设计的规划，可以搞的

**Comment by Liubey** [comment]
> 

那我是不是可以动工了

**Comment by power-lin** [comment]
可以的
