### ISSUE TITLE
3.1.0 

### ISSUE THREAD

**Issue by jeeGu** [dianping/cat#2227]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/27198826/174198729-82dc043b-885d-4e2e-9d15-9ff9e638535e.png">

**Comment by jeeGu** [comment]
3.1.0

**Comment by jeeGu** [comment]
看到readme 说不再维护 关闭了

**Comment by qmwu2000** [comment]
这个问题是由于codegen plugin没有正确运行导致的。

CAT客户端会继续维护和升级，3.2.0将会是一个大版本，会有大量的重构和重写，近期会发布，欢迎关注！
