### ISSUE TITLE
告警延迟分析

### ISSUE THREAD

**Issue by romanticmj** [dianping/cat#2243]
**背景**
微服务>50，告警>2w时，经常出现告警延迟，最多时候达到1h以上

**原因分析**
SendExcutor每5min拉取一次告警，通过arthas分析，主要是在 m_decoratorManager.generateTitleAndContent 耗时长，发现是其中有一条SQL执行很慢
`SELECT al.id,al.domain,al.alert_time,al.category,al.`type`,al.content,al.metric,al.creation_date FROM alert al WHERE al.alert_time >= ? AND al.alert_time <= ? AND al.category = ? AND al.domain = ? ORDER BY al.alert_time asc`

**解决策略**
增加索引index idx_alert_time_category_domain(`alert_time`,`category`,`domain`);
`alter table `alert` add index idx_alert_time_category_domain(`alert_time`,`category`,`domain`);`

**建议**
在初始化的CatApplication.sql中，补充该索引

**Comment by qmwu2000** [comment]
麻烦顺便发个pull request，谢谢！

**Comment by romanticmj** [comment]
> 
PR：https://github.com/dianping/cat/pull/2245

**Comment by qmwu2000** [comment]
Merged into master
