### ISSUE TITLE
为什么已经满足了告警条件却没有触发告警邮箱接口？

### ISSUE THREAD

**Issue by tabular-rasa** [dianping/cat#2258]
![image](https://user-images.githubusercontent.com/57778159/200823555-f363e823-25d2-470f-8c80-22e65bb2fa18.png)
可以看待transaction已经开启
![image](https://user-images.githubusercontent.com/57778159/200823664-66b58bca-47fc-4528-b35a-05efe332b79a.png)
我设置的触发条件
![image](https://user-images.githubusercontent.com/57778159/200823744-5c7b6eb6-73de-4d73-b6fe-f40d389ab99d.png)
可以看到已经满足触发的条件

请问cat的日志是否可以包含告警的记录？不然出现类似这种情况我如何知道是否发生告警了呢？

**Comment by qmwu2000** [comment]
告警输入数据是每分钟的增量，不是累计总量

**Comment by tabular-rasa** [comment]
那我设置cat自身的告警触发阈值如下
![image](https://user-images.githubusercontent.com/57778159/201283841-ab188375-ccfd-4844-a54d-0b6de7b593c1.png)
然后访问CAT
依旧收不到相应的告警信息，按理说我已经满足了告警的条件

**Comment by tabular-rasa** [comment]
解决了 是docker版本路径映射的问题
