### ISSUE TITLE
请问如何配置GC或者慢SQL等相关的告警？

### ISSUE THREAD

**Issue by M1sury** [dianping/cat#2296]
比如GC设置某个阈值，到达阈值通知相关开发的这种功能，目前支持吗？应该如何配置？

**Comment by everiu** [comment]
- 客户端上报的Heartbeat信息中应该每分钟的GC相关信息，可以尝试配置下Heartbeat告警
- 慢SQL告警，目前Problem报表会有Long SQL的数据，可以尝试配置下Problem告警

**Comment by M1sury** [comment]
> * Java客户端上报的Heartbeat信息中有每分钟的GC相关信息，可以尝试配置下Heartbeat告警
> * 慢SQL告警，目前Problem报表会有Long SQL的数据，可以尝试配置下Problem告警

感谢，我去探索探索
