### ISSUE TITLE
Transaction 统计不到接口时间

### ISSUE THREAD

**Issue by zyl0622** [dianping/cat#2300]
**Describe the bug**
使用的开源master分支的版本4.0-RC1，搭建启动cat-home，transaction中不显示接口统计时间

![image](https://github.com/dianping/cat/assets/14835633/8e37e65b-4b91-4d7a-8f4f-bc6d0903ee2a)

**Comment by everiu** [comment]
点击logview查看客户端上报的原始数据中，有耗时的数据吗

**Comment by zyl0622** [comment]
logview 显示 “Sorry, the message is not there. It could be missing or archived.”

**Comment by zyl0622** [comment]
> 

logview 显示 “Sorry, the message is not there. It could be missing or archived.”

**Comment by zyl0622** [comment]
> 
logview 显示 “Sorry, the message is not there. It could be missing or archived.” 
State 菜单也不显示处理消息量
![image](https://github.com/dianping/cat/assets/14835633/d4febba9-d0f6-4881-8b33-796f34035adb)

**Comment by zyl0622** [comment]
切换版本分支3.1
