### ISSUE TITLE
cat-home build 失败

### ISSUE THREAD

**Issue by lycplus** [dianping/cat#574]
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.dianping.cat:cat-home:war:1.1.3
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-maven-plugin/1.1.3/cat-maven-plugin-1.1.3.pom
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-maven-plugin/1.1.3/cat-maven-plugin-1.1.3.pom
[WARNING] The POM for com.dianping.cat:cat-maven-plugin:jar:1.1.3 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.dianping.cat:cat-maven-plugin:1.1.3: Plugin com.dianping.cat:cat-maven-plugin:1.1.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.dianping.cat:cat-maven-plugin:jar:1.1.3
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building cat-home 1.1.3
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.dianping.cat:cat-maven-plugin:jar:1.1.3 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.dianping.cat:cat-maven-plugin:1.1.3: Plugin com.dianping.cat:cat-maven-plugin:1.1.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.dianping.cat:cat-maven-plugin:jar:1.1.3
[INFO]
[INFO] >>> maven-jetty-plugin:6.1.26:run (default-cli) @ cat-home >>>
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-consumer/1.1.3/cat-consumer-1.1.3.pom
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-consumer/1.1.3/cat-consumer-1.1.3.pom
[WARNING] The POM for com.dianping.cat:cat-consumer:jar:1.1.3 is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-consumer-advanced/1.1.3/cat-consumer-advanced-1.1.3.pom
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-consumer-advanced/1.1.3/cat-consumer-advanced-1.1.3.pom
[WARNING] The POM for com.dianping.cat:cat-consumer-advanced:jar:1.1.3 is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-hadoop/1.1.3/cat-hadoop-1.1.3.pom
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-hadoop/1.1.3/cat-hadoop-1.1.3.pom
[WARNING] The POM for com.dianping.cat:cat-hadoop:jar:1.1.3 is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-client/1.1.3/cat-client-1.1.3.pom
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-client/1.1.3/cat-client-1.1.3.pom
[WARNING] The POM for com.dianping.cat:cat-client:jar:1.1.3 is missing, no dependency information available
[WARNING] The POM for org.unidal.framework:foundation-service:jar:2.0.11 is missing, no dependency information available
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-consumer/1.1.3/cat-consumer-1.1.3.jar
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-consumer-advanced/1.1.3/cat-consumer-advanced-1.1.3.jar
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-hadoop/1.1.3/cat-hadoop-1.1.3.jar
Downloading: http://repo1.maven.org/maven2/com/dianping/cat/cat-client/1.1.3/cat-client-1.1.3.jar
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-consumer/1.1.3/cat-consumer-1.1.3.jar
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-consumer-advanced/1.1.3/cat-consumer-advanced-1.1.3.jar
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-hadoop/1.1.3/cat-hadoop-1.1.3.jar
Downloading: https://raw.github.com/dianping/cat/mvn-repo/com/dianping/cat/cat-client/1.1.3/cat-client-1.1.3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.979s
[INFO] Finished at: Mon Oct 27 10:40:25 CST 2014
[INFO] Final Memory: 8M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cat-home: Could not resolve dependencies for project com.dianping.cat:cat-home:war:1.1.3: The following artifacts could not be resolved: com.dianping.cat:cat-consumer:jar:1.1.3, com.dianping.cat:cat-consumer-advanced:jar:1.1.3, com.dianping.cat:cat-hadoop:jar:1.1.3, com.dianping.cat:cat-client:jar:1.1.3: Could not find artifact com.dianping.cat:cat-consumer:jar:1.1.3 in central (http://repo1.maven.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by nuaazyzcf** [comment]
I have the same problem now, can you tell me how to solve this, thanks!

**Comment by yanglifan** [comment]
located in China? across the fire wall
