### ISSUE TITLE
客户端要求配置的jar包没有

### ISSUE THREAD

**Issue by yutian** [dianping/cat#610]
<dependency>
             <groupId>com.dianping.zebra</groupId>
             <artifactId>zebra-ds-monitor-client</artifactId>
             <version>2.5.9</version>
       </dependency>
       <dependency>
             <groupId>com.dianping.cat</groupId>
             <artifactId>cat-core</artifactId>  
             <version>1.1.3</version>
             </dependency>
       <dependency>
             <groupId>com.dianping.cat</groupId>
             <artifactId>cat-client</artifactId>  
             <version>1.1.3</version>
             </dependency>
       <dependency>
              <groupId>com.dianping</groupId>
              <artifactId>avatar-dao</artifactId>
             <version>2.1.7</version>
       </dependency>
       <dependency>
              <groupId>com.dianping.dpsf</groupId>
              <artifactId>dpsf-net</artifactId>
             <version>1.8.1</version>
       </dependency>
       <dependency>
              <groupId>com.dianping.hawk</groupId>
              <artifactId>hawk-client</artifactId>
             <version>0.6.7</version>
       </dependency>
       <dependency>
              <groupId>com.dianping</groupId>
              <artifactId>avatar-cache</artifactId>
             <version>2.2.4</version>
       </dependency> 

集成帮助文档 这些jar包都没有，怎么样集成呢？另外要怎么登陆后台？

**Comment by zuzong** [comment]
用了两个仓库地址，都不行。。。没有上面哪个jar包能集成吗？
		<repository>
   			<id>dianping.repo</id>
   			<url>http://mvn.dianpingoa.com/dianping-releases</url>
   		</repository>
   		<repository>
			<id>cat.repo</id>
			<url>https://raw.github.com/dianping/cat/mvn-repo</url>
		</repository>
