### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by yq76034150** [dianping/cat#697]
git clone master代码后在ide编译不通过，没有找到 com.dianping.cat.configuration.client的源码。
如：
com.dianping.cat.configuration.client.entity.ClientConfig
com.dianping.cat.configuration.client.entity.Domain

等。

**Comment by afredlyj** [comment]
hi，你最后解决了吗？

**Comment by yq76034150** [comment]
解决了，他和maven绑定的比较死，按照说明 执行完mvn命令，再倒入ide即可

----- 原文 ----- 
发件人: Liyuanjun 
主　题: Re: [cat] 编译不通过 (#697)
时　间: 2015年2月28日  上午11:09:28
抄　送: stone yang, &nbsp;

hi，你最后解决了吗？

**Comment by afredlyj** [comment]
我这儿一直不行，貌似codegen-maven插件生成的代码不对。

2015-02-28 12:30 GMT+08:00 stone yang <notifications@github.com>:

**Comment by afredlyj** [comment]
你生成的  com.dianping.cat.home.rule.transform.DefaultJsonBuilder 类，有
buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)方法吗？

2015-02-28 12:30 GMT+08:00 stone yang <notifications@github.com>:

**Comment by yq76034150** [comment]
有这个方法：
public String buildArray(Collection<? extends IEntity<?>> entities) {

1.是不是它最新提交的代码有问题？ 
2.是不是你mvn执行过程中部分jar没有下载成功？

----- 原文 ----- 
发件人: Liyuanjun 
主　题: Re: [cat] 编译不通过 (#697)
时　间: 2015年2月28日  下午3:04:41
抄　送: stone yang, 

你生成的  com.dianping.cat.home.rule.transform.DefaultJsonBuilder 类，有


buildArray(java.util.List&lt;com.dianping.cat.home.rule.entity.Config&gt;)方法吗？



2015-02-28 12:30 GMT+08:00 stone yang &lt;notifications@github.com&gt;:



&gt; 解决了，他和maven绑定的比较死，按照说明 执行完mvn命令，再倒入ide即可


&gt;


&gt; ----- 原文 -----


&gt; 发件人: Liyuanjun


&gt; 主 题: Re: [cat] 编译不通过 (#697)


&gt; 时 间: 2015年2月28日 上午11:09:28


&gt; 抄 送: stone yang, &amp;nbsp;


&gt;


&gt; hi，你最后解决了吗？


&gt; —


&gt; Reply to this email directly or view it on GitHub.


&gt;


&gt;


&gt;


&gt; —


&gt; Reply to this email directly or view it on GitHub


&gt; &lt;https://github.com/dianping/cat/issues/697#issuecomment-76509930&gt;.


&gt;

**Comment by qmwu2000** [comment]
你有没有新克隆一个git repository试过，不要用maven私服？还是怀疑你本地环境的问题，travis build通过了，应该没问题的。

**Comment by yq76034150** [comment]
我想问下，我现在小时模式可以但历史模式有问题，不知道需要怎么处理？

----- 原文 ----- 
发件人: Frankie Wu 
主　题: Re: [cat] 编译不通过 (#697)
时　间: 2015年3月2日  上午8:43:21
抄　送: stone yang, &nbsp;

你有没有新克隆一个git repository试过，不要用maven私服？还是怀疑你本地环境的问题，travis build通过了，应该没问题的。



Sent from my iPhone


&gt; On Mar 1, 2015, at 20:00, stone yang &lt;notifications@github.com&gt; wrote:

&gt; 

&gt; 

&gt; 有这个方法：

&gt; public String buildArray(Collection&lt;? extends IEntity&lt;?&gt;&gt; entities) {

&gt; 

&gt; 1.是不是它最新提交的代码有问题？ 

&gt; 2.是不是你mvn执行过程中部分jar没有下载成功？

&gt; 

&gt; ----- 原文 ----- 

&gt; 发件人: Liyuanjun 

&gt; 主　题: Re: [cat] 编译不通过 (#697)

&gt; 时　间: 2015年2月28日 下午3:04:41

&gt; 抄　送: stone yang, 

&gt; 

&gt; 你生成的 com.dianping.cat.home.rule.transform.DefaultJsonBuilder 类，有

&gt; 

&gt; 

&gt; buildArray(java.util.List&amp;lt;com.dianping.cat.home.rule.entity.Config&amp;gt;)方法吗？

&gt; 

&gt; 

&gt; 

&gt; 2015-02-28 12:30 GMT+08:00 stone yang &amp;lt;notifications@github.com&amp;gt;:

&gt; 

&gt; 

&gt; 

&gt; &amp;gt; 解决了，他和maven绑定的比较死，按照说明 执行完mvn命令，再倒入ide即可

&gt; 

&gt; 

&gt; &amp;gt;

&gt; 

&gt; 

&gt; &amp;gt; ----- 原文 -----

&gt; 

&gt; 

&gt; &amp;gt; 发件人: Liyuanjun

&gt; 

&gt; 

&gt; &amp;gt; 主 题: Re: [cat] 编译不通过 (#697)

&gt; 

&gt; 

&gt; &amp;gt; 时 间: 2015年2月28日 上午11:09:28

&gt; 

&gt; 

&gt; &amp;gt; 抄 送: stone yang, &amp;amp;nbsp;

&gt; 

&gt; 

&gt; &amp;gt;

&gt; 

&gt; 

&gt; &amp;gt; hi，你最后解决了吗？

&gt; 

&gt; 

&gt; &amp;gt; —

&gt; 

&gt; 

&gt; &amp;gt; Reply to this email directly or view it on GitHub.

&gt; 

&gt; 

&gt; &amp;gt;

&gt; 

&gt; 

&gt; &amp;gt;

&gt; 

&gt; 

&gt; &amp;gt;

&gt; 

&gt; 

&gt; &amp;gt; —

&gt; 

&gt; 

&gt; &amp;gt; Reply to this email directly or view it on GitHub

&gt; 

&gt; 

&gt; &amp;gt; &amp;lt;https://github.com/dianping/cat/issues/697#issuecomment-76509930&amp;gt;.

&gt; 

&gt; 

&gt; &amp;gt;

&gt; 

&gt; —

&gt; Reply to this email directly or view it on GitHub.

&gt; 

&gt; 

&gt; 

&gt; —

&gt; Reply to this email directly or view it on GitHub.

&gt;

**Comment by youyong205** [comment]
/data/appdatas/cat/server.xml  config  job-machine=true
