### ISSUE TITLE
怎么在自己的环境中使用cat？

### ISSUE THREAD

**Issue by liming430** [dianping/cat#698]
假如现在要在自己的环境(也就是非点评的环境)中使用cat，应该怎么用呢？有哪些需要注意的地方？
我的理解是：
cat-client-_.jar和应用端代码集成在一起，应用端代码调用相关API记录要监控的消息；
然后再将cat-alpha-_.war发布在应用容器中作为监控的服务端；
并在数据库中初始化Cat.sql创建相应的表，如果用到大数据还要再搭建hadoop环境。
做完这些是不是就可以了？

**Comment by kingcent** [comment]
由于公司内部各类原因，cat server有可能停止服务。client的消息只放到内存很容易OOM，怎样考虑先放到本地log文件，再异步发送？

**Comment by qmwu2000** [comment]
client内存占用是有限的，如果cat server不能接收新的日志消息，客户端队列会满，然后会消息溢出并丢弃，不会影响系统稳定性，只是暂时的监控能力受损。


发自我的 iPhone
