### ISSUE TITLE
在应用中使用cat-client报错

### ISSUE THREAD

**Issue by catshitaf** [dianping/cat#699]
你好，我用maven导入了cat-client:1.1.9 编译成功；但是在执行后，访问含有以下代码的服务接口，就报错；
### 环境：

osX + tomcat + java7 or java6 + spring or servlet
### 代码：

``` java

        Transaction t = Cat.getProducer().newTransaction("URL", "af-trans");  // 这行报错

        try {
            Cat.logEvent("URL.Server", "af-event");
            Cat.logMetricForCount("convert-cnt");
            String data = this.getData();
            resp.setContentType("text/html;charset=GBK");
            resp.getOutputStream().write(data.getBytes("GBK"));
            t.setStatus(Transaction.SUCCESS);
        } catch (Exception e) {
            t.setStatus(e);
        } finally {
            t.complete();
        }
```
### 报错：

``` java
exception

java.lang.RuntimeException: Unable to get instance of Logger, please make sure the environment was setup correctly!
    org.unidal.initialization.DefaultModuleContext.<init>(DefaultModuleContext.java:28)
    com.dianping.cat.Cat.initialize(Cat.java:91)
    com.dianping.cat.Cat.initialize(Cat.java:87)
    com.dianping.cat.Cat.checkAndInitialize(Cat.java:45)
    com.dianping.cat.Cat.getManager(Cat.java:72)
    com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:104)
    com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:406)
    com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
root cause

org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository
      role: org.codehaus.plexus.logging.LoggerManager
  roleHint: 
classRealm: none specified
    org.codehaus.plexus.DefaultComponentRegistry.getComponentManager(DefaultComponentRegistry.java:435)
    org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:353)
    org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:178)
    org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:383)
    org.unidal.initialization.DefaultModuleContext.<init>(DefaultModuleContext.java:24)
    com.dianping.cat.Cat.initialize(Cat.java:91)
    com.dianping.cat.Cat.initialize(Cat.java:87)
    com.dianping.cat.Cat.checkAndInitialize(Cat.java:45)
    com.dianping.cat.Cat.getManager(Cat.java:72)
    com.dianping.cat.servlet.CatFilter$CatHandler$1.handle(CatFilter.java:104)
    com.dianping.cat.servlet.CatFilter$Context.handle(CatFilter.java:406)
    com.dianping.cat.servlet.CatFilter.doFilter(CatFilter.java:53)
```

我在spring mvc项目和最简单的servlet项目中都试过，报的时同样的错误；
请问使用cat-client还有别的隐藏条件吗？这个问题折磨了我好久！希望大侠尽快回复~呜呜呜

**Comment by adonis2014** [comment]
@catshitaf 这个问题解决了没？我现在也遇到这个问题。服务是启动成功了，http://localhost:2281/cat，

**Comment by youyong205** [comment]
check  /data/appdatas/cat/ 这个路径是否有读写权限

**Comment by sunnyhui2010** [comment]
@adonis2014 @catshitaf 这个问题解决了吗？我也遇到这个问题了，我home已经跑起来了的。

**Comment by songwie** [comment]
大家好我也遇到这个错误，发现用maven 的tomcat插件启动就会有这个错误，正常的tomcat启动不会有问题，怀疑maven插件jar冲突，其他人又遇到的么

**Comment by yue-ch** [comment]
这个问题无解吗？

**Comment by yue-ch** [comment]
换成jetty-maven-plugin就没有问题

**Comment by qmwu2000** [comment]
有人报，这个问题是tomcat7-maven-plugin所依赖的plexus-container-default与cat依赖的有冲突导致的。我会找时间看一下

**Comment by zhang-xiang-career** [comment]
我也遇到同样的问题，请问  有解决方式吗？

**Comment by armysheng** [comment]
很有可能是打包的时候没有带上**META-INF/component.xml**文件引起的，检查一下确保该文件存在

**Comment by zeuskingzb** [comment]
加入如下依赖:<dependency>
			<groupId>com.bailian.cat.client</groupId>
			<artifactId>cat-client</artifactId>
			<version>1.3.6</version>
		</dependency>


		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>


                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

**Comment by zeuskingzb** [comment]
加入如下依赖
<dependency>
			<groupId>com.bailian.cat.client</groupId>
			<artifactId>cat-client</artifactId>
			<version>1.3.6</version>
		</dependency>


		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>


                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

**Comment by zeuskingzb** [comment]
加下如下依赖:



<dependency>
			<groupId>com.bailian.cat.client</groupId>
			<artifactId>cat-client</artifactId>
			<version>1.3.6</version>
		</dependency>


		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>


                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>


org.unidal.framework 需要上传到自己的私仓

**Comment by zeuskingzb** [comment]
加入如下包到项目:

**Comment by zeuskingzb** [comment]
加入如下包


  <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

**Comment by zeuskingzb** [comment]
`  <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>`

**Comment by zeuskingzb** [comment]
>   <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

**Comment by zeuskingzb** [comment]
>   <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>


加入依赖就行

**Comment by zeuskingzb** [comment]
> 
  <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

**Comment by zeuskingzb** [comment]
>          <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

**Comment by zeuskingzb** [comment]
<dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

**Comment by zeuskingzb** [comment]
> 

  <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>

>

**Comment by zeuskingzb** [comment]
>  
             <dependency>
			<groupId>com.dianping.cat</groupId>
            <artifactId>cat-client</artifactId>   
			<version>1.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-container-default</artifactId>
			<version>1.6</version>
		</dependency>
                <dependency>
		     <groupId>org.unidal.framework</groupId>
		     <artifactId>foundation-service</artifactId>
		     <version>2.2.0</version>
	        </dependency>


目前这是最靠谱的解决办法

**Comment by yuweibo** [comment]
你好这个问题解决了吗

**Comment by sungine** [comment]
我也遇到了这种问题,出现概率30%吧.

**Comment by bhxiaoxinba** [comment]
在应用中调用cat client api收集数据时出错

tomat+spring
`Transaction t = Cat.getProducer().newTransaction("URL", "af-trans");  // 这行报错`

错误:
`java.lang.RuntimeException: Unable to create Plexus container!   
  Element(component-discoverer-manager) is not expected under plexus!`

但是在java项目中不会，各位大神又遇到同样的问题吗，求帮忙？
