### ISSUE TITLE
配套RPC框架实现机制以及集群部署时的实时报表获取问题

### ISSUE THREAD

**Issue by liming430** [dianping/cat#712]
关于cat，还有2个问题想咨询一下：
1、关于跨服务器的RPC调用跟踪，RPC框架是怎么将cat的message id串联起来的呢？能具体介绍一下实现细节或者代码片段么？
2、看cat的文档里，说实时的报表是从cat服务端的内存里获取的。当cat服务端是集群部署的时候，这些报表数据在集群里是同步的么？如果不是的话，如何实时获取完整的报表呢？
谢谢！

**Comment by qmwu2000** [comment]
RPC调用链是这样的：客户端生成msg id，传到服务器端，同时客户端纪录一个event，包含此msg id。这样客户端logview就可以显示一个link，指向该消息。服务端的消息则以这个传过来的id保存。

ps，可以知道你是哪家公司的吗？


Sent from my iPhone
Frankie
