### ISSUE TITLE
有每个模块的介绍文档吗？

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#714]
想研究一下cat，但是没看到每个模块的功能介绍，能简单介绍一下吗？

**Comment by qmwu2000** [comment]
系统搭起来，就有了。

**Comment by afredlyj** [comment]
ok, 看到了，感谢~

**Comment by afredlyj** [comment]
oppo                             原始邮件                             发件人: Frankie Wu<notifications@github.com>收件人: dianping/cat<cat@noreply.github.com>抄送: Liyuanjun<csulyj@gmail.com>发送时间: 2015年1月9日(周五) 17:13主题: Re: [cat] 有每个模块的介绍文档吗？ (#714)可以知道你是哪家公司吗？
