### ISSUE TITLE
logMetricForSum参数构造错误导致Metric记录失败

### ISSUE THREAD

**Issue by chinaboard** [dianping/cat#718]
\cat\cat-client\src\main\java\com\dianping\cat\Cat.java
line 211
logMetricInternal(name, "S,C", String.format("%.2f,%s", sum, quantity));

\cat\cat-home\src\main\java\com\dianping\cat\report\page\monitor\Handler.java
line 76
defaultMetric.addData(String.format("%s,%.2f", 1, value));

两个String.format的参数方式不一样，导致logMetricForSum(String name, double sum, int quantity)
这个方法的值无法正确记录
请修改一下

**Comment by youyong205** [comment]
OK,thx~~~
