### ISSUE TITLE
Report Task处理有问题

### ISSUE THREAD

**Issue by stone1100** [dianping/cat#721]
当Task表中有积压任务时，处理的Task会很慢
TaskConsumer，每次只能一个Task，实际会把所有Todo task都取到client端，再取一条，这样就性能很差，可以批量去，或者在sql中加一个limit 1，每次取一条返回。虽然在dal中，设置了setFetchSize=1，但是在mysql下，这个参数不启作用
	try {
				if (checkTime()) {
					Task task = findDoingTask(localIp);//每次只拿一个
					if (task == null) {
						task = findTodoTask();//每次只拿一个
					}
					boolean again = false;
					if (task != null) {
						try {
							task.setConsumer(localIp);
							if (task.getStatus() == TaskConsumer.STATUS_DOING || updateTodoToDoing(task)) {
								int retryTimes = 0;
								while (!processTask(task)) {
									retryTimes++;
									if (retryTimes < MAX_TODO_RETRY_TIMES) {
										taskRetryDuration();
									} else {
										updateDoingToFailure(task);
										again = true;
										break;
									}
								}
								if (!again) {
									updateDoingToDone(task);
								}
							}
						} catch (Throwable e) {
							Cat.logError(task.toString(), e);
						}
					} else {
						taskNotFoundDuration();
					}
				} else {
					try {
						Thread.sleep(60 * 1000);
					} catch (InterruptedException e) {
						// Ignore
					}
				}

**Comment by stone1100** [comment]
task这个表的status也需要加一个index，最好是status,consumer两个的复合索引，status在前，这样的话通过consumer+status或者status查询应该都可以走到这个index

**Comment by youyong205** [comment]
每次取一个就是这么设计的，因为有些job需要有顺序执行。job执行慢我不知道为啥这样，我们目前生产环境的规模一小时3000任务，几分钟执行完了（5分钟左右）

每次取一条返回。虽然在dal中，设置了setFetchSize=1，但是在mysql下，这个参数不启作用。这个不理解啊，我们这边就是mysql

**Comment by youyong205** [comment]
status  加不加索引意义不大，因为区分度很小。

**Comment by stone1100** [comment]
fetchsize应该是每次fetch多少条数据，实际还会把所有的符合条件的记录都返回给client，这样如果task积压的话，每处理一个task都会返回几万条数据，每次拿第1条，而且跟数据库交互还是一条一条，所以会很慢，如果把fetchsize设大一些，估计性能还会好一些，现在我们是加了一个limit 1，很快就把积压的task处理完了

**Comment by youyong205** [comment]
limit 1 我现在加上去，更加明确点。

我明白你的意思了，就是fetch size 不起作用，返回值很大了。

我们这边也是用mysql，没遇到你这样问题，没有limit 1还是一条。可能和服务端一些config有关了。

**Comment by qmwu2000** [comment]
应该有用，否则就全表扫描了。毕竟todo的消息占比还是比较低的。
