### ISSUE TITLE
在client端获取不到服务器地址

### ISSUE THREAD

**Issue by nxnnxn** [dianping/cat#723]
在client端APP打得jar包中没有设置client.xml,但在/data/appdata/cat/client.xml设置了client.xml,结果读不到配置服务器。
	if (configFile != null) {
			if (configFile.exists()) {
				String xml = Files.forIO().readFrom(configFile.getCanonicalFile(), "utf-8");

				globalConfig = DefaultSaxParser.parse(xml);
				m_logger.info(String.format("Global config file(%s) found.", configFile));
			} else {
				m_logger.warn(String.format("Global config file(%s) not found, IGNORED.", configFile));
			}
		}

		// load the client configure from Java class-path
		clientConfig = loadConfigFromEnviroment();

		if (clientConfig == null) {
			clientConfig = loadConfigFromXml();
		}

		// merge the two configures together to make it effected
		if (globalConfig != null && clientConfig != null) {
			globalConfig.accept(new ClientConfigMerger(clientConfig));
		}

		if (clientConfig != null) {
			clientConfig.accept(new ClientConfigValidator());
		}

		m_config = clientConfig;

代码逻辑如上，先读到/data/appdata/cat/client.xml，然后再读APP包中的client.xml
然后再merge一下，但在最后返回的clientConfig，假如这个为空，什么也取不到
正常逻辑应该为APP中client.xml取不到，应该用globalConfig,而不是clientConfig

**Comment by youyong205** [comment]
clientConfig 是必须的，必须有才行。因为他代表应用的名称。

globalConfig 主要是为了以后运维方便，cat服务端的地址可能有调整。
