### ISSUE TITLE
TcpSocketSender不能无限制地发异步请求，会导致OOM

### ISSUE THREAD

**Issue by kikanjuu** [dianping/cat#724]
CAT Java客户端，TcpSocketSender的SendInternal()，每调用一次会发出一个异步网络写请求“writeAndFlush()”，并申请10KB的direct memory空间。

经过压力测试发现，这里产生了过高并发量的异步网络写请求，导致过于频繁的10KB buffer申请，最终引起OOM。
本质上，网络带宽无法承受如此高并发的异步IO。应对异步IO (writeAndFlush()) 的发起速率有所控制。

要修复这个问题，我们通过检查channel.isWritable()来控制异步IO请求速率。在TcpSocketSender的checkWritable()中：

将if (channel.channel().isActive()) {...}改为 if (channel.channel().isActive()&&channel.channel().isWritable()) {...}

关于isWritable()作用，请参见http://stackoverflow.com/questions/10143834/channel-iswritable-notofication-in-netty和http://stackoverflow.com/questions/19720956/get-oom-exception-when-sending-message-with-a-high-speed-with-netty

**Comment by youyong205** [comment]
谢谢，这个问题我研究下。

**Comment by youyong205** [comment]
以前这个问题遇到过，netty3 时候

**Comment by youyong205** [comment]
回头看下以前1.1.3版本code的，之前就是check isWriteable

后面我重构netty4时候，重构出了点故障，我们这边netty4 的客户端还没有上。
