### ISSUE TITLE
DefaultForkedTransaction.forkedMessageId建议由父transaction所在的线程生成，而不是forked transaction所在线程产生。

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#728]
1. 目前，DefaultForkedTransaction.fork()会为这个forked transaction产生forkedMessageId。
2. 当这个forked transaction的父transaction调用complete()时，会调用DefaultMessageManager.markAsRunAway()进行linking，此时会读取forked trasaction的forkedMessageId。

以上两点，意味着父线程的complete() 和 DefaultMessageManager.markAsRunAway()必须在子线程forked transaction.fork()执行之后，再执行。

这样，父线程就必须等待子线程完成Fork()调用的信号，造成同步上的难度。
在实际埋点中，子线程可能不是由应用，而是由系统后台线程池创建、启动、调度，所以子线程的启动时机无法确定。因此，如果父线程要等待子线程调用Fork()完成后再调用markAsRunAway()，会造成无法预知的延迟。

为了简化这个问题，去掉父子线程的同步等待，建议改成DefaultForkedTransaction.forkedMessageId由父transaction所在的线程创建，再传给forked transaction。
这样父transaction无需等待forked transaction.fork()——可以随时执行linking markAsRunAway()逻辑，父线程也可以随时退出。

**Comment by huang--yijian** [comment]
按老吴打的比方，儿子的名字应该由老子生成——这样比较合理。

**Comment by youyong205** [comment]
OK，收到。

这个bug应该一直存在。不过此API用的比较少，我们这边业务没用到。用在部分框架中。
