### ISSUE TITLE
cat的远程仓库不可用吗

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#731]
https://raw.github.com/dianping/cat/mvn-repo/
我把这个地址添加到sonatype 中，不可用？

**Comment by youyong205** [comment]
应该是github被封的问题吧。我这边要翻墙。

**Comment by afredlyj** [comment]
直接访问400: Invalid request

但是构建总是连不上

**Comment by afredlyj** [comment]
能提供具体的接入文档吗？
2015-02-04 10:52 GMT+08:00 youyong205 <notifications@github.com>:

**Comment by youyong205** [comment]
文档在项目启动就有了
