### ISSUE TITLE
点击跳转到Cache Report丢失了当前的domain

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#739]
假设我正在看名为920402的domain 的transaction report。
然后，我单击左侧菜单栏的 Cache - > 访问情况。

这时，我发现顶部搜索栏中的domain变成了cat——丢失了当前的domain 920402。
我们春节前刚从github更新了代码，发现了这个问题。以前记得是没有的。

**Comment by youyong205** [comment]
这个功能还在开发中，有些ui上还不是很完善
