### ISSUE TITLE
构建第一步cat-home报错

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#740]
* mvn clean install -DskipTests

第一步，构建cat-home报错，生成的DefaultJsonBuilder类没有buildArray方法：

~~~~  

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project cat-home: Compilation failure: Compilation failure:
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[53,45] 找不到符号                                                                                                                                     
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                             
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[54,54] 找不到符号                                                                                                                                     
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                         
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                            
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[250,50] 找不到符号                                                                                                                                           
[ERROR] 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.MetricItem>,java.lang.String)                                                                                                                                                       
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                             
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[251,42] 找不到符号                                                                                                                                           
[ERROR] 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.Config>,java.lang.String)                                                                                                                                                           
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                             
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[91,46] 找不到符号                                                                                                                             
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                              
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                            
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[92,44] 找不到符号                                                                                                                             
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                             
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                    

~~~~

**Comment by qmwu2000** [comment]
travis上build是成功的，应该是你本地环境的问题。你把这几个有错的文件删除掉，试试。

**Comment by afredlyj** [comment]
删除这几个java源文件，clean ，然后install，还是失败。

~~~~

[INFO] Building cat-home 1.1.8
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- codegen-maven-plugin:2.0.9:dal-model (generate dal model files) @ cat-home ---
[INFO] 20 files generated.
[INFO] 17 files generated.
[INFO] 15 files generated.
[INFO] 20 files generated.
[INFO] 13 files generated.
[INFO] 19 files generated.
[INFO] 21 files generated.
[INFO] 19 files generated.
[INFO] 20 files generated.
[INFO] 24 files generated.
[INFO] 18 files generated.
[INFO] 21 files generated.
[INFO] 15 files generated.
[INFO] 17 files generated.
[INFO] 17 files generated.
[INFO] 15 files generated.
[INFO] 21 files generated.
[INFO] 14 files generated.
[INFO] 19 files generated.
[INFO] 14 files generated.
[INFO]
[INFO] --- codegen-maven-plugin:2.0.9:dal-jdbc (generate dal jdbc model) @ cat-home ---
[INFO] 34 files generated.
[INFO] 13 files generated.
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ cat-home ---
[debug] execute contextualize
[INFO] Using 'utf-8' encoding to copy filtered resources.
[INFO] Copying 132 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ cat-home ---
[INFO] Compiling 1044 source files to F:\cat-master\cat-home\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[53,45] 找不到符号                                                                                                                                     
符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                                     
位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                    
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[54,54] 找不到符号                                                                                                                                     
符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                                 
位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                    
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[250,50] 找不到符号                                                                                                                                                
符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.MetricItem>,java.lang.String)                                                                                                                                                               
位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                                     
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[251,42] 找不到符号                                                                                                                                           
符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.Config>,java.lang.String)                                                                                                                                                                        
位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                                     
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[92,46] 找不到符号                                                                                                                             
符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                                 
位置： 类 com.dianping.cat.hom    e.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                    
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[93,44] 找不到符号                                                                                                                             
符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                                     
位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                        
[INFO] 6 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................ SUCCESS [1.387s]
[INFO] cat-client ........................................ SUCCESS [19.699s]
[INFO] cat-core .......................................... SUCCESS [16.065s]
[INFO] cat-consumer ...................................... SUCCESS [59.264s]
[INFO] cat-hadoop ........................................ SUCCESS [25.627s]
[INFO] cat-home .......................................... FAILURE [1:31.624s]
[INFO] broker-service .................................... SKIPPED
[INFO] cat-agent ......................................... SKIPPED
[INFO] cat-maven-plugin .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:34.578s
[INFO] Finished at: Sat Feb 28 14:32:36 CST 2015
[INFO] Final Memory: 32M/254M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project cat-home: Compilation failure: Compilation failure:
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[53,45] 找不到符号                                                                                                                                     
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                             
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[54,54] 找不到符号                                                                                                                                     
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                         
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                            
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[250,50] 找不到符号                                                                                                                                           
[ERROR] 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.MetricItem>,java.lang.String)                                                                                                                                                       
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                             
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[251,42] 找不到符号                                                                                                                                           
[ERROR] 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.Config>,java.lang.String)                                                                                                                                                           
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                             
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[92,46] 找不到符号                                                                                                                             
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                              
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                            
[ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[93,44] 找不到符号                                                                                                                             
[ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                             
[ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cat-home

~~~~

**Comment by qmwu2000** [comment]
你用一个干净的workspace试过了吗？


Sent from my iPhone

> On Feb 28, 2015, at 14:35, Liyuanjun <notifications@github.com> wrote:
> 
> 删除这几个java源文件，clean ，然后install，还是失败。
> 
> 
> [INFO] Building cat-home 1.1.8
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- codegen-maven-plugin:2.0.9:dal-model (generate dal model files) @ cat-home ---
> [INFO] 20 files generated.
> [INFO] 17 files generated.
> [INFO] 15 files generated.
> [INFO] 20 files generated.
> [INFO] 13 files generated.
> [INFO] 19 files generated.
> [INFO] 21 files generated.
> [INFO] 19 files generated.
> [INFO] 20 files generated.
> [INFO] 24 files generated.
> [INFO] 18 files generated.
> [INFO] 21 files generated.
> [INFO] 15 files generated.
> [INFO] 17 files generated.
> [INFO] 17 files generated.
> [INFO] 15 files generated.
> [INFO] 21 files generated.
> [INFO] 14 files generated.
> [INFO] 19 files generated.
> [INFO] 14 files generated.
> [INFO]
> [INFO] --- codegen-maven-plugin:2.0.9:dal-jdbc (generate dal jdbc model) @ cat-home ---
> [INFO] 34 files generated.
> [INFO] 13 files generated.
> [INFO]
> [INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ cat-home ---
> [debug] execute contextualize
> [INFO] Using 'utf-8' encoding to copy filtered resources.
> [INFO] Copying 132 resources
> [INFO]
> [INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ cat-home ---
> [INFO] Compiling 1044 source files to F:\cat-master\cat-home\target\classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[53,45] 找不到符号                                                                                                                                     
> 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                                     
> 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                    
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[54,54] 找不到符号                                                                                                                                     
> 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                                 
> 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                    
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[250,50] 找不到符号                                                                                                                                                
> 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.MetricItem>,java.lang.String)                                                                                                                                                               
> 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                                     
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[251,42] 找不到符号                                                                                                                                           
> 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.Config>,java.lang.String)                                                                                                                                                                        
> 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                                     
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[92,46] 找不到符号                                                                                                                             
> 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                                 
> 位置： 类 com.dianping.cat.hom    e.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                    
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[93,44] 找不到符号                                                                                                                             
> 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                                     
> 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                        
> [INFO] 6 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] parent ............................................ SUCCESS [1.387s]
> [INFO] cat-client ........................................ SUCCESS [19.699s]
> [INFO] cat-core .......................................... SUCCESS [16.065s]
> [INFO] cat-consumer ...................................... SUCCESS [59.264s]
> [INFO] cat-hadoop ........................................ SUCCESS [25.627s]
> [INFO] cat-home .......................................... FAILURE [1:31.624s]
> [INFO] broker-service .................................... SKIPPED
> [INFO] cat-agent ......................................... SKIPPED
> [INFO] cat-maven-plugin .................................. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 3:34.578s
> [INFO] Finished at: Sat Feb 28 14:32:36 CST 2015
> [INFO] Final Memory: 32M/254M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project cat-home: Compilation failure: Compilation failure:
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[53,45] 找不到符号                                                                                                                                     
> [ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                             
> [ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\BaseProcesser.java:[54,54] 找不到符号                                                                                                                                     
> [ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                         
> [ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                            
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[250,50] 找不到符号                                                                                                                                           
> [ERROR] 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.MetricItem>,java.lang.String)                                                                                                                                                       
> [ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                             
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\config\BaseRuleConfigManager.java:[251,42] 找不到符号                                                                                                                                           
> [ERROR] 符号： 方法 parseArray(java.lang.Class<com.dianping.cat.home.rule.entity.Config>,java.lang.String)                                                                                                                                                           
> [ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonParser                                                                                                                                                                                             
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[92,46] 找不到符号                                                                                                                             
> [ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.MetricItem>)                                                                                                                                                                              
> [ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                            
> [ERROR] F:\cat-master\cat-home\src\main\java\com\dianping\cat\system\page\config\processor\MetricConfigProcessor.java:[93,44] 找不到符号                                                                                                                             
> [ERROR] 符号： 方法 buildArray(java.util.List<com.dianping.cat.home.rule.entity.Config>)                                                                                                                                                                             
> [ERROR] 位置： 类 com.dianping.cat.home.rule.transform.DefaultJsonBuilder                                                                                                                                                                                                
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :cat-home
> 
> —
> Reply to this email directly or view it on GitHub.
>

**Comment by afredlyj** [comment]
我把所有模块下的target文件夹都删除了，算是一个干净的workspace了吧？

**Comment by afredlyj** [comment]
mvn 加-fae选项，其他模块都能成功，就cat-home会失败，还是老地方。

**Comment by afredlyj** [comment]
编译成功了，是我先前把codegen-maven-plugin的version改为了2.0.9，应该是2.0.14。
多谢。

**Comment by mars333** [comment]
codegen-maven-plugin 是干嘛的我也下不了
