### ISSUE TITLE
Cat服务端与客户端启动顺序问题

### ISSUE THREAD

**Issue by wadekun** [dianping/cat#742]
初次使用cat，试了几次，貌似只有在先启动客户端，在启动服务端的情况下，客户端的信息（domain）才会在监控服务端显示。如果客户端宕机、或者项目挂掉的时候再次启动客户端、或者在服务端运行时新增客户端项目，服务端仍旧不显示其domian。不知道是什么原因呢？是我哪里没有配置，还是CAT系统就是这样设计。

**Comment by youyong205** [comment]
点击导航的now的，可以看到最新的时间的domain。

导航是动态生成，比如这个小时有5个domain，导航就是5个，下个小时有10个，就是10个domain

**Comment by youyong205** [comment]
服务端和客户端的启动顺序没有影响的，建议你先pull下最新的code，从头搭建一边试试。

**Comment by wadekun** [comment]
我在客户端的集成有三步：
1：添加依赖client
![image](https://cloud.githubusercontent.com/assets/6241705/6498380/646b9426-c326-11e4-8c07-5a7d200275e6.png)
客户端只依赖了client
2：然后resource下配置domain信息
![image](https://cloud.githubusercontent.com/assets/6241705/6498394/8c15c94c-c326-11e4-9972-f77c161ae648.png)，
3：然后就是部署服务器上配置client.xml。。这三步。

**Comment by youyong205** [comment]
需要在/data/appdatas/cat/client.xml  指定cat服务端的地址。

不知道客户端是不知道服务器在哪里，数据发到哪里。你可以check下cat服务器的这个目录文件。

**Comment by wadekun** [comment]
嗯。client.xml 里面是有指定的，这三个步骤都是按照集成API来做的。不过日志报如下错误。
![image](https://cloud.githubusercontent.com/assets/6241705/6498645/5de6a502-c329-11e4-9fdf-52ee130fe608.png)
。。后面三个地址貌似是客户端请求服务端的一个URL返回的。。不知道这三个ip是怎么来的。

**Comment by youyong205** [comment]
/cat/s/config?op=routerConfigUpdate

**Comment by youyong205** [comment]
不过你的cat应该起来了，即使获取的错误的地址，消息会自动发送到你配置的一个地方。

监控数据也应该有的吧。

**Comment by youyong205** [comment]
可能你们那边的应用登录不了。我们这边使用ldap登录。有一些修改权限。回头我设定一个默认的用户名和密码也可以统一登录。

**Comment by wadekun** [comment]
恩恩。是的。。监控数据是有的。。但是会偶尔会出现我之前说的 domain丢失的情况。。而且在客户端更新或其他原因重启后。服务端相应的domain就 一直不显示了。正常的情况应该是服务端随时可以接受新配置的客户端的消息。。所以我才有  服务端客户端是否有启动顺序要求的疑问。

**Comment by youyong205** [comment]
domain丢失我还没有遇到，你下次遇到可以放一些截图上来。

除非客户端监控消息全部丢失了才会这样。

**Comment by wadekun** [comment]
恩恩。好的，因为比较急好多东西不太熟悉。。谢谢指点

**Comment by youyong205** [comment]
你是什么公司呀

**Comment by wadekun** [comment]
嘿嘿，南京的一家小公司

**Comment by youyong205** [comment]
南京的，我以前就南京读书的。以后有机会回母校和你们交流交流。

**Comment by youyong205** [comment]
能搭建起来用起来，这里面其实有很多高级的功能，搭建也更加复杂，不过即使简单的那么几个report，就能有很大作用了。

**Comment by wadekun** [comment]
哈哈。好的呀。。。叫你学长还是 前辈呢。。。有空要多向您学习
