### ISSUE TITLE
CAT如何部署使用？

### ISSUE THREAD

**Issue by haqiaolong** [dianping/cat#744]
您好，服务端我已经部署好了，客户端我通过配置web.xml形式也配置好了。。
  为什么在服务端看不到指标？是流程不对？还是求指导。。或者发我一份详细的部署流程

**Comment by youyong205** [comment]
服务端里面有文档。
/cat/r/home?op=view&docName=integration

**Comment by afredlyj** [comment]
客户端要配置web.xml？

**Comment by youyong205** [comment]
你看下写的文档，有教你怎么在本地跑起来。
