### ISSUE TITLE
怎样修改cat-client上传数据的目标服务器地址

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#745]
根据cat-client的代码，目标服务器的地址是通过`http://127.0.0.1:2281/cat/s/router?domain=Cat`地址获取的，这个值应该在哪儿配置？
另外，后台登录配置要怎样改？

**Comment by youyong205** [comment]
/cat/s/config?op=routerConfigUpdate

可以用catadmin catadmin登录

**Comment by afredlyj** [comment]
catadmin
这个配置是写死在代码里面的？
配置文件没找到啊

**Comment by afredlyj** [comment]
这个还是登录不了，还需要改什么配置吗？

**Comment by youyong205** [comment]
重新pull下code吧，留的一个后门账号登录的，其他是使用ldap登录
