### ISSUE TITLE
运行CatTest没有数据显示？

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#749]
运行mvn jetty:run后，CAT管理后台正常启动，但是运行cat-client中的CatTest测试上传数据，在cat-home没有正常显示。

还有其他地方要注意的吗？？

* update:

 重启完之后，能看到数据，但是点击`Log View`，无法查看详情，而是显示：  

>Sorry, the message is not there. It could be missing or archived.  

另外，数据似乎没有入库，服务重启之后，数据就没有了。

**Comment by youyong205** [comment]
这个我说不清楚，太笼统了。。
还是建议按照说明一步步搭建。很多人都OK没有问题。

数据一个小时一个小时才入库，不是实时插入数据库的。

**Comment by afredlyj** [comment]
一直按照流程走的，现在能看到每个纬度的数据，但是点击Log View，一直显示：

>Sorry, the message is not there. It could be missing or archived.

这也是数据没有实时入库的原因吗？

**Comment by youyong205** [comment]
logview 看不到，你check下是不是/data/appdatas/cat/bucket 下面是否有一些文件，这里用处存储原始的log

**Comment by afredlyj** [comment]
没有bucket 这个目录。

/data/appdatas/cat/目录下只有这几个文件。

2015-03-11 13:13 GMT+08:00 youyong205 <notifications@github.com>:

**Comment by afredlyj** [comment]
在server.xml中尝试添加节点解决：

~~~~  
<storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
</storage>   
~~~~

**Comment by youyong205** [comment]
或者你拉下code，用最新的里面默认的server.xml  看看能否解决问题
