### ISSUE TITLE
CAT war包部署在tomcat下报错

### ISSUE THREAD

**Issue by haqiaolong** [dianping/cat#751]
HTTP Status 500 - Error occured when handling uri: /cat/r

type Status report

message Error occured when handling uri: /cat/r

description The server encountered an internal error (Error occured when handling uri: /cat/r) that prevented it from fulfilling this request.
Apache Tomcat/6.0.13\

请问这个是什么原因？

**Comment by youyong205** [comment]
这个很难说的，还是建议按照说明一步步搭建。很多人都OK。

**Comment by jjeejj** [comment]
@haqiaolong 这个问题怎么解决的呢？ 我现在本地部署 tomcat 启动后访问，也是报的这个错
