### ISSUE TITLE
关于 CAT的sql 调用展示支持

### ISSUE THREAD

**Issue by wadekun** [dianping/cat#752]
CAT Transaction logview中打印的sql是需要手动埋点吗？还是只需配置下。
![caquestion2](https://cloud.githubusercontent.com/assets/6241705/6551151/df80bd94-c66e-11e4-82d6-2619f82b036f.png)

看到集成文档有：
![catquestion1](https://cloud.githubusercontent.com/assets/6241705/6551154/e6447aee-c66e-11e4-9076-fda8313b42c9.png)

**Comment by youyong205** [comment]
需要自己埋点的，上面这些都是我们点评内部自己的JAR，这些都已经做好埋点。

**Comment by wadekun** [comment]
哦，酱紫。谢谢

**Comment by youyong205** [comment]
任何监控都需要埋点~~~
