### ISSUE TITLE
cat 远程部署问题

### ISSUE THREAD

**Issue by haqiaolong** [dianping/cat#754]
您好，我现在想把CAT部署下服务器上 使用mysql配置
 请问怎么配置啊？ 文档里部署不是很清楚

**Comment by afredlyj** [comment]
我是找遍所有的配置，然后把mysql相关的都改了。

**Comment by youyong205** [comment]
现在我写了一份部署文档。

你们可以参考下，在/cat/r/home?op=view&docName=deploy

**Comment by haqiaolong** [comment]
需要重新 download吗?

**Comment by youyong205** [comment]
需要重新pull代码
