### ISSUE TITLE
Cat在tomcat中部署问题

### ISSUE THREAD

**Issue by wadekun** [dianping/cat#760]
关于Cat服务端在tomcat中部署，是直接把cat\cat-home\target\cat-alpha-1.3.0.war 发布在tomcat中就可以吗；本地把cat-alpha-1.3.0.war 部署在tomcat中访问报错
![cat tomcat](https://cloud.githubusercontent.com/assets/6241705/6613127/2243c0bc-c8c3-11e4-89c8-cf8b810354c8.png)

使用命令 mvn jetty:run 启动是没有问题的。

**Comment by afredlyj** [comment]
跟我一样

**Comment by wadekun** [comment]
。。。改下server.xml、client.xml中的 Http端口。
