### ISSUE TITLE
显示拓扑图

### ISSUE THREAD

**Issue by yancl** [dianping/cat#761]
Hi,我创建了两个原生服务A,B。没有使用web container 和web.xml。所以完全在代码中手动实现的MessageTree设置与获取,然后通过A访问B,目前调用关系以及Trace都可以在CAT中看到。

但是在Dependency列表下没有看到拓扑关系.请问需要我在LogEvent中指定A,B的domainName吗？

谢谢。

**Comment by youyong205** [comment]
恩，是的。需要用logEvent的方式表达显示的依赖关系。
t13:04:22.058	PigeonCall	shoplistService:myListService_2.0.0:getCorrelatedLists(int,List)		
  E13:04:22.058	PigeonCall.server	10.1.108.10:2027	 	[5, [8972444]]
  E13:04:22.058	PigeonCall.app	shoplist-server	 	
  E13:04:22.058	PigeonCall.requestSize	<1k	 	289
  [:: show ::]	
T13:04:22.326	PigeonCall	shoplistService:myListService_2.0.0:getCorrelatedLists(int,List)	 	268ms CallType=sync&Timeout=1000

**Comment by yancl** [comment]
谢谢。
我通过Http协议实现了两个单独应用,一个是hellocat(localhost:8000),一个是worldcat(localhost:80001),然后访问/hellocat，显示的日志如下,明确可以看到client domain(helloClient)到world domain(worldServer)之间的Trace数据,但是还是没有发现dependency graph里面有数据，请问下面的数据有什么问题吗？
据我所知的，该记录的数据都记录了:(


t11:36:43.668	URL	http://localhost:8000/hellocat		
  t11:36:43.668	PigeonCall	http://localhost:8001/worldcat		
    E11:36:43.736	PigeonCall.app	worldServer	 	
    E11:36:43.736	PigeonCall.server	127.0.0.2	 	
    E11:36:43.736	PigeonCall.port	8001	 	
    [:: hide ::]	
        t11:36:47.576	PigeonService	http://localhost:8001/worldcat		
        E11:36:47.577	PigeonService.client	127.0.0.1	 	
        E11:36:47.577	PigeonService.app	helloClient	 	
        T11:36:47.594	PigeonService	http://localhost:8001/worldcat	 	18ms
   T11:36:47.807	PigeonCall	http://localhost:8001/worldcat	 	4139ms CallType=sync
T11:36:47.808	URL	http://localhost:8000/hellocat	 	4140ms

**Comment by youyong205** [comment]
看起来数据没有问题，依赖关系是需要调用才有，也就图上面11点36分钟才有依赖关系调用。

**Comment by yancl** [comment]
请问一下,你这里说的"需要调用才有的"指的是?或者你那里方便提供一下你们用来测试这个dg代码正常的代码吗?我在我本地运行一下,查看一下输出差异。我这里从安装CAT之后就没有看到dg显示过,所以很好奇。最近事情有些多,我想先让他工作起来,不然我可以查看一下相关代码:)
