### ISSUE TITLE
求集成文档

### ISSUE THREAD

**Issue by yangchenhui** [dianping/cat#766]
你好，
      1.找了一上午资料，度娘上只有一份github的主页复制
      2.ISSUES从头看到尾，希望能找到点东西，结果发现只有一个架构的讲解，文档据说是需要启动起来服务端才能看到。
      3.代码down下来之后，mvn install不成功，codegen依赖一直找不到，翻墙也不行
       
求一份集成文档，用来评估下项目是否适合我们的在建项目，感激不尽，或者由打包好的war给运行也行

**Comment by youyong205** [comment]
travis ci 都能build成功。你们是不是哪里环境出了点问题。

首页上最后有部分是用来引导你怎么安装的，有几个步骤，可以step by step试试。

**Comment by yangchenhui** [comment]
codegen-maven-plugin.jar下载不下来，中央仓库好像么有，git仓库也连不上,下载下来源码build也报错，现在就想要个集成文档，评估下是否可以使用在我们项目中，可以的话再深入研究。 谢谢

**Comment by qmwu2000** [comment]
在mvn-repo branch上有codegen-maven-plugin的。


发自我的 iPhone

**Comment by youyong205** [comment]
集成文档写在里面的jsp里面，在jsp/report/page/home 下。
