### ISSUE TITLE
cat测试环境部署问题

### ISSUE THREAD

**Issue by dlyss** [dianping/cat#770]
我在resin上部署了cat，resin及cat相关端口都正常启动，但访问时报：/cat/r was not found on this server.  想咨询下该url的匹配规则是怎样的，它找的是那个类或页面。（本地testserver方式没问题）。
另外，我看部署文档的jvm参数分配的堆空间都挺大，这是基于cat程序需要？谢谢

**Comment by youyong205** [comment]
resin没有玩过，我不知道里面具体是什么，你可以用tomcat试试，丢进webapps就行了。

jvm参数堆很大，那是服务端的程序，当然是我们这边的一些配置，因为处理的消息比较多，这个可以根据实际情况来。

**Comment by dlyss** [comment]
好的，谢谢
