### ISSUE TITLE
公司推广cat时需要一些完整的资料

### ISSUE THREAD

**Issue by xirong** [dianping/cat#772]
@youyong205 ，好，我看过cat的视频分享，正好自己公司也要做这块，规划的挺大，时间上是个很大的问题，既然你们已经做了这套东西，你们线上运行的还不错，而且很多功能和我们计划的类似，为了节省时间，想定制下我们自己的内容然后推广到线上，现在的问题是要说服领导使用，需要些资料，网上搜素到的都是你们13年14年初时候的PPT了，能提供下最新的说明资料么？

**Comment by youyong205** [comment]
你可以本地搭建起来，就可以看到实际的demo了，demo比任何资料都有好，另外文档也基本写在里面。

**Comment by xirong** [comment]
嗯，好的~ 多谢
