### ISSUE TITLE
客户端发送消息的逻辑

### ISSUE THREAD

**Issue by dlyss** [dianping/cat#777]
你好，客户端搭建完成，但实际测试中服务端未收到消息。请问下客户端发送的逻辑：达到某一时间值或缓存满 或其他阈值达到就发消息到服务端。谢谢

**Comment by youyong205** [comment]
check下客户端机器/data/appdatas/cat/client.xml 里面配置的ip
发送是实时的

**Comment by dlyss** [comment]
好的，谢谢。
