### ISSUE TITLE
允许用户添加自己的extension到heartbeat报表中

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#787]
提供一种机制，让用户注册自己的回调方法，收集自定义的性能数据，发送自定义的extension到heartbeat报表中。

**Comment by huang--yijian** [comment]
这个需求得到了Frankie的支持。我在pull request中给的实现，其思路也得到Frankie的同意。
StatusUpdateTask从plexus容器获取用户注入的StatusExtensionBuilder。每一分钟，生成heartbeat报表时，执行这个StatusExtensionBuilder，获取用户自定义的heartbeat数据。

**Comment by youyong205** [comment]
StatusExtensionRegister.getInstance()  这个本来就有的。我们这边已经用上了

**Comment by huang--yijian** [comment]
哦。之前我没看到。但是Frankie和我觉得你的实现需要编程来注册extension，没有依赖注入的方式好。

**Comment by huang--yijian** [comment]
另外一个问题是，StatusExtension没有默认的实现，对用户来说不太方便。要自己从零搞个实现。

**Comment by youyong205** [comment]
本来就不需要默认实现吧，这个是spi，就是用来给用户实现的。

依赖注入不太好吧，个人感觉。注册对业务简单，他获取一个单例就行了，不然还需要自己写pleux的什么实现，后者更加不现实
