### ISSUE TITLE
CAT客户端取IP，没有考虑NetworkInteface为Loopback，但旗下InetAddress不是Loopback的情况

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#790]
我们在生产环境发现特殊情况：
一个网卡对象（NetworkInteface）的isLoopback()为true，
而其下一个InetAddress的isLoopbackAddress()为false。

所以，在忽略lookback address时，要考虑NetworkInterface.isLookback()，不能只考虑InetAdress.isLoopbackAddress()。

生产环境的网卡配置如下，导致了问题：
eth0      Link encap:Ethernet  HWaddr 00:50:56:92:27:24  
          inet addr:10.8.13.94  Bcast:10.8.13.255  Mask:255.255.255.0
          inet6 addr: fe80::250:56ff:fe92:2724/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3683730801 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5818588005 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:536065016720 (499.2 GiB)  TX bytes:5811339333590 (5.2 TiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:61851 errors:0 dropped:0 overruns:0 frame:0
          TX packets:61851 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:15278444 (14.5 MiB)  TX bytes:15278444 (14.5 MiB)

lo:0      Link encap:Local Loopback  
          inet addr:10.8.13.246  Mask:255.255.255.255
          UP LOOPBACK RUNNING  MTU:16436  Metric:1

lo:1      Link encap:Local Loopback  
          inet addr:10.8.13.247  Mask:255.255.255.255
          UP LOOPBACK RUNNING  MTU:16436  Metric:1

我们想取到10.8.13.94，但程序错误地取到了10.8.13.246
对于10.8.13.246，Loopback是网卡上的属性，不是InetAddress的属性。

**Comment by huang--yijian** [comment]
Frankie在foundation service 2.2.1中已经fix了这个问题。新版会考虑NetworkInterface.isLoopback()的。
请在CAT Java客户端中引用foundation service 2.2.1，并调用Networks类获取IP。

这样，可以忽略我在pull request中的fix。

**Comment by youyong205** [comment]
ok

**Comment by pingpong006** [comment]
我在生产环境也复现了这个问题，cat-client版本3.0.0。
