### ISSUE TITLE
Truncate child transaction的操作会导致极短的root transaction被reset()掉，root transaction丢失

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#792]
我用以下例子说明问题：

Transaction rootTransaction = Cat.newTransaction(...);
Thread.sleep(2 hour);

// 由于childTransaction和rootTransaction相差超过了(1小时+10秒)，
// 导致触发了 addTransactionChild() 调用 truncateAndFlush()，即触发了截短transaction操作。
// 接着，truncateAndFlush() 调用 flush()调用reset()
// 如果此时context的duration为0，reset()会清空整个context （即m_context.remove()）。
// 这种情况常见，正如这个例子。
Transaction childTransaction = Cat.newTransaction(...);
childTransaction.setStatus("0");
childTransaction.complete();

rootTransaction.setStatus("0");
// 由于整个context被上文中的reset()清空了，导致这里的complete()没有把rootTransaction发出去。因为此时context==null。
// 所以整个截短的效果很奇怪：logview中，RemoteCall event有，但是Transaction报表中看不到root transaction。
rootTransaction.complete();

解决方案：
在reset()中去掉以下逻辑：
if (ctx.m_totalDurationInMicros == 0) {
   ctx.m_stack.clear();
   m_context.remove();
}

不能随意清空m_stack。只能依靠transaction.complete()按顺序清空。

**Comment by youyong205** [comment]
sleep 2hour，这个本身就不支持。消息传输到后端也会丢弃。

**Comment by youyong205** [comment]
接着，truncateAndFlush() 调用 flush()调用reset()// 如果此时context的duration为0，reset()会清空整个context （即m_context.remove()）。

这个时候context的duration不会为0的，duration会加上已经待发送出去的消息的duration。

**Comment by huang--yijian** [comment]
sleep 2hour 我认为需要的。我这里有一些长时间的Job要埋点，所以会有长达数小时的transaction。这个需求还是很普通的吧。

**Comment by youyong205** [comment]
这个就不支持，设计就是这样，sleep2 hour，不会有这样的case的。

**Comment by huang--yijian** [comment]
我和Frankie聊过。Sleep 2 hour不认为是一个合理的case。正常情况下，应该在这段时间内打一些埋点
