### ISSUE TITLE
dependency graph 中 如果出现双向依赖，存在bug

### ISSUE THREAD

**Issue by BlackScai** [dianping/cat#796]
![111](https://cloud.githubusercontent.com/assets/7445275/7224247/0ead1298-e762-11e4-8c48-1f0bd4ea35b6.jpg)
图中，15210 15219 和中心点150732 存在双向依赖，15210 15219点存在2个，两条边只画在其中一个点上，导致另一个点成为孤立的点。

**Comment by youyong205** [comment]
双向依赖一直不支持的。这个就说明是双向依赖出问题的。
