### ISSUE TITLE
Metric不工作，因为新的Metric都被忽略掉了

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#797]
假设用户通过Cat.logMetric()记一个从来没出现过的新Metric，并希望看到实时的这个新Metric的业务大盘。

1.  在CAT客户端中，logMetric(String name, String status, String nameValuePairs)会把新建的Metric对象的type设为空字符串（“”）

2.
在MetricAnalyzer中的processMetric(MetricReport report, MessageTree tree, Metric metric)里面，
有判断 if (StringUtils.isNotEmpty(group)) {... // 创建productLine }。
因为这里的group就是第1点中的Metric对象的type，所以结果为false，导致MetricReport report为null。
系统没有机会调用MetricAnalyzer.findOrCreateReport()，来第一次创建MetricReport。

所以，接下来，if (config != null && report != null) {...} 也为false。其中的metric记录逻辑没有走到。

如此一来，等于所有通过Cat.logMetricForCount(), Cat.logMetricForSum()等记下的Metric，全部被忽略掉了。

**Comment by youyong205** [comment]
在CAT客户端中，logMetric(String name, String status, String nameValuePairs)会把新建的Metric对象的type设为空字符串（“”）
这个接口是废弃的接口。

**Comment by huang--yijian** [comment]
那么正确的记Metric的接口是什么？

**Comment by huang--yijian** [comment]
找到问题了，我们的配置有错——一个domain属于了多个product line。现在metric曲线出来了。
