### ISSUE TITLE
Metric的type不应该与productLine匹配

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#798]
当查询Metric时，LocalModelService调用MetricAnalyzer.getReport( Product Line )——即根据用户在metric.jsp中选择的业务线(Product Line)查询。

接着，在MetricAnalyzer.getReport()里面，会把Product Line和CAT客户端记的Metric的type作匹配。

我觉得这样不合理。
因为在CAT客户端里，通过Cat.logMetricForCount()记录的Metric的type是固定的空字符串。所以导致匹配永远不成立，总是拿不到Metric数据。

**Comment by youyong205** [comment]
需要到后面config，productline和domain的对应关系。

**Comment by huang--yijian** [comment]
找到问题了，我们的配置有错——一个domain属于了多个product line。现在metric曲线出来了。
