### ISSUE TITLE
求cat broker API文档

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#800]
我们公司的移动端访问数据想接入CAT的app => 访问量分布 报表。

从代码可知，需要调用CAT broker的http接口（即broker/api/page/batch|connection|speed/Handler.java）发送这些数据给CAT。
数据格式似乎是\n分隔不同的记录，\t分隔不同的字段。但是具体内容不详。

请问http接口及其数据格式是什么样的？有没有API文档？
或者给我们一些示例数据（包含注释说明字段名称和类型）参考？

**Comment by huang--yijian** [comment]
另外，有没有Java客户端调用CAT broker的？

**Comment by youyong205** [comment]
文档里面接口文档，写的应该很清楚。

**Comment by huang--yijian** [comment]
谢谢。我找到CAT自带的相关文档了。

**Comment by HouZhiHouJue** [comment]
cat broker的war包 貌似没有看见

**Comment by chinaboard** [comment]
broker已经不开源了，有需求的话拉旧版本






On Thu, Dec 17, 2015 at 12:14 AM -0800, "灬后知后觉" <notifications@github.com> wrote:












cat broker的war包 貌似没有看见
