### ISSUE TITLE
Cat客户端后台线程占用多少内存？

### ISSUE THREAD

**Issue by wadekun** [dianping/cat#802]
想问下，单个集成了Cat的客户端，Cat的后台的消息队列、发送消息线程等操作大概占用多少内存，有没有官方的测试数据呢？

**Comment by youyong205** [comment]
影响5%以内吧

**Comment by wadekun** [comment]
占tomcat配置内存的5%？

**Comment by youyong205** [comment]
总共内存消耗和应用埋点相关吧。几十M吧，最多了。

**Comment by wadekun** [comment]
好吧，之前出现过内存告警的情况，把端口2280 占用清掉后，释放了10G内存，并且这台服务器只部署了两个应用。。

**Comment by wadekun** [comment]
好像是 关闭tomcat的时候，Cat的后台进行没有干掉。重新启动，又重新启动了一个进程。。难道每次都需要手动 kill 吗？

**Comment by youyong205** [comment]
进程关闭不掉都需要kill的，这个可以写在脚本里面。
