### ISSUE TITLE
highchart 折线图（line chart）的数据源里有null点，导致整条曲线渲染不出来。

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#806]
对于提供给highchart的series（数据点的数组），如果一个点为0，那么其值应该表示为0.0，不能是null。

在linechart.jsp中，有var data = ${model.lineChart.jsonString};
我们发现运行时，data变成了这样：
var data = { ... ,"values":[],"valueObjects":[[..., null,null,10000.0,null,25712.0.0,null, ...]]

这里的null, 导致highchart理解不能，***不仅是零点，整条曲线都渲染不出来***。
所以，应该修正为：
var data = { ... ,"values":[],"valueObjects":[[..., 0.0,0.0,10000.0,0.0,25712.0,0.0, ...]]

修正前的效果，如下图：
![image](https://cloud.githubusercontent.com/assets/7484190/7534029/21e639f2-f5a9-11e4-95f7-59887a7f9455.png)

修正后的效果，如下图：
![image](https://cloud.githubusercontent.com/assets/7484190/7534031/253dab62-f5a9-11e4-9baa-55ab5963200c.png)

代码fix我贴在回复中。这未必是最佳的fix点，仅供参考。

**Comment by huang--yijian** [comment]
我们的代码fix:
diff --git a/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppConnectionService.java b/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppConnectionService.java
index d0d352f..1fc4c89 100644
--- a/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppConnectionService.java
+++ b/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppConnectionService.java
@@ -119,6 +119,11 @@ public class AppConnectionService {
 		int n = convertedData.getDuration();
 		Double[] value = new Double[n];
 
+        // ctrip yj.huang replace null with 0.0, for highchart to render zero points correctly
+        for (int i = 0; i < value.length; i++) {
+            value[i] = 0.0;
+        }
+
 		for (Entry<Integer, List<AppConnectionData>> entry : convertedData.getRecords().entrySet()) {
 			for (AppConnectionData data : entry.getValue()) {
 				double count = data.getAccessNumberSum();
diff --git a/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppDataService.java b/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppDataService.java
index 95f8e5d..5583228 100644
--- a/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppDataService.java
+++ b/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppDataService.java
@@ -119,6 +119,11 @@ public class AppDataService {
 		int n = convertedData.getDuration();
 		Double[] value = new Double[n];
 
+        // ctrip yj.huang replace null with 0.0, for highchart to render zero points correctly
+        for (int i = 0; i < value.length; i++) {
+            value[i] = 0.0;
+        }
+
 		for (Entry<Integer, List<AppCommandData>> entry : convertedData.getRecords().entrySet()) {
 			for (AppCommandData data : entry.getValue()) {
 				double count = data.getAccessNumberSum();
diff --git a/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppSpeedService.java b/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppSpeedService.java
index 0b1d07a..84f17fa 100644
--- a/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppSpeedService.java
+++ b/cat-home/src/main/java/com/dianping/cat/report/page/app/service/AppSpeedService.java
@@ -192,6 +192,11 @@ public class AppSpeedService {
 		int n = convertedData.getDuration();
 		Double[] value = new Double[n];
 
+        // ctrip yj.huang replace null with 0.0, for highchart to render zero points correctly
+        for (int i = 0; i < value.length; i++) {
+            value[i] = 0.0;
+        }
+
 		for (Entry<Integer, List<AppSpeedData>> entry : convertedData.getRecords().entrySet()) {
 			for (AppSpeedData data : entry.getValue()) {
 				double count = data.getAccessNumberSum();

**Comment by youyong205** [comment]
应该就是用null，没有数据就是null，而不是0

**Comment by huang--yijian** [comment]
那么我这个整条线都不能渲染的问题应该如何解决？
你们没有遇到过吗？

**Comment by youyong205** [comment]
那是数据量太少的问题，正常情况不会的，如果把null作为0，这样曲线就升或者降，很难看
