### ISSUE TITLE
ProductLineConfigManager类的m_metricProductLines可见性？

### ISSUE THREAD

**Issue by afredlyj** [dianping/cat#808]
ConfigReloadTask负责周期性更新配置项，同时其他业务线程会读取m_metricProductLines中的值，这个对象不需要volatile保证可见性吗？

**Comment by youyong205** [comment]
最后会把这个量修改引用的

**Comment by afredlyj** [comment]
就因为修改引用，所以只需要volatile，而不是加锁。

**Comment by youyong205** [comment]
yes
