### ISSUE TITLE
在“API 访问趋势”报表中的“项目”、“命令字”下拉列表中，允许用户输入过滤条件

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#809]
在“API 访问趋势”报表中，我们的“项目”、“命令字”的下拉菜单很长，用户查找、选择很不方便。

所以，我们需要允许用户输入关键字，以过滤下拉菜单中的候选项。
即使用jquery autocomplete控件替换普通的下拉菜单。

实现后的效果：
1 用户什么都不输入，只是单击文本框，还是下拉菜单的效果
![image](https://cloud.githubusercontent.com/assets/7484190/7582027/3e107ed8-f8bc-11e4-9bc2-9732c2586a03.png)

2 用户输入关键字，可以过滤下拉菜单中的候选项
![image](https://cloud.githubusercontent.com/assets/7484190/7582034/5cb00e3a-f8bc-11e4-9833-608694deb051.png)

![image](https://cloud.githubusercontent.com/assets/7484190/7582170/a85fb1ae-f8bd-11e4-87f2-9a28bc34db9d.png)

目前，只在“API 访问趋势”报表中实现了这一效果。其他报表的实现方式估计类似。

**Comment by youyong205** [comment]
赞

**Comment by youyong205** [comment]
我拉下来code，发现不work，我自己实现下好叻。

**Comment by huang--yijian** [comment]
奇怪，不work? 你后来自己实现，有发现不work的原因吗？

**Comment by huang--yijian** [comment]
你是有js error报错吗？有没有详细的错误信息？

**Comment by youyong205** [comment]
我们自己重新做了一份，等下你们pull code吧。
event合并我也搞好了。
