### ISSUE TITLE
请教agent事务采集原理

### ISSUE THREAD

**Issue by rayshen3** [dianping/cat#811]
您好，我们是scala 应用，主要是后端服务，单纯的java环境。现在想在线上使用cat系统，目前处于调研阶段，看完部署、配置手册，发现agent端只装了一个war包，想请教下它是如何拿到各种事务的？

比如：某个接口的调用次数，某段代码的执行时间和次数等等，单纯靠监听拿不到吧，是不是需要应用代码里做些修改。

我是运维，考虑的是对代码无污染可能会更好，麻烦能简单解答一下吗?  或者是我理解的不够多，谢谢。

ps: 有没有cat技术沟通的群或者社区，想跟大家一起讨论   ^_^

**Comment by youyong205** [comment]
agent其实现在用不到，主要是cat-client，需要和应用集成集成。

对代码无污染，是做不到的。

**Comment by rayshen3** [comment]
回头又看了看相关文档，大致明白了，现在需要跟RD sync下，感谢回复！
