### ISSUE TITLE
event横向报表实时性不如transaction横向报表？请review event横向报表配置

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#817]
对于跨domain的横向报表，
transaction的横向报表是在查询时统计的；
event的横向报表是在每小时做checkpoint时统计的。
两者的行为请统一一下？

另外，为什么我们手动调用checkpoint，event横向报表还是出不来？
我们的配置如下：

<all-config>
	<report id="transaction">
		<type id="URL">
			<name id="*"></name>
		</type>
	</report>
	<report id="event">
		<type id="DAL.version">
			<name id="*"></name>
		</type>
		<type id="Redis.version">
			<name id="*"></name>
		</type>
                <type id="SOA2Service.version">
			<name id="*"></name>
		</type>
		<type id="SOA2Client.version">
			<name id="*"></name>
		</type>
		 <type id="ESBClient.version">
			<name id="*"></name>
		</type>
	</report>
</all-config>

**Comment by youyong205** [comment]
问题已经fix了
