### ISSUE TITLE
speed.jsp：“页面”选择框需要根据URL参数初始化； 判断空字符串有误

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#824]
在speed.jsp中，

1. “页面”选择框应该初始化为当前URL中的页面参数所指向的页面，即增加以下逻辑：

 if(typeof words[1] != "undefined"  && words[1].length > 0) {
     $("#page").val(words[1]);
 }

2. 一个判断空字符串的逻辑中，|| 应该改为 &&。否则浏览器报Null reference错误，即：

-if(step['title'] != undefined || step['title'].length > 0){
+if(step['title'] != undefined && step['title'].length > 0){

如果speed.jsp界面还有其他类似bug，请一并fix。谢谢。

**Comment by huang--yijian** [comment]
diff文件截图：
![image](https://cloud.githubusercontent.com/assets/7484190/7978727/76185d0c-0acb-11e5-961f-594d57fe44e4.png)

**Comment by jialinsun** [comment]
谢谢提醒，相关bug会一并修复。
