### ISSUE TITLE
将代码导入到eclipse中一直报错

### ISSUE THREAD

**Issue by wn905** [dianping/cat#833]
使用eclipse的java ee IDE版本，eclipse-jee-luna-SR2-linux-gtk-x86_64

使用import功能，导入到eclipse中，之前也尝试了mvn eclipse:eclipse
报错截图如下：

![2015-06-21 19 50 40](https://cloud.githubusercontent.com/assets/4796332/8271610/f808e702-1852-11e5-900a-b0c23aec6beb.png)

**Comment by qmwu2000** [comment]
请不要以maven project方式导入，以正常的java项目导入。


发自我的 iPhone
