### ISSUE TITLE
最新Master版本，按照文档走，最后一步启动，报错。appdatas\cat 下面config文件都有

### ISSUE THREAD

**Issue by mt830813** [dianping/cat#836]
以下是详细报错信息。
[06-24 15:39:37.722] [ERROR] [ServletHolder] Servlet initializing failed. org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

![image](https://cloud.githubusercontent.com/assets/5535178/8325091/1d93dc06-1a89-11e5-89c8-2fea3ac2481c.png)
配置文件截图

**Comment by mt830813** [comment]
尝试按照说明文档放入tomcat 还是同样的报错。Http 500

**Comment by coffeesweet** [comment]
我也遇到这种问题，按照操作文档一步一步走的。

![33](https://cloud.githubusercontent.com/assets/982472/8332132/ce043df8-1abe-11e5-8d52-363bda7b216f.jpg)

**Comment by coffeesweet** [comment]
下面是root cause
![44](https://cloud.githubusercontent.com/assets/982472/8345232/bddba6e0-1b1e-11e5-97d2-04e8e650f90b.jpg)

**Comment by xfworld** [comment]
是不是环境没准备好？貌似缺少必要的jar包

**Comment by youyong205** [comment]
你们在本地运行mvn eclipse:eclipse 然后作为普通项目倒入eclipse，然后运行cat-home里面的testserver试试

**Comment by mt830813** [comment]
作为maven项目放入 Intellij中，能运行。但是出现404错误。如截图。
![image](https://cloud.githubusercontent.com/assets/5535178/8346217/0a38d83e-1b2c-11e5-8a6d-ac96f013d473.png)

**Comment by mt830813** [comment]
![image](https://cloud.githubusercontent.com/assets/5535178/8346231/2d2f6c54-1b2c-11e5-9d46-20cbd8f155e0.png)

**Comment by mt830813** [comment]
使用 mvn eclipse:eclipse 后 还是和楼上一样的能运行，但是404

**Comment by coffeesweet** [comment]
你们在本地运行mvn eclipse:eclipse 然后作为普通项目倒入eclipse，然后运行cat-home里面的testserver试试

这种可以，为什么呢？奇怪了

**Comment by mt830813** [comment]
是否是因为是部署在windows中？我看了一下issue 历史，好像有好几个也是和我一样的问题，但是都没有真正的解决。

**Comment by coffeesweet** [comment]
是否是因为是部署在windows中？我看了一下issue 历史，好像有好几个也是和我一样的问题，但是都没有真正的解决。

我打成war包后扔到linux上报的下面这个错误：
![44](https://cloud.githubusercontent.com/assets/982472/8346293/0c1a1d10-1b2d-11e5-9b26-2c747753c14e.jpg)

**Comment by coffeesweet** [comment]
重新pull代码以后，本地 mvn eclipse:eclipse后运行也报上面的错，配置了相应的client.xml,server.xml,datasource.xml等

**Comment by coffeesweet** [comment]
master版本不行，release版本的zip包直接下载可以

**Comment by mt830813** [comment]
试试

**Comment by mt830813** [comment]
没找到Release Branch呀。楼上有地址么？

**Comment by mt830813** [comment]
你用的是1.03这个版本么？去年1月份的版本呀。有点老了吧？

**Comment by coffeesweet** [comment]
只有这个版本能跑起来。。。

**Comment by mt830813** [comment]
以下链接也是类似问题。
https://github.com/dianping/cat/issues/820

**Comment by coffeesweet** [comment]
连接里面并没有解决问题，而且作者说的那个用docker的问题和#820描述的不一样，那个是把端口弄错了，找不到资源，我们这个是500服务错误，麻烦作者看看，现在的master按照操作步骤确实跑不起来。

**Comment by youyong205** [comment]
你们在本地运行mvn eclipse:eclipse 然后作为普通项目倒入eclipse，然后运行cat-home里面的testserver试试. 如果这种可以说明至少编译一切都OK的。

另外导入到tomcat的，因为tomcat 默认是8080起来的，所以/data/appdata/cat/server.xml  需要改个配置。
 <remote-servers>127.0.0.1:2281</remote-servers> 改为8080端口。

master用的code和我现在点评内部用的code是一样的。

**Comment by mt830813** [comment]
导入TomCat后，端口配置是正确的，并且通过/cat去访问可以正确的hit到应用，这点从日志可以看到。
但是还是一样的报错信息。
![image](https://cloud.githubusercontent.com/assets/5535178/8349484/e02db37e-1b4f-11e5-846a-39bb5a9f1558.png)
可以看到是一样的报错。
无论Tomcat还是jetty都是一样的报错信息。
不知道点评是部署在linux还是windows下面？？
并且版本是什么？我试过server 2012和 win 8，都是相同的问题。

**Comment by mt830813** [comment]
有木有交流群呀？这样的沟通效率有点慢。
我们公司现在正在考虑使用Cat作为日志引擎，由于我们是.net环境，所以需要对Cat进行一下考察，看是否能满足我们现在的需求以及满足我们现在的规模所需要的易用性。
但是目前没有办法跑起来就很让人丧失信心了。

**Comment by coffeesweet** [comment]
哥们，你把/data/appdata/cat/client.xml这个文件先去掉试试

**Comment by jialinsun** [comment]
@mt830813 : 部署在centos上的。我们都是在Eclipse上通过导入Java项目引入的，Intellij支持不太好。

**Comment by mt830813** [comment]
好吧，我还是搞一台linux试试吧。

**Comment by mt830813** [comment]
@coffeesweet 我尝试把client.xml文件删除了重启tomcat后，还是一样的报错。

**Comment by coffeesweet** [comment]
建议整个qq群

**Comment by mt830813** [comment]
@youyong205 @jialinsun 
经测试，相同的部署方式，ubuntu上可以正确的看到文档了。
但是在windows 2008和server 2012环境下面部署失败。
初步估计是跑在windows上有一些问题。

**Comment by mt830813** [comment]
@coffeesweet 建议你还是使用最新版的cat在linux环境下部署。

**Comment by mt830813** [comment]
@youyong205 @jialinsun 
能否加我一下qq：443344315
后面也方便交流一下Cat的问题

**Comment by raddle60** [comment]
我也是用master，通过命令行打出来的war包，放到tomcat中启动，也报这个错误。
不过eclipse中使用testserver可以启动。
最后发现还是编译出来的class有差别，具体不知道什么差别。命令行编译出来的比eclipse编译出来的class每个类多一个文件，像是内部类的文件。但实际上没有内部类。反编译比较后也只有一些变量名上的差别。
将cat-home\target\classes下面的classes覆盖到war包里的classes就可以正常启动

**Comment by qmwu2000** [comment]
很好的发现！可以告知是具体是哪个类吗？我可以看一下


发自我的 iPhone

**Comment by moujian** [comment]
"Caused by: java.lang.RuntimeException: Duplicated name(home) found between handleInbound() and handleInbound() of class com.dianping.cat.report.ReportModule"
如果出错的root exception是上面这个那么，确保jdk是1.7 及一下。
@qmwu2000 
这个bug出现在jdk8里面，上次debug这个问题到 org.unidal.web.mvc.model.ModelManager.buildModuleFromMethods(ModelManager.java:179) 里面
supermethod.getAnnotation 返回了 childmethod的annotation "InboundActionMeta".

不知道是不是和http://stackoverflow.com/questions/26515016/annotations-on-an-overridden-method-are-ignored-in-java-8-propertydescriptor 有关， 不过也和用到的proxy有。

**Comment by qmwu2000** [comment]
研究了一下，貌似jdk8的bug。


发自我的 iPhone

**Comment by moujian** [comment]
还是plexus container 返回的org.codehaus.plexus.ContainerHolder.lookup()返回的class出的问题。

更新用最新的plexus container问题消失了，估计是plexus fix了这个bug     
<dependency>
	<groupId>org.codehaus.plexus</groupId>
	<artifactId>plexus-container-default</artifactId>
	<version>1.6</version>
	<exclusions>
		<exclusion>
			<artifactId>google-collections</artifactId>
			<groupId>com.google.collections</groupId>
		</exclusion>
	</exclusions>
      </dependency>
      
   </dependencies>

**Comment by pengkw** [comment]
我这个边的是将data目录下的datasources.xml文件删除掉的话可以正常启动，加上这个文件就报错ava.lang.RuntimeException: Unable to get component: interface com.dianping.cat.analysis.MessageConsumer

**Comment by pengkw** [comment]
搞定了，是我的datasources.xml文件配置有问题

**Comment by enyesFang** [comment]
我也出现了相同的情况。我的环境主要是：Mac、JDK8、TOMCAT8、IntelliJ。错误原因JDK8。重新安装JDK7，并重新打包后，启动正常。

**Comment by raddle60** [comment]
@qmwu2000 很好的发现！可以告知是具体是哪个类吗？我可以看一下
这个我一直没回，最近没上来。我是在windows 7 64位上编译的，jdk 8 1.8.0_45编译的。
我把文件截图放在附件。很多类都会多一个文件。
这是eclipse编译出来的class
![eclipse-class](https://cloud.githubusercontent.com/assets/8675208/12437885/c5dacc76-bf5c-11e5-9235-c62bad08ae06.png)
这是通过maven命令编译cat-home出来的类，多一个$1的class文件
![maven-class](https://cloud.githubusercontent.com/assets/8675208/12437895/d04ddad6-bf5c-11e5-884f-228a7b407afb.png)
这是maven命令中途报过的一个错误
![maven-error](https://cloud.githubusercontent.com/assets/8675208/12437908/da273e26-bf5c-11e5-90e4-7f2bdfbd80f9.png)
这是编译出来的class文件
[class文件.zip](https://github.com/dianping/cat/files/96853/class.zip)

**Comment by qmwu2000** [comment]
呵呵，看来plexus-maven-plugin在windows下要bug，我会想办法fix下。


发自我的 iPhone

**Comment by czwer** [comment]
我也遇到这个问题里，最后解决了，参：https://www.oschina.net/question/584441_2203579

**Comment by avajing** [comment]
@pengkw 搞定了，是我的datasources.xml文件配置有问题

一语惊醒梦中人，大家都是聪明反被聪明误啊。我是事前就搞好了数据库，手动建库导表，后来运行 CAT 安装插件命令  maven cat:install  。其中需要输入jdbc:mysql://127.0.0.1:3306。而我自作聪明在后面加入了/cat。其实这条命令就是自动建库并生成配置文件。其后我查看datasources.xml，返现用户名密码都是正确的，以为命令把这个文件配置好了。 其实URL是“jdbc:mysql://127.0.0.1:3306/cat/cat” 。这才导致了我这个错误。 修改此文件，重启tomcat就OK了。
结语：还是谷歌靠谱，百度了N久无法解决。我是jdk 1.7 64位的。

**Comment by zhousiyuan0428** [comment]
> @pengkw 搞定了，是我的datasources.xml文件配置有问题
> 
> 一语惊醒梦中人，大家都是聪明反被聪明误啊。我是事前就搞好了数据库，手动建库导表，后来运行 CAT 安装插件命令 maven cat:install 。其中需要输入jdbc:mysql://127.0.0.1:3306。而我自作聪明在后面加入了/cat。其实这条命令就是自动建库并生成配置文件。其后我查看datasources.xml，返现用户名密码都是正确的，以为命令把这个文件配置好了。 其实URL是“jdbc:mysql://127.0.0.1:3306/cat/cat” 。这才导致了我这个错误。 修改此文件，重启tomcat就OK了。
> 结语：还是谷歌靠谱，百度了N久无法解决。我是jdk 1.7 64位的。

首先，谢谢这位师兄，这个答案居然都是4年前的了，给了解题思路
补充： 关于datasource.xml配置中是否需要加 /cat 追加至 jdbc:mysql://127.0.0.1:3306/ 是需要看情况的
我按照 DINGPING/CAT wiki 中的部署文档进行部署的，使用的打包命令为：
> mvn clean install -DskipTests
所以其实是需追加 /cat 的
