### ISSUE TITLE
windows开发环境乱码问题

### ISSUE THREAD

**Issue by longting** [dianping/cat#838]
访问配置-》项目配置信息-》项目分组配置，出现了???乱码

**Comment by youyong205** [comment]
那你是本地的tomcat的问题吧

**Comment by junphine** [comment]
我也遇到了，用了各种方法都没成功。
后来一怒之下加了 org.springframework.web.filter.CharacterEncodingFilter

**Comment by longting** [comment]
用项目里面的jetty启动的,jettty:run

**Comment by chlliu** [comment]
请问这个问题是怎么解决的？mysql的编码设置问题还是哪里，现在在项目分组配置添加新的产品线也是加不进去，烦请各位知道解决办法的分享下

**Comment by 22996963** [comment]
@chlliu @longting   请问有解决吗？
