### ISSUE TITLE
Cat.destroy()无法关闭客户端，因为bootstrap event loop不是daemon线程池

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#842]
用户虽然调用了Cat.destroy()，但是程序仍然没有退出。
因为CAT客户端的bootstrap event loop不是daemon线程池。

所以我们fix如下，在com.dianping.cat.message.io.ChannelManager的构造方法中：

// Set thread to be daemon.
EventLoopGroup group = new NioEventLoopGroup(1, new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                Thread t = new Thread(r);
                t.setDaemon(true);
                return t;
            }
});

**Comment by youyong205** [comment]
OK
