### ISSUE TITLE
远程url调用时messageid如何传递和设置

### ISSUE THREAD

**Issue by yangming860101** [dianping/cat#843]
请问远程url调用时messageid如何传递和设置，需要自己埋点时设置吗？

**Comment by yangming860101** [comment]
![image](https://cloud.githubusercontent.com/assets/5293889/8495309/2dd13772-219f-11e5-9707-1a6a80f6b9af.png)

**Comment by yangming860101** [comment]
如上图，URL-》远程调用CALL1-》远程调用CALL2
按照cat文档在web工程加上了catFilter，然后在http远程调用的httpUtil做了埋点
Transaction t = Cat.newTransaction("URL_CALL", url);
http get
t.setStatus(Message.SUCCESS);
t.complete();
但在logview中只显示出一级调用栈，httputil组件中埋点时是否还需在http header中加相关参数？

**Comment by youyong205** [comment]
cat.logRemoteCallClient
cat.logRemoteCallServer
