### ISSUE TITLE
Dashboard中业务大盘，应用大盘无数据显示

### ISSUE THREAD

**Issue by yangming860101** [dianping/cat#845]
我已经通过埋点接入了几个web系统，系统之间有调用依赖，现在详细的调用栈已经能够展示出来（transaction），但Dashboard中业务大盘，应用大盘无数据显示，是否还需要在cat系统中为每个接入的系统做相应配置？

**Comment by youyong205** [comment]
肯定是需要进行数据埋点的

**Comment by yangming860101** [comment]
@youyong205 ,有没有实例可参考？
