### ISSUE TITLE
求API说明文档

### ISSUE THREAD

**Issue by karl7** [dianping/cat#846]
很多api的作用不清楚，比如Cat.newTransactiion和Cat.newForkTransaction的区别，有说明文档吗
建议增加点示例代码，比如像以下这种复杂的用法：
                MessageTree tree = Cat.getManager().getThreadLocalMessageTree();
                if (tree == null) {
                    Cat.setup(null);
                    tree = Cat.getManager().getThreadLocalMessageTree();
                }
                String rootMessageId = tree.getRootMessageId() == null ? tree.getMessageId() : tree.getRootMessageId();
                String currentMessageId = tree.getMessageId();
                invocationContext.putContextValue(CatConstants.PIGEON_ROOT_MESSAGE_ID, rootMessageId);
                invocationContext.putContextValue(CatConstants.PIGEON_CURRENT_MESSAGE_ID, currentMessageId);
                invocationContext.putContextValue(CatConstants.PIGEON_SERVER_MESSAGE_ID, serverMessageId);
                cat.logEvent(CatConstants.TYPE_REMOTE_CALL, CatConstants.NAME_REQUEST, Transaction.SUCCESS, serverMessageId);

**Comment by youyong205** [comment]
这个我回去完善完善，这类api都是后面加上的，用在一些特定场合，其实点评内部也没有用到这些。

**Comment by reid3290** [comment]
现在有了吗？求链接
