### ISSUE TITLE
如何统计Cache信息？

### ISSUE THREAD

**Issue by karl7** [dianping/cat#848]
Cat中没有统计Cache的方法，但是报表中有Cache的统计结果页面，请问要用什么方式收集这个信息？

**Comment by chinaboard** [comment]
看这里的代码 
[https://github.com/dianping/cat/blob/1d3ce65a151b3b0ef47a585dfa0b1e86650239ad/cat-home/src/test/java/com/dianping/cat/demo/TestMaxMessage.java](https://github.com/dianping/cat/blob/1d3ce65a151b3b0ef47a585dfa0b1e86650239ad/cat-home/src/test/java/com/dianping/cat/demo/TestMaxMessage.java)

**Comment by karl7** [comment]
type用加固定前缀"Cache."，统计的信息就会计入cache中，SUCCESS会被认为命中，missed会被认为未命中
