### ISSUE TITLE
BlockDumper多线程化，大大减少存储块丢失(block loss)

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#849]
在CAT的存储机制中，虽然前面都是多线程、异步的（如多线程gzip压缩），
但是最后一公里路——com.dianping.cat.consumer.dump.BlockDumper却是单线程的。

通过将它多线程化，有效提高了写入/data/appdatas/cat/bucket/dump的吞吐量，加快了消费LocalMessageBucketManager.m_messageBlocks队列的速度，从而减少了block loss。

1 参考实现——只需加个线程池而已：
![image](https://cloud.githubusercontent.com/assets/7484190/8664726/b3836bda-2a0d-11e5-818e-222b02a16ef9.png)
![image](https://cloud.githubusercontent.com/assets/7484190/8664733/c444e052-2a0d-11e5-91c5-3ecacab40735.png)

2 线程安全性：
为保证线程安全，需要留意几点：
(1) MessageBlockWriter.writeBlock()本来就是synchronized的。
     所以写不同的bucket实现了并行，而写相同的bucket是串行的、线程安全的。

(2) LocalMessageBucketManager中的m_messageBlocks队列和m_buckets都是线程安全的。

(3) 以下几个变量要改成AtomicLong/AtomicInteger:
    BlockDumper.m_errors
    ServerStatistic$Statistic.m_blockTotal
    ServerStatistic$Statistic.m_blockLoss

3 优化效果：
    生产环境中，优化前，每小时丢失约20万-30万block (约2%)：
![image](https://cloud.githubusercontent.com/assets/7484190/8664776/5a2e1ebc-2a0e-11e5-8deb-2f0852d53cad.png)
    优化后，彻底消灭了block loss：
![image](https://cloud.githubusercontent.com/assets/7484190/8664785/6c579fe6-2a0e-11e5-85a1-2d205133bc83.png)

**Comment by youyong205** [comment]
OK
