### ISSUE TITLE
NetGraphManager.NetGraphReloader 死循环Bug（current 变量位置错误）

### ISSUE THREAD

**Issue by raddle60** [dianping/cat#851]
cat-home/src/main/java/com/dianping/cat/report/page/network/nettopology/NetGraphManager.java

151 行 long current = System.currentTimeMillis();
这行应该在while里面
放在外面
if (duration < DURATION) {
将永远是false，进不了sleep语句。

**Comment by youyong205** [comment]
OK 收到~~~thx~
