### ISSUE TITLE
需求：实现对heartbeat的告警

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#852]
我们有个需求，通过分析heartbeat消息，实现对CPU利用率高, memory利用率异常高, IO吞吐量异常等的告警，发送告警邮件。

告警机制需要灵活——能够对自定义的heartbeat指标(extension)，进行分析。

**Comment by huang--yijian** [comment]
你们有计划做吗？
如果没有，我们做。这也是Frankie提出的需求。

**Comment by youyong205** [comment]
有的，你们看看heartbeatalert

**Comment by youyong205** [comment]
有的，你们看看heartbeatalert

**Comment by huang--yijian** [comment]
好的。正在看了。
