### ISSUE TITLE
messageid重复

### ISSUE THREAD

**Issue by yangming860101** [dianping/cat#858]
cat的messageid规则为domain-ip-timestamp-index
timestamp=MilliSecondTimer.currentTimeMillis() / 3600 * 1000L;
index=AtomicInteger.getAndIncrement();
在同一个小时内，domain-ip-timestamp不变，index从0递增，但当一个应用在一台server上部署多个端口时，messageid就会出现重复，建议index的生成使用UUID（或者改变前面的规则保证全局唯一）

**Comment by jialinsun** [comment]
我们目前应用的使用场景中，还不存在这样的问题。即使存在这样的场景，也不应使同一个应用部署在同一台服务器的不同端口上。

**Comment by yangming860101** [comment]
一个应用是分布式部署在多台server上的，出于服务器资源合理使用考虑，一台server可能会部署多个端口

**Comment by jialinsun** [comment]
如果的确需要服务器上部署多个server到不同端口，可以尽量做到不同应用部署在同一台服务器上，这样domain可以控制唯一性了，更重要的是机器宕机，对应用集群的影响会更低一些。

**Comment by youyong205** [comment]
目前不支持同一个domain部署在同一台机器上，部署超过两个实例。

**Comment by slankka** [comment]
[如何让CAT支持同一个机器多个端口的服务](https://slankka.github.io/CatCookbook/zh/guide/tutorial/article-02.html)
Hello，我今天试了一下，这个方案似乎可行。
