### ISSUE TITLE
不支持JDK8

### ISSUE THREAD

**Issue by Percy0601** [dianping/cat#861]
目前了解到CAT不支持JDK8，在JDK7运行一切正常，望官方更新一下代码，看一下JDK8为什么不能执行，毕竟JDK9马上就要到来了。。。

**Comment by youyong205** [comment]
jdk8的问题是客户端依赖的一个jar有点问题，jdk7 以及 6都是ok的。

8的问题我在想想办法

**Comment by Percy0601** [comment]
@youyong205 JDK8问题修复了？
