### ISSUE TITLE
请教一下cat的服务端部署架构

### ISSUE THREAD

**Issue by yangl** [dianping/cat#865]
哪位能发一下cat的部署架构文档？现在不太明白服务端、客户端、agent之间的区别！我的理解是只要部署几台cat-home做为服务端，然后在业务代码中加入client的jar包依赖并调用接口再配置一下client.xml就可以了吗？麻烦各位答复下

**Comment by youyong205** [comment]
agent现在没什么用，cat-home作为服务端，客户端依赖cat-client即可。

**Comment by yangl** [comment]
5、配置所有客户端和服务端的配置文件client.xml，文件路径/data/appdatas/cat/client.xml。


	<config mode="client">
	    	<servers>
	                <server ip="10.1.1.1" port="2280" http-port="8080"/>
	                <server ip="10.1.1.2" port="2280" http-port="8080"/>
	                <server ip="10.1.1.3" port="2280" http-port="8080"/>
	    	</servers>
	</config>

服务端也能用到这个配置吗？


如果不用hdfs，那么服务端的文件是每台都保存各自的吗？


<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="10.1.1.1" backup-server-port="2280">
   <default-server id="10.1.1.2" port="2280" enable="true"/>
   <default-server id="10.1.1.3" port="2280" enable="true"/>
</router-config>
这个配置backup-server中的server 是只做为job-machine=true，alert-machine=true了吗？那为啥10.1.1.2和10.1.1.3也能访问管理后台呢？

谢谢！
