### ISSUE TITLE
怎么理解这几种规则类型

### ISSUE THREAD

**Issue by renshui1983** [dianping/cat#866]
<img width="806" alt="qq20150819-1 2x" src="https://cloud.githubusercontent.com/assets/13866684/9356763/a25c40b0-46b5-11e5-89ca-b221b4edf0cd.png">

对几种监控规则类型有些疑问：
1. 下降百分比（比基线）： 基线指的是上一天的同一分钟吗？
2. 总和最大值： 指的是当天监控时间内总的计数吗？
3. 波动上升百分比（当前值）： 指的是当前分钟的指标比前一分钟的上升百分比吗？

麻烦配置过的同学解答一下， 谢谢！

**Comment by jialinsun** [comment]
这些概念，可以通过读代码理解，具体来说如下：
1. 基线，是过去四周特定周几的那4天的数据的求平均得出。
2. 总和最大值（当前值），是在最近持续分钟之内的指标值总和，例如图中所配就是最近三分钟的count总和。
3. 波动上升百分比（当前值），是指当前最近一分钟的指标值，分别与前面的持续时间内（除最后一分钟）的每分钟的值做对比，图中所示即为分别与前两分钟的值做对比，同时满足触发的条件才会触发告警。
注意：持续N分钟，就代表必须满足至少N-1个条件，每分钟触发的条件逻辑与之后，才能决定最后是否触发告警。
PS: 后续会完善相关类似的文档。

**Comment by renshui1983** [comment]
谢谢了，解释的很明白
