### ISSUE TITLE
ping告警里面的ip(socket)告警是否有实现？

### ISSUE THREAD

**Issue by huzhiwen1992** [dianping/cat#868]
![cat](https://cloud.githubusercontent.com/assets/13942051/9437286/0a82d5fc-4a88-11e5-891a-b5bb28aeffc9.jpg)

ping告警里面的ip(socket)告警是否有实现？因为我看了代码，只看到了http的验证规则并告警，ip(socket)则只有规则的配置没有验证及报警。麻烦哪个同学能够解答下。

**Comment by jialinsun** [comment]
确实没有实现，本身也没有怎么使用。后续会实现的。
