### ISSUE TITLE
如果有多个CAT的consumer实例接收监控数据，同一个应用发过来的监控数据可能会发到不同的consumer，那么Analyzer如何保证分析数据的正确性

### ISSUE THREAD

**Issue by long187** [dianping/cat#870]
如果有多个CAT的consumer实例接收监控数据，同一个应用发过来的监控数据可能会发到不同的consumer，那么Analyzer如何保证分析数据的正确性。
因为Analyzer分析时可能需要累计的数据进行分析，而数据又分散在多个consumer。

**Comment by youyong205** [comment]
展示层做数据合并

发自我的 iPhone

**Comment by qmwu2000** [comment]
一个消息只会被一个消费者处理。
UI显示的时候会将多个消费者的数据进行聚合，再展示。


发自我的 iPhone
