### ISSUE TITLE
std的计算方式和标准差的计算方式不一样，请问这个是有特殊原因吗？ line95的合并计算是每个sum(line95)/count(line95)，而不是对整体重新计算，请问这个又是为什么

### ISSUE THREAD

**Issue by xiaozujun1** [dianping/cat#871]
代码中的计算方式	
std计算：
double std(long count, double avg, double sum2, double max) {
		double value = sum2 / count - avg * avg;

		if (value <= 0 || count <= 1) {
			return 0;
		} else if (count == 2) {
			return max - avg;
		} else {
			return Math.sqrt(value);
		}
	}

 line95计算：
if (totalCountSum > 0) {
			double line95Values = old.getLine95Value() * old.getTotalCount() + other.getLine95Value()
			      * other.getTotalCount();

			old.setLine95Value(line95Values / totalCountSum);
		}

**Comment by youyong205** [comment]
95line只能单机运算相对准备，后面合并只是做了加权合并，这个值没必要精确。
