### ISSUE TITLE
MVC框架调用Cat.initialize(file) 与 Cat客户端自身lazy调用 Cat.initialize(file) 造成重复初始化

### ISSUE THREAD

**Issue by huang--yijian** [dianping/cat#872]
1. MVC.java中，MVC.initializeCat() 会调用 Cat.initialize(file)，这里的file是Cat Home下的"config/client.xml"。

2. Cat自身的lazy initialization，即Cat.getProducer() => Cat.checkAndInitialize() 也会调用Cat.initialize (file)，这里的file是 Cat Home下的"client.xml"。

由于MVC.initializeCat()调用Cat.initialize()时，没有检查Cat.s_init标志位，所以以上两个调用有可能同时发生，导致状态相互覆盖。这里造成了重复初始化。

而且，以上两个调用所尝试读取的client.xml还是不同的，第一个是config/client.xml，第二个是client.xml。建议统一一下。

**Comment by huang--yijian** [comment]
我个人认为MVC框架没有必要显式初始化CAT客户端——让CAT客户端自己lazy initialize就行了。

**Comment by huang--yijian** [comment]
CAT客户端里有如下判断，避免CatClientModule初始化两次：
Module module = ctx.lookup(Module.class, CatClientModule.ID);
 if (!module.isInitialized()) ...

但是我建议MVC读取的client.xml从config/client.xml改成client.xml，和CAT客户端自身行为一致。

**Comment by youyong205** [comment]
这个应该是bug，MVC应该直接调用 checkAndInitialize 就ok了。
