### ISSUE TITLE
heatbeat问题请教

### ISSUE THREAD

**Issue by huzhiwen1992** [dianping/cat#873]
1、客户端有Cat.logHeatBeat(type, name, status, nameValuePairs);这个怎么使用？服务端界面怎么配置能够显示？
2、客户端有Cat.logError(message, Throw);这个message的作用是什么，服务端界面只有logView中看到，其他地方没看到？异常告警能够根据自己对错误的命名进行告警吗？

**Comment by jialinsun** [comment]
1.Cat.logHeartBeat是client端自动做的，一般不需要使用，服务端problem和heartbeat那边界面就有相应数据，不需要配置。
2. message可以自定义，比如堆栈信息。这些Message就是在logview里看的，其他地方没有。异常告警当然可以对自己命名的特定异常进行告警。
