### ISSUE TITLE
problem 的Long-service, Long-cache , Long-sql代表那种类型的报表及怎麽配置

### ISSUE THREAD

**Issue by fangleu** [dianping/cat#874]
![qq 20150901181141](https://cloud.githubusercontent.com/assets/12028575/9601566/0cffcae4-50d5-11e5-90f6-39d85c1c4f88.png)

**Comment by fangleu** [comment]
![11111](https://cloud.githubusercontent.com/assets/12028575/9601643/8f8aa2c2-50d5-11e5-8f90-604c5dda07fb.png)

**Comment by youyong205** [comment]
这边阈值都是固定的

**Comment by weishubin** [comment]
在创建一个Transaction的时候type指定为CatConstants.TYPE_URL,CatConstants.TYPE_SERVICE,CatConstants.TYPE_SQL
