### ISSUE TITLE
添加项目报失败

### ISSUE THREAD

**Issue by zxj19880903** [dianping/cat#877]
@尤大师 @佳林
我在本地安装成功，目前是添加新项目报错，不清楚为什么！希望能解答一下
![qq20150911-1 2x](https://cloud.githubusercontent.com/assets/7284550/9814648/3f974636-58c2-11e5-9a97-4df53294df94.png)

**Comment by youyong205** [comment]
不需要添加项目，项目是当客户端连接上去，自动会有的。
