### ISSUE TITLE
应用接入该怎么改造！

### ISSUE THREAD

**Issue by zxj19880903** [dianping/cat#880]
@尤大师  
cat接入应用，需要怎么去改造，有这方面的资料吗？

**Comment by youyong205** [comment]
参考首页集成文档

**Comment by dankes** [comment]
首页集成文档写得较简单，如果有详细的最好，如分布式应用如何整合。

**Comment by chinaboard** [comment]
参考项目test代码即可






On Sun, Dec 27, 2015 at 7:34 AM -0800, "dankes" <notifications@github.com> wrote:












首页集成文档写得较简单，如果有详细的最好，如分布式应用如何整合。

**Comment by dankes** [comment]
rootid，messageid，praentid在夸进程如何设置，在分布式logview里 面点show后显示不正确，请指导，谢谢。
