### ISSUE TITLE
告警规则问题请教

### ISSUE THREAD

**Issue by huzhiwen1992** [dianping/cat#881]
![qq 20150917104543](https://cloud.githubusercontent.com/assets/13942051/9923725/1745b574-5d2b-11e5-962a-ae02d184360a.png)
请问这个规则的持续时间不能超过十分钟的意图是什么？我们有超过十分钟的需求是不是可以删除掉限制？

**Comment by zxj19880903** [comment]
你们这边开始接入应用没？

**Comment by huzhiwen1992** [comment]
接入了。是这样，我们有个这个得应用场景，比如我们有个每半小时的执行得定时任务，我们就想通过设置业务指标监控持续时间30分钟，然后设置综合最小值为1，在这30分钟没执行的话就让他报警。然后我们也看了代码，持续时间越长可能需要处理得数据也就越多，所以我想是不是持续时间设置过长会对系统有负担。我们这边能不能自己去掉限制，好像只是前端加了限制？

**Comment by youyong205** [comment]
30分钟应该没问题，你们可以去掉的，这个是前端限制的，和后端没啥关系

**Comment by LSN1234** [comment]
改为一个小时可以吗，服务的数据量不是很大
