### ISSUE TITLE
cat服务端关闭后，会导致应用OOM

### ISSUE THREAD

**Issue by heytong** [dianping/cat#883]
应用程序内存dump出来后的截图如下：

![laloauj4qs0bys0chg_646_354](https://cloud.githubusercontent.com/assets/1266875/9988986/a3ad92e8-6087-11e5-9d37-d054d728751d.png)

请问下该如何避免这个情况？

**Comment by youyong205** [comment]
你的版本很老很老了吧？

**Comment by heytong** [comment]
是最新版本的主线，cat服务端停了一阵子以后才出现这个状况

**Comment by qmwu2000** [comment]
cat服务器不可用时，消息会暂存在客户端，客户端duilie有一个大小。如果此时各个消息都比较大的话（比如心跳消息），会占用客户端一些内存的。

但这不应该是正常的case，可以将cat客户端disable。


发自我的 iPhone

**Comment by youyong205** [comment]
MessageQueue m_queue = new DefaultMessageQueue(SIZE);

SIZE=5000  不太清楚是在什么样的场景下会是这样。

**Comment by heytong** [comment]
当时cat在测试环境部署准备试用，找了一个应用A进行最简单的web.xml配置没有问题，后因业务有紧急需求，一段时间没管cat，cat server宕机了（只有一台），某段时间之后应用A发现OOM了，就是如我截图所示.
