### ISSUE TITLE
Report a possible race issue

### ISSUE THREAD

**Issue by baigd** [dianping/cat#884]
Hi, Developers of dianping/cat,

I am writing to report a race issue on use of ConcurrentHashMap. The issue is reported by our tool in an automatic way. Although manually confirmed, it would be a false positive, given we do not know the specification of the program. We would very appreciate if you could check below for details and confirm with us whether it is a real problem. For more information, please refer to our website: http://sav.sutd.edu.sg/?page_id=2845

File: 
dianping/cat/cat-core/src/main/java/com/dianping/cat/report/DefaultReportManager.java
Location: (104/100, 61/153)
Description: 
The synchronized block from line 99 to line 106 contains a get-then-put operation on "m_reports". If the intention of this locking is to guarantee the atomicity of the get-then-put operation, then the remove operation in line 61 may break this atomicity since it is not properly locked. The put operation in line 153 may have the same effect though it may not be serious. Relying on the ConcurrentHashMap to ensure exclusive access is dangerous since ConcurrentHashMap has no guarantee of exclusive access.

**Comment by qmwu2000** [comment]
Thanks for notification! We will fix this kind of issues.


发自我的 iPhone
