### ISSUE TITLE
cat 异常问题请教

### ISSUE THREAD

**Issue by natsuforyou** [dianping/cat#887]
出现两次了，cat出现内存溢出的情况。
请教一下，应该如何解决或优化？
![2015-09-29 14 34 41](https://cloud.githubusercontent.com/assets/13536764/10156849/7ce8507c-66b7-11e5-9726-714fe15a3588.png)

**Comment by youyong205** [comment]
这个是客户端，客户端你的启动参数是啥？

**Comment by natsuforyou** [comment]
-Xms512m -Xmx2048m -XX:PermSize=128M -XX:MaxNewSize=256m -XX:MaxPermSize=512m

**Comment by youyong205** [comment]
你把gc禁用了吧，开启try 试试

参考下 http://www.open-open.com/lib/view/open1431570358826.html

**Comment by youyong205** [comment]
后面如果oom，你们可以dump下来分析分析，很多时候看堆栈也看不出来问题。
