### ISSUE TITLE
不同domain相同业务指标的合并

### ISSUE THREAD

**Issue by renshui1983** [dianping/cat#890]
拿“创建订单请求数”这个业务指标举例， 订单可能是来自App应用， 也有可能来在Web应用， 也有可能来自为合作伙伴提供的open api应用， 如何汇总统计多个来源的业务指标？

**Comment by youyong205** [comment]
现在是没有支持这个情况。

我们这边这类都是统一的调用订单服务，然后订单服务肯定是同一个项目，然后在订单服务里面统一埋点。

**Comment by qmwu2000** [comment]
CAT中有一个叫“All”的虚拟domain，可以合并统计来自多个domain的event和transaction，只需要在系统中配置一下即可。

这个能解决你的问题吗？

发自我的 iPhone

**Comment by renshui1983** [comment]
我主要是想合并某些业务指标， 不是event和transaction
