### ISSUE TITLE
cat-core 工程中serverfilter.xml文件配置确认

### ISSUE THREAD

**Issue by copoo** [dianping/cat#893]
请问在core-core工程中resources/config/serverFilter.xml有如下两行配置：

<transaction-name>piegonService:heartTaskService:heartBeat</transaction-name>
<transaction-name>piegonService:heartTaskService:heartBeat</transaction-name>
“piegonService”是否是在pigeon集成时使用，还是其他用途，谢谢。

**Comment by copoo** [comment]
请问在core-core工程中resources/config/serverFilter.xml有如下两行配置：

	<transaction-name>piegonService:heartTaskService:heartBeat</transaction-name>
	<transaction-name>piegonService:heartTaskService:heartBeat</transaction-name>
“piegonService”是否是在pigeon集成时使用，还是其他用途，谢谢。

**Comment by youyong205** [comment]
这个是内部的一些框架里面，需要把这些统计给过滤掉。

因为这些和是业务统计在一起，最终影响到实际的响应时间。
