### ISSUE TITLE
使用Rest风格的URL，会不会影响Transaction页面加载的时间

### ISSUE THREAD

**Issue by renshui1983** [dianping/cat#894]
如果使用Rest风格，URL中含有产品id， 会造成URL的数量非常庞大， Transaction的页面好像没有分页，单页显示所有的数据， 会不会导致页面加载时间非常长？

**Comment by qmwu2000** [comment]
会。建议使用URL pattern作为transaction name。看一下CatFilter

发自我的 iPhone

**Comment by renshui1983** [comment]
CatFilter的pattern如何使用， 没找到相关文档 ，能不能给个例子

**Comment by youyong205** [comment]
单页数据都做过限制了，我印象中最多500个。

同时restful的url pattern可以定制的，比如shop/${id}  在埋点的时候通过修改http header的一些属性，可以统一定向到shop.do， shop.do可以自己定义

具体可以看下首页的集成文档，有具体的说明的。
