### ISSUE TITLE
cat-agent\dashboard下面的应用大盘、dependency依赖关系这些都需要什么规范能否给出一个文档呢？

### ISSUE THREAD

**Issue by vwyuheng** [dianping/cat#897]
cat-agent\dashboard下面的应用大盘、dependency依赖关系这些都需要什么规范能否给出一个文档呢？谢谢!

**Comment by youyong205** [comment]
cat-agent 是不需要使用的，后面我们已经会remove掉。

dependency依赖关系我后面在把埋点规范在写清楚一些。
