### ISSUE TITLE
Transaction历史统计报表无法显示数据

### ISSUE THREAD

**Issue by lovewhll** [dianping/cat#898]
Hi ，

Transaction历史统计报表无法显示数据是什么原因？

**Comment by qmwu2000** [comment]
应该是后台job没有跑。server.xml中有配job-machine=“true”吗？


发自我的 iPhone

**Comment by lovewhll** [comment]
好的，配置下看看，谢谢！

**Comment by lovewhll** [comment]
昨天配置了server.xml中有配job-machine=“true”，但还是切换历史模式还是没有数据
日志中没发现有处理历史报表的线程信息。

**Comment by lovewhll** [comment]
@qmwu2000 @youyong205  帮忙一下，谢谢！

**Comment by weishubin** [comment]
我也有同样的问题，job-machine=“true”已经设置了
