### ISSUE TITLE
Transaction监控中Max(ms)、Avg(ms)和Total项中的数据误差问题

### ISSUE THREAD

**Issue by chlliu** [dianping/cat#899]
您好，应用过程中遇到一些问题，烦请帮忙解答一下。
1，在Transaction监控中，一个小时内的时时total项数据不能及时显示，一个项目，四台机器，total项多的达到几万，少的机器total项只有几百。
2 看日志发现，每临近整点时会有一些 analyzer线程启动，这时total项的数据会进行更新，四台机器都达到几万的数据量，但是Max和Avg的时间会被一些异常的transaction拖慢，导致数据不准确。
3 日志中会出现 netty write buffer is full 这样的错误。请问这个问题是什么原因导致的？不知道是否和这个有关？
4 请问Transaction的机制是怎么样的？
用的是最新的1.3.6 master版本
![qq 20151029143138](https://cloud.githubusercontent.com/assets/15336978/10813571/129e2046-7e5b-11e5-9079-8dde3250a10d.png)

**Comment by youyong205** [comment]
你自己看看服务端的压力？然后服务端是不是虚拟机，虚拟机一般都很弱

**Comment by chlliu** [comment]
服务端确实是虚机，但是部署了两台，十五分钟load平均不到0.2，网络、磁盘io也都ok。client端的netty write buffer is full 这个错误会对transaction等消息传输有影响吗？这个错误只要启动就会有

**Comment by youyong205** [comment]
netty write buffer is full  这个错误是当启动时候发送消息发布出去，打印出来的日志。
后面会重新重发，只要这个日志不是一直有就没问题的。

**Comment by youyong205** [comment]
后面建议虚拟机的话，内存8g以上吧，4g的有点吃力的。
