### ISSUE TITLE
请教cat-agent中引用的org.unidal.*组织中的jar包资源到哪个maven仓库地址中可以下载

### ISSUE THREAD

**Issue by AndyAndAndy** [dianping/cat#901]
请教cat-agent中引用的org.unidal.*组织中的jar包资源到哪个maven仓库地址中可以下载
有看到点评的仓库 http://mvn.dianpingoa.com/dianping-releases
但该仓库不能访问
如下面资源：
    
    <dependency>
         <groupId>org.unidal.framework</groupId>
         <artifactId>foundation-service</artifactId>
         <version>2.2.0</version>
      </dependency>

      <dependency>
         <groupId>org.unidal.webres</groupId>
         <artifactId>WebResServer</artifactId>
         <version>1.2.1</version>
      </dependency>

      <dependency>
         <groupId>org.unidal.framework</groupId>
         <artifactId>web-framework</artifactId>
         <version>2.2.1</version>
      </dependency>

**Comment by yalida** [comment]
在github中搜索  unidal  ，可以找到相关源码，只能自己编译打包，放到自己的私服上了

**Comment by youyong205** [comment]
在cat mvn-repo分支上，自己download下来也可以的。

**Comment by j2cms** [comment]
同问
