### ISSUE TITLE
请教：测试程序运行后：shutdown task TcpSocketSender..................

### ISSUE THREAD

**Issue by AliBokerDestroyer** [dianping/cat#904]
我的测试代码：
        Transaction t = Cat.newTransaction("SequencerTEST", "test.method");
        Cat.logEvent("Method_test——eclipse", "test");
        Cat.logEvent("Method_event——eclipse", "test2");
        t.complete();

控制台输出如下：
Logger file D:\data\applogs\cat\cat_20151106.log
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
[11-06 13:53:33.033] [WARN] [cat] Cat is lazy initialized!
shutdown task TcpSocketSender
shutdown task TcpSocketSender-ChannelManager
shutdown task merge-atomic-task
shutdown task StatusUpdateTask

刷新CAT监控页面，也没有监控到Transaction和Event。
公司等着用，请尽快回复，谢谢！

**Comment by qmwu2000** [comment]
cat客户端是异步发送消息的，需要在测试代码中sleep一小会。

发自我的 iPhone

**Comment by AliBokerDestroyer** [comment]
这个大约要sleep多久呢。。。
话说还真是cat啊，有点懒啊、、、、

**Comment by AliBokerDestroyer** [comment]
如果一定要sleep，如果在高并发的代码里埋点，效率上不是会有影响吗？请问有没有其他方式可以做到类似埋点的功能？

**Comment by jialinsun** [comment]
很快的，几秒钟就够了。你可以试试，底层是netty框架实现的，正常服务启动的话，你就不用care这部分的东西，因为你是跑testcase，所以很快就结束了，才需要这样做（sleep）。正是因为要高并发，所以才要异步。如果不是跑case，正常逻辑代码，不需要sleep。

**Comment by AliBokerDestroyer** [comment]
这样啊，我明白了。我刚刚测了一下，至少需要sleep 50ms。。。
