### ISSUE TITLE
dianping cat 问题

### ISSUE THREAD

**Issue by jiucai** [dianping/cat#906]
1.  多次访问url后，事务总数更新对了，但是logview里面只有第1次访问的消息,后面的多没有

2、自定义Matrix  logMetricForCount 在实时数据查询不到

3、使用文件方式保存log，cat应用重启后，log查询不到了

<config local-mode="true" hdfs-machine="true" job-machine="true" alert-machine="true">

4、开启hadoop写入，文件没有写入成功，log里面也没有相关的error

请指教，谢谢。

**Comment by jiucai** [comment]
版本是用最新的master的主干的代码

**Comment by youyong205** [comment]
1、多次访问url后，事务总数更新对了，但是logview里面只有第1次访问的消息,后面的多没有
    cat 设计就是这样，如果你访问1000kw次，不会给你1kw的link。更多有问题的link在problem
2、自定义Matrix logMetricForCount 在实时数据查询不到
   matrix 有问题吧，是metric吧，可以参考首页的业务监控
3、使用文件方式保存log，cat应用重启后，log查询不到了
   重启需要做一个docheckpoint，可以参考下 home action的code
4、开启hadoop写入，文件没有写入成功，log里面也没有相关的error
  这个不太清楚了，hadoop是你自己搭建一个hadoop集群的，cat不负责搭建hadoop集群的
