### ISSUE TITLE
请教：为什么我监控的transaction的失败率总是100%？

### ISSUE THREAD

**Issue by AliBokerDestroyer** [dianping/cat#912]
如题，请尽快回复，下周上线。

**Comment by jialinsun** [comment]
你是不是没有设置status，不设置就会全部失败。

**Comment by AliBokerDestroyer** [comment]
status？和http的代码一致还是说有自己的一套？能不能贴下代码？

**Comment by jialinsun** [comment]
![image](https://cloud.githubusercontent.com/assets/4188173/11119275/47f21ef4-8983-11e5-85a9-0209148ccb73.png)

**Comment by jialinsun** [comment]
多看看文档，这些文档里都有

**Comment by AliBokerDestroyer** [comment]
好的，谢谢了！再问一下：原来cat里有的那些测试的代码怎么去掉？
