### ISSUE TITLE
使用CAT遇到的两个问题

### ISSUE THREAD

**Issue by 269629151** [dianping/cat#915]
你好，公司准备接入cat，目前在预研，现在遇到几点问题想请教一下
1、JDK8支持问题，发现cat-home不支持，cat-client运行在jdk8没报错，您是否已解决或者找到出现问题的jar包？
2、测试时发现client连接一段时间后会出现[ERROR] [TcpSocketSender] Netty write buffer is full! Attempts: 124000 错误，然后一直不能发送消息

**Comment by qmwu2000** [comment]
1. 可以拉一下最新master上代码，应该是可以了。
2. 应该是cat server没有配对。

**Comment by codeongit** [comment]
master的最新代码
本地java版本JDK1.8.0_20
报类似这种错
http://www.oschina.net/question/1269776_241663?fromerr=gm5tYQVM
换成1.7可以

**Comment by 269629151** [comment]
拉了最新的代码。用jdk1.8.0_40编译后 jetty:run 没问题 ，丢掉tomcat下报跟之前没修复时一样的错误，jdk7编译就不会

**Comment by chenghaojun** [comment]
问题都没有解决怎么能 close 掉？
