### ISSUE TITLE
build cat 1.0.3 不成功，请问这些依赖的jar包，需要自己在本地build吗?

### ISSUE THREAD

**Issue by mikerain** [dianping/cat#917]
plugin org.unidal.maven.plugins:codegen-maven-plugin:2.1.2 or one of its dependencies could not be resolved: Failure to find org.unidal.maven.plugins:codegen-maven-plugin:jar:2.1.2

**Comment by joeyliu616** [comment]
我用的私服, 编译不过.  后来把setting.xml 恢复默认就可以了. cat有些包没有放到中央仓
