### ISSUE TITLE
请问客户端路由具体是干啥的？

### ISSUE THREAD

**Issue by moujian** [dianping/cat#921]
翻了readme和文档都没有找到相应的信息，只在部署文档里面看到需要配置这个
>启动一台服务端10.1.1.1，修改服务端路由文件，url地址 http://10.1.1.1:8080/cat/s/config?op=routerConfigUpdate
>      需要用户名密码登陆，如果配置ldap即可直接登陆，或者用默认账号catadmin/catadmin登陆。
>      可以将10.1.1.1 部署为提供内部访问，并设置job-machine=true，alert-machine=true，让这台机器进行后续job以及告警处理，这些都可能影响到consumer性能。
>      将10.1.1.2,10.1.1.3 处理全部监控请求，如果后续需要扩容，可以直接添加default-server的节点。

```xml
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="10.1.1.1" backup-server-port="2280">
   <default-server id="10.1.1.2" port="2280" enable="true"/>
   <default-server id="10.1.1.3" port="2280" enable="true"/>
</router-config>
```

**Comment by youyong205** [comment]
以后的扩容可以在这边动态调整。

**Comment by moujian** [comment]
@youyong205 :thought_balloon: :+1:  catclient 有逻辑会感知这个更改吗？代码没看到

**Comment by chinaboard** [comment]
@moujian java客户端会有个更新server节点的逻辑，.net不会

**Comment by oyo-kermit** [comment]
客户端路由修改，显示操作失败，是什么情况呀，日志里面也没记录

**Comment by oyo-kermit** [comment]
@youyong205 
客户端路由这样修改，显示‘操作失败’，日志页面看到，请问下是什么原因呢？
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="IP1" backup-server-port="2280">
   <default-server id="IP2" weight="1.0" port="2280" enable="true"/>
</router-config>

客户端的client.xml 和服务的client.xml一致，都是配置了两个server-IP
