### ISSUE TITLE
服务端集群负载均衡和客户端路由的问题

### ISSUE THREAD

**Issue by chlliu** [dianping/cat#923]
1 根据测试发现，客户端会读取client.xml中的第一个server配置，其他server会当做备用机。
2 客户端路由配置并不生效，增加weight=1.0属性也不成，客户端还是默认根据client.xml去找server
<?xml version="1.0" encoding="utf-8"?>
<router-config backup-server="10.1.1.1" backup-server-port="2280">
   <default-server id="10.1.1.2" port="2280" enable="true"/>
   <default-server id="10.1.1.3" port="2280" enable="true"/>
</router-config>

请问youyong老师，是我配置的哪里有问题吗?还是cat并支持负载均衡配置? 最好能详细点说一下，这部分很多人都有疑问，感谢！

**Comment by youyong205** [comment]
客户端会根据client.xml 的配置找到一个server，然后通过http接口获取到真正的router。

**Comment by youyong205** [comment]
这个配置在config，里面客户端路由

**Comment by chlliu** [comment]
非常感谢！
