### ISSUE TITLE
就是依赖的第三方写的太垃圾了

### ISSUE THREAD

**Issue by dltc** [dianping/cat#924]
依赖的：org.unidal.* 这个 实在是写的太垃圾了，我想在CAT上做修改都做不了。
建议一些基础MVC，JDBC等可以使用Spring大众化依赖。
依赖一个不知道谁写的MVC框架，难以理解不说，还不好扩展，那个依赖有BUG，不能再Java8中运行。
我现在想修改下都修改不了。

**Comment by qmwu2000** [comment]
不好意思，org.unidal中所有的代码都是我写的。当然cat中核心代码也是我写的。

你理解不了的不一定就不好，希望你多花点时间，当然文档不够确实是个问题。Spring有它适合的场景，也有它不太适合的场景，不要简单地非白即黑。

cat现在不支持jdk 8是已知问题，我会尽快抽时间fix这个问题，敬请期待！



发自我的 iPhone

**Comment by qmwu2000** [comment]
jdk8 issues fixed, please verify, thanks

**Comment by youyong205** [comment]
dltc 你牛逼你来啊。you can you up  没人逼着你用cat。
说话注意方式，ok？

**Comment by ainilife** [comment]
@dltc，你对unidal这个框架不熟甚至不会，这可以理解，但这不能代表这个框架垃圾。这是@qmwu这位我尊敬的程序员将近20年的时间沉淀的结果。在里面的各个设计细节和思考，像你这种不懂思考只会喷的人是永远也不能理解的。

**Comment by jialinsun** [comment]
@qmwu2000 也是我最为敬重的架构师之一，有不同意见的人可以给出建议，不要恶言诋毁。这个框架我一直在用，请不要对一件尚不了解的事物轻易做出评价与判断。对于 @qmwu2000 的胸怀与视野，后辈真是佩服，我会一直支持unidal及cat，并付诸行动来使之更完美。

**Comment by dltc** [comment]
我已经修复了：   在org.unidal.web.mvc.model.ModelManager  line 175 
if (Modifier.isStatic(modifier) || Modifier.isAbstract(modifier) || method.isBridge()) {
                continue;
 }

**Comment by projim-tao** [comment]
感觉cat不使用spring这种通用的而是自己写了一个新的框架应该有其考虑的，不知道 @qmwu2000 @youyong205 能不能讲讲是因为考虑到哪些情况而选择重新开发一个框架的？

**Comment by qmwu2000** [comment]
plexus框架是maven的组件容器（DI/IOC）框架，短小精悍，目标明确，设计简洁明了，高性能低开销，尤其是对unit test有非常好的支持。现在maven迁移到Guice作为它的组件容器框架，但做了很多的适配。


发自我的 iPhone
