### ISSUE TITLE
cat  历史数据无法显示 问题，

### ISSUE THREAD

**Issue by yalida** [dianping/cat#929]
代码是从master上拉下来build的，现在可以显示当前小时的信息和 -1h 的信息，-2h 就没有数据了，切换到历史模式也没有任何数据，我想问问，是不是那里配置的不对啊 ，server.xml 配置如下：
<config local-mode="false" hdfs-machine="false" job-machine="true" alert-machine="true">
	
	<storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
	
	</storage>
	
	<console default-domain="Cat" show-cat-domain="true">
		<remote-servers>127.0.0.1:8080</remote-servers>		
	</console>
	
	<ldap ldapUrl="ldap://192.168.50.11:389/DC=dianpingoa,DC=com"/>
	
</config>

**Comment by yalida** [comment]
<config local-mode="false" hdfs-machine="false" job-machine="true" alert-machine="true">   没贴完全

**Comment by yalida** [comment]
config local-mode="false" hdfs-machine="false" job-machine="true" alert-machine="true"

**Comment by youyong205** [comment]
设置job-machine=true 就ok了吧。

**Comment by yalida** [comment]
@ youyong205  我这边就是 这么配置的 啊，
 config local-mode="false" hdfs-machine="false" job-machine="true" alert-machine="true"
这就是我的  server.xml 配置啊，但是就是没有历史数据

**Comment by chlliu** [comment]
这块我也出现过问题，感觉和每小时的消息总量，和transaction的name过多有关。当时是同一个type下有两百多个name，消息量大的时候就看不到历史数据了。怀疑是不是超过了BLOB的最大限制导致的。请@youyong老师指正

**Comment by youyong205** [comment]
transaction 和 event 的埋点的name要做限制的，不能很随意，不然没办法展示了。

不过数据量大看看插入数据有木有异常，就知道是不是因为数据量比较大看不到历史报表了。

**Comment by chlliu** [comment]
@youyong205 ok  非常感谢 有空了彻查一下
