### ISSUE TITLE
软路由问题

### ISSUE THREAD

**Issue by HouZhiHouJue** [dianping/cat#931]
你好：
    由于.NET客户端没有实现软路由问题，故我正在补充软路由相关的逻辑，根据你之前的说明，客户端会根据client.xml 的配置找到一个server，然后通过http接口获取到真正的router。这个代码Java的部分我看到了，但是服务端的执行逻辑并不是很明白,具体的如下：
 1 首先的执行逻辑是 m_configManager.getRouterConfig().findDomain(domain)，如果找到了那么直接返回
2  如果没找到 执行RouterConfig report = m_reportService.queryReport(Constants.CAT, start, end); 在这个里面查一把，如果找到了，返回
3 如果再没有，根据客户端路由配置随机挑两个。
请问是否能详细说明一下。

**Comment by qmwu2000** [comment]
方便告知是什么公司吗？

发自我的 iPhone

**Comment by HouZhiHouJue** [comment]
找钢网 ：http://www.zhaogang.com/v

**Comment by qmwu2000** [comment]
携程内部的cat .net客户端功能更完善，线下联系吧。


发自我的 iPhone

**Comment by HouZhiHouJue** [comment]
我的QQ ：582105721 方便加下么
