### ISSUE TITLE
在java7和java8生成的war包有问题，但是java6生成的就很正常

### ISSUE THREAD

**Issue by zgc** [dianping/cat#933]
java6生成的war可以在任何环境下使用，但是java7和java8生成的war包，启动会http500

**Comment by zzjhacn** [comment]
完美解决JDK8问题：

1、增加ant依赖，

org.apache.ant
ant
1.9.6
2、把jetty和jetty-util版本升到6.1.26
3、把jsp-api-2.1，和jsp-2.1版本升到6.1H.14.1

done
