### ISSUE TITLE
cat hdfs max-hdfs-storage-time设置未生效问题

### ISSUE THREAD

**Issue by eagle00001** [dianping/cat#937]
你好，我在测试服务器上搭建了cat 的htfs模式的环境。cat有3台（1,2,3），cat的server.xml配置如下。
&lq;config local-mode="false" hdfs-machine="true" job-machine="fales" alert-machine="false">
	
	<storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="3" local-report-storage-time="7" local-logivew-storage-time="7">
		<hdfs id="logview" max-size="128M" server-uri="hdfs://192.168.156.24:9000/user/cat" base-dir="logview"/>
		<hdfs id="dump" max-size="128M" server-uri="hdfs://192.168.156.24:9000/user/cat" base-dir="dump"/>
		<hdfs id="remote" max-size="128M" server-uri="hdfs://192.168.156.24:9000/user/cat" base-dir="remote"/>
	</storage>
	
	<console default-domain="Cat" show-cat-domain="true">
		<remote-servers>192.168.156.22:8081,192.168.156.23:8081,192.168.156.24:8081</remote-servers>	
	</console>
	
	<ldap ldapUrl="ldap://192.168.50.11:389/DC=dianpingoa,DC=com"/>
	
&lq;config>

其中，主服务器为1，配置文件 job-machine值为true，max-hdfs-storage-time值也是9天。但运行一段时间后发现，hdfs上的dump文件超过9天的数据并未被清理。请帮忙看看是否配置问题，还是其他原因？谢谢。

以下是hdfs中历史的dump文件截图：
![hdfsdump](https://cloud.githubusercontent.com/assets/6975121/11924833/642759dc-a7f0-11e5-994f-d37fbbf30313.png)

**Comment by youyong205** [comment]
这里是没有自动删除的hdfs记录的，要写个脚本自动删除。
这边配置了，只不过是超过这些天就不会访问hdfs
