### ISSUE TITLE
mysql表没有数据

### ISSUE THREAD

**Issue by dankes** [dianping/cat#938]
hi，我最近在搭建环境，发现mysql里面只有config表有数据，其它表没数据，请问是哪里配置问题吗？

**Comment by chinaboard** [comment]
正常，跑起来就有数据了






On Sat, Dec 26, 2015 at 7:42 AM -0800, "dankes" <notifications@github.com> wrote:












hi，我最近在搭建环境，发现mysql里面只有config表有数据，其它表没数据，请问是哪里配置问题吗？
