### ISSUE TITLE
关于夸机器的messageid传递

### ISSUE THREAD

**Issue by dankes** [dianping/cat#941]
rpc间的调用，如何传递messageid，有没有例子，谢谢

**Comment by chinaboard** [comment]
自己改组件加入传递的方式






On Sun, Dec 27, 2015 at 8:23 AM -0800, "dankes" <notifications@github.com> wrote:












rpc间的调用，如何传递messageid，有没有例子，谢谢

**Comment by youyong205** [comment]
msg Id 自己在rpc框架传递，具体看看cat的api，logRemoteCallClient logRemoteCallServer

**Comment by dankes** [comment]
多谢
