### ISSUE TITLE
Dependency中拓扑图的埋点方式

### ISSUE THREAD

**Issue by chlliu** [dianping/cat#945]
拓扑图及应用大盘这块儿设计的非常实用！但是埋点的方式没有文档，有几个问题请问？
1 在cat-consumer中找到了DependencyAnalyzerTest这个测试类，拓扑图的埋点方式是否可以参看这个类？
2  请问具体的埋点方式可以贴一下吗？或者项目中有没有可参考的类，烦请把类名贴一下
不少人都卡在这个功能了
不胜感激

**Comment by chinaboard** [comment]
拓扑图好像只支持Service,DB,Cache三种依赖

**Comment by chlliu** [comment]
看了看源码  已搞定
