### ISSUE TITLE
拉的最新的代码，采用mvn jetty:run方式启动，点击实时中导航栏的cross时控制台会出现一个异常，FileNotFoundException

### ISSUE THREAD

**Issue by smile326** [dianping/cat#949]
![image](https://cloud.githubusercontent.com/assets/14938265/12321013/d1ce1f4e-bae6-11e5-971f-1aef84d5b564.png)

@youyong205 老师，这个是不是有痕迹没抹去，youyong也许是用户名==

**Comment by smile326** [comment]
这个问题在Windows和Linux下面都有

**Comment by smile326** [comment]
在\cat-master\cat-home\src\main\java\com\dianping\cat\report\page\cross文件夹下面的Handler.java文件中有一句 String xml = Files.forIO().readFrom(new File("/Users/youyong/Desktop/cross.xml"), "utf-8");
要改成自己的路径这个错误就不会有了。
我想问下cross.xml文件是自动生成的还是需要自己配置？格式有是什么规定么

**Comment by youyong205** [comment]
这个code 是我不小心放上去的，很久没更新code。这段你先注释掉即可。即使不注释也没有影响。
把try catch那部分注释掉
