### ISSUE TITLE
cat 中 messageid 是否全局唯一？

### ISSUE THREAD

**Issue by yalida** [dianping/cat#951]
请问  用 messageId = Cat.createMessageId(); 生成的 messageId 是否是永远唯一？
看了你们的算法，看的不是很懂？能否解释下？跪谢。。。。。

**Comment by qmwu2000** [comment]
是唯一的。message id分四部分：1）domain；2）本机IP地址；3）小时序号；4）小时内顺序号。


发自我的 iPhone
