### ISSUE TITLE
transaction告警，name等于All，响应时间告警没有作用

### ISSUE THREAD

**Issue by raddle60** [dianping/cat#952]
cat-home/src/main/java/com/dianping/cat/report/alert/transaction/TransactionAlert.java
当告警时间为All时，响应时间用的是每分钟的平均时间。
比如：我报sql时长大于100ms的方法，方法很多，每个name去配置非常麻烦。
就配置一个name=All的。但是这样一个sql 2ms，一个sql 500ms，很多3ms的sql。
这个500ms的根本无法报警出来。
现在是针对
if (AVG.equalsIgnoreCase(monitor) && name.equals(Constants.ALL)) 
的情况，遍历每个name判断时长是否超过报警
[TransactionAlert.txt](https://github.com/dianping/cat/files/95310/TransactionAlert.txt)
TransactionType t = report.findOrCreateMachine(Constants.ALL).findOrCreateType(type);
for (String eachName : t.getNames().keySet()) {
    if (Constants.ALL.equals(eachName)) {
        continue;
    }
    double[] data = buildArrayData(start, end, type, eachName, monitor, report);
    results.addAll(m_dataChecker.checkData(data, conditions));
}
还有一种改进方式，是在每分钟的Range里加入min和max。All的响应时间用max，而不用avg。
这种效率高一点。

**Comment by youyong205** [comment]
min max没什么用的，我碰到的需求都是avg的
