### ISSUE TITLE
使用过程中发现Transaction监控到的次数会比实际运行的次数要少

### ISSUE THREAD

**Issue by smile326** [dianping/cat#954]
![image](https://cloud.githubusercontent.com/assets/14938265/12419538/c105227a-bef1-11e5-9e7f-f526ff1a4996.png)
照着文档中这样的一个例子来使用transaction时发现并不是每运行一次程序对应的统计次数都会+1，漏掉的概率还是有点大，应该可以排除网络原因的。但是如果在
![image](https://cloud.githubusercontent.com/assets/14938265/12419580/faf56ff8-bef1-11e5-9241-66c5d7042131.png)
finally中的complete之后有个延时，统计次数立马就准确了。
可以请教一下是什么原因么，我可以用什么其他方式来避免么==

**Comment by qmwu2000** [comment]
cat客户端消息发送是在异步线程中进行的。

发自我的 iPhone

**Comment by smile326** [comment]
但是在业务完成之后使用异步线程来commit依然是会出现漏掉次数的情况呢，都没有sleep100的时候稳定==汗，求指教！

**Comment by youyong205** [comment]
因为你写test，主线程结束，整个jvm就没有了。所以异步线程不会执行的。

**Comment by smile326** [comment]
那有什么好的办法来保证commit已经成功提交了呢，毕竟业务完成之后需要主动来等待么，但是commit并没有提供成功应答这样的呀

**Comment by smile326** [comment]
不过在测试过程中又发现如果上面例子中的代码是写在了servlet中，统计的次数是准确的呢！棒！
