### ISSUE TITLE
多核下CPU使用率超过100%信息会大量丢失的问题

### ISSUE THREAD

**Issue by xiaozujun1** [dianping/cat#956]
我做性能测试的时候遇到如下问题，分别做两个应用的压力测试：
1.测试不太耗CPU资源的应用时， TPS达到400也不会发生数据的丢失， CPU使用率在40%左右
2.测试相对比较耗CPU资源的应用时，TPS达到70的时候，CPU使用率超过100%的时候会发生大量数据的丢失

说明一下：两个应用在相同的测试服务器上，测试服务器为4个逻辑CPU， 测试时loadaverage也就达到1.5左右， io使用也比较低
数据丢失发生在客户端

在客户端的代码
		EventLoopGroup group = new NioEventLoopGroup(1, new ThreadFactory() {
			@Override
			public Thread newThread(Runnable r) {
				Thread t = new Thread(r);
				t.setDaemon(true);
				return t;
			}
		});

这里设置线程数为1有什么特殊意义吗？
当我修改为netty默认的核数*2的时候，即使CPU在120%左右也不会发生丢失。
不知道大神有没有遇到过这样的情形，如果我作了修改会不会有什么影响？

**Comment by youyong205** [comment]
设计上就是监控可以丢失消息，监控只是整个业务的非常小的一部分。不能因为监控影响业务
