### ISSUE TITLE
用maven安装不下去了，跪求帮忙

### ISSUE THREAD

**Issue by sunfaces** [dianping/cat#957]
mvn clean install -DskipTests
当执行到Downloading: https://raw.github.com/dianping/cat/mvn-repo/org/unidal/maven/plugins/codegen-maven-plugin/2.3.2/codegen-maven-plugin-2.3.2.pom
报这个错误

[ERROR] Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.3.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.unidal.maven.plugins:codegen-maven-plugin:jar:2.3.2: Could not transfer artifact org.unidal.maven.plugins:codegen-maven-plugin:pom:2.3.2 from/to cat.repo (https://raw.github.com/dianping/cat/mvn-repo): java.security.ProviderException: java.security.KeyException -> [Help 1]

跪求大神解救

**Comment by 247687009** [comment]
请翻墙
