### ISSUE TITLE
客户端正常启动，但是提示CAT Disable

### ISSUE THREAD

**Issue by sunfaces** [dianping/cat#961]
大神们，log里提示这个：
  [02-01 17:15:28.819] [INFO] [DefaultModuleContext] Current working directory is /Users/sunfei/IdeaProjects/log4j_kafka
[02-01 17:15:28.839] [INFO] [DefaultClientConfigManager] Global config file(/data/appdatas/cat/client.xml) found.
[02-01 17:15:28.840] [INFO] [DefaultClientConfigManager] Can't find app.properties in /META-INF/app.properties
[02-01 17:15:28.848] [WARN] [DefaultTransportManager] CAT was DISABLED due to not initialized yet!

客户端代码是这样的
   import com.dianping.cat.Cat;
import com.dianping.cat.message.Event;
import com.dianping.cat.message.Transaction;
import com.dianping.cat.message.MessageProducer;
import com.dianping.cat.message.Transaction;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Test {
    private static Logger logger = LogManager.getLogger("tf56");

    static Transaction t1 = Cat.getProducer().newTransaction("tf56_trans", "test_trans");

    public static void main(String[] args) {
        Cat.initialize("");
        System.out.println(Cat.isInitialized());
        produceLog(1);
    }

    static void produceLog(int times) {
        for (int i = 0; i < times; i++) {
            try {
                logger.warn("{operatorid:994757521}");
                Cat.getProducer().logEvent("tf56_event", "test_event", Event.SUCCESS, "{\"key1\":\"v1\"}");
                t1.setStatus(Transaction.SUCCESS);
                Thread.sleep(10);
            } catch (InterruptedException e) {

            } finally {
                t1.complete();
            }
        }

    }

}

运行后，控制台输出:
   Logger file /data/applogs/cat/cat_20160201.log
[02-01 17:15:28.028] [WARN] [cat] Cat is lazy initialized!
true
2016-02-01 17:15:28.865 [main] WARN  tf56 - {operatorid:994757521}

client.xml的配置：
   <?xml version="1.0" encoding="utf-8"?>

<config mode="client" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="config.xsd">
        <domain id="test" enabled="true"/>
        <servers>
                
                <server ip="10.3.14.112" port="2280" http-port="2281" />
                
                
        </servers>
</config>

为什么会启动不了CAT呢？求大神解惑

**Comment by youyong205** [comment]
[DefaultClientConfigManager] Can't find app.properties in /META-INF/app.properties  可以看看首页集成文档
