### ISSUE TITLE
CAT 重启后历史Transaction 和 Event 的数据都显示不出来了

### ISSUE THREAD

**Issue by chixuan777** [dianping/cat#965]
我的server.xml是
<config local-mode="false" hdfs-machine="false" job-machine="true" alert-machine="true">
	
	<storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
	
	</storage>
	
	<console default-domain="Cat" show-cat-domain="true">
		<remote-servers>127.0.0.1:2281</remote-servers>		
	</console>
	
	<ldap ldapUrl="ldap://192.168.50.11:389/DC=dianpingoa,DC=com"/>
	
</config>

**Comment by youyong205** [comment]
job-machine=true

**Comment by SandyJiang** [comment]
<config local-mode="false" hdfs-machine="false" job-machine="true" alert-machine="false">
	
	<storage  local-base-dir="/data/appdatas/cat/bucket/" max-hdfs-storage-time="15" local-report-storage-time="7" local-logivew-storage-time="7">
	
	</storage>
	
	<console default-domain="Cat" show-cat-domain="true">
		<remote-servers>127.0.0.1:8080</remote-servers>		
	</console>
	
	<ldap ldapUrl="ldap://192.168.50.11:389/DC=dianpingoa,DC=com"/>
	
</config>

即便设置了job-machine=true，重启还是历史数据全部显示。
