### ISSUE TITLE
Cat好像无法查看某一次具体的调用过程

### ISSUE THREAD

**Issue by xlweifeng** [dianping/cat#966]
Cat貌似在一段时间内只会记录第一次调用的明细，后续相同type和name进来的时候，只会计数和计算平均耗时。当系统遇到问题，想要查看相关调用逻辑时无法看到，Cat是出于什么考虑没有提供这种能力，感觉这个需求还是比较重要的。该明细在文件或hdfs中是否有保存，具体查看的方法是什么？

**Comment by youyong205** [comment]
cat不支持这个功能。
所有有问题的link都在problem里面，包括包含exception，包括long-url等。

你说的需求是日志search需求
