### ISSUE TITLE
连不上cat server [ChannelManager]类报错

### ISSUE THREAD

**Issue by lkyprogramer** [dianping/cat#968]
Service启动后 查看log发现连不上部署的cat server

[DefaultClientConfigManager] Find domain name cat from app.properties.
[DefaultTransportManager] Remote CAT servers: [/10.16.40.54:2280]
[ChannelManager] Error when init CAT server /10.16.40.54:2280;
 [ERROR] [ChannelManager] Error when try connecting to /10.16.40.54:2280
[INFO] [ChannelManager] close channel null

**Comment by youyong205** [comment]
那自己debug检查是否有问题吧。网络什么的

**Comment by lkyprogramer** [comment]
网络的问题 已解决
