### ISSUE TITLE
cat 集群疑惑

### ISSUE THREAD

**Issue by yalida** [dianping/cat#969]
请问cat集群模型是主备关系？ 还是具有负载作用么？   因为如果是主备关系，那么只能通过提升硬件来提升cat服务端性能（垂直扩展）。如果具有负载作用，那么就可以通过添加机器来提升性能（水平扩展）。

如果是负载的，那么cat是怎么做到数据一致性的？
麻烦能够解释下cat集群的工作原理，不胜感激。。。拜谢！！！

**Comment by qmwu2000** [comment]
cat的集群是分布式的，去中心化的，分片处理。cat自带负载均衡机制，一台机器down掉应该不会影响集群可用性。

可以通过添加机器提升容量，需要后台配置一下。


发自我的 iPhone

**Comment by youyong205** [comment]
数据一致性是在最后展示层对针对所有机器的合并。
