### ISSUE TITLE
cat-home启动报503错误

### ISSUE THREAD

**Issue by yugy23** [dianping/cat#970]
在进入cat-home目录，执行mvn jetty:run命令的时候报HTTP ERROR: 503错误
我本地环境为mac系统，maven 3.3版本，jdk1.8，代码下载的是最新的master分支的。
麻烦尤勇老大这是什么问题？

org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------
RequestURI=/cat/r

Caused by:

javax.servlet.UnavailableException: org.unidal.lookup.LookupException: Component(org.unidal.web.lifecycle.RequestLifecycle) lookup failure. details: Unable to lookup component 'org.unidal.web.lifecycle.RequestLifecycle', it could not be started.
      role: org.unidal.web.lifecycle.RequestLifecycle
  roleHint: mvc
classRealm: plexus.core
-----------------------------------------------------
realm =    plexus.core
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 0

-----------------------------------------------------

	at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:406)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:442)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:643)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)

**Comment by jialechan** [comment]
遇到一样的问题，jdk版本是8.

**Comment by no-east** [comment]
一样的问题，版本是JDK8

**Comment by youyong205** [comment]
参考 新的readme 用tomcat部署试试
