### ISSUE TITLE
mvn jetty:run 运行无报错停滞

### ISSUE THREAD

**Issue by bicey** [dianping/cat#972]
在cat-home目录下执行mvn jetty:run停滞于如下：
 Starting jetty 6.1.26 ...
[INFO] jetty-6.1.26
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
Logger file /data/applogs/cat/cat_20160315.log
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
[03-15 06:29:23.023] [WARN] [cat] Cat is lazy initialized!
[INFO] Started SelectChannelConnector@0.0.0.0:2281
[INFO] Started Jetty Server
**# [INFO] Starting scanner at interval of 10 seconds.
[INFO] Working directory is /usr/local/cat/cat-home
[INFO] War root is /usr/local/cat/cat-home/src/main/webapp**
停滞于此

ctrl+C 跳过
^C[INFO] Shutdown hook executing
[INFO] Stopped SelectChannelConnector@0.0.0.0:2281
shutdown task TcpSocketSender
shutdown task TcpSocketSender-ChannelManager
shutdown task merge-atomic-task
shutdown task StatusUpdateTask
shutdown task Server-Filter-Config-Reload
shutdown task LocalMessageBucketManager-BlockDumper
shutdown task LocalMessageBucketManager-OldMessageMover
shutdown task Message-Gzip-0
shutdown task Message-Gzip-1
shutdown task RealtimeConsumer-PeriodManager
shutdown task Config-Reload
shutdown task UrlPattern-Config-Reload
shutdown task App-Config-Reload
shutdown task App-Speed-Config-Reload
shutdown task Aggreation-Config-Reload
shutdown task App-Rule-Config-Reload
shutdown task DependencyAnalyzer-6-0
shutdown task DependencyAnalyzer-6-1
shutdown task DumpAnalyzer-6-0
shutdown task DumpAnalyzer-6-1
shutdown task TransactionAnalyzer-6-0
shutdown task TransactionAnalyzer-6-1
shutdown task MetricAnalyzer-6-0
shutdown task HeartbeatAnalyzer-6-0
shutdown task EventAnalyzer-6-0
shutdown task EventAnalyzer-6-1
shutdown task MatrixAnalyzer-6-0
shutdown task StateAnalyzer-6-0
shutdown task ProblemAnalyzer-6-0
shutdown task ProblemAnalyzer-6-1
shutdown task StorageAnalyzer-6-0
shutdown task CrossAnalyzer-6-0
shutdown task CrossAnalyzer-6-1
shutdown task TopAnalyzer-6-0
[INFO] Shutdown hook complete
[INFO] Jetty server exiting.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:00 min
[INFO] Finished at: 2016-03-15T06:32:37-04:00
[INFO] Final Memory: 50M/120M
[INFO] ------------------------------------------------------------------------

结果显示BUILD SUCCESS但并不能使用，请问这是为何原由？

**Comment by bicey** [comment]
系统环境
OS：CentOS 7
JDK：1.7
maven：3.3.9
mysql：14.14
git：1.8.3.1

**Comment by jialechan** [comment]
mvn jetty:run -X

加个-X好像可以多很多日志？

**Comment by bicey** [comment]
我觉应该是少了什么东西，可是不知道到底缺少了什么。

RESPONSE  /cat/s/router/  200
EOF

**Comment by youyong205** [comment]
参考下wiki首页 使用tomcat部署试试
