### ISSUE TITLE
使用cat的话哪些jar包要导入到业务主机？

### ISSUE THREAD

**Issue by slowlizard** [dianping/cat#977]
还是说不需要导入，直接做监控

**Comment by sunnyhui2010** [comment]
这个我也想问，我们建个群一起研究讨论吧？群号：494303185

**Comment by slowlizard** [comment]
关键是要懂得人啊。。

**Comment by jialinsun** [comment]
只需要cat-client就够了，有一个微信交流群，可以去申请加入。看issue。

**Comment by slowlizard** [comment]
我加了，但是还没有回复。使用cat监控是不是所有的都需要埋点？能不能监控错误信息供开发人员排查？

**Comment by jialinsun** [comment]
可以，这是基本的功能，可以先看看文档(http://unidal.org/cat/r/home?docName=integration)，有一个CatAppender和CatFilter，可以留意一下用法和作用。其他的埋点可以根据自己需要做斟酌。

**Comment by sunnyhui2010** [comment]
![image](https://cloud.githubusercontent.com/assets/943458/13974842/6fc19b3e-f0ea-11e5-8387-41d97fb7bdf1.png)
我已经配置了remoteserver了，为什么他还是要连127.0.0.1啊

**Comment by jialinsun** [comment]
连哪台服务器IP是由client.xml配置的，这项配置需要在所有用cat-client的应用里/data/appdatas/cat/client.xml里配置。等待 @youyong205 回复，拉你进群交流吧

**Comment by sunnyhui2010** [comment]
@jialinsun 我配置了的，而且只配了121那个，为什么还是要连127.0.0.1呢，你有没有遇到
![image](https://cloud.githubusercontent.com/assets/943458/13974915/28903d1e-f0eb-11e5-8c1e-fcd846e34e26.png)

**Comment by jialinsun** [comment]
还有路由，你在路由设置里把那个路由机器默认配置改一下。/cat/s/config?op=routerConfigUpdate

**Comment by sunnyhui2010** [comment]
@jialinsun 多谢，现在正常了，但是貌似我服务器端收不到我的测试用例发送的message，客户端console显示如下：
![image](https://cloud.githubusercontent.com/assets/943458/13975037/579c8ef4-f0ec-11e5-85cc-4cf8d4ee2d09.png)

**Comment by jialinsun** [comment]
这些问题之前都有回答过，你翻翻以前的issue。测试用例需要在退出前sleep几秒，因为是Netty异步发送消息的。

**Comment by slowlizard** [comment]
请问本地测试安装好以后，默认的用户名和密码是多少？

**Comment by youyong205** [comment]
admin随便填写就可以登录。
