### ISSUE TITLE
第一次rpc异常，第二次rpc正确，Transaction中还显示的是第一次的异常

### ISSUE THREAD

**Issue by zhaoypmit** [dianping/cat#979]
第一次rpc异常，第二次rpc正确，Transaction中还显示的是第一次的异常

**Comment by qmwu2000** [comment]
Transaction报表的设计就是这样的，以问题为中心。


发自我的 iPhone

**Comment by zhaoypmit** [comment]
以后的调用都是成功的，但是 Transaction报表中会一直显示第一次的异常信息。这个是否能加个判断条件，如果第二次是成功的则清除掉上次的异常信息，只是调用次数增加就行。

**Comment by youyong205** [comment]
建议研究研究这个报表吧。听你的描述是不懂

**Comment by zhaoypmit** [comment]
目前的问题就是：第一次rpc 失败了，Transaction报表中会记录下调用失败的异常信息，但是上一次调用出错的那个地方在以后都是成功的，而Transaction报表中仍然显示的是第一次调用失败的异常信息。

**Comment by qmwu2000** [comment]
transaction报表关心发生过什么，如实地记录下来，但不在意现在有没有恢复。

发自我的 iPhone
