### ISSUE TITLE
客户端配置cat-filter报错

### ISSUE THREAD

**Issue by sunnyhui2010** [dianping/cat#982]
![image](https://cloud.githubusercontent.com/assets/943458/13978432/e4d2f906-f10b-11e5-8246-e4386858bff0.png)
服务器端都配置好了，客户端的配置文件也授权了，eclipse引入cat-client工程测试用例也跑成功了，但是自己项目里面使用的时候出现问题。

**Comment by youyong205** [comment]
用pom的标准方式依赖cat
