### ISSUE TITLE
构建的时候报这错，做了google的hosts代理

### ISSUE THREAD

**Issue by emperorente** [dianping/cat#985]
Failed to execute goal org.unidal.maven.plugins:codegen-maven-plugin:2.3.2:dal-model (generate data model) on project cat-client: Execution generate data model of goal org.unidal.maven.plugins:codegen-maven-plugin:2.3.2:dal-model failed: Plugin org.unidal.maven.plugins:codegen-maven-plugin:2.3.2 or one of its dependencies could not be resolved: Failed to collect dependencies at org.unidal.maven.plugins:codegen-maven-plugin:jar:2.3.2 -> org.unidal.maven.plugins:common:jar:2.2.0 -> org.unidal.framework:foundation-service:jar:2.2.0: Failed to read artifact descriptor for org.unidal.framework:foundation-service:jar:2.2.0: Could not transfer artifact org.unidal.framework:parent:pom:2.0.6 from/to cat.repo (https://raw.github.com/dianping/cat/mvn-repo): java.security.ProviderException: java.security.KeyException -> [Help 1]
[ERROR]

**Comment by youyong205** [comment]
可以参考首页的文档解决

**Comment by hehe431** [comment]
我在安装的时候也遇到了这样的问题，请问大神是怎样解觉的啊？
