### ISSUE TITLE
关于CAT客户端发送数据疑问

### ISSUE THREAD

**Issue by foxinmy** [dianping/cat#990]
尝试使用CAT，有几个问题想搞清楚。

1、客户端每次发送MessageTree的字节大小是多少？
看到`TcpSocketSender`类在发送消息的时候有这样的代码：
```java ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer(10 * 1024); // 10K ```
是不是意味着每次发送消息都是分配`10k`的缓冲池？

2、如果客户端在MessageQueue还有数据的情况下意外退出，已有消息意味着是不是会全部丢失？
```java
      @Override
	public void shutdown() {
		m_active = false;
		m_manager.shutdown();
	}
```

3、我该如何去测试CAT的性能，比如客户端发送消息的大小对现有业务的影响。

期待回复，谢谢。

**Comment by youyong205** [comment]
1、PooledByteBufAllocator 这个是对象缓存池
2、是的，这块还可以优化，但是cat并不是一个100%可靠的
3、简单来说就是不加cat之前测试性能，加了cat测试性能。还得看你们qa自己
