### ISSUE TITLE
邮件，电话和微信的警告如何配置

### ISSUE THREAD

**Issue by WiXiN9** [dianping/cat#991]
您好，我目前是需要监控url 返回值是否是200，按照文档里面的内容配置邮箱，微信和手机后无效，请问邮箱，手机和微信是否需要再做其他绑定？邮箱是否只限制点评的内部邮箱？谢谢。

**Comment by youyong205** [comment]
不需要绑定，你需要按照api规范自己实现http的短信和邮件
