### ISSUE TITLE
cat-home工程中是否是有部分代码未公布?

### ISSUE THREAD

**Issue by LiPan1989** [dianping/cat#994]
cat-home工程中是否是有部分代码未公布?当然其他工程也发现有部分代码缺失,能否公布完整代码以供研究~

**Comment by qmwu2000** [comment]
所有代码都在的。


发自我的 iPhone

**Comment by LiPan1989** [comment]
譬如com.dianping.cat.report.alert.app.AppAlert类中import的
com.dianping.cat.home.rule.entity.Condition;
com.dianping.cat.home.rule.entity.Config;
com.dianping.cat.home.rule.entity.MonitorRules;
com.dianping.cat.home.rule.entity.Rule;
这几个类就找不到,请问是我什么地方搞错了吗?

**Comment by qmwu2000** [comment]
你的mvn build有问题。请在命令行build，然后以正常项目倒入IDE，如eclipse中。


发自我的 iPhone

**Comment by jahnkey** [comment]
@qmwu2000 ，请问为什么要在命令行build是呢？

**Comment by Jane09** [comment]
idea compile 一下就好了
